### PR TITLE
LOC CHECKIN | dotnet/sdk release/3.0.1xx | 20190620

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by nguerrera** [comment]
@tmeschter master is still merging into 3.0.1xx so I don't think we need this as I also saw PRs to master. 

On the other hand, it won't do harm.

@livarcocc  OK to merge this?

**Comment by nguerrera** [comment]
I'm going to close this since we will soon branch from master that already has the translations.

**Comment by nguerrera** [comment]
See https://github.com/dotnet/cli/pull/11601#issuecomment-506058198

**Review by nguerrera — CHANGES_REQUESTED** [review]
"Requesting changes" while we figure out the plan for 3.0 loc.

**Comment by nguerrera** [comment]
Tom is OOF. I'll go ahead and redirect this to master. It's a bit of work but we'll get the translations in preview users hands sooner.

**Comment by nguerrera** [comment]
Seems we did have all the strings but one french one and all of zh-Hant, which looks like an xliff-tasks bug (second time I see it and I didn't catch it this time in 46917a9b622ea05377dc438db9f6b6e184bd3d83

**Comment by nguerrera** [comment]
I will look at fixing the xliff-tasks bug, I think there's a lingering issue with more than one project with same resx.

**Review by nguerrera — APPROVED** [review]

**Comment by tmeschter** [comment]
@nguerrera Do we have a bug in https://github.com/dotnet/xliff-tasks tracking that problem?

**Comment by nguerrera** [comment]
I believe https://github.com/dotnet/xliff-tasks/issues/59

**Pull request merged**
