### PR TITLE
Fix null reference exception error

### PR DESCRIPTION
**Pull request by jyoungyun**
Related issue: https://github.com/dotnet/sdk/issues/1094, https://github.com/dotnet/cli/issues/5927

### CODE REVIEW

**Review by eerhardt — CHANGES_REQUESTED** [review]
This isn't really a valid fix for the issue. Instead it is a hack workaround for a JIT issue: https://github.com/dotnet/coreclr/issues/10780.
Throwing an ArgumentNullException here is going to kill the build just as a NullReferenceException would.

I'd rather see a comment here saying this is a workaround for the above issue, and maybe even making the workaround explicitly looking like it isn't a valid check.

Ex. 

```C#
// Workaround for JIT bug on arm processors. See https://github.com/dotnet/coreclr/issues/10780 
if (string.Empty == null)
{
    throw new Exception();
}
```

**Comment by jyoungyun** [comment]
@eerhardt When I use your workaround, `dotnet build` works well. Do you want to add this workaround before fixing JIT bug about https://github.com/dotnet/coreclr/issues/10780? If not, I will close this issue and follow it on your issue.

**Comment by hqueue** [comment]
@eerhardt @jyoungyun I agree with this workaround to avoid ARM32 JIT bug, i.e. inserting meaningless comparison :)

 I've look into  dotnet/coreclr#10780 and found out that it's realy JIT bug in ARM32.
However the code with bug is a result of multiple optimization, at least it is to loop hoisting and CSE.

**Comment by eerhardt** [comment]
@hqueue - do you have an estimate on when the underlying JIT bug will be fixed?  If it will be fixed in the next day or two, then let's not take this work around in the SDK. But if it will take longer, let's take it so we can continue testing the SDK on arm processors.

**Comment by eerhardt** [comment]
test Windows_NT_FullFramework Release

**Review by eerhardt — APPROVED** [review]
Approving. Let's take this change if the underlying arm bug won't be fixed soon.

**Comment by hqueue** [comment]
@eerhardt I didn't look in depth, but I think it may take more than two days. In addition, I'm working on other issue now, so if there is no other person can look this bug, it may take more.

**Pull request merged**
