### PR TITLE
Merge Dev15 rc3 to master

### PR DESCRIPTION
**Pull request by srivatsn**
@dotnet/project-system 

Tagging @MattGertz for RTM approval. Normal codeflow of RC3 fixes to RTM.

### CODE REVIEW

**Review by natidea — APPROVED** [review]

**Comment by srivatsn** [comment]
How do I merge this? This is a PR from the rc3 branch to master but it looks like GitHub wants us to merge master into the rc3 branch before merging back. Probably need an admin to override this. @nguerrera

**Comment by natidea** [comment]
I think we really want to create a branch off master and use that to merge RC3 changes instead of merging dev15-rc3 to master directly. E.g. see the script in this Roslyn PR: https://github.com/dotnet/roslyn-internal/pull/1513

**Comment by davkean** [comment]
Oh shit, I accidentally merged this - why do they even have that button?

**Comment by davkean** [comment]
Trying to fix this...

**Comment by natidea** [comment]
I think you can reset hard the branches since no one else has pulled these changes

**Comment by davkean** [comment]
Yeah, the branch should be protected, so I'll need to run that off first

**Comment by davkean** [comment]
What's a good way to see what RC-3 was sitting at before this merge?

**Comment by natidea** [comment]
Probably by looking at the signed builds. Looks like it was: https://github.com/dotnet/sdk/commit/b616fc44ef90bb4391fcb8cf6547fd5c989c3beb

**Comment by natidea** [comment]
And master was at https://github.com/dotnet/sdk/commit/7b038dab015f2aa13eb0bc89bfbb242e98aee8ae

**Comment by srivatsn** [comment]
I think you'll just need to roll back the one merge commit in rc3 (PS: That update branch button is evil)

**Comment by davkean** [comment]
Yeah came to the same conclusion, I've reset it and re-protected the branch.

**Comment by davkean** [comment]
I reset not rolled back.

**Comment by davkean** [comment]
From an admin point of view - there's nothing that I can see let's me override "this Update branch". What's the point of this?

**Comment by srivatsn** [comment]
Can you also merge this in - I think you need to remove the protection and merge from rc3 to master and push. Can't think of any other way. Even if we created another branch as Nat suggests I assume it'll give the branch is out of date with base branch error

**Comment by davkean** [comment]
Oh there is, and turned it off.

**Comment by srivatsn** [comment]
Ah what was the setting? Require branches to be up-to-date before merging?

**Comment by davkean** [comment]
Yeah. Who turned that check box on? This is my point about having silly admin enforced polices - it blocks things like this.

**Comment by srivatsn** [comment]
No idea. Make sure it's off in project system as well.

**Comment by davkean** [comment]
It's off.

**Comment by davkean** [comment]
It says that project-system folks are admins - do you not have rights to turn this off?

**Comment by davkean** [comment]
if not, we should make leads admins at the dotnet org.

**Pull request merged**
