### PR TITLE
Unstable branding with rtm label and empty iteration

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@mmitche To confirm, we're keeping the branding unstable until a later date, correct?

**Comment by mmitche** [comment]
> @mmitche To confirm, we're keeping the branding unstable until a later date, correct?

Correct. We flip on the 14th I think

**Review by nagilson — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@dotnet/source-build-internal why is source build including a workload uninstall test? Not sure how source build figures out the version of wasm to uninstall.
`System.InvalidOperationException : Failed to execute /vmr/artifacts/obj/extracted-dotnet-sdk/dotnet workload uninstall wasm-tools\nExit code: 1\nRemoving workload installation record for wasm-tools...\nWorkload uninstallation failed: Workload version 9.0.100-rtm.24467.1 was not found.`

**Comment by MichaelSimons** [comment]
> @dotnet/source-build-internal why is source build including a workload uninstall test? Not sure how source build figures out the version of wasm to uninstall.

These aren't source-build specific tests, these are the Unified Build's scenarios tests which are run to validate source-build.

This [test is the Test](https://github.com/dotnet/scenario-tests/blob/main/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs#L213).  The core logic is [here](https://github.com/dotnet/scenario-tests/blob/main/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotnetWorkloadTest.cs#L33).  It looks like it installs and uninstalls the workload.

**Comment by marcpopMSFT** [comment]
> These aren't source-build specific tests, these are the Unified Build's scenarios tests which are run to validate source-build.
> 
> This [test is the Test](https://github.com/dotnet/scenario-tests/blob/main/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs#L213). The core logic is [here](https://github.com/dotnet/scenario-tests/blob/main/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotnetWorkloadTest.cs#L33). It looks like it installs and uninstalls the workload.

Who owns those tests then? uninstall is one of the least used workload commands (<1% of workloads customers) so I probably wouldn't cover it in these set of tests. I think this is probably related to workload sets not working well with no prerelease iteration. @dsplaisted you mentioned that -rtm feature bands were specially cased but something in the uninstall logic I think is trying to uninstall a baseline workload version. That error at least to me looks like WorkloadVersionRequestedNotFound.

**Comment by MichaelSimons** [comment]
> Who owns those tests then?

@richaverma1 had reached out to product teams to gather the tests scenarios.  I believe she is the keeper of the tests but really it is the product teams that own their own scenarios. @mattscheffer implemented, and @mmitche has been involved as well.

This is good feedback.

**Comment by marcpopMSFT** [comment]
@richaverma1 @mmitche @mattscheffer how can I remove the uninstall step from this particular PR for now? This likely only affects the unstable rtm builds and it's creating confusion since the public rtm branch is still rc2 branded.

CC @dsplaisted in case he knows of a product fix we can make for uninstall long term.

**Comment by richaverma1** [comment]
> @richaverma1 @mmitche @mattscheffer how can I remove the uninstall step from this particular PR for now? This likely only affects the unstable rtm builds and it's creating confusion since the public rtm branch is still rc2 branded.
> 
> CC @dsplaisted in case he knows of a product fix we can make for uninstall long term.

I moved Matthew Scheffer to another project and he is full time working on that. @mattscheffer do you have any suggestion on this though?

**Comment by mmitche** [comment]
You can't remove the uninstall step in this PR. It will have to be done in the scenario-tests repo (9.0 branch) then flow in.

**Comment by mattscheffer** [comment]
I made these tests quite a while ago but wasn't involved in bringing them to this repo, so unfortunately, I don't know if there is a quick way to skip them. I suspect that something with the branding is tripping up the checks to dotnet workload list. I'm guessing you'll need to remove/fix them in the scenario-tests repo, if they are actively being pulled from there.

**Comment by marcpopMSFT** [comment]
I'll need this approved, merged, and to flow the build into this PR: https://github.com/dotnet/scenario-tests/pull/114

**Pull request merged**
