### PR TITLE
Include log files in Jenkins archive

### PR DESCRIPTION
**Pull request by dsplaisted**
This will include the structured log of the build in the Jenkins archive which will be helpful diagnosing build issues.

### CODE REVIEW

**Comment by dsplaisted** [comment]
@dotnet-bot test ci please

**Comment by 333fred** [comment]
With the binary logging you guys are doing now, do you really want to also be logging all warns, errors, and infos, at a diagnostic level?

**Comment by dsplaisted** [comment]
@333fred I think the text log is also valuable, partly since binary logging is a new thing and the viewer doesn't always display things in a way that's clear.

The text log is large though (133MB it looks like), so if there are issues with space for the Jenkins archive we can exclude it from being archived.

**Review by 333fred — APPROVED** [review]

**Comment by dsplaisted** [comment]
@dotnet-bot test Windows_NT_FullFramework Debug

**Comment by dsplaisted** [comment]
@MattGertz FYI for an infrastructure change

**Pull request merged**
