### PR TITLE
Convert dotnet-install.sh to POSIX shell script

### PR DESCRIPTION
**Pull request by am11**
In operating systems where bash is not installed, users are required to
install bash in order to just execute `dotnet-install.sh`. This change
removes the bash dependency and makes the public facing script
compatible with POSIX shell (sh).

#### Usage:

(from https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)

```diff
- curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 3.0
+ curl -sSL https://dot.net/v1/dotnet-install.sh | sh /dev/stdin -Channel 3.0

# or

curl -sSL https://dot.net/v1/dotnet-install.sh | /usr/bin/env sh /dev/stdin -Channel 3.0
```

#### Summary of changes:

* Removed `local`, as it does not exist in POSIX shell.
* Removed `-o piefail`, as it does not exist in POSIX shell either.
* `FUNCNAME[0]` is bash built-in, replaced with explicit
  `FUNCTION_NAME` from callsite.
* Conditions of form `if [[ "$x" = "$y" ]]` are replaced with
  `if [ "$x" = "$y" ]`.
* Conditions of form `if [[ "$x" = "$y"* ]]` with pattern matching are
  replaced with `case "$x" in "$y"*)`.
* Expressions of the form `var+="more"` are replaced with
  `var="$var more"`, as operator `+=` does not exist in POSIX shell.
* Removed some unused variables.
* `LDCONFIG_COMMAND` is ran just once, instead of for each dependency.
* Function `parse_jsonfile_for_version` is rewritten due to:
  * in its current form (master branch), it is not working with
    global.json taken from dotnet/corefx and dotnet/runtime repos.
  * it is also not working with minified JSON.
  * it is strongly recommended by shell script community to parse JSON
    with tools like jq or JSON.sh, instead of using regular sed and
    awk, which is highly error prone.

  Now it tries to use jq, then falls back to acquiring and using
  JSON.sh.

### CODE REVIEW

**Comment by dsplaisted** [comment]
Can you separate the changes that were missed from the repo merge and the changes you're making on top of them into two separate commits?

**Comment by am11** [comment]
Done; f521a6d is the sync commit.

**Comment by am11** [comment]
@dsplaisted, @sdmaclea, please take a look. Thanks! 🙁

**Comment by wli3** [comment]
I mentioned this in a different issue. This script does not have a good test coverage. And we don't have a good way to ensure the script continues to be POSIX. And my team currently don't have expertise in shell script anymore. So the review process could take a long time. I am sorry.

**Comment by am11** [comment]
@wli3, no problem at all. There are some unit tests in this repo invoking this script. The first line (shebang: `#!/env/usr/bin sh`) on all major Linux distributions point to Bourne-Again shell (aka POSIX shell). If we use Bash syntax in this script, we immediately get error (due to the said shebang first line).
If you could point me which options we should add to the unit tests, that do not have coverage, i would happily add those.

I have used [`shellcheck(1)`](https://www.shellcheck.net/) to fix all kinds of errors and warnings in this script

toolset repo's master branch (f521a6d):
> warning: 47
> info: 35

PR (171b0d7):
> warning: 6
> info: 3

* remaining warnings are related to extra (unused) colors.
* two infos are about `/etc/os-release` path (spellcheck explicitly want it as input), and one is about single quoted `invocation='...'` expression, that we later `eval`.

we can use shellcheck in the CI run as well to ensure it does not degrade. Shell check is one of the best tool to detect that script is conforming to the standard (based on the shebang value). e.g. https://github.com/microsoft/fabrikate/blob/6420623/testdata/generate-yaml/helm_repos/grafana/.circleci/config.yml#L11

**Comment by am11** [comment]
The master branch was updated with dotnet/toolset's master tag, I have rebased and removed the additional sync commit.

**Comment by bozturkMSFT** [comment]
@grinrag

**Comment by donJoseLuis** [comment]
This would be a lower pri issue for our current road map due to the following...
1. there are plans to re-engineer this solution e2e
1. prior to that, prioritized investment will be around improving resiliency

**Comment by am11** [comment]
@donJoseLuis

**Pull request closed without merging**
