### PR TITLE
Update to nuget build used in cli/toolset

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by sfoslund — APPROVED** [review]

**Comment by sfoslund** [comment]
@mmitche looks like the `ResolvePackageAssets` task is failing, any idea why?

**Comment by mmitche** [comment]
No idea... @rrelyea Any ideas?

**Comment by wli3** [comment]
/azp run
```
File name: 'NuGet.ProjectModel, Version=5.6.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
```

@sfoslund we likely need to update stage 0 once toolset and core-sdk's nuget is merged

**Comment by rrelyea** [comment]
Sounds like @wli3 believes another update is needed to toolset to adapt to 5.6 nuget bits.
@wli3 - do you see the reason why the change is necessary? (can you give a bit more data)

@nkolev92

**Comment by wli3** [comment]
> do you see the reason why the change is necessary? (can you give a bit more data

Mostly from the error message and experience. SDK don't have any change between them. It is likely caused by dll hell during test. And we usually have to do a stage 0 update whenever there is an major nuget insertion.

**Review by wli3 — APPROVED** [review]

**Pull request merged**
