### PR TITLE
[release/5.0.2xx] Update to 5.0.2 runtime

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by sfoslund — APPROVED** [review]

**Comment by mmitche** [comment]
Merge away when green.

**Comment by wli3** [comment]
@mmitche why updating runtime this late? I need to start the insertion all over again instead of just replace SDK version

**Comment by mmitche** [comment]
@wli3, @marcpopMSFT Said this was ideal if there was time (there were additional fixes to be checked into the SDK)

**Comment by mmitche** [comment]
@wli3 Also needed to unblock https://github.com/dotnet/sdk/pull/15465

**Pull request merged**
