### PR TITLE
Rename "Cache" to "Store".

### PR DESCRIPTION
**Pull request by eerhardt**
Also, rename "FilterProjectFiles" to "TargetManifestFiles".

@ramarag @nguerrera @dsplaisted

### CODE REVIEW

**Comment by ramarag** [comment]
@eerhardt i thought we were only renaming the cli part of this feature, what is the need to do so in sdk ?

**Comment by eerhardt** [comment]
> what is the need to do so in sdk ?

To make it understandable for anyone working in the code and for our customers. Why call it "store" in one place and "cache" in another?  `ComposeCache` is a public target so it follows the same naming guidelines as any other public contract.

**Review by ramarag — APPROVED** [review]

**Comment by ramarag** [comment]
@nguerrera @dsplaisted we should consider removing long file asserts for .net core builds

**Comment by eerhardt** [comment]
test Windows_NT_FullFramework Release

**Pull request merged**
