### PR TITLE
Never mark files from nuget as in-box fx ref assemblies

### LINKED ISSUE #1738: ResolveAssemblyReference is incorrectly marking references from NuGet packages as referenceassembly
Reproduced in VS 2017 15.4.4.

1. Create an Mvc application targeting net471
2.  Build and run the application.

Views fail to compile with an error stating from DependencyModel stating reference assemblies cannot be resolved:

```C#
System.InvalidOperationException: Cannot find reference assembly 'System.AppContext.dll' file for package System.AppContext.Reference
   at Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
...
```

### Notes from @eerhardt's investigation

I quickly looked at this scenario, and it appears to be a dotnet/sdk bug to me.  The SDK is getting confused about a bunch of references:

 eric

All these references are being marked as “Reference Assembly” references, when in actuality they are coming from NuGet packages.

The reason they are being marked as “Reference Assembly” references (as far as I can tell) is because RAR is seeing the same file in the ‘C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1’ RedistList, which is causing them to get the “FrameworkFile=true” metadata on them.  The dotnet/sdk then thinks that this is a “Reference Assembly” (i.e. it comes from C:\Program Files (x86)\Reference Assemblies) because “FrameworkFile=true” on them.

I’ve added a quick check locally to that SDK code that appears to fix the issue:

```xml
<_FrameworkReferenceAssemblies Include="@(ReferencePath)"
                             Condition="(%(ReferencePath.FrameworkFile) == 'true' or
                                        %(ReferencePath.ResolvedFrom) == 'ImplicitlyExpandDesignTimeFacades') and
                                        %(ReferencePath.NuGetSourceType) == ''" />
```

### PR DESCRIPTION
**Pull request by nguerrera**
Before conflict resolution between nuget and redist list, we would end up in
situations where MSBuild marked an assembly from nuget matching redist list with
<= version with FrameworkFile=true metadata. This caused us to designate the
assembly as type "referenceassembly" in deps.json for
PreserveCompilationContext. However, that is not correct as that designation
means that the assembly is literally from the targeting pack in Program Files
and not from nuget.

This no longer happens because the nuget assembly with smaller assembly version
will be discarded during conflict resolution, favoring the in-box assembly that
is correctly designated as "referenceassembly". Furthermore, an OOB with greater
version than in-box will not get FrameworkFile=true set by MSBuild. As such,
there's no longer a known real scenario (and hence no test here) where we will
observe FrameworkFile=true on an assembly from nuget. This is therefore an
defensive change in case it ever happens in the wild for unforeseeable reasons.

Fix #1738

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
thanks!

**Comment by nguerrera** [comment]
Hmm, seems I was wrong about this not impacting anything because tests are failing. Investigating

**Comment by nguerrera** [comment]
So it turns out that NuGetSourceType == Package and NuGetIsFrameworkReference == true when a package nuspec indicates that a framework reference is to be added. So the fix is wrong for that case, and thankfully we had a test that hit it.

This makes me concerned that all NuGetSourceType != '' are vulnerable to this. :(

**Comment by nguerrera** [comment]
@eerhardt Can you look at 0089c00?

**Review by eerhardt — APPROVED** [review]

**Comment by livarcocc** [comment]
@nguerrera is this good to go in?

**Comment by eerhardt** [comment]
somehow someone denied me write access to this repo, meaning my reviews no longer "count".  😝

**Pull request merged**
