### PR TITLE
Fix typo: s/Refernces/References/

### PR DESCRIPTION
**Pull request by nguerrera**
@ramarag @dsplaisted

### CODE REVIEW

**Comment by ramarag** [comment]
fixup https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenARemoveDuplicatePackageReferences.cs#L45 too

**Comment by ramarag** [comment]
my bad missed that it was done

**Comment by nguerrera** [comment]
But file name is still bad. ;) Fixing.

**Review by ramarag — APPROVED** [review]

**Comment by nguerrera** [comment]
(Disregard deleted comment about file name, that was already fixed and showing on diff link)

**Review by dsplaisted — APPROVED** [review]

**Pull request merged**
