### PR TITLE
Insert NuGet Build 4.7.0-preview3.5039 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-preview3.5039 into sdk release/2.1.2xx branch

### CODE REVIEW

**Comment by zhili1208** [comment]
@livarcocc Fixed the pack issue and target to 2.1.2xx

**Comment by livarcocc** [comment]
@MattGertz Matching of dependencies in VS.

**Comment by MattGertz** [comment]
@livarcocc I presume you meant that as an FYI since this sort of thing is "auto-approved," but lemme know if there is something more going on.

**Comment by livarcocc** [comment]
@MattGertz Yes, FYI.

**Comment by livarcocc** [comment]
@dotnet-bot Test Ubuntu14.04 Debug

**Comment by rohit21agrawal** [comment]
@livarcocc will this be in for Preview3?

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
It will have to go in in escrow.

**Pull request merged**
