### PR TITLE
Update a test to skip running for target frameworks not supported by current OS

### PR DESCRIPTION
**Pull request by dsplaisted**

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
Still relevant?

**Comment by nguerrera** [comment]
Reopen if this is still needed, I'm not clear on why things are green without this.

**Comment by dsplaisted** [comment]
I think this was to enable the test to be run as an integration test in the core-sdk repo

**Comment by wli3** [comment]
good to go?

**Comment by nguerrera** [comment]
Did this kick off unwanted builds, @mmitche ?

@wli3 @dsplaisted Be careful checking into release branches.

**Comment by nguerrera** [comment]
Oh, just saw 1 minute ago, so I assume @wtgodbe is turning off flow fast enough to not matter?

**Comment by dsplaisted** [comment]
Oops, I didn't pay attention to the branch this was targeting.  Should we try to back it out? @mmitche @wtgodbe 

Sorry about that.

**Comment by nguerrera** [comment]
Since it's a test only change I don't think there's any point in backing it out. The only concern I have is triggering an unwanted build with the wrong branding. Doesn't really matter if there's another dotnet/sdk build with same branding, but don't want this making a core-sdk.

**Pull request merged**
