### PR TITLE
Migrated to newest version of `FluentAssertions`

### PR DESCRIPTION
**Pull request by vlada-shubina**
Migrated to latest version of `FluentAssertions` (templating using latest)
~~Removed duplicate `TestHelper` code and referenced package from templating instead.~~  will be done in separate PR

### CODE REVIEW

**Comment by dsplaisted** [comment]
Do you want us to go ahead and review this?  It's marked as a draft PR.

**Comment by vlada-shubina** [comment]
> Do you want us to go ahead and review this? It's marked as a draft PR.

I'm still working on tests (was not aware that reviewers are notified for draft).
Generally, I need just an approval for uplifting `FluentAssertions`. I will fix the tests issues prior to converting from draft/

**Comment by ViktorHofer** [comment]
@vlada-shubina I think you accidentally included two of my PR commits into your branch. Please remove them.

**Comment by vlada-shubina** [comment]
> @vlada-shubina I think you accidentally included two of my PR commits into your branch. Please remove them.

Thanks for catching, removing them now

**Review by JanKrivanek — APPROVED** [review]
Great to see the sdk code update the stale reference!

**Pull request merged**
