### PR TITLE
Dev/merge internal 05142020/release/3.1.2xx

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@wli3 why did you undo my changes here? They're necessary, see https://github.com/dotnet/sdk/pull/11654

**Comment by wli3** [comment]
@wtgodbe ah, sorry I forget to pull. I force pushed to restart the failed CI.

**Comment by wtgodbe** [comment]
Consistent test failure in It_gives_the_correct_error_if_duplicate_compile_items_are_included_and_default_items_are_disabled

> Expected command to fail but it did not.\r\nFile Name: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe\r\nArguments: /t:Build F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\DuplicateCompileItems.csproj /restore\r\nExit Code: 0\r\nStdOut:\r\nMicrosoft (R) Build Engine version 16.6.0-preview-20208-15+2f58c1427 for .NET Framework\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\nBuild started 5/16/2020 3:36:06 AM.\r\nProject "F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\DuplicateCompileItems.csproj" on node 1 (Restore target(s)).\r\n_GetAllRestoreProjectPathItems:\r\n Determining projects to restore...\r\nRestore:\r\n Restoring packages for F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\DuplicateCompileItems.csproj...\r\n Committing restore...\r\n Generating MSBuild file F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\obj\DuplicateCompileItems.csproj.nuget.g.props.\r\n Generating MSBuild file F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\obj\DuplicateCompileItems.csproj.nuget.g.targets.\r\n Writing assets file to disk. Path: F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\obj\project.assets.json\r\n Restored F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\DuplicateCompileItems.csproj (in 803 ms).\r\n \r\n NuGet Config files used:\r\n F:\workspace\_work\1\s\artifacts\tmp\Release\NuGet.Config\r\n F:\workspace\_work\1\s\NuGet.Config\r\n C:\Users\vsagent\AppData\Roaming\NuGet\NuGet.Config\r\n C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config\r\n \r\n Feeds used:\r\n https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-aspnetcore-8a4133b3/nuget/v3/index.json\r\n https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-aspnetcore-e81033e0/nuget/v3/index.json\r\n https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json\r\n https://api.nuget.org/v3/index.json\r\n https://dotnetfeed.blob.core.windows.net/nuget-nugetclient/index.json\r\n https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json\r\nDone Building Project "F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\DuplicateCompileItems.csproj" (Restore target(s)).\r\nProject "F:\workspace\_work\1\s\artifacts\tmp\Release\DuplicateComp---D1326FC3\DuplicateCompileItems\DuplicateCompileItems.csproj" on node 1 (Build target(s)).\r\nPrepareForBuild:\r\n Creating directory "bin\Debug\netstandard1.6\".\r\n Creating directory "obj\Debug\netstandard1.6\".\r\nCoreCompile:\r\n C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;DEBUG;NETSTANDARD;NETSTANDARD1_6 /highentropyva+ /reference:F:\workspace\_work\1\s\artifacts\.nuget\packages\microsoft.win32.primitives\4.3.0\ref\netstandard1.3\Microsoft.Win32.Primitives.dll /reference:F:\workspace\_work\1\s\artifacts\.nuget\packages\system.appcontext\4.3.0\ref\netstandard1.6\System.AppContext.dll /reference:F:\workspace\_work\1\s\artifacts\.nuget\packages\system.collections.concurrent\4.3.0\ref\netstandard1.3\System.Collections.Concurrent.dll /reference:F:\workspace\_work\1\s\artifacts\.nuget\packages\system.collections\4.3.0\ref\netstandard1.3\System.Collections.dll /reference:F:\workspace\_work\1\s\artifacts\.nuget\packages\system.console\4.3.0\re

**Comment by wli3** [comment]
looking into....

**Comment by wli3** [comment]
cherry-pick this fix https://github.com/dotnet/sdk/commit/cfbb43f95db08a9cdbf85d019b5d9c3ed9616e21

**Pull request merged**
