### PR TITLE
[Internal to External Port] Templating Nuget Config Changes, MSBuild

### PR DESCRIPTION
**Pull request by nagilson**
This ports more of the security changes we did internally for the now public MSRC

* Not sure if we need to preserve the change to nuget-client trusted.  @kartheekp-ms is getting back on that * https://github.com/dotnet/sdk/pull/28548/commits/59fa9ca0bd4332de208c4d3a50c7ade6c3d8290d --> We're OK here.

* Why is the diff showing changes to eng\versions when they actually reflect what is currently in the release/7.0.1xx branch? Might be a GH bug ? --> Yes it's a github bug. 

* We may want to have template engine confirm that we don't need to downgrade ubuntu and any of their dependency changes have gone in related to the changes here @dotnet/templating-engine-maintainers --> This is due to changes internally and should be fine, OK

* Getting confirmation from MSBuild side @Forgind --> OK

### CODE REVIEW

**Comment by kartheekp-ms** [comment]
> Not sure if we need to preserve the change to nuget-client trusted. @kartheekp-ms is getting back on that * https://github.com/dotnet/sdk/commit/59fa9ca0bd4332de208c4d3a50c7ade6c3d8290d

The commit linked above overwrites other commits because the [current version in `release/7.0.1xx`](https://github.com/dotnet/sdk/blob/release/7.0.1xx/eng/Version.Details.xml#L108-L111) is higher than the version mentioned in the commit https://github.com/dotnet/sdk/commit/59fa9ca0bd4332de208c4d3a50c7ade6c3d8290d. We are working on a new insertion into .NET SDK  cc @dominoFire @nkolev92

**Comment by nagilson** [comment]
> > Not sure if we need to preserve the change to nuget-client trusted. @kartheekp-ms is getting back on that * [59fa9ca](https://github.com/dotnet/sdk/commit/59fa9ca0bd4332de208c4d3a50c7ade6c3d8290d)
> 
> The commit linked above overwrites other commits because the [current version in `release/7.0.1xx`](https://github.com/dotnet/sdk/blob/release/7.0.1xx/eng/Version.Details.xml#L108-L111) is higher than the version mentioned in the commit [59fa9ca](https://github.com/dotnet/sdk/commit/59fa9ca0bd4332de208c4d3a50c7ade6c3d8290d). We are working on a new insertion into .NET SDK cc @dominoFire @nkolev92

Makes sense, that's what I figured. Thank you for confirming 😄

**Comment by Forgind** [comment]
> * Why is the diff showing changes to eng\versions when they actually reflect what is currently in the release/7.0.1xx branch? Might be a GH bug ? --> Yes it's a github bug.

I'm a bit surprised by this, since it looks like the changes (at least the one I looked at) went in 17 hours ago, so you'd think it'd be up-to-date by now. I noticed there are conflicts, so maybe it has something to do with that?

> * Getting confirmation from MSBuild side @Forgind

Sorry, what am I confirming?

**Review by JanKrivanek — APPROVED** [review]
Looks good from template engine point of view. Thank you!

**Comment by nagilson** [comment]
@marcpopMSFT  we have confirmation now from all relevant parties

**Pull request merged**
