### PR TITLE
Include app.config file in published files if it exists

### LINKED ISSUE #314: AutoGenerateBindingRedirects config file not included in publish output
I manually set AutoGenerateBindingRedirects to true (although I noticed this will happen by default per #267), but when I run 'dotnet publish3 <name>.csproj', the file '<name>.exe.config' is not included in publish output.

I'm repro-ing this on an ASP.NET Core (.NET Framework) Web API project

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #314

### CODE REVIEW

**Comment by dsplaisted** [comment]
#### Scenario 
Publish an ASP.NET Core application targeting .NET Framework.

#### Bug
#314

#### Workarounds
Copy file manually from output folder to publish folder.

It would probably also be possible to add a target to the .csproj file to inject the intermediate app.config file in the items to publish.

#### Risk
Low - this adds an additional file to the publish output which was already part of the normal output.

#### Performance Impact
Minimal - copying an additional file during build

#### Regression Analysis
This is probably a regression from the project.json based .NET CLI, but has probably never worked before with the MSBuild-based .NET Core tooling.

**Comment by dsplaisted** [comment]
@nguerrera @srivatsn for review

**Review by nguerrera — APPROVED** [review]

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
@MattGertz for approval

**Review by eerhardt — APPROVED** [review]

**Comment by MattGertz** [comment]
Approved.

**Pull request merged**
