### PR TITLE
Package System.IO.FileSystem facade with SDK

### PR DESCRIPTION
**Pull request by natidea**
Fixes [365633](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/365633)

This is a tactical fix to package this façade along with the SDK.

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by natidea** [comment]
/cc @MattGertz for Escrow

**Customer scenario**: Users building .NET Core Apps occasionally run into build failures stating that `System.IO.FileSystem` was not found. There are multiple scenarios where this occurs including after adding a NuGet package, or adding a Unit test to the solution. This is likely caused by a recent change to relocate the csc compiler in the MSBuild Bin directory. This is a tactical fix to package this façade along with the SDK.

**Bugs this fixes:**: [365633](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/365633) https://github.com/NuGet/Home/issues/4233

**Workarounds, if any**: Copy `System.IO.FileSystem` into `%VSINSTALLDIR%\MSBuild\Sdks\Microsoft.NET.Sdk\tools\net46\`

**Risk**: Low. 

**Performance impact**: Adds a small DLL (23KB) to the relevant workloads

**Is this a regression from a previous update?**: Yes, likely caused by MSBuild update which moved location of facades

**Root cause analysis:** This is likely caused by a recent change to relocate the csc compiler and facades in the MSBuild Bin directory.

**How was the bug found?**: Dogfooding

**Comment by rainersigwald** [comment]
I have no problem with this tactical fix, so all of these questions can wait.

What specifically broke when Roslyn moved? Was something inadvertently locating this assembly from the MSBuild folder? What's the right long-term fix?

cc @OmarTawfik

**Comment by natidea** [comment]
The Microsoft.NET.Build.Tasks relies on this façade, indirectly through one of its portable library dependencies (probably NuGet). The Fusion logs show:

```
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/System.IO.FileSystem.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/System.IO.FileSystem/System.IO.FileSystem.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/System.IO.FileSystem.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/System.IO.FileSystem/System.IO.FileSystem.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/Sdks/Microsoft.NET.Sdk/tools/net46/System.IO.FileSystem.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/Sdks/Microsoft.NET.Sdk/tools/net46/System.IO.FileSystem/System.IO.FileSystem.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/Sdks/Microsoft.NET.Sdk/tools/net46/System.IO.FileSystem.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/Sdks/Microsoft.NET.Sdk/tools/net46/System.IO.FileSystem/System.IO.FileSystem.EXE.
```

**Comment by tmat** [comment]
@rainersigwald This is good fix long term as well. We can also consider shipping CoreFX facades and libraries with msbuild (in ```MSBuild/15.0/Bin``` dir), so that they are available to all tasks and tasks that ship with msbuild don't need to carry these dlls with them.

**Comment by tmat** [comment]
It's ok for now, but I would avoid hardcoding the assembly version numbers in Microsoft.NET.Sdk.Nuget.targets. It would be more robust if they were generated based on the versions of the real dependencies.

**Comment by tmat** [comment]
👍

**Comment by OmarTawfik** [comment]
@rainersigwald @tmat I agree. If MSBuild depends on these libraries, then it should deploy its own copy to the `bin` directory (instead of relying on the Roslyn ones).

**Comment by rainersigwald** [comment]
@OmarTawfik MSBuild doesn't, but arbitrary tasks that run in our process might, and it seems reasonable to not force task authors to redistribute them. https://github.com/Microsoft/msbuild/issues/1542 to track @tmat's suggestion.

**Comment by natidea** [comment]
Approved to merge

**Pull request merged**
