### PR TITLE
[Containers] Fix parsing and error reporting of ports that lack port type metadata

### PR DESCRIPTION
**Pull request by baronfel**
## Description

Users that attempted to use the SDK to declare open ports in their containers had a very difficult time using the documented pathways due to bugs in the validation and error reporting. The reported error didn't match the user's _actual_ data problem, and the suggested fix wouldn't resolve the users' problem.

## Customer Impact

Customers could workaround the issue by fully-specifying the Port to declare, but this was hard to discover and the docs, errors, and user expectations for MSBuild didn't guide users to success.

## Regression

**No**, this has been a problem since the first version of the feature

## Risk
**Low** - we have very broad test coverage, and in fact had codified _bad_ behavior in the tests. Making the tests reflect the actual desired user experience verified the error and the fix very easily.

## Technical details

Fixes https://github.com/dotnet/sdk-container-builds/issues/596

There were two problems:
* non-existent metadata from MSBuild is an empty string, not null, so the 'is a port present' check needed to take this into account
* the flags error enum needs to be made of all-non-zero members or else `Enum.HasFlag` will always return true for the zero value. this is documented and understandable behavior (since HasFlag is shorthand for `(value & target) == target`, and anything AND-ed with 0 will be 0.

### CODE REVIEW

**Review by MiYanni — APPROVED** [review]

**Review by JanKrivanek — APPROVED** [review]

**Comment by baronfel** [comment]
Sanity check - @marcpopMSFT this was targeting 9.0.100 because it's a bug in validation and is hard for users to understand. Guessing we need Tactics approval at this point?

**Review by MichalPavlik — APPROVED** [review]

**Comment by baronfel** [comment]
Closing as @surayya-MS got this merged in already in teh 8.0.4xx prerequisite PR she got merged!

**Comment by baronfel** [comment]
wrong PR - this one got approved by servicing.

**Pull request merged**
