### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by dsplaisted**
- Suppress .NET CLI first run experience in Visual Studio
- Support environment variable to run tests using full framework MSBuild instead of .NET Core version

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
We should investigate if Jenkinks already has a good enough msbuild to run desktop msbuild tests. If so, let's make this a gate.

**Comment by dsplaisted** [comment]
@srivatsn Since this only affects tests, can we go ahead and merge this (ie without escrow signoff)?

**Comment by dsplaisted** [comment]
> We should investigate if Jenkinks already has a good enough msbuild to run desktop msbuild tests. If so, let's make this a gate.

@nguerrera Good idea.  Command line builds using full framework MSBuild are currently broken in master, so we'll need to merge dev15-rc3 into master first to get the fix from #699.

We'll also need to make sure we don't hit path length issues in our infrastructure.  Full framework MSBuild appears to generate files with longer paths, and as such I disabled the path too long checks if we're using the full version.

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
@MattGertz this is a test-only change. Can you please approve?

**Comment by MattGertz** [comment]
@srivatsn I don't need to approve test-only.  Go for it.

**Comment by nguerrera** [comment]
> We'll need to merge dev15-rc3 into master first

#728

**Pull request merged**
