### PR TITLE
Update branding to 6.0.117

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@dotnet/domestic-cat looks like the same test failing multiple times. But since this is only a version update, any ideas what could cause this failure?

**Comment by nagilson** [comment]
The test is hard to decipher and I don't think we should've checked it in the way it was written, but it's failing because net46 tests are failing as they can't load due to a "Security Exception":

```
Testhost process exited with error: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'testhost.net46.x86, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```
But I don't see any strong name assembly references (and it the testhost for net46) so I'm not sure why this is happening yet and asking around. Let me know if you've seen this before.

**Comment by marcpopMSFT** [comment]
I pinged @nohwnd offline and he'll take a look on Tuesday once he's back from time off. Warned tactics that we won't be open for  changes till next week in this branch.

**Comment by nagilson** [comment]
@joeloff have been looking at it as well this morning. It happens regardless of the TFM, even for net452 and net48. We were hoping to see if there was a change in the testhost exes but all of the green 6.0.100 runs were deleted :(

**Comment by nagilson** [comment]
@joeloff noticed the testhost is only delay-signed. Not sure if that helps. Thanks @nohwnd for taking a look.

**Comment by mmitche** [comment]
@nohwnd @nagilson What are the next steps here? This will block the May release.

Re: costs, the retention policy on AzDO runs is only 60 days max, IIRC.

**Pull request merged**
