### PR TITLE
Bump Microsoft.Extensions.DependencyModel to 1.0.2

### PR DESCRIPTION
**Pull request by TheRealPiotrP**
@srivatsn @livarcocc

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Comment by dsplaisted** [comment]
What's the context for this change?  It looks like it's failing on full MSBuild because of an assembly version mismatch for Microsoft.DotNet.PlatformAbstractions.

**Comment by eerhardt** [comment]
> It looks like it's failing on full MSBuild because of an assembly version mismatch for Microsoft.DotNet.PlatformAbstractions.

@livarcocc - do you know of this issue?

> What's the context for this change? 

We were depending on a pre-release version of DependencyModel.  Instead, we should be using an officially shipped version.  I'll send you the full email on the issue.

**Comment by srivatsn** [comment]
This was approved in shiproom as part of a CLI change.

**Comment by livarcocc** [comment]
@eerhardt we chatted with @dsplaisted a few days ago. I believe we are on the same page.

**Pull request merged**
