### PR TITLE
Insert NuGet Build 4.6.0-rtm-4918 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-rtm-4918 into sdk release/2.1.1xx branch

### CODE REVIEW

**Comment by nguerrera** [comment]
Ping @livarcocc @rohit21agrawal who is on point for driving this through?

**Comment by rohit21agrawal** [comment]
@nguerrera I can help, what do you need from us?

**Comment by nguerrera** [comment]
@rohit21agrawal I got caught up on why the prior PRs failed and I'm investigating. I will let you know if I need something from you.

**Comment by nguerrera** [comment]
@livarcocc @rohit21agrawal OK, the original thing (about the redist list path) is addressed. Next failure is because nuget targets are using a feature that did not exist in msbuild 15.3 -- SkipNonExistentTargets. I don't think we should be taking that into 2.1.100. Do we not expect that to work in 15.3? We have done some work to warn about using 15.7 for .NET Core 2.1 / SDK 2.1.300, but not >15.3 for 2.1.100.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT_FullFramework Debug
@dotnet-bot Test Windows_NT_FullFramework Release

Have updated the machine affinity for full framework tests to 15.5. The tests should pass now.

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
