### PR TITLE
Fixed the download scripts to consume cli rel/1.0.0 branch

### PR DESCRIPTION
**Pull request by 333fred**
This fixes the download script to download from the correct location. This is an infrastructure-only change.

### CODE REVIEW

**Comment by 333fred** [comment]
Tagging @srivatsn @dotnet/project-system for review.

**Comment by 333fred** [comment]
Until this is merged, new clones will not be able to build, and Jenkins builds will fail.

**Review by srivatsn — APPROVED** [review]

**Review by dsplaisted — APPROVED** [review]
There are some unnecessary whitespace changes, it would be nice to only change the script url.

**Comment by nguerrera** [comment]
💯

**Comment by nguerrera** [comment]
@333fred removing the whitespace changes in separate commit is the worst of both worlds. No cleanup and still difficult to review diff in history.

**Review by nguerrera — APPROVED** [review]

**Comment by 333fred** [comment]
@nguerrera squashed

**Comment by nguerrera** [comment]
:shipit: (thanks for squashing)

**Pull request merged**
