### PR TITLE
Merge 3.1.4xx branches to 5.0.100/master

### PR DESCRIPTION
**Pull request by rainersigwald**
This includes changes from @sfoslund, @MSLukeWest, @AaronRobinsonMSFT, and @drewnoakes that weren't merged into master  already. Can y'all please check my conflict resolution?

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by MSLukeWest — APPROVED** [review]

**Review by sfoslund — APPROVED** [review]
Thanks Rainer!

**Review by drewnoakes — APPROVED** [review]

**Comment by wli3** [comment]
2 tests are failing

**Comment by sfoslund** [comment]
> RunFilesCopiedToPublishDirTest
Expected collection to contain a single item matching i.RelativePath.Equals(Format("{0}{1}", value(Microsoft.NET.Publish.Tests.FilesCopiedToPublishDirTests+<>c__DisplayClass2_1).CS$<>8__locals1.testProject.Name, value(Microsoft.NET.Publish.Tests.FilesCopiedToPublishDirTests+<>c__DisplayClass2_1).exeSuffix), OrdinalIgnoreCase), but the collection is empty.

> GroupBuildsWithoutPublish
Expected directory "F:\workspace\_work\1\s\artifacts\tmp\Release\GroupBuildsWi---EFE7EAA9\TestPublishOutputGroup\bin\Debug\netcoreapp3.0\win-x86\publish" not to exist.

@MSLukeWest it looks like you wrote these tests, any idea why they're failing?

**Comment by MSLukeWest** [comment]
> > RunFilesCopiedToPublishDirTest
> > Expected collection to contain a single item matching i.RelativePath.Equals(Format("{0}{1}", value(Microsoft.NET.Publish.Tests.FilesCopiedToPublishDirTests+<>c__DisplayClass2_1).CS$<>8__locals1.testProject.Name, value(Microsoft.NET.Publish.Tests.FilesCopiedToPublishDirTests+<>c__DisplayClass2_1).exeSuffix), OrdinalIgnoreCase), but the collection is empty.
> 
> > GroupBuildsWithoutPublish
> > Expected directory "F:\workspace_work\1\s\artifacts\tmp\Release\GroupBuildsWi---EFE7EAA9\TestPublishOutputGroup\bin\Debug\netcoreapp3.0\win-x86\publish" not to exist.
> 
> @MSLukeWest it looks like you wrote these tests, any idea why they're failing?

I checked in an update to fix the tests, let me know if they still fail

**Comment by sfoslund** [comment]
@rainersigwald is this good to go in?

**Comment by rainersigwald** [comment]
Should be good to go now after conflict resolution.  Looks like a Roslyn update snuck into 3.1 that hadn't gotten to master yet, so I went ahead and took it.

**Pull request merged**
