### PR TITLE
Switch the templates authoring to produce V3 VSIXes

### PR DESCRIPTION
**Pull request by srivatsn**
fixes: [364332](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=364332&triage=true)

@jinujoseph @mavasani @dotnet/project-system

### CODE REVIEW

**Comment by mavasani** [comment]
Can you also add this commit so templates get deployed to the hive during build: https://github.com/dotnet/sdk/pull/616/commits/c74000d64d662271acd65fa9685b1fa0de5f108a

**Comment by srivatsn** [comment]
Tried that but it doesn't deploy the C# templates because the installed version is higher. We'll need more changes to build version 42.42.42.42 and since that's not related to vsix v3, i'll keep that out of this PR.

**Review by jinujoseph — APPROVED** [review]

**Review by mavasani — APPROVED** [review]

**Comment by srivatsn** [comment]
Tagging @MattGertz  for approval. VS's setup build wants to eliminate all VSIX v2s and this helps with that. I've installed a PR build and verified that it installs correctly.

**Comment by natidea** [comment]
Approved to merge via [377254](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/377254)

**Pull request merged**
