### PR TITLE
Fix regression vs. MSBuild.Sdk.Extras additional TFM support

### PR DESCRIPTION
**Pull request by nguerrera**
**Customer scenario**
Using MSBuild.Sdk.Extras community package to build libraries cross-targeting to UWP/Xamarin/PLIB. Popular libraries like Rx.NET cannot build with 2.0 Preview 2 SDK without this.

**Bugs this fixes:**
#1335 

**Workarounds, if any**
None

**Risk**
Low.

**Performance impact**
Low

**Is this a regression from a previous update?**
Yes

**Root cause analysis:**
Missing test coverage for scenario (added)

**How was the bug found?**
Customer reported

--

I have verified that I can build Rx.NET. 

There were in fact two issues:

1. Not respecting NuGetTargetMoniker over TargetFrameworkMoniker in assets file check
2. Running unsupported TFM check in front of restore, which prevents MSBuild.Sdk.Extras from being restored and handling TFMs that we do not

(2) means some compromise on recent work to clean up the error messages in the invalid target framework cases. Restore has a sub-optimal message that can mask our better error message in build when build is not run after failed restore, which is often the case. I've filed https://github.com/NuGet/Home/issues/5413 to get a better error message from restore. Our better error still shows up nicely in the IDE and I've taken care to make sure that we don't regress other design-time noise that (2) fixed while still getting out of restore's way. 

@onovotny @dotnet/dotnet-cli

### CODE REVIEW

**Comment by nguerrera** [comment]
@MattGertz for approval

**Review by livarcocc — APPROVED** [review]

**Comment by nguerrera** [comment]
Linux test failure is because MSBuild.Sdk.Extras imports a file with casing different than the actual file name: https://github.com/onovotny/MSBuildSdkExtras/blob/master/src/build/netstandard1.0/MSBuild.Sdk.Extras.props#L3

I thought my trick to reset language targets to default would be enough to test x-plat, but it is not due to that. Changing to WindowsOnlyFact

**Comment by onovotny** [comment]
@nguerrera I can fix that in an update to the package

**Comment by nguerrera** [comment]
If it's not too much trouble. It would help devs working on *nix catch any regression locally without delaying until Windows CI kicks in. It's not urgent though.

**Comment by livarcocc** [comment]
@MattGertz this is the regression we talked about. This is the last fix we have to take for preview2. After this goes in, I can insert the SDK into the CLI and branch the CLI. Can you approve?

**Comment by onovotny** [comment]
@nguerrera I just pushed 1.0.3 to NuGet with the case-sensitivity fix, should be visible in a few min once it's indexed.

**Comment by nguerrera** [comment]
Thanks. I've amended the fix for the test failure on linux to just pull in 1.0.3. :)

**Comment by onovotny** [comment]
Will this be in the nightly build that is available tomorrow to try out?

**Comment by livarcocc** [comment]
@onovotny Yes.

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Release

**Comment by onovotny** [comment]
@livarcocc where do I find the Preview2 build that has this fix? When I look at https://github.com/dotnet/cli/tree/release/2.0.0-preview2, the latest tag has already jumped to preview 3?

**Pull request merged**
