### PR TITLE
Free metadata reader and assembly after reading metadata

### LINKED ISSUE #1453: GetFileDependsOnNETStandard holds handles to assemblies after it returns
I believe this is the root cause of https://github.com/NuGet/Home/issues/5609.

I've been looking at this with @mishra14. 

It appears that [GetFileDependsOnNETStandard](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.netstandard.cs#L14), introduced to support .NET Standard 2.0 in VS 15.3, holds locks on files longer than it should.

It [appears](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.net46.cs#L130) to close the handle to the files it's inspecting, but we can observe through the debugger that they don't get closed immediately--stepping over that line and running a `handle.exe` search shows the handle still open.

When `devenv.exe` is started from an environment with `set ImplicitlyExpandNETStandardFacades=false`, project creation succeeds. That property [disables calling `GetDependsOnNETStandard`](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L24).

### PR DESCRIPTION
**Pull request by ericstj**
Fixes leak of assemblies where they weren't being closed until GC.

Fixes #1453 

/cc @rainersigwald @livarcocc

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Review by rainersigwald — APPROVED** [review]

**Comment by rainersigwald** [comment]
I applied the private you sent offline and can confirm that this fixes the scenario from https://github.com/NuGet/Home/issues/5609.

**Comment by ericstj** [comment]
@dotnet-bot test Windows_NT_FullFramework Release

**Comment by ericstj** [comment]
@livarcocc / @nguerrera I think folks want to take this for 2.0, anything we need to do to get that on the table?

**Comment by nguerrera** [comment]
We need the same template here as other 2.0 pull requests and a linked VSO bug with the same ask mode template as the other bug fix we took to extensions (crypto facade change). I can't chase down links right now as I'm on my phone. I'll be in the office at ~10:30.

**Comment by livarcocc** [comment]
This has been approved in shiproom.

**Pull request merged**
