### PR TITLE
Cleanup yaml

### PR DESCRIPTION
**Pull request by mmitche**
- Remove unused and obselete variables
- Remove unneeded feeds (faster restores?)
- Update test data package to a 7.0 version

### CODE REVIEW

**Comment by mmitche** [comment]
Official build test: https://dnceng.visualstudio.com/internal/_build/results?buildId=1936997&view=results

**Comment by mmitche** [comment]
The Extensions.FileSystemGlobbing dependency was 6.0 preview,7 old. Which is wild.

**Comment by mmitche** [comment]
Official build test: https://dnceng.visualstudio.com/internal/_build/results?buildId=1937501&view=results

**Comment by AraHaan** [comment]
I had a similar PR but since this is newer it could be closed as a duplicate then.

**Pull request closed without merging**
