### PR TITLE
Fix workload nuget retry issue

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/21319

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]
Is there a way to have test coverage of this code that was broken?

**Comment by sfoslund** [comment]
> Is there a way to have test coverage of this code that was broken?

Sure, just added test coverage

**Comment by jonathanpeppers** [comment]
Went to see if this made it to `dotnet/installer/release/6.0.1xx-rc2` yet, but I don't see a commit or even a PR for it:

* https://github.com/dotnet/installer/commits/release/6.0.1xx-rc2
* https://github.com/dotnet/installer/pulls?q=is%3Apr+is%3Aopen+6.0.1xx-rc2

Is the code flowing correctly? Maybe I'm just checking too soon.

**Comment by sfoslund** [comment]
Thanks for pointing this out, the subscription was disabled somehow. I've reenabled it and the PR is here: https://github.com/dotnet/installer/pull/12128

**Comment by mmitche** [comment]
> Thanks for pointing this out, the subscription was disabled somehow. I've reenabled it and the PR is here: [dotnet/installer#12128](https://github.com/dotnet/installer/pull/12128)

The flow is internal for rc2, so we should keep this off

**Comment by jonathanpeppers** [comment]
@mmitche I commented in Teams on this. Let us know how we're supposed to be consuming internal builds, thanks!

Right now our subscription is:
```
https://github.com/dotnet/installer (.NET 6.0.1xx SDK RC 2) ==> 'https://github.com/xamarin/xamarin-android' ('release/6.0.1xx-preview9')
- Id: 0a869813-3c57-4385-2032-08d97cd9a8c8
- Update Frequency: EveryDay
- Enabled: True
- Batchable: False
- Merge Policies: []
- Last Build: 20210923.54 (3694b8b984f3b0e885277793600210f115e7b32a)
```

**Pull request merged**
