### PR TITLE
Merge release/2.0.0 into master

### PR DESCRIPTION
**Pull request by livarcocc**
@dotnet/dotnet-cli 

@MattGertz Merging branches.

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Debug

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Release

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Release

**Comment by nguerrera** [comment]
Failure on full framework is because this incoming change to netci.groovy does not impact the current PR: https://github.com/dotnet/sdk/pull/1305/files#diff-2d212ad84506951c8f928e21aed24580

**Pull request merged**
