### PR TITLE
Merge release/2.1 into master

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
Empty PR that is just merging empty merge commits.

**Comment by tannergooding** [comment]
test Windows_NT Debug please
test Windows_NT Release please
test Windows_NT_FullFramework Release please

**Comment by tannergooding** [comment]
test Ubuntu14.04 Release please
test Windows_NT Debug please
test Windows_NT_FullFramework Release please

**Comment by tannergooding** [comment]
test Windows_NT Debug please
test Windows_NT Release please
test Windows_NT_FullFramework Release please

**Review by ghost — APPROVED** [review]

**Pull request merged**
