### PR TITLE
Add the test that verifies generated join symbol with Ref to derived symbol can be evaluated correctly

### PR DESCRIPTION
**Pull request by GangWang01**
### Problem
https://github.com/dotnet/templating/issues/6291 - lacks test for generated symbol with ref to computed symbol.

### Solution
Add the test.

### CODE REVIEW

**Comment by vlada-shubina** [comment]
Please move this test to dotnet/templating as it is testing authoring feature. example: https://github.com/dotnet/templating/blob/main/test/Microsoft.TemplateEngine.IDE.IntegrationTests/SnapshotTests.cs

**Comment by GangWang01** [comment]
> Please move this test to dotnet/templating as it is testing authoring feature. example: https://github.com/dotnet/templating/blob/main/test/Microsoft.TemplateEngine.IDE.IntegrationTests/SnapshotTests.cs

@vlada-shubina when I moved the test to dotnet/templating using verification engine as you suggested, I found a problem. dotnet used by the verification engine in dotnet/templating is specified in https://github.com/dotnet/templating/blob/b1a9547fd5633e59fec7eb609b644c0b387cdf02/global.json#L3 which doesn't have the latest change to dotnet/templating. It's not able to catch issues through the test. I think the test should be placed in SDK. How do you think?

**Comment by vlada-shubina** [comment]
> > Please move this test to dotnet/templating as it is testing authoring feature. example: https://github.com/dotnet/templating/blob/main/test/Microsoft.TemplateEngine.IDE.IntegrationTests/SnapshotTests.cs
> 
> 
> 
> @vlada-shubina when I moved the test to dotnet/templating using verification engine as you suggested, I found a problem. dotnet used by the verification engine in dotnet/templating is specified in https://github.com/dotnet/templating/blob/b1a9547fd5633e59fec7eb609b644c0b387cdf02/global.json#L3 which doesn't have the latest change to dotnet/templating. It's not able to catch issues in time through the test. I think the test should be placed in SDK. How do you think?

We should use API when launching verify tests in templating.

**Comment by GangWang01** [comment]
I see. Thanks for the explanation!

**Pull request closed without merging**
