### PR TITLE
Add support to generate publish WebJob Run command file compatible wi…

### PR DESCRIPTION
**Pull request by anvillan**
Add support for WebJobs to generate `run` file compatible with Linux OS:
 - Define new `IsLinux` property in `Microsoft.NET.Sdk.Publish.TransformFiles.targets` target that will be taken by the command file content generator
 - In `GenerateRunCommandFile.cs` take `IsLinux` value to determine the `run` command file extension: Win: `.cmd`, Linux: `.sh`
 - In `WebJobsCommandGenerator.cs` use `IsLinux` to:
   - For `UseAppHost=True` use `dot-space` syntax to invocate command
   - Use property `pass-all-parameters` argument according to OS: Win:`%*`, Linux: `"$@"`
   - Add the `shebang` line to indicate it is a BASH scritp
 - Add UTs

### CODE REVIEW

**Review by vijayrkn — APPROVED** [review]

**Comment by vijayrkn** [comment]
@marcpopMSFT - The CI failures are unrelated to this change. This change is needed by VS. Can you please help merge this change?

**Comment by vijayrkn** [comment]
@marcpopMSFT - Also, can you pls confirm if this needs to be ported to any other 9.0 branches so that this will reach VS in the next insertion.

**Comment by anvillan** [comment]
@vijayrkn @marcpopMSFT 

After the 5th run, I was able to get a clean run. I just merged this PR.

@marcpopMSFT, we still need your help with Vijay's question about 9.0 branches to port the change, so it reaches VS.

**Comment by vijayrkn** [comment]
@anvillan - Looks like this needs to be ported to [release/9.0.1xx-preview7](https://github.com/dotnet/sdk/tree/release/9.0.1xx-preview7). Can you please do a cherry-pick?

**Comment by baronfel** [comment]
We've got a backport command you can use in this repo as well - /backport to BRANCH_NAME

**Comment by baronfel** [comment]
/backport to release/9.0.1xx-preview7

I did the backport to get you unblocked - we can take a look at repo perms for @anvillan

**Comment by anvillan** [comment]
@baronfel  
I just changed my 'Membership' to 'Public' (was 'Private'). This should make it work the next time

**Pull request merged**
