### PR TITLE
[9.0.2xx] sln migrate, sln list, sln add

### PR DESCRIPTION
**Pull request by edvilme**
Manual backport of #44419 , #44537 , #44661 #44570, #45130, and #45366 to release/9.0.2xx

Fixes https://github.com/dotnet/sdk/issues/40913.

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@baronfel we should get this reviewed tomorrow and merge so that it can get into the next VS insertion for preview 3.

**Review by Forgind — APPROVED** [review]
Content-wise, I glanced through the commits, and they looked equivalent to what was merged as I'd expected, but it's essentially a whole new set of commits, which I don't like too much. I would've hoped for at least some of them to not be in need of resolving merge conflicts, especially if you tweak it to look as the next commit would expect in earlier commits...but I probably shouldn't nitpick on that right now. You can make that a little easier too by making sure all your commits are in order, which you mostly did except one that got moved out of place 😉

**Review by baronfel — APPROVED** [review]

**Comment by baronfel** [comment]
Since the only failing checks are due to the macOS arm64 leg, let's merge on read and get this in! @marcpopMSFT care to do the honors?

**Comment by marcpopMSFT** [comment]
> Content-wise, I glanced through the commits, and they looked equivalent to what was merged as I'd expected, but it's essentially a whole new set of commits, which I don't like too much. I would've hoped for at least some of them to not be in need of resolving merge conflicts, especially if you tweak it to look as the next commit would expect in earlier commits...but I probably shouldn't nitpick on that right now. You can make that a little easier too by making sure all your commits are in order, which you mostly did except one that got moved out of place 😉

We can give pointers when he's back in the office as there are some strategies for avoiding merge conflicts especially in our repo (target the live branch and let codeflow take to main as an example).

**Comment by marcpopMSFT** [comment]
We'll get remove in once it passes checks.

**Pull request merged**
