### PR TITLE
Publish Roslyn Framework Toolset package as part of SDK

### PR DESCRIPTION
**Pull request by jjonescz**
Part of https://github.com/dotnet/roslyn/issues/72672.
Official build run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2413757&view=results

### CODE REVIEW

**Review by jaredpar — APPROVED** [review]

**Comment by jaredpar** [comment]
@baronfel

**Review by baronfel — APPROVED** [review]
This LGTM - I tested locally and it does what it says on the tin. We could merge and start checking installer outputs.

**Comment by baronfel** [comment]
@jjonescz can you solve conflicts? Happy to merge after that.

**Comment by jjonescz** [comment]
Unfortunately an unrelated test (`CanSortByDownloadCountAndThenByName`) started failing now (it's failing in all other PRs as well)

**Comment by baronfel** [comment]
I'm working on backports to skip that test until we can fix it up

**Pull request merged**
