### PR TITLE
Rollback razor tooling version

### PR DESCRIPTION
**Pull request by chsienki**

### CODE REVIEW

**Comment by chsienki** [comment]
@MichaelSimons @wtgodbe This rolls back the version of the razor tooling to the last version that included the now deleted package. I also set the dependencies to `Pinned="true"` which I *think* should stop them updating?

**Review by wtgodbe — APPROVED** [review]
Nice! This means we won't have to disable the darc subscription either - but we'll need to remember to un-pin these once we ingest the "new" thing from razor-compiler.

**Comment by chsienki** [comment]
I've added the unpin to the umbrella merge issue so we don't forget, thanks

**Review by MichaelSimons — APPROVED** [review]
LGTM - Thanks for fixing this.

**Comment by wtgodbe** [comment]
This is the pipeline for this run but for whatever reason it's now showing up in the UI: https://dev.azure.com/dnceng/public/_build/results?buildId=1834837&view=results

**Comment by marcpopMSFT** [comment]
Darwin leg test failure may need this commit: https://github.com/dotnet/sdk/pull/26100/commits/83cc471c41263778c6980f660ab02f179c2e8459

**Comment by wtgodbe** [comment]
> Darwin leg test failure may need this commit: https://github.com/dotnet/sdk/commit/83cc471c41263778c6980f660ab02f179c2e8459

Done

**Pull request merged**
