### PR TITLE
[3.1.2xx] Update core-setup to 3.1.1

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
Probably will need a stage0 with 3.1.1

**Review by mmitche — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
The SDK from https://dev.azure.com/dnceng/internal/_build/results?buildId=505488 should unblock this

**Comment by wtgodbe** [comment]
> Expected command to pass but it did not.\r\nFile Name: F:\workspace\_work\1\s\.dotnet\dotnet.exe\r\nArguments: msbuild /t:Build F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj /restore /p:CopyLocalLockFileAssemblies=false\r\nExit Code: 1\r\nStdOut:\r\nMicrosoft (R) Build Engine version 16.5.0-preview-20079-01+2e5c73b34 for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n Restore completed in 836.83 ms for F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj.\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.NET.HostModel, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: File name: 'Microsoft.NET.HostModel, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: at Microsoft.NET.Build.Tasks.TaskBase.Execute() in //src/Tasks/Common/TaskBase.cs:line 38 [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\nF:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: [F:\workspace\_work\1\s\artifacts\tmp\Release\FSharp_app_ca---E240F746\TestApp.fsproj]\r\n\r\nStdErr:\r\n\r\n

Maybe need to get CLI -> Toolset -> Core-SDK as well

**Comment by wtgodbe** [comment]
Which would mean https://dev.azure.com/dnceng/internal/_build/results?buildId=505922

**Pull request merged**
