### PR TITLE
Deploy watch to redist

### PR DESCRIPTION
**Pull request by tmat**
This allows us to avoid rebuilding the whole `redist` layout every single time a change is needed in donet-watch during inner loop.

Previous workflow in dotnet-watch project was extremely painful:

After every change:
1)  close VS to avoid 
```
D:\sdk\src\Layout\redist\targets\OverlaySdkOnLKG.targets(47,5): error MSB3026: Could not copy "D:\sdk\.dotnet\shared\Microsoft.NETCore.App\8.0.0-alpha.1.22575.4\mscordbi.dll" to "D:\sdk\artifacts\bin\redist\Debug\dotnet\\shared\Microsoft.NETCore.App\8.0.0-alpha.1.22575.4\mscordbi.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App\8.0.0-alpha.1.22575.4\mscordbi.dll' because it is being used by another process. The file is locked by: "Microsoft Visual Studio 2022 Preview (65120)" [D:\sdk\src\Layout\redist\redist.csproj]
```
2) `taskkill /im dotnet.exe /f`
3) `taskkill /im msbuild.exe /f`
4) `build Redist.csproj`
5) Restart VS from `dogfood.cmd` environment.
6) Run test.

### CODE REVIEW

**Comment by tmat** [comment]
@arunath

**Comment by arkalyanms** [comment]
Think this might fire off a new S360 alert. I am not getting the dotnet/sdk repo alerts. It might hitting Jon.

**Review by arunchndr — APPROVED** [review]

**Comment by kasperk81** [comment]
related error randomly failing in prs:
> src\Layout\redist\targets\PublishDotnetWatch.targets(16,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not copy "D:\a\_work\1\s\artifacts\bin\dotnet-watch\Release\net8.0\cs\Microsoft.CodeAnalysis.Features.resources.dll" to "D:\a\_work\1\s\artifacts\bin\redist\Release\dotnet\sdk\8.0.100-ci\DotnetTools\dotnet-watch\8.0.100-ci\tools\net8.0\any\cs\Microsoft.CodeAnalysis.Features.resources.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\_work\1\s\artifacts\bin\redist\Release\dotnet\sdk\8.0.100-ci\DotnetTools\dotnet-watch\8.0.100-ci\tools\net8.0\any\cs\Microsoft.CodeAnalysis.Features.resources.dll' because it is being used by another process.

**Comment by tmat** [comment]
> 

Fixed in https://github.com/dotnet/sdk/pull/29343

**Pull request merged**
