### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by github-john-doe**

### CODE REVIEW

**Comment by github-john-doe** [comment]
Hello?

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@github-john-doe thanks for the PR. Please know that given the changes, I will squash your PR when merging.

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX10.12 Release

**Comment by github-john-doe** [comment]
Please?

**Comment by livarcocc** [comment]
Argh, forgot to squash. Oh well. It is in the past now.

@github-john-doe Thanks for the PR.

**Pull request merged**
