### PR TITLE
Merging internal commits for release/5.0.2xx

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mmitche this is hitting the incoherency issue too, what should we change the dependencies to?

**Comment by mmitche** [comment]
@wtgodbe This looks different. It looks like 5.0.207 should have been released but did not. @rbhanda

**Comment by mmitche** [comment]
https://www.nuget.org/packages/Microsoft.TemplateSearch.Common/6.0.100-rc.1.21451.20

**Comment by wtgodbe** [comment]
@mmitche @riarenas @MattGal any idea why the arcade restore is failing on mac?

> /Users/runner/work/1/s/artifacts/toolset/restore.proj : error : Package 'Microsoft.DotNet.Arcade.Sdk 5.0.0-beta.21427.7' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json': The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.

CC @marcpopMSFT and @lukas-lansky, this is still blocking us from finishing the 5.0 build

**Comment by mmitche** [comment]
> @mmitche @riarenas @MattGal any idea why the arcade restore is failing on mac?
> 
> > /Users/runner/work/1/s/artifacts/toolset/restore.proj : error : Package 'Microsoft.DotNet.Arcade.Sdk 5.0.0-beta.21427.7' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json': The author primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
> 
> CC @marcpopMSFT and @lukas-lansky, this is still blocking us from finishing the 5.0 build

Woah..this repo is somehow using a 5.0.200 preview version of the SDK. I've updated to 5.0.207

**Pull request merged**
