### PR TITLE
Switch away from expiring helix queues

### PR DESCRIPTION
**Pull request by dsplaisted**

### CODE REVIEW

**Review by MattGal — APPROVED** [review]
Thanks for staying on top of change!

**Review by mmitche — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@MattGal do you know what version of VS is in the Build.Windows.10.Amd64.VS2019.Open queues and is there a way for us to tell that from the test run?  A lot of tests are failing to find the SDK which implies we're using either an older VS or a newer SDK in the tests that aren't compatible.

**Comment by dsplaisted** [comment]
This has been superseded by a PR from @marcpopMSFT to switch to VS2022 queues.

**Pull request closed without merging**
