### PR TITLE
Update error message text when 2.0 SDK is required to build a project

### PR DESCRIPTION
**Pull request by dsplaisted**
Update error message to account for #1387.

cc @ericstj @terrajobst

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@MattGertz this is the other bug that needs insertion into VS. The one about .NET Framework and NETStandard 1.5 and 1.6.

**Comment by MattGertz** [comment]
VSO?

**Comment by livarcocc** [comment]
@MattGertz https://devdiv.visualstudio.com/DevDiv/_workitems?id=470493&_a=edit&triage=false

**Review by ericstj — COMMENTED** [review]
LGTM

**Pull request merged**
