### PR TITLE
Update Test project TestAppEchoDotnetRoot to current framework

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Comment by dsplaisted** [comment]
@mateoatr Any chance you could take a look at this?  We're updating tests to target the most recent target framework, and the `WhenDotnetRootIsSetItShouldSetDotnetRootToDirectoryOfMuxer` test is failing.  It looks like you updated it here: https://github.com/dotnet/sdk/commit/36e9be07f45cdcefdc54a7807de028272e89631b#diff-4ace2b060986c50233b1c04425f02134681963dea35c7a1f84ecd061a2abc122

**Comment by v-wuzhai** [comment]
@agocke @mateoatr any updates?

**Comment by mateoatr** [comment]
> @agocke @mateoatr any updates?

PTAL #25480

**Comment by v-wuzhai** [comment]
@mateoatr The test WhenDotnetRootIsSetItShouldSetDotnetRootToDirectoryOfMuxer is still failed after merged https://github.com/dotnet/sdk/pull/25480/commits/ad0001a0d0f8c38f723dff8a88991c4fcc1a2f17, Could you take a look?

**Comment by marcpopMSFT** [comment]
@v-wuzhai it looks like the change https://github.com/dotnet/sdk/commit/ad0001a0d0f8c38f723dff8a88991c4fcc1a2f17 was in main only but this change is against 6.0.4xx. Can you cherry-pick that into this branch to see if that fixes the test?

**Comment by marcpopMSFT** [comment]
Never mind, you already did that. @mateoatr Jason cherry-picked your fix into this branch but WhenDotnetRootIsSetItShouldSetDotnetRootToDirectoryOfMuxer is still failing. Can you take a look?

**Comment by agocke** [comment]
Mateo's no longer on the team -- I can take a look

**Comment by marcpopMSFT** [comment]
@v-wuzhai can you retarget or close depending on whether we still need this or not?

**Pull request closed without merging**
