### PR TITLE
update nuget to 4.3.0-rtm-4294

### PR DESCRIPTION
**Pull request by rohit21agrawal**
update nuget to 4.3.0-rtm-4394 to keep consistent with the latest insertion into VS d15rel branch.

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@nguerrera can you take a look at the failures here?

**Comment by rohit21agrawal** [comment]
ping.... @livarcocc @dsplaisted @nguerrera can anyone help investigate failures here?

**Comment by livarcocc** [comment]
@dotnet-bot Test this please.

**Comment by livarcocc** [comment]
@natidea can you take a look at these failures? They are happening in tests you added and I am not sure what the expected behavior is here.

**Comment by livarcocc** [comment]
@natidea can you take a look at these failures? They are happening in tests you added and I am not sure what the expected behavior is here.

**Comment by natidea** [comment]
Only looked briefly but it appears that the NuGet API is returning a (default) target framework after reading a log message that did not contain one, probably [on this line](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ReportAssetsLogMessages.cs#L79). 

Is this a recent/expected change? @emgarten @mishra14

**Comment by emgarten** [comment]
> Is this a recent/expected change? @emgarten @mishra14

This is expected, on the NuGet side the API was updated so that assets file log messages with no target graphs return all target graphs. Usually this means it is an error or warning that isn't specific to a TFM or RID, so it applies everywhere it can be shown.

Here is the change: https://github.com/NuGet/NuGet.Client/blame/dev/src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileExtensions.cs#L29-L33

Let me know if this is causing any issues for you. I can't fully tell from the code referenced as to why it is dropping the library when the target graphs are null, but I'm interested in any scenarios where the empty target graphs was needed.

**Comment by natidea** [comment]
OK thanks. I'll take a look and provide a patch for this PR

**Comment by emgarten** [comment]
Thanks @natidea!

**Comment by livarcocc** [comment]
@natidea do you have an ETA for the fix?

**Comment by livarcocc** [comment]
@srivatsn Flow of dependencies into the CLI.

**Comment by livarcocc** [comment]
@natidea We will have to port the fixes here as well: https://github.com/dotnet/sdk/pull/1428.

**Comment by rohit21agrawal** [comment]
@natidea the ubuntu tests are still failing.

**Comment by natidea** [comment]
This does not appear to be related to the diagnostics logger. @livarcocc do you know what is plaguing the Linux tests? Porting my commit to the other PR now.

**Comment by nguerrera** [comment]
```
13:25:43 dotnet-install: Download failed: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006779/dotnet-dev-ubuntu-x64.2.0.0-preview3-006779.tar.gz
```

**Comment by rohit21agrawal** [comment]
updated cli version

**Review by livarcocc — APPROVED** [review]

**Pull request merged**
