### PR TITLE
Insert NuGet Build 5.0.0-rtm.5821 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.0-rtm.5821 into sdk release/2.1.6xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
//cc @wli3

**Review by nguerrera — APPROVED** [review]

**Comment by wli3** [comment]
@dotnet-bot test this please

**Comment by wli3** [comment]
@dotnet-bot test this please

**Comment by wli3** [comment]
@dotnet-bot test OSX10.12 Debug
@dotnet-bot test OSX10.12 Release

**Pull request merged**
