### PR TITLE
Insert NuGet Build 4.6.0-preview1-4688 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-preview1-4688 into sdk master branch

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
ping @livarcocc

**Comment by livarcocc** [comment]
We need a CLI with this NuGet before this PR can turn green. Working on it.

**Comment by johnbeisner** [comment]
@rohit21agrawal 
Any ideas?

**Comment by rohit21agrawal** [comment]
What’s the error?

**Comment by johnbeisner** [comment]
@rohit21agrawal 
I think I understand the error now; see: https://github.com/dotnet/sdk/pull/1798
I am going to fix the '15.5 - master' merge first and then see if that resolves the NuGet insertion errors - pardon the noise.

**Comment by jainaashish** [comment]
@johnbeisner we've started a new insertion into VS and corresponding to SDK/CLI so i think we can run with new PR and discard this?

New PR# https://github.com/dotnet/sdk/pull/1807

**Comment by johnbeisner** [comment]
Discarding per @jainaashish

**Pull request closed without merging**
