### PR TITLE
Do not transform solution project dependencies into ProjectReference dependencies

### PR DESCRIPTION
**Pull request by cdmihai**
Fixes https://github.com/Microsoft/msbuild/issues/2274

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]
I'm not sure we should do this workaround instead of fixing #939. Then there wouldn't be anything special about SDK projects' solution build.

If we want to fix this for 15.3, this workaround seems like a good idea. For 15.5 I'd rather see the root cause fixed.

**Review by rainersigwald — CHANGES_REQUESTED** [review]
Last comment was supposed to be red, not green, sorry.

**Comment by cdmihai** [comment]
I think this change could be orthogonal to #939. It enables msbuild to behave like VS does, in the presence of sln based project dependencies. Without this change msbuild injects an extra ProjectReference, whereas VS does not. This makes building in VS different from building in the command line. Right now this difference in behaviour exposes #939. In the future it might have other random side effects.

**Comment by cdmihai** [comment]
In addition, the right user gesture for #939 is to explicitly declare a project reference inside the csproj file, whereas this PR handles the case when the user wants (for some unknown reason) a sln based dependency.

On the other hand, we could consider sln based dependencies obsolete, and in that sense encourage users to mark the dependency accordingly in the csproj instead. From this point of view it makes sense to not take this PR, and guide users to the correct solution when they use sln based dependencies and get a build error from the command line.

**Comment by rainersigwald** [comment]
When MSBuild is generating the from-solution-dependencies `ProjectReferences`, we [mark them](https://github.com/Microsoft/msbuild/blob/07c3b3392dc05e0e3aba18bdec235a374aa72301/src/Tasks/ResolveProjectBase.cs#L291-L295) with the same metadata that a user would use for an explicit reference.

This knob _is_ orthogonal to correct ProjectReference behavior, but I'm concerned about changing the in-solution build experience _only_ for SDK projects. That seems like something that'd come back to bite us in the future.

**Pull request closed without merging**
