### PR TITLE
Enable signing on all except pgo

### PR DESCRIPTION
**Pull request by mmitche**
Currently only dry-run signing

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
What about source-build?

**Comment by mmitche** [comment]
> What about source-build?

Source build does not sign. Excluded.

**Review by ellahathaway — APPROVED** [review]

**Comment by ViktorHofer** [comment]
`sdk-source-build` got broken by this change. It didn't get triggered.

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/sdk/pull/44324 to unblock builds

**Pull request merged**
