### PR TITLE
Add nativeToolsOnMachine flag

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes the failing Windows VMR builds

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@jkotas https://github.com/dotnet/runtime/commit/7745b5ec3db34cd358b26710c0ec32db8b0b23f7 might have broken source-build. Can you please take a look?

> /vmr/src/runtime/src/coreclr/tools/Common/TypeSystem/Common/Utilities/CustomAttributeTypeNameParser.cs(73,85): error CS0246: The type or namespace name 'TypeName' could not be found (are you missing a using directive or an assembly reference?) [/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler.TypeSystem/ILCompiler.TypeSystem.csproj]
    /vmr/src/runtime/src/libraries/Common/src/System/Reflection/TypeNameParser.Helpers.cs(107,31): error CS0246: The type or namespace name 'TypeName' could not be found (are you missing a using directive or an assembly reference?) [/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler.TypeSystem/ILCompiler.TypeSystem.csproj]
    /vmr/src/runtime/src/libraries/Common/src/System/Reflection/TypeNameParser.Helpers.cs(192,50): error CS0246: The type or namespace name 'TypeName' could not be found (are you missing a using directive or an assembly reference?) [/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler.TypeSystem/ILCompiler.TypeSystem.csproj]
    /vmr/src/runtime/src/coreclr/tools/Common/TypeSystem/Common/Utilities/CustomAttributeTypeNameParser.cs(32,33): error CS0246: The type or namespace name 'TypeNameParseOptions' could not be found (are you missing a using directive or an assembly reference?) [/vmr/src/runtime/src/coreclr/tools/aot/ILCompiler.TypeSystem/ILCompiler.TypeSystem.csproj]

https://dev.azure.com/dnceng-public/public/_build/results?buildId=660798&view=logs&j=609589e2-4f74-5576-cdb7-914bcaea778b&t=5ba03121-3cea-598c-07fa-53815ace41ff

**Comment by ViktorHofer** [comment]
Looks like source-build needs to use a newer System.Reflection.Metadata (`SystemReflectionMetadataVersion` property). @dotnet/source-build-internal I assume we need a re-bootstrap for that?

**Review by mmitche — APPROVED** [review]

**Pull request merged**
