### PR TITLE
WIP Insert NuGet Build 4.8.0-preview4.5318 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-preview4.5318 into sdk release/2.1.4xx branch

### CODE REVIEW

**Comment by nguerrera** [comment]
Needs https://github.com/dotnet/cli/pull/9611 to be merged and stage0 updated.

@nkolev92 @dsplaisted

**Comment by nguerrera** [comment]
Marked as WIP to wait for branch to open for P5.

**Comment by nkolev92** [comment]
@nguerrera 

Just fyi, the VS PR has been merged. 

https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/131171

**Comment by nguerrera** [comment]
Replaced by #2391

**Pull request closed without merging**
