### PR TITLE
[Razor] Introduce razor language version 6.0

### PR DESCRIPTION
**Pull request by javiercn**
Adding version 6.0 to the SDK so that it flows into the compiler. This is needed for the new generic type constraints feature.

### CODE REVIEW

**Comment by pranavkm** [comment]
I think you need a new compiler (Razor.Lang) version before this change can go in. Also this needs to be updated: https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets#L47-L55

**Comment by javiercn** [comment]
@pranavkm I realized that. I started updating it on the compiler, however it was not flowing. So what I'm going to do is enable the feature unconditionally on the compiler for now while I also introduce the new version, and then once that is in, get this PR in and update the feature to only work in 6.0

**Review by TanayParikh — APPROVED** [review]

**Comment by TanayParikh** [comment]
Looks like the CI is still having issues.

**Comment by captainsafia** [comment]
@javiercn Heads up that the SDK repo just branched a few hours ago so this PR will need to be retargeted/go through tactics now.

**Comment by javiercn** [comment]
@captainsafia I plan to merge this on preview5. I already took measures in the compiler to enable gtc unconditionally for preview 4 and will update check once this PR gets merged.

**Pull request merged**
