### PR TITLE
Add netstandard2.1 to the list of supported target frameworks.

### PR DESCRIPTION
**Pull request by livarcocc**
Fixes internal bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761489

### CODE REVIEW

**Review by dsplaisted — CHANGES_REQUESTED** [review]
I think we should wait to add this until we can actually successfully build .NET Standard 2.1 projects.

Based on the linked bug, it looks like the template may have been updated to target .NET Standard 2.1.  I don't think this is correct, I think that we wanted the default to still be .NET Standard 2.0.  Even if we do change the default we should wait until we can successfully build .NET Standard 2.1 projects, which I believe is still [work in progress](https://github.com/dotnet/standard/pull/1047).

cc @terrajobst

**Comment by livarcocc** [comment]
If that's the case, we need to revert the template change back to netstandard2.0.

cc @jmarolf @jjmew could one of you do that?

**Comment by jmarolf** [comment]
@mlorbetske 	@livarcocc 	So this PR should be reverted? https://github.com/dotnet/templating/pull/1701

**Comment by livarcocc** [comment]
@mlorbetske @jmarolf netstandard2.1 should not be picked up as the default one. netstandard2.0 should be the default. @mlorbetske is this something that can be changed on the template?

**Comment by mlorbetske** [comment]
@Livarcocc yep, the priority of the template should be changed - or the default value depending on the authoring

@vijayrkn @seancpeters

**Comment by vijayrkn** [comment]
@seancpeters - can you please take care of this.

**Comment by seancpeters** [comment]
@livarcocc - I want to make sure I correctly understand what you'd like done here. With an install of a 3.0.100-preview-xxxxx sdk, I see the Microsoft.DotNet.Common.ProjectTemplates.3.0 are installed, and the older versions of the template pack are not. This makes sense. So if in understand correctly, we just want to ensure that the default framework version should be netstandard2.0

If this is the case, then nothing needs to be done. The PR dotnet/templating#1701 adds netstandard2.1 as one of the possible choices for the framework, but the default is still netstandard2.0. Here is the full definition of the Framework symbol in the C# classlib template in the Microsoft.DotNet.Common.ProjectTemplates.3.0:
```
    "Framework": {
      "type": "parameter",
      "description": "The target framework for the project.",
      "datatype": "choice",
      "choices": [
        {
          "choice": "netcoreapp3.0",
          "description": "Target netcoreapp3.0"
        },
        {
          "choice": "netstandard2.0",
          "description": "Target netstandard2.0"
        },
        {
          "choice": "netstandard2.1",
          "description": "Target netstandard2.1"
        }
      ],
      "replaces": "netstandard2.0",
      "defaultValue": "netstandard2.0"
    },
```

The F# and VB templates are similarly configured.

**Comment by livarcocc** [comment]
@seancpeters can you help me understand how VS created a netstandard2.1 class library by default as described here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761489? That's the root of this conversation.

**Comment by seancpeters** [comment]
If we revert the change in dotnet/templating#1701 VS will give the netstandard2.0 templates. But then dotnet/templating#1699 will not be satisfied.

**Comment by dsplaisted** [comment]
Are we sure that VS is choosing the highest version from the template?  Or is it maybe just choosing the last one (in which case we could work around the issue by just reordering them)?

**Comment by seancpeters** [comment]
It's choosing the highest version. I ran through the code with the debugger.

**Comment by phenning** [comment]
@seancpeters this definitely looks like an issue with how we determine which net standard to use. I agree that hat we should be using the best supported default value that the customer has installed.

**Comment by livarcocc** [comment]
Should we file an issue to track fixing this in VS?

@dsplaisted meanwhile, any reason why we should still not take this PR, given that if this is not the default, we should still display values for it in the properties page?

**Comment by nguerrera** [comment]
I think the reason for not showing it as an option yet is that it doesn't work yet.

**Comment by dsplaisted** [comment]
> I think the reason for not showing it as an option yet is that it doesn't work yet.

Yes, exactly

**Comment by seancpeters** [comment]
I think our best option is to revert the change that added the netstandard2.1 framework to those templates. It's quick and easy, and doesn't require a riskier change in VS.

**Comment by vijayrkn** [comment]
Lets revert the change for you.

**Comment by livarcocc** [comment]
Closing this PR for now as we have reverted the template change.

**Pull request closed without merging**
