### PR TITLE
update nuget to 4.0.0-rtm-2241

### PR DESCRIPTION
**Pull request by rohit21agrawal**
@rrelyea @nguerrera @srivatsn

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
@dotnet-bot test this please.

**Comment by 333fred** [comment]
@rohit21agrawal, Jenkins is broken until #721 is merged.

**Comment by rohit21agrawal** [comment]
@333fred thanks for the update! any ETA on the fix?

**Comment by 333fred** [comment]
@rohit21agrawal change is in master now.

**Comment by rohit21agrawal** [comment]
@333fred thanks! rebasing and trying again

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
Tagging @MattGertz. @rohit21agrawal accidentally merged this but this is updating the SDK with changes that were approved for insertion to VS today morning in shiproom - this is syncing the version. Can you please approve?

**Pull request merged**
