### PR TITLE
Add an environment variable to prevent prompting rude edits (#22891)

### PR DESCRIPTION
**Pull request by pranavkm**
* Fixes https://github.com/dotnet/aspnetcore/issues/38798

Port #22891 to release/6.0.2xx

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]
Approving backport

**Comment by pranavkm** [comment]
FYI @zbecknell

**Comment by pbering** [comment]
Did this release as part of 6.0.2: https://github.com/dotnet/aspnetcore/issues?q=milestone%3A6.0.2++is%3Aclosed+label%3Aservicing-approved+?

**Comment by pbering** [comment]
Just did a quick test, my container is running with dotnet sdk v6.0.102 and it does not seem to work, still seeing ` watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?`. Seems it did not make the 6.0.2 release...

**Comment by TanayParikh** [comment]
> Just did a quick test, my container is running with dotnet sdk v6.0.102 and it does not seem to work, still seeing ` watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?`. Seems it did not make the 6.0.2 release...

This PR merged the changes into the 6.0.2xx branch. Can you please confirm if you've set the `DOTNET_WATCH_RESTART_ON_RUDE_EDIT` env var to `true`? Also what's the output of `dotnet --version`, perhaps a global.json is causing issues in your case.

**Comment by pbering** [comment]
`SET` inside the container reports `DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true` 

` docker exec XXX cmd /s /c dotnet --version` reports `6.0.102`

`docker inspect XXX` reports `Image: sha256:6cb5d7f92d4560052f711f60ae6e4270e94d823420731315933cadc41f8f1251` which is the image tag I use: `mcr.microsoft.com/dotnet/sdk:6.0.102-nanoserver-ltsc2022`

Also did a test directly on my host and it yields the same results, still asking to restart.

**Comment by zbecknell** [comment]
Oh man, thanks so much @baronfel!  Totally didn't realize that as I was sitting there trying to get it to work.

**Comment by pbering** [comment]
Thanks for clearing that up! Will wait a bit to test that out then 😉

**Comment by pranavkm** [comment]
You could consider grabbing a nightly build of the installer from https://github.com/dotnet/installer#installers-and-binaries to give it a spin.

**Pull request merged**
