### PR TITLE
Fix images used for helix tests in CI

### PR DESCRIPTION
**Pull request by joeloff**

### CODE REVIEW

**Review by MiYanni — APPROVED** [review]
Are you running an internal build with this change? (meaning, pushed this `helix` branch internally and started a build with it)

**Comment by joeloff** [comment]
> Are you running an internal build with this change? (meaning, pushed this `helix` branch internally and started a build with it)

not yet, and it's not guaranteed to fail. The COM issue is a race condition

**Comment by joeloff** [comment]
@dotnet/razor-compiler any idea why the tests might be failing to find some types in the generated DLL?

```
Microsoft.NET.Sdk.Razor.Tests.BuildWithComponentsIntegrationTest.Build_Components_WithDesktopMSBuild_Works [FAIL]
      Expected type MvcWithComponents.TestComponent to be in assembly, but it is not.
```

**Comment by jjonescz** [comment]
> any idea why the tests might be failing to find some types in the generated DLL?

Because of this:

<samp>
CSC : warning CS9057: The analyzer assembly 'C:\h\w\C20509CF\p\d\sdk\9.0.200-ci\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.dll' references version '4.13.0.0' of the compiler, which is newer than the currently running version '4.12.0.0'. [C:\h\w\C20509CF\t\dotnetSdkTests\dkhprd0b.wx0\Publish60Host---0200F604\Client\BlazorWasmHosted60.Client.csproj]
</samp>

**Comment by jjonescz** [comment]
But it seems unrelated to this PR, the same error is in other PRs.

**Comment by marcpopMSFT** [comment]
The helix images appear to be on 17.12 now but we have 17.13 in this branch which is leading to that CSC warning on some tests. Should we suppress that warning in these tests? Should we try to use the framework hosted compiler (I believe we had trouble doing that in tests since we end up building a -ci version of the package)

**Comment by jjonescz** [comment]
Or maybe we could just bump this number?

https://github.com/dotnet/sdk/blob/262b9c3d6cf67287f649e38d83e6c5d9d08feb8a/test/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs#L15

**Comment by marcpopMSFT** [comment]
> Or maybe we could just bump this number?
We'd just have to update it again the next time they updated the helix image to one different than the msbuild version we were using in the test. Should we intentionally set BuildWithNetFrameworkHostedCompiler to true in these tests and see if that works?

**Comment by jjonescz** [comment]
> Should we intentionally set BuildWithNetFrameworkHostedCompiler to true in these tests and see if that works?

Yep, that works.

Remaining failures are something with UseUwpTools property:

<samp>
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\WindowsXaml\v17.0\8.21\Microsoft.Windows.UI.Xaml.ModernNET.CSharp.targets(259,5): error : This project is setting the UseUwpTools property, which indicates that a UWP (XAML) app is being built using modern .NET, but the target device family being used (10.0.22621.0) is not supported for this configuration. Upgrade the target SDK version to '10.0.26100.0' or higher. It is recommended to do this by updating the target framework being used (currently set to net9.0-windows10.0.22621.0). [C:\h\w\A83C097E\t\dotnetSdkTests\3ve541pp.ba2\ItWarnsWhenBu---8D29E5B0\A\A.csproj]
</samp>

**Pull request merged**
