### PR TITLE
[NO MERGE] Re-enable Crossgen2 tests

### LINKED ISSUE #13279: Reenable crossgen test coverage
Crossgen test coverage had to be disabled in https://github.com/dotnet/sdk/pull/13168 because api-ms-win-core-console-l1-2-0.dll was missing. These tests need to be reenabled when this is fixed.

### PR DESCRIPTION
**Pull request by AntonLapounov**
Fixes #13279.

### CODE REVIEW

**Comment by sfoslund** [comment]
@AntonLapounov looks like the crossgen tests are still failing

**Comment by wli3** [comment]
@AntonLapounov ?

**Comment by AntonLapounov** [comment]
@wli3 This branch still uses Crossgen2 pack version 5.0.0-rc.1.20430.6 produced on 08/30/2020.  The issue was fixed in the beginning of September: dotnet/runtime#41784.

**Comment by AntonLapounov** [comment]
The latest Crossgen2 package version I can use in this branch is 5.0.0-rc.2.20475.5.  That version had a different issue with System.IO.Pipelines.dll and System.Net.Connections.dll listed in the crossgen2.deps.json file but missing in the package.

**Pull request closed without merging**
