### PR TITLE
Update to the 6.0.3 runtime for preview 3

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@dotnet/domestic-cat any idea why this test keeps failing? Seems unrelated to the runtime version:
Given_multi_target_It_should_get_suggested_workload_by_GetRequiredWorkloads_target
```
Expected collection {"macos", "android"} to contain {"macos", "android-aot"}, but could not find {"android-aot"}.
```

**Comment by joeloff** [comment]
Nope, but I'll spend some time digging into it

**Comment by marcpopMSFT** [comment]
@joeloff I don't see any reason why that would be caused by this PR. Other 3xx PRs are passing. I wonder if we picked up a bad change? I'll try forcing a remerge.

**Pull request merged**
