### PR TITLE
Target resolver to .NET 6

### PR DESCRIPTION
**Pull request by dsplaisted**
Retarget workload SDK resolver to .NET 6 so that VS for Mac can load it.

### CODE REVIEW

**Comment by mmitche** [comment]
@crummel @MichaelSimons Is it okay to target net6 in net7 source-build? I thought there was some issue with SBRPs.

**Comment by mmitche** [comment]
Also @lbussell

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
There were two PR build failures. One was a virtual hive issue and one was a space issue. Neither related to this change so merging for now to try to get an installer build we can test/sign.

**Pull request merged**
