### PR TITLE
rename SDK_CONTAINER_* to DOTNET_CONTAINER

### LINKED ISSUE #41609: environment variables with DOTNET_CONTAINER_ or DOTNET_SDK_CONTAINER_ prefix
i see that it's an existing pattern in containers that a generic SDK_ prefix is used instead of DOTNET_CONTAINER_ or DOTNET_SDK_CONTAINER_ which is a better namespace prefix.

1. The Twelve-Factor App Methodology

https://12factor.net/config
A litmus test for whether an app has all config it needs in env vars is whether the codebase could be made open source at any moment, without compromising any credentials. Using namespaced prefixes like MYAPP_ helps prevent collisions and makes it clear which app an environment variable pertains to.

2. Heroku's Best Practices for Config Vars

https://devcenter.heroku.com/articles/config-vars
Use a common prefix for related variables to group them logically. For example, if your app’s name is 'MYAPP', then a good practice is to prefix your variables with 'MYAPP_' to avoid collisions with other applications and to make it clear which application a variable pertains to.

3. AWS Lambda Environment Variables Best Practices

https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
To avoid naming conflicts, use a consistent naming convention, such as APPNAME_VARIABLE, where APPNAME is the name of your application or service.

4. Kubernetes Configuration Best Practices

https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
Use descriptive variable names and consider namespacing them with your application or organization name to avoid conflicts and to maintain clarity.

5. Google Cloud Environment Variables Best Practices

https://cloud.google.com/functions/docs/configuring/env-var
Prefix your environment variables with the service name or application name to prevent collisions and to organize them clearly, such as SERVICE_NAME_VARIABLE_NAME.

### PR DESCRIPTION
**Pull request by kasperk81**
fix https://github.com/dotnet/sdk/issues/41609

### CODE REVIEW

**Review by baronfel — CHANGES_REQUESTED** [review]
Thanks for starting this! We can't take this change as a direct name replacement right now, at minimum we have to keep backwards compatibility with the existing names so that we don't break `azd` without helping them migrate: https://github.com/ellismg/azure-dev/blob/947e1b8fab76c74b59d15c3bc46607e9038a0072/cli/azd/pkg/tools/dotnet/dotnet.go#L171.

**Review by baronfel — APPROVED** [review]

**Review by MichalPavlik — APPROVED** [review]

**Comment by baronfel** [comment]
If we can get the build to go green we'll merge this - and also backport to 8.0.4xx so that we don't have to release the insecure registry support with the old-style environment variable at all. Thanks for this @kasperk81!

**Pull request merged**
