### PR TITLE
Update dependencies from xdt

### PR DESCRIPTION
**Pull request by MichaelSimons**
Related to https://github.com/dotnet/installer/pull/12124

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
@MichaelSimons It looks like this dependency is actually used within the repo (in the publish tasks). Since we already shipped a 3.1.0 this probably means that we'll need to formally rev Xdt and ship a new stable servicing version.

I'd coordinate with @vijayrkn on this.

**Comment by vijayrkn** [comment]
@mmitche - Yes, this a netstandard library. So it is not required to be rev'd with all .NET Core versions. Pinning to 3.1.0 should work.

**Comment by vijayrkn** [comment]
We can get a 5.0 version out from main. This doesn't have to align with the .NET Core schedule.

**Comment by vijayrkn** [comment]
I have created a release/5.0 branch. I can get stable build out of that and we can pin dotnet/sdk to the 5.0 version at that point.

**Comment by mmitche** [comment]
> I have created a release/5.0 branch. I can get stable build out of that and we can pin dotnet/sdk to the 5.0 version at that point.

@vijayrkn Are there meaningful changes between 3.1 and 5.0? Otherwise I would service 3.1.0 as 3.1.1, with the updated sha that includes the fixes for source-build.

**Comment by vijayrkn** [comment]
Ya, that would work. Let me do that instead.

**Comment by marek-safar** [comment]
@mmitche should this PR be closed?

**Pull request closed without merging**
