### PR TITLE
Backport https://github.com/dotnet/sdk/pull/19873 to RC1

### PR DESCRIPTION
**Pull request by javiercn**
## Description

Small fixes to some more advanced scenarios for static web assets
* Fixes an issue with projects not working with reference assemblies  using HintPath.
* Fixes an issue where files without an extension where being included inside an additional folder with the file name on nuget packages.
* Adds additional error logging for the brotli compression tool.
* Adds additional login for the gzip compress task.
* Adds editor config files in the blazor wasm and razor sdk folders to handle 'var' usage preferences in ASP.NET Core projects.
* Performs a more selective filtering for static web assets candidates from the build candidates in blazor webassembly applications.
* Fixes an issue with AppendTargetFramework=false causing issues

## Customer Impact

Some existing customers aren't able to update to the latest preview due to some of the issues. Specifically:
* Fixes an issue with projects not working with reference assemblies  using HintPath.
* Fixes an issue with AppendTargetFramework=false causing issues

Other changes are fixes to other scenarios we believe didn't work before either

## Regression?
- [X] Yes (for the two issues outlined above)
- [ ] No

Preview6

## Risk

- [X] Low

We have extensive end to end test coverage (all fixes include new automation to validate the scenarios) and the changes don't affect core scenarios.

## Verification
- [X] Automated

dotnet/aspnetcore#35349
dotnet/aspnetcore#32744
dotnet/aspnetcore#29561
dotnet/aspnetcore#35561

### CODE REVIEW

**Comment by Pilchie** [comment]
I'm in favor of this fix for RC1, given the VS Feedback items behind it.

**Comment by javiercn** [comment]
@Pilchie @pranavkm good to merge?

**Review by pranavkm — APPROVED** [review]
Signing off since this is a straight backport. That said, this might need to go thru tactics to be merged.

**Comment by javiercn** [comment]
@pranavkm who is coordinating that

**Comment by Pilchie** [comment]
I'll discuss it today at Tactics.

**Pull request merged**
