### PR TITLE
Fix stale dependencies by removing duplicate properties

### LINKED ISSUE #10759: Microsoft.NET.Sdk package produced from official build bundling outdated NuGet
According to BAR, the most recent build from dotnet/sdk should include a build from NuGet/NuGet.Client at 
NuGet/NuGet.Client@64f2febf7d1de8b0228eca5afed97a96c5a30bba, however, by downloading the package from the build at https://dev.azure.com/dnceng/internal/_build/results?buildId=543706 and inspecting the versions of NuGet in the Microsoft.NET.Sdk package, it looks like it bundles a copy of NuGet from commit NuGet/NuGet.Client@cb402b5a3340ab5b2605ecc72de7f70aaac95344.

My guess would be that the bug is because in `eng/Versions.props` the line that Darc updates

https://github.com/dotnet/sdk/blob/1f2a4a110e356808d721358ce358de4f88923795/eng/Versions.props#L21

is overridden by 
https://github.com/dotnet/sdk/blob/1f2a4a110e356808d721358ce358de4f88923795/eng/Versions.props#L43-L57

and as a result, the NuGet version is pinned to an older version. This is blocking dotnet/runtime from uptaking a NuGet fix to prevent spurious CI failures.

cc: @ViktorHofer

### PR DESCRIPTION
**Pull request by ViktorHofer**
Removing duplicated nuget properties to fix stale dependencies

Fixes https://github.com/dotnet/sdk/issues/10759

cc @jkoritzinsky @jaredpar

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]
Does this need to get fixed in preview 1?

**Comment by nguerrera** [comment]
Note there are more flow problems since repo merge. Version.* is changed quite a bit in preview 1 and merge to master is still being worked on. Even P1 still has wrong toolset version flowing from here to core-sdk. Sigh.

**Comment by ViktorHofer** [comment]
@nguerrera yes, nuget is stale there as well: https://github.com/dotnet/sdk/blob/release/5.0.1xx-preview1/eng/Versions.props#L45

**Comment by ViktorHofer** [comment]
cc @nkolev92 for the failing NuGet tests

**Review by dsplaisted — APPROVED** [review]

**Comment by nguerrera** [comment]
I'll pick this up in the merge from preview1 to master

**Pull request closed without merging**
