### PR TITLE
Copy Installer Pipeline ymls

### PR DESCRIPTION
**Pull request by ellahathaway**
Related to https://github.com/dotnet/source-build/issues/4357

This is the first step in migrating unified-build and source-build installer pipelines to sdk pipelines.

This PR copies files in [installer/eng/pipelines](https://github.com/dotnet/installer/tree/main/eng/pipelines) to sdk/eng/pipelines. Also copies [installer/eng/vmr-sync.sh](https://github.com/dotnet/installer/blob/main/eng/vmr-sync.sh) and [installer/eng/vmr-sync.ps1](https://github.com/dotnet/installer/blob/main/eng/vmr-sync.ps1).

This step allows us to (in future steps):
1) Create the public pipelines. The public pipelines depend on the ymls being in the public repo.
2) Update [ci.yml](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/eng/pipelines/ci.yml) and [pr.yml](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/eng/pipelines/pr.yml) to reference `sdk/eng/pipelines`.

### CODE REVIEW

**Comment by ellahathaway** [comment]
@ViktorHofer - I've left out the sync logic and related ymls from this PR since I wasn't sure if they would impact builds. Let me know if you think I should include them. Thanks in advance.

**Comment by ViktorHofer** [comment]
Just as a general question, do we feel strongly about including history for these files? I'm not sure tbh. cc @MichaelSimons @mmitche

**Comment by ViktorHofer** [comment]
> @ViktorHofer - I've left out the sync logic and related ymls from this PR since I wasn't sure if they would impact builds. Let me know if you think I should include them. Thanks in advance.

Yeah I think we need everything. Those files shouldn't impact any existing builds.

- All of https://github.com/dotnet/installer/tree/main/eng/pipelines
- https://github.com/dotnet/installer/blob/main/eng/vmr-sync.ps1 and
- https://github.com/dotnet/installer/blob/main/eng/vmr-sync.sh

**Review by ViktorHofer — APPROVED** [review]
This is a straight copy without any modifications, right?

**Comment by ellahathaway** [comment]
> This is a straight copy without any modifications, right?

Correct. I can make the modifications for installer to sdk if we want. Almost all of them are related to the syncing.

**Comment by ViktorHofer** [comment]
Let's do the edits in another PR to keep this focused on just the code move. Feel free to merge.

**Pull request merged**
