### PR TITLE
Update man pages

### LINKED ISSUE #21449: Update man page for .NET 6.0
We have man pages for .NET in our repo: https://github.com/dotnet/sdk/tree/main/documentation/manpages/sdk

Unfortunately, they haven't been updated in a while. They are missing lots of fixes, as well as entire subcommands like `dotnet sdk`.

If we can't update them automatically, perhaps they should be manually updated shortly before release? 

See also https://github.com/dotnet/sdk/issues/8545 and https://github.com/dotnet/sdk/issues/9896#issuecomment-484320147

### To Reproduce

Look at https://github.com/dotnet/sdk/tree/main/documentation/manpages/sdk. There's no `dotnet-sdk.1`, among other pages.

### PR DESCRIPTION
**Pull request by omajid**
The current .NET man pages were updated a long time ago and are missing docs for a number of components, including `dotnet format` and `dotnet workload install`.

The man pages are still generated from the contents of https://github.com/dotnet/docs/tree/main/docs/core/tools

Please use `man ./relative/path/to/file.1` to see the rendered views.

There's two major changes in this commit:

1. Update the tooling and toolset to generate the man pages

2. The actual changes (addition/updates) for the man pages

For the first, the container has been updated to use a newer pandoc and python3. The pandoc filter has been updated to remove the link-removal since it doesn't seem necessary for this version of pandoc anymore. Alsoadded another early pass over the document files: this inlines all !INCLUDE'd references so the manual pages are complete.

Fixes: #21449

### CODE REVIEW

**Comment by omajid** [comment]
cc @dsplaisted @mairaw

**Comment by mairaw** [comment]
Tagging @tdykstra for CLI docs

**Review by dsplaisted — APPROVED** [review]
I don't know anything specifically about man page generation, but it's good to get them updated.

**Review by tdykstra — COMMENTED** [review]
LGTM

**Comment by am11** [comment]
Ideally, manpages should live in installer repo so they are included in .deb, .rpm, .tar.gz and macOS .pkg. See https://github.com/dotnet/installer/issues/5860 like other software (perhaps as a separate docs package) e.g. this code is outdated: https://github.com/dotnet/installer/blob/56b47dce2c121ae60afbd0a47f8b629ba6243e9a/src/redist/targets/GenerateDebs.targets (notice that we transitioned from cli->toolset->sdk and core-setup->installer since the issue was opened).

**Comment by KexyBiscuit** [comment]
Seems that the manual pages are still missing in official binaries from https://dotnet.microsoft.com/download/dotnet/6.0?

**Pull request merged**
