### PR TITLE
Update branding to 6.0.111

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@dotnet/aspnet-blazor-eng there are a bunch of blazor and razor tests failing across the three branding PRs into 6. It looks pretty consistent to me. Can you please take a look and prioritize this asap as these need to get in to unblock servicing changes?

https://github.com/dotnet/sdk/pull/28323
https://github.com/dotnet/sdk/pull/28324

**Comment by TanayParikh** [comment]
> @dotnet/aspnet-blazor-eng there are a bunch of blazor and razor tests failing across the three branding PRs into 6. It looks pretty consistent to me. Can you please take a look and prioritize this asap as these need to get in to unblock servicing changes?
> 
> #28323 #28324

Looks like it's in need of some baseline updates. Taking a look...

**Comment by TanayParikh** [comment]
I've been trying to update the baselines, but not getting the expected results. Investigating further.

**Comment by marcpopMSFT** [comment]
@TanayParikh I assume that https://github.com/dotnet/sdk/pull/28346 is an attempt at fixing the tests for the branding updates?  Looks like it's still failing at the moment.  Why would branding break this?

**Comment by TanayParikh** [comment]
> @TanayParikh I assume that #28346 is an attempt at fixing the tests for the branding updates? Looks like it's still failing at the moment. 

Yes indeed. Still failing, I just pushed another commit a short while back which should hopefully give us a bit more diagnostic information.

> Why would branding break this?

It really shouldn't, but the warning messages are those of a baseline conflict. Maybe some other update went through which resulted in these failures? 

cc/ @javiercn in case Javier has additional context.

**Comment by TanayParikh** [comment]
Benchmark changes not having an impact. @javiercn any ideas on what may be going on here?

**Comment by TanayParikh** [comment]
Spoke with @javiercn offline. It looks like there could've been some changes to the project config, and missing RIDs which could be causing this. It's very unclear why this would be impacted by branding however.

**Comment by marcpopMSFT** [comment]
@TanayParikh should we consider disabling these tests temporarily while a fix is investigated?

**Comment by TanayParikh** [comment]
How urgently do we need to get this (and the other servicing PRs) in? I've been looking into this but haven't had much luck yet.

**Comment by marcpopMSFT** [comment]
> How urgently do we need to get this (and the other servicing PRs) in? I've been looking into this but haven't had much luck yet.

We'll be generating builds next week for 6.0 but there are a few PRs backed up waiting on branding to go in first afaik. Looks like ~5 PRs waiting for the branches to open: https://github.com/dotnet/sdk/pulls?q=is%3Apr+is%3Aopen+base%3Arelease%2F6 (the middle five from revert through the linker update)

**Comment by TanayParikh** [comment]
Got it, thanks for the clarification. In that case, should things not be resolved by mid-day tomorrow, let's disable these tests temporarily. Would that be acceptable?

**Comment by TanayParikh** [comment]
Looks like we may actually be running into https://github.com/dotnet/sdk/blob/release/7.0.1xx-rc1/documentation/general/SelfContainedBreakingChangeNotification.md. However that's a 7.0 change, so not sure why it would have an impact here.

cc/ @dsplaisted in case there's some additional context we may be missing.

**Comment by dsplaisted** [comment]
@TanayParikh The change had parts both in MSBuild and in the SDK.  The MSBuild changes weren't supposed to change any behavior without the SDK changes.  However, we had a bug which is probably why you are seeing these test failures in the full framework legs.  It was fixed for GA in this PR: https://github.com/dotnet/msbuild/pull/8002

So it looks like the test failures are due to a regression in Full Framework MSBuild behavior which will be fixed for 17.4 GA.

**Comment by marcpopMSFT** [comment]
@dsplaisted the sdk we're using to build 1xx, 3xx, and 4xx is all 6.0 based SDKs that shouldn't have the msbuild change (which as 17.4 only), correct?  So is the issue here that we're using prerelease helix queues so the tests are actually running against 17.4 previews rather than 17.3 and earlier?
https://github.com/dotnet/sdk/blob/573ebc6b3ec43ade419eff04be97111935997f9f/.vsts-ci.yml#L94

**Comment by marcpopMSFT** [comment]
I went ahead and switched from the .pre images which should be 17.3.3 to see if that'll fix this PR.

**Comment by TanayParikh** [comment]
Looks like there are some infra issues (403s), and some other tests failing. But the razor/blazor tests are working now.

**Comment by marcpopMSFT** [comment]
@TanayParikh I spoke to dnceng and while there are build images with 17.3, there are no test images. As such, I think the best path forward is to disable these tests temporarily. Any concerns?

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/28430  Here's an attempt and branding and test disablement. If this works, port to the other two branches.

**Comment by TanayParikh** [comment]
> Any concerns?

@dsplaisted to confirm, this regression shouldn't have any product experience impact?

**Comment by dsplaisted** [comment]
> > Any concerns?
> 
> @dsplaisted to confirm, this regression shouldn't have any product experience impact?

There was a regression in a preview of MSBuild, which is what is causing the tests to fail.  It will be fixed in the GA release.

**Pull request closed without merging**
