### PR TITLE
Add telemetry data points for .NET Core 2.0

### PR DESCRIPTION
**Pull request by wli3**
https://github.com/dotnet/cli/issues/7283

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@wli3 we need the ask mode template filled up here too.

**Comment by wli3** [comment]
**Customer scenario**

Please reference issue https://github.com/dotnet/cli/issues/7283

**Bugs this fixes**

https://github.com/dotnet/cli/issues/7283

**Workarounds, if any**

N/A

**Risk**

Low

**Performance impact**

Low

**Root cause analysis**

N/A

**How was the bug found?**

N/A feature

@MattGertz for approval

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Release

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Debug

**Comment by wli3** [comment]
@dotnet-bot  test Windows_NT_FullFramework Release

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT Debug

**Pull request merged**
