### PR TITLE
Fix ArgumentNullException when no reference assemblies are installed on the machine

### PR DESCRIPTION
**Pull request by eerhardt**
Needed to fix Docker scenarios.

@nguerrera @dsplaisted 

/cc @dotnet/project-system @stevelasker

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]
Thanks!

**Review by nguerrera — APPROVED** [review]
Thanks!

**Comment by nguerrera** [comment]
I didn't realize it was this trivial when reading the stack on the bus ride home without the corresponding code. ;)

**Comment by nguerrera** [comment]
@MattGertz @Pilchie FYI. This is blocking and trivial so I'll just merge.

**Comment by Pilchie** [comment]
Approved, but even for trivial fixes we'll need divisional escrow approval now, so please don't merge before approval anymore.

**Comment by nguerrera** [comment]
Ok. Got it.

**Pull request merged**
