### PR TITLE
Added 🟣 to step names

### PR DESCRIPTION
**Pull request by MiYanni**
## Summary

Added a purple circle to every ~~stage, job, and~~ step defined within the context of this repo (**_excluding_** Arcade and source-build templates). This allows you to easily identify what this repo defines when looking through a build log. With all the 1ES tasks, it hurts my brain looking through the build logs, trying to understand what we actually run. 😵‍💫

The reason I used a purple circle is because when you look up dotnet images, you see something similar to this:
image

### CODE REVIEW

**Comment by mmitche** [comment]
I would suggest only adding this to steps. Because most of the jobs and stages are not supplied by 1ES, I think it's adding noise to the GitHub PR view UX.

**Comment by MiYanni** [comment]
@mmitche Yeah. When I created the PR, I forgot that GitHub functions on a formatted string of the display names of things. Meaning, it broke our required checks since you have to reference them by that string name. So, not worth it for that reason. And the extra noise on stages/jobs.

**Review by Forgind — APPROVED** [review]
I remember you talking about this in standup and thought it was a great idea.

Does it also need to be applied to the official yml?

**Comment by MiYanni** [comment]
@Forgind The pipeline definition yamls `.vsts-pr.yml` and `.vsts-ci.yml` don't currently contain any steps in them. This PR changes the templates we use to do the build that have the actual steps in them. To answer your question, this change will be applied to both the PR and official pipeline runs.

**Pull request merged**
