### PR TITLE
Merge branch 'release/6.0.4xx' => 'main'

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@gkulin I've resolved the conflict, could you help to review them?

**Comment by marcpopMSFT** [comment]
@joeloff @gkulin There's one test failure in this codeflow: Microsoft.DotNet.Cli.Workload.Install.Tests.GivenDotnetWorkloadInstall.GivenWorkloadInstallItTreatsPreviewsAsSeparateFeatureBands

Looks like the test end ups triggering a null exception in the releases library so adding both of you.

System.ArgumentNullException : Value cannot be null. (Parameter 'input')


Stack trace
   at Microsoft.Deployment.DotNet.Releases.ReleaseVersion.Parse(String input)
   at Microsoft.Deployment.DotNet.Releases.ReleaseVersion..ctor(String version)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkFeatureBand..ctor(String version) in /_/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkFeatureBand.cs:line 14
   at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, String installedFeatureBand) in /_/src/Cli/dotnet/commands/InstallingWorkloadCommand.cs:line 73
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds, String installedFeatureBand) in /_/src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs:line 46
   at Microsoft.DotNet.Cli.Workload.Install.Tests.GivenDotnetWorkloadInstall.GivenWorkloadInstallItTreatsPreviewsAsSeparateFeatureBands() in /_/src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs:line 413

**Review by joeloff — APPROVED** [review]

**Comment by v-wuzhai** [comment]
@gkulin It seems that the test is still failed

**Pull request merged**
