### PR TITLE
Disable workload resolver sentinel for workload imports

### PR DESCRIPTION
**Pull request by dsplaisted**
The resolver sentinel was previously disabled (or more precisely, switched from opt-in to opt-out) for the workload resolver.  However, it is also used in the .NET SDK targets to determine whether the workload .props and .targets should be imported, so that logic needs to be updated as well in order to enable workloads without the opt-in.

### CODE REVIEW

**Review by sfoslund — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Comment by dsplaisted** [comment]
@sfoslund FYI, I had to update some of the tests now that workloads are enabled by default: https://github.com/dotnet/sdk/pull/17306/commits/7c1b21fd5db62c89ed5589f3392487cf22d1d50d

**Comment by dsplaisted** [comment]
@wli3 There are some tests that seem to be failing consistently here, but the failures don't seem to be related to the changes in the PR and the tests pass when I run them locally.  Can you take a look (assuming you're domestic cat).

**Comment by lewing** [comment]
@dsplaisted the failures I saw before looked like https://github.com/dotnet/core-eng/issues/12969

**Comment by lewing** [comment]
Some of the current failures look relevant

```
    Microsoft.NET.Restore.Tests.RestoreWithOlderNuGet.ItCanBuildProjectRestoredWithNuGet5_7 [FAIL]
Process ID: 2332
      Expected command to pass but it did not.
      File Name: C:\h\w\BCDA09D9\w\B5C60A32\e\Assets\.nuget\5.7.0\nuget.exe
      Arguments: restore C:\h\w\BCDA09D9\t\dotnetSdkTests\ym5unxeq.k2a\ItCanBuildPro---2831E99A\ItCanBuildProjectRestoredWithNuGet5_7\ItCanBuildProjectRestoredWithNuGet5_7.csproj -PackagesDirectory C:\h\w\BCDA09D9\w\B5C60A32\e\Assets\.nuget\packages
      Exit Code: 1
      StdOut:
      MSBuild auto-detection: using msbuild version '16.10.0.18105' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin'.
      StdErr:
      C:\h\w\BCDA09D9\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): error : C:\h\w\BCDA09D9\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.SDK.WorkloadAutoImportPropsLocator\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
      C:\h\w\BCDA09D9\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [C:\h\w\BCDA09D9\t\dotnetSdkTests\ym5unxeq.k2a\ItCanBuildPro---2831E99A\ItCanBuildProjectRestoredWithNuGet5_7\ItCanBuildProjectRestoredWithNuGet5_7.csproj]
      
      Stack Trace:
           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in FluentAssertions.dll:token 0x600015c+0x1d
           at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in FluentAssertions.dll:token 0x6000164+0x11
           at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in FluentAssertions.Core.dll:token 0x6000372+0x0
           at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in FluentAssertions.Core.dll:token 0x600034f+0x71
        /_/src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs(32,0): at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.Pass()
        /_/src/Tests/Microsoft.NET.Restore.Tests/RestoreWithOlderNuGet.cs(40,0): at Microsoft.NET.Restore.Tests.RestoreWithOlderNuGet.ItCanBuildProjectRestoredWithNuGet5_7()
      Output:
        > C:\h\w\BCDA09D9\w\B5C60A32\e\Assets\.nuget\5.7.0\nuget.exe restore C:\h\w\BCDA09D9\t\dotnetSdkTests\ym5unxeq.k2a\ItCanBuildPro---2831E99A\ItCanBuildProjectRestoredWithNuGet5_7\ItCanBuildProjectRestoredWithNuGet5_7.csproj -PackagesDirectory C:\h\w\BCDA09D9\w\B5C60A32\e\Assets\.nuget\packages
        MSBuild auto-detection: using msbuild version '16.10.0.18105' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin'.
```

**Comment by dsplaisted** [comment]
FYI @marcpopMSFT, I'm bumping the minimum MSBuild version to 16.10, as the SDK is now trying to import workload targets by default, and it needs the workload resolver enabled for that to work.

**Comment by sfoslund** [comment]
@dsplaisted has this been ported to main?

**Pull request merged**
