### PR TITLE
Remove XCopy-MSBuild

### LINKED ISSUE #12560: Remove XCopyMSBuild and reenable full framework C++ tests
Since https://github.com/dotnet/sdk/pull/12202 leveraged a new MSBuild feature, we needed to use XCopyMSBuild to get the full framework CI legs working. This change also required several others which should be reverted:
- [x] Disabled full framework C++ tests, which rely on props and targets that are not available with this package. 
- [x] Disabled F# tests which rely on props and targets that are not available with this package (see https://github.com/dotnet/sdk/pull/13085#issuecomment-680242294)
- [x] Reverted #12812, which relies on a version of MSBuild that was not yet inserted.

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes #12560

### CODE REVIEW

**Comment by sfoslund** [comment]
> error NETSDK1145: The Apphost pack is not installed and NuGet package restore is not supported. Upgrade Visual Studio, remove global.json if it specifies a certain SDK version, and uninstall the newer SDK. For more options visit   https://aka.ms/targeting-apphost-pack-missing  Pack Type:Apphost, Pack directory: F:\workspace\_work\1\s\artifacts\bin\redist\Debug\dotnet\packs\Microsoft.NETCore.App.Host.win-x64, targetframework: netcoreapp5.0, Pack PackageId: Microsoft.NETCore.App.Host.win-x64, Pack Package Version: 5.0.0-rc.2.20468.4 


@wli3 the C++ pack test is failing when I reenable it, do you know what the problem is here?

**Comment by wli3** [comment]
@sfoslund C++ tests cannot be enabled anytime soon. C++ does not support package restore. So, it is cannot download apphost pack from the internet. Since I made a change recently to use stage 2 bundled version props file instead of stage 0 (to avoid needing to update stage 0 when runtime insert), apphost will not be in the "dotnet" folder. The solution could be, in the test set up, download the missing apphost pack. But that will duplicate a lot of dotnet/installer code. Or move these tests to dotnet/installer. We don't have C++ feature work for 5.0. I think keep disabling these tests for now is fine. We still have manual tests.

**Comment by sfoslund** [comment]
@wli3 okay, sounds good. Do you have an issue for tracking reenabling them or should I make a new one?

**Comment by wli3** [comment]
Let's reuse this one https://github.com/dotnet/sdk/issues/11008

**Comment by sfoslund** [comment]
@wli3 @dsplaisted there are 2 tests failing with project to project references with both projects targeting net5.0-windows. This doesn't repro with the latest VS dogfood locally so I believe it's just the version of nuget in the images. I've disabled them for now and am tracking reenabling them with https://github.com/dotnet/sdk/issues/13728

**Review by dsplaisted — APPROVED** [review]

**Review by wli3 — APPROVED** [review]

**Pull request merged**
