### PR TITLE
Fix #1435 - calculation of ResolvedPath for project references

### LINKED ISSUE #1435: ResolvePackageDependencies produces invalid ResolvedPath for `<ProjectReference .../>`
Running on latest previews (VS2017.3 Preview 4, .net sdk 2.0.0-preview2-006497) my build fails because the `ResolvePackageDependencies` Task produces invalid results / output. I'm building from within VS.

In short, a path included in `@(PackageDefinitions->'%(ResolvedPath)'` is wrong. Here is the actual vs the expected path:

> C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\StaticProxy.Fody\StaticProxy.Fody.csproj
C:\Development\StaticProxy.Fody.VS2017\StaticProxy.Fody\StaticProxy.Fody.csproj

The actual path does not exist, that's why a consumer of this path fails.

The complete output for that particular PackageDefinition (which results from a `<ProjectReference Include="..\StaticProxy.Fody\StaticProxy.Fody.csproj" />`) is:

> 2>                StaticProxy.Fody/1.0.0
> 2>                        Name=StaticProxy.Fody
> 2>                        Path=../StaticProxy.Fody/StaticProxy.Fody.csproj
> 2>                        ResolvedPath=C:\Development\StaticProxy.Fody.VS2017\IntegrationTests\StaticProxy.Fody\StaticProxy.Fody.csproj
> 2>                        Type=project
> 2>                        Version=1.0.0

Excerpts from the *.csproj of the project (targeting net462) follows, but I would like to mention that some of the projects in the solution actualy do target netstandard - don't know if that makes a difference?

	<?xml version="1.0" encoding="utf-8"?>
	<Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
		<TargetFrameworks>net462</TargetFrameworks>
	  </PropertyGroup>
	  <ItemGroup>
		<Reference Include="System" />
		...
		<PackageReference Include="Castle.Core" Version="4.1.1" />
		...
      </ItemGroup>
	  ...
	  <ItemGroup>
		<ProjectReference Include="..\StaticProxy.Fody\StaticProxy.Fody.csproj" />
	  </ItemGroup>
	</Project>

Link to project: https://github.com/BrunoJuchli/StaticProxy.Fody/tree/7d8b924d90759cb3248803514ba631463358494a/

Diagnostic MSBuild Log: https://gist.github.com/BrunoJuchli/c5c8b5e74571cbaa99e8e8e5997acaf3/raw/9bc0f0bd94cd77ccf0cbfb58bf66982dfca961bb/MsBuildLog.txt

### PR DESCRIPTION
**Pull request by BrunoJuchli**
See #479 and #1435 for error description and analysis of the problem. In short:

The old implementation combined the relative `<ProjectReference Include="..." />` path with the directory of the `ProjectAssetFile`.
Corrected this to combine the relative project reference with the current's project path.

Questions:
 - Is it actually the desired outcome that ResolvedPath points to the csproj file? Or should it point to the output directory of that project?
 - Is ProjectPath always passed in as full path? (otherwise it needs to be enclosed by a `Path.GetFullPath`)

### CODE REVIEW

**Comment by nguerrera** [comment]
@natidea

**Comment by nguerrera** [comment]
The code before the change does look wrong. I'm trying to understand why this wasn't reported sooner. The repro steps in #1435 don't seem out of the ordinary. @dsplaisted @livarcocc

**Comment by natidea** [comment]
@nguerrera this was being tracked with #479 
Is this incorrect metadata being used anywhere, or is this usage something custom for the reported project?

**Comment by nguerrera** [comment]
@natidea #1435 says the build is failing due to this.

 @BrunoJuchli Do you have anything custom reading this ResolvedPath ?

**Comment by BrunoJuchli** [comment]
@nguerrera In my case there's no project.json involved. However, the solutions mixes classic *.csproj + "modern" (VS2017,..) .csproj. And some csproj target .net full framework and others netstandard.

Full source code here: https://github.com/BrunoJuchli/StaticProxy.Fody/tree/7d8b924d90759cb3248803514ba631463358494a/

note: there's two solutions. The relevant is **StaticProxy.Fody.sln**

And yes, there's something **custom** reading the resolved path: [Fody](https://www.github.com/Fody/Fody). The `ResolvedPath`s is one of the ways its looking for weaver-dll's.

Don't think it will work after this change though. I'm also not sure that this change is correct. As stated in the entry-post I'm unsure whether `ResolvedPath` pointing to a *.csproj is valid. Shouldn't it point to where the (built) assemblies of of the `<ProjectReference...>` are located? All the other `ResolvedPath`s do.

**Comment by BrunoJuchli** [comment]
@natidea 
I concur that #1435 seems to be a duplicate of #479. Sorry for posting the duplicate.

@nguerrera 
#479 states

> The resolved path for project references is not actually used anywhere currently, so this bug does not cause any problems, but should be fixed anyway.

Hence only the consumers will "fail", but a standard built without any custom code won't "fail" - it just produces invalid output for external consumers.

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
