### PR TITLE
Containers: don't push manifest digest when pushing manifest tags.

### PR DESCRIPTION
**Pull request by tmds**
This behavior is consistent with CLI tools and fixes an issue with the OpenShift internal image repository.

Fixes https://github.com/dotnet/sdk/issues/35431.

@baronfel ptal.

### CODE REVIEW

**Comment by tmds** [comment]
@baronfel can you please check this change with your tests that run against multiple registries?

I expect there to be no issue because this matches the behavior of `podman`, which has been battle tested against many registry implementations.

It may be interesting to check what `docker` does exactly, if there there is a simple way to get the logs. It may be doing the exact same thing as `podman` and what we're changing to here.

**Comment by baronfel** [comment]
Corresponding Actions run for the manifest upload tests: https://github.com/baronfel/sdk-container-demo/actions/runs/6199744366

So far seems to be good!

**Review by baronfel — APPROVED** [review]
This passes tests and unblocks a partner scenario. Thanks for the contribution, @tmds!

**Comment by tmds** [comment]
Thank you, @baronfel!

**Pull request merged**
