### PR TITLE
[Port] Updating the web deploy reference to 4.0.5

### PR DESCRIPTION
**Pull request by vijayrkn**
- This update is needed to support publishing to App Service from VS Mac.

### CODE REVIEW

**Comment by vijayrkn** [comment]
PR: https://github.com/dotnet/sdk/pull/12317
Issue (internal): [1149072 ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1149072)

#### Summary
The change is updating the Web Deploy references from 3.6.0 to 4.0.4. As part of the websdk code port to sdk, some of the external dependencies had to be updated. The latest web deploy reference available in NuGet during the time of the port was 3.6.0 which did not have the updates to make web deploy work with mono. IIS team has made the latest version available in NuGet with mono support. 

#### Customer Impact
Publishing to IIS targets from VS Mac including Azure app service will not work without this change. 

#### Regression?
This functionality works in preview6. This is a regression in master due to the code port from websdk to sdk.

#### Testing
Will be testing the latest package in VS mac once the build is available. 

#### Risk
Low.

**Review by mrward — APPROVED** [review]
Replacing the dlls in .NET Core 5.0 preview 7 SDK with the dlls from [Microsoft.Web.Deployment v4.0.4](https://www.nuget.org/packages/Microsoft.Web.Deployment/4.0.4) fixes the Azure publish problem on the Mac. Thanks.

**Comment by vijayrkn** [comment]
This PR is ready to merge once approved.

**Review by mmitche — APPROVED** [review]

**Comment by vijayrkn** [comment]
@wli3 - I am not sure how the pr merges happen in dotnet/sdk repo. Is the expectation to cherry-pick these prs to master individually?

**Comment by wli3** [comment]
@vijayrkn you can do a merge from release/5.0.1xx-preview7 to master. Or cherry-pick is also fine. We cannot keep the auto branch merge up-to-date with the current rate of branch creation.

**Pull request merged**
