### PR TITLE
CreatePDB doesn't work without DiaSymReader on the path

### PR DESCRIPTION
**Pull request by eerhardt**
To fix this, copy crossgen to the netcoreapp folder that has DiaSymReader in it, and invoke crossgen from there.

Fix https://github.com/dotnet/cli/issues/6778

/cc @gkhanna79

### CODE REVIEW

**Comment by eerhardt** [comment]
@MattGertz for approval

**Customer scenario**

`dotnet store` recently changed to generate profiling symbols by default.  In order to generate .ni.pdb files on Windows, crossgen needs to be able to find Microsoft.DiaSymReader.Native.  All our testing was done using VS Developer command prompts, which has DiaSymReader on the path.  However, customers are trying to use this command outside of VS Developer Command Prompts and it is failing.

**Bugs this fixes:** 

https://github.com/dotnet/cli/issues/6778

**Workarounds, if any**

Run the command from VS Developer Command Prompt.

**Risk**

Almost none.  We are just moving the same crossgen executable from the NuGet restored location to inside our "working directory" that already has DiaSymReader.

**Performance impact**

None

**Is this a regression from a previous update?**

Yes.  When we weren't generating .ni.pdbs, the command passed successfully.  Once we started generating symbols by default, the command will fail if DiaSymReader isn't on the PATH.

**Root cause analysis:**

All our tests run in VS Developer Command Prompts, so we didn't catch this issue when first implemented.

**How was the bug found?**

ASP.NET originally found it through dogfooding.  Also reported by the JIT Bench team.

**Review by gkhanna79 — APPROVED** [review]

**Comment by nguerrera** [comment]
Sorry I didn't get to this sooner. Copying a tool around to run it feels hacky. Why is the dll guaranteed to be in that working dir?

**Comment by eerhardt** [comment]
The directory crossgen is being copied to is basically a flat folder of the shared fx.  Here is the code that creates the `$(_NetCoreRefDir)` folder:

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets#L300-L335

(I'm not entirely sure why this doesn't just publish a self-contained project, but that's besides this point.)

So `$(_NetCoreRefDir)` is basically a mini-shared framework folder.  On Windows, the shared framework contains the necessary Microsoft.DiaSymReader.Native assembly.  So running `crossgen` from that folder allows it to load the correct Microsoft.DiaSymReader.Native assembly.

Previously, we were just running `crossgen` out of the nuget cache - it comes as part of Microsoft.NETCore.App nupkg in the `tools` folder, but none of its dependencies are in that folder.

An alternative that @gkhanna79 and I discussed were to pass the path to DiaSymReader into crossgen using the `/DiaSymReader` option.  But I decided against that approach because it was more complex:

1. The option is only available on Windows.
2. The DiaSymReader file has the architecture in its name, but the architecture doesn't align with our RID/Platform architecture names - i.e. `amd64` vs `x64`.  So we would have needed a mapping to get the correct file name and update it as we supported new architectures.

**Comment by nguerrera** [comment]
Well, if we're already copying the world into this folder, what's one more thing, I guess. 😕

**Pull request merged**
