### PR TITLE
Updating nuget packages to 4.0.0-rc-2037

### PR DESCRIPTION
**Pull request by emgarten**
Updating nuget packages to 4.0.0-rc-2037

Fixes https://github.com/NuGet/Home/issues/3817

### CODE REVIEW

**Comment by nguerrera** [comment]
The problem was a conflict with assemblies next to msbuild.exe in the older CLI we were using for testing. I've pushed a new commit to the PR branch that updates the CLI. This passed locally with my own build of CLI from rel/1.0.0 head, but won't succeed in CI until v3961 of the CLI is available for download.

@rrelyea @livarcocc @srivatsn

**Review by livarcocc — APPROVED** [review]

**Comment by nguerrera** [comment]
In the future, let's do nuget -> CLI, then nuget+CLI -> SDK

**Comment by nguerrera** [comment]
@dotnet-bot test Windows_NT Debug please

**Comment by nguerrera** [comment]
@dotnet-bot test Windows_NT Release please

**Comment by nguerrera** [comment]
Looks like the windows package is now available and I'm expecting the builds to pass.

**Comment by srivatsn** [comment]
Can this be merged now?

**Comment by emgarten** [comment]
Merged, thanks for the help!

**Pull request merged**
