### PR TITLE
Update SystemTextJsonToolsetPackageVersion

### PR DESCRIPTION
**Pull request by am11**
cc @MichaelSimons just fixed this in runtime https://github.com/dotnet/runtime/pull/108704. (being proactive) :D

### CODE REVIEW

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
VS hasn't yet shipped with updated binding redirects for STJ/8.0.0.5. That change got merged 6 days ago: https://github.com/dotnet/msbuild/commit/eacead39b9a7e0047c415db7318123c91af6f8e5#diff-2c2e83275077d3c65c1190f9aabc894271ab22132b4f5675f16fb1301c0639d8

**Comment by ViktorHofer** [comment]
cc @rainersigwald

**Comment by am11** [comment]
Or maybe just apply/cherry-pick on https://github.com/dotnet/sdk/pull/44011

**Comment by ViktorHofer** [comment]
I mean that we usually have to wait around two months until our windows CI clients have a VS installed with the updated binding redirects.

**Comment by am11** [comment]
> I mean that we usually have to wait around two months until our windows CI clients have a VS installed with the updated binding redirects for .NET Framework msbuild.

Ah ok, lets close this one until that happen. FWIW, this was a CVE fix which started breaking builds last week (and this is the fourth PR of the kind runtime,diagnostics,msbuild are already on 8.0.5).

**Pull request closed without merging**
