### PR TITLE
Merge toolset repo into sdk

### PR DESCRIPTION
**Pull request by dsplaisted**
Remaining work (some of it can be after this is merged)

- [ ] Fix Version.Details.xml
- [ ] Update Roslyn package (https://github.com/dotnet/toolset/pull/3808)
- [ ] Merge or rebase in latest changes from dotnet/toolset (and possibly dotnet/cli if there are any)
- [ ] Go through remaining files in `toolset` directory of repo root, either delete them or move them to a new location.  I think the main things to consider keeping is the Documentation folder, and to update the README in the root as appropriate
- [ ] Make sure MSBuildSdkResolver tests are running (both for .NET Framework and .NET Core).  These seem to be skipped when I do a local build.
- [ ] Make sure that all the correct artifacts are published as part of official builds, and that all the correct dependencies are flowing in (DARC subscriptions from dotnet/toolset probably need to be copied to dotnet/sdk)
- [ ] Re-enable Helix
- [x] Re-enable tests as tools

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
> However, we have made some mistakes in the past (e.g. large binaries, multitudes of automated PRs for flowing bits and source between repos, etc.), and we plan to rewrite history to correct those mistakes wherever possible and impactful.

Are you keeping the original history for sdk repos?

**Comment by dsplaisted** [comment]
@livarcocc Remaining work for this I'm aware of:

- Merge or rebase in latest changes from dotnet/sdk, notably including Will's Helix support
- Merge or rebase in latest changes from dotnet/toolset (and possibly dotnet/cli if there are any)
- Go through remaining files in `toolset` directory of repo root, either delete them or move them to a new location.  I think the main things to consider keeping is the Documentation folder, and to update the README in the root as appropriate
- Get tests running in CI (currently they're passing locally for me)
- Make sure MSBuildSdkResolver tests are running (both for .NET Framework and .NET Core).  These seem to be skipped when I do a local build.
- Make sure that all the correct artifacts are published as part of official builds, and that all the correct dependencies are flowing in (DARC subscriptions from dotnet/toolset probably need to be copied to dotnet/sdk)

**Comment by am11** [comment]
@dsplaisted, fyi: with this move, (at least) the files under `docs/` and `scripts/` are quite old when compared to what we had in cli and toolset. All commits, e.g. https://github.com/dotnet/cli/pull/12642, https://github.com/dotnet/toolset/pull/3510, https://github.com/dotnet/toolset/pull/3511 etc. are lost (along with the entire chain of authorship).

**Comment by am11** [comment]
In https://github.com/dotnet/sdk/pull/10721, I picked up the latest version of `obtain/build.sh` `toolset` repo's tree and made changes on top. Some diffs are look scary due to old revision of file. Other files are missing the changes made in Q4 2019.

**Comment by am11** [comment]
In https://github.com/dotnet/sdk/pull/10721, I picked up the latest version of `obtain/build.sh` from `toolset` repo's tree and made changes on top. Some diffs are looking scary due to old revision of file. Other files are missing the changes made in Q4 2019.

**Pull request merged**
