### PR TITLE
Optional Workloads: Add managed library for Windows Installer

### PR DESCRIPTION
**Pull request by joeloff**
This is just a starting point for some of the APIs I've identified that we'd need. Also hoping to keep the PRs more manageable.

Couple of items to call out

- There are very few unit tests. Proper tests would require actually building installers and then installing them which would require elevation on the CI machine when tests are executed. Even if we generated per-user installs, we'd still be altering the CI machine.
- 90% is just boring enums/flags pulled from msi.h, winerror.h, and msiquery.h
- The most interesting code is probably the UI handler, but again, testing it requires hooking up an actual MSI installation
- I deliberately chose the namespace to fit with other Win32 conventions in the runtime. 
- There's a small amount of duplication, e.g. the MessageBox and DialogResult primitives. I duplicated those to avoid taking a dependency on WinForms.
- A few places have missing doc comments (most of the comments come from actual docs or were pieced together from header files, etc.). I felt that we need to have these primitives well documented so they're easier to understand.
- The WindowsInstallerException class doesn't add anything new, except that it provides for a separate exception class that can be utilized to surface install errors.

### CODE REVIEW

**Comment by wli3** [comment]
The lack of tests is indeed a problem. I don't know what these code does exactly. And I don't know what to do if I need to edit the code. Do you think a Windows docker test is viable? Or at least write manual tests so that we can let vendors to test them. And also help the dev to verify when edits are made.

**Comment by joeloff** [comment]
I can provide a simple console app that can be manually run. We'd still need a test MSI too.

**Comment by joeloff** [comment]
@wli3 I added a demo/sample application that illustrates some of the API uses and we can expand that in the future as the API surface grows/changes.

**Comment by wli3** [comment]
@joeloff do you have a write up for how to use them? Could you also put in the source or somewhere in the onenote?

**Comment by joeloff** [comment]
> @joeloff do you have a write up for how to use them? Could you also put in the source or somewhere in the onenote?
> 
> how to build, how to tests, what is the expected behavior

Let me add a readme with some information

**Review by wli3 — APPROVED** [review]

**Pull request merged**
