### PR TITLE
[VMR] Use CopyFiles@2 task instead of manual copying

### PR DESCRIPTION
**Pull request by akoeplinger**
Discussed in https://github.com/dotnet/sdk/pull/44969

### CODE REVIEW

**Review by ViktorHofer — COMMENTED** [review]
Looks great. The `hasScenarioTestResults` variable is now unset but read later. I'm unsure if we really need / want the variable. The task doesn't throw an error if it can't find any scenario test result files but I think it emits a warning.

**Comment by akoeplinger** [comment]
@ViktorHofer looks like it doesn't emit a warning because the glob doesn't match anything (i.e. what we want).

Removed the hasScenarioTestResults.

**Comment by akoeplinger** [comment]
Yes good point, the task will emit a warning which is noisy. I'll add back setting the hasScenarioTestResults.

**Review by ViktorHofer — APPROVED** [review]

**Review by ellahathaway — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@akoeplinger the prebuilt-report folder shouldn't appear for non-source-only builds:

image

Also, I'm not sure if scenario-tests was at this location:

image

I don't really care about the scenario-tests location though.

**Comment by akoeplinger** [comment]
Yeah I saw the prebuilt-report, will fix it.

The scenario-tests artifacts were there before.

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
