### PR TITLE
Fixes for german translations.

### LINKED ISSUE #750: German translation issue with NU1007
Looking over the German translations, I find the [translation of NU1007](https://github.com/dotnet/sdk/blob/890e56ee6f0355f0bf0f1971ed85ba8b8629095a/src/Tasks/Microsoft.NET.Build.Tasks/Resources/xlf/Strings.de.xlf#L156-L160) peculiar:
```xml
<source>Dependency specified was '{0}' but ended up with '{1}'.</source>
<target state="new">Die angegebene Abhängigkeit war „{0}“, aber es endete mit „{1}“.</target>
```
I think there are two issues about this. First, the German translation is a bit off - translated back, the second half of the sentence means `but it ended with '{1}'.`. However, I'm unable to come up with a good translation myself without completely rephrasing the sentence and focusing on the meaning - e.g. `Die angeforderte Abhängigkeit war "{0}", bekam jedoch "{1}".`

This message is very similar to NU1012 (`Dependency conflict. '{0}' expected '{1}' but received '{2}'`) which is imho more clearly understandable.

I'd suggest the english version of NU1007 should be replaced with a simpler message or at least the German translation should be updated.
Suggestions: `The requested dependency was "{0}", but has been resolved to '{1}'.`, `…, but received '{1}'`

cc @natidea @janbaltus

### PR DESCRIPTION
**Pull request by dasMulli**
Fixes #750 as per @akoeplinger's suggestion.
Also fixes a small nit in the translation that @akoeplinger discovered while we discussed this..

cc @nguerrera

### CODE REVIEW

**Comment by nguerrera** [comment]
Thanks! I've tagged #750 as 'localization' which our localization team now monitors. We need to wait for them to approve the change before we can merge.

**Comment by nguerrera** [comment]
@janbaltus

**Review by nguerrera — APPROVED** [review]

**Review by dsplaisted — APPROVED** [review]

**Comment by dasMulli** [comment]
Rebased onto master where the 2nd issue has been fixed already. NU1007 remains.

**Comment by eerhardt** [comment]
@srivatsn @nguerrera @dsplaisted - 

What's the status of taking this change?  Can it be merged?

**Comment by nguerrera** [comment]
Not until loc team approves. I will ping them.

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by janbaltus** [comment]
Fixed translation:
https://github.com/dotnet/sdk/pull/937

**Comment by nguerrera** [comment]
Closing in favor of #937. 

Comment from the translator on that change there: 

> This string translates back to Dependency specified was '{0}' but the actual dependency was '{1}'; this should be correct in the context.

With that said, they also seconded @akoeplinger's sentiment that "However, I'm unable to come up with a good translation myself without completely rephrasing the sentence and focusing on the meaning".

We have to keep our xlf files in sync with the loc team's database so even if there is further discussion, the correct recourse here is to merge #937 and close this.

I think that if we're still not happy with the wording we should focus on making the English text clearer (possibly merging with similar but clearer errors) first. That would make the experience better for all languages.

Thank you, @akoeplinger and @dasMulli for your help with this. I also apologize for the long turnaround time. There was a glitch in the query for localization tagged issues (now fixed) that slowed us down on this one.

**Comment by akoeplinger** [comment]
Thanks. It's better than the original but I think there's still room for improvement to convey clearly that the build task picked a different dependency than the specified one.

I agree however that improving the English text should be the first step :)

**Comment by eerhardt** [comment]
Looking through this (rather quickly so I probably missed something), I don't see where this resource string is used in our code.  @nguerrera - do you know?

**Comment by nguerrera** [comment]
@natidea defensively pulled in all of the nuget dependency diagnostics pre loc deadline. Some may not be used (yet?).

**Comment by eerhardt** [comment]
I only see 2 of the 9 "NU10xx" strings actually used.

I don't see any of the 5 "DOTNET10xx" strings being used.

For as much time as was spent on this unused string, I wonder if the cost of pulling those strings in early out-weighed the benefits.

**Comment by akoeplinger** [comment]
CLI seems to be using it: https://github.com/search?q=org%3Adotnet+NU1007&type=Code (though looks like only in PJ migration).

**Comment by nguerrera** [comment]
We should clean it up for sure. As far as benefits, I think going through the motions of how to fix translations and coordinate with loc team in this new process was a useful exercise regardless.

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/issues/938

**Pull request closed without merging**
