### PR TITLE
always use design time targets

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by srivatsn** [comment]
You should retarget to the 1.1 branch since that's what goes into 15.3

**Comment by brettfo** [comment]
The changed file doesn't exist in `rel/1.1.0`.  #1172 added this file to `master`, do you want it cherry-picked here, too?

**Comment by nguerrera** [comment]
Looks good. I assumed when reviewing this originally with @KevinRansom that the design time targets would be imported by the inner F# targets already.

**Comment by nguerrera** [comment]
I'm not sure about putting this in 1.1 though, because the 1.1 CLI doesn't have F# as of yet. Does that need to happen too?

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Debug.

**Comment by livarcocc** [comment]
This is a weird one that we have no anticipated. This is 2.0 functionality for the CLI but in the box for VS. What will happen if we ship these targets in the 1.1 CLI?

**Comment by brettfo** [comment]
@dotnet-bot test this please

**Comment by brettfo** [comment]
Ping for review for inclusion in 1.1 as part of Dev 15.3 RTW.

We're aware that this puts the CLI into a weird spot where the F# targets are included but the compiler is not, but we need this functionality to get the IDE working in the scenario:

- `dotnet new console -lang F#`
- `devenv MyProject.fsproj`

These targets files are what will allow the language service to function in VS.

In the situation that a user has the 1.1 CLI installed without F# VS support, they won't be able to do `dotnet new console -lang F#` and if they tried to build an `.fsproj` then they would get the expected error that the compiler isn't present, because that's not supported anyways.

@KevinRansom for visibility.

**Comment by nguerrera** [comment]
I don't follow. 

If the user has only 1.1 CLI installed, then `dotnet new console -lang F#` will create a project using FSharp.NET.Sdk, which the bundled targets here detect and short-circuit.

**Comment by brettfo** [comment]
After talking with @nguerrera and @KevinRansom we decided that the experience of telling users to manually install dotnet 2.0 is fine, especially since 2.0 will be appropriately bundled with future versions (>15.3) of VS anyways.

PR has been retargeted to 2.0.

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
Fill out the template as in https://github.com/dotnet/sdk/pull/1352 and tag Matt for approval.

**Comment by brettfo** [comment]
@dotnet-bot test this please

**Comment by brettfo** [comment]
Tagging @MattGertz for approval pending CI tests.

**Customer scenario**
When editing an F# dotnet core project in VS, much of the Solution Explorer's functionality is disabled leaving only a flat list of files under the project and this is undesirable.

**Bugs this fixes**
Discovered during manual testing; no actively tracked bug.

**Workarounds, if any**
None.

**Risk**
Low

**Performance impact**
Low; additional targets files are processed at project open, but these are needed to enable basic functionality.

**Is this a regression from a previous update?**
No, dotnet core support hasn't been provided in the past.

**Root cause analysis**
Other project types only need to conditionally include the design time targets when doing cross-targeting builds.  When this was copy/pasted from that location the invalid condition came along with it.

**How was this bug found?**
Ad-hoc testing.

**Pull request merged**
