### PR TITLE
Update to VSTest 16.5

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
See #10735 

Leaving that open to track the automation

**Comment by nguerrera** [comment]
@mmitche @wli3 @dsplaisted Should we try to take this in P1? My inclination is no at the point we're at and judging by other P1 issues we were willing to reject.

Tests are failing due to different test output and that will take some time to sort out.

**Comment by mmitche** [comment]
> @mmitche @wli3 @dsplaisted Should we try to take this in P1? My inclination is no at the point we're at and judging by other P1 issues we were willing to reject.
> 
> Tests are failing due to different test output and that will take some time to sort out.

Nah, let's just catch the next branch date (I think it's next week)

**Comment by nguerrera** [comment]
Will fix this up to target master

**Comment by nguerrera** [comment]
I'll cherry-pick the commit onto the merge to master

**Pull request closed without merging**
