### PR TITLE
Fix FXVersion manifest version bug

### LINKED ISSUE #17567: workload install failing because of android manifest package version
```
dotnet --version
6.0.100-preview.5.21261.3
```

```
dotnet workload install microsoft-net-sdk-blazorwebassembly-aot          

Failed to update the advertising manifest microsoft.net.workload.blazorwebassembly: microsoft.net.workload.blazorwebassembly.manifest-6.0.100 is not found in NuGet feeds https://api.nuget.org/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json, https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json",.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.ios.
Installing workload manifest microsoft.net.sdk.android version 30.0.100---ci.main.0.
Workload installation failed, rolling back installed packs...
Installing workload manifest microsoft.net.sdk.android version 11.0.200---ci.main.256.
Installation roll back failed: Failed to install manifest microsoft.net.sdk.android version 11.0.200---ci.main.256: The transaction has aborted..
Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 30.0.100---ci.main.0: One or more errors occurred. (microsoft.net.sdk.android.manifest-6.0.100::30.0.100---ci.main.0 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json",).
install
  Install a workload.

Usage:
  dotnet [options] workload install [<PACKAGE_ID>...]

Arguments:
  <PACKAGE_ID>  The NuGet Package Id of the workload to install.

Options:
  --sdk-version <VERSION>                                                  The version of the SDK.
  --configfile <FILE>                                                      The NuGet configuration file to use.
  --add-source <SOURCE>                                                    Add an additional NuGet package source to use during installation.
  --skip-manifest-update                                                   Skip updating the workload manifests.
  --from-cache <from-cache>                                                Complete the operation from cache (offline).
  --include-previews                                                       Allow prerelease workload manifests.
  --disable-parallel                                                       Prevent restoring multiple projects in parallel.
  --ignore-failed-sources                                                  Treat package source failures as warnings.
  --no-cache                                                               Do not cache packages and http requests.
  --interactive                                                            Allows the command to stop and wait for user input or action (for example to complete authentication).
  -v, --verbosity <d|detailed|diag|diagnostic|m|minimal|n|normal|q|quiet>  Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  -?, -h, --help                                                           Show help and usage information


```

```
nuget list -Source xamarin -Prerelease microsoft.net.sdk.android.manifest
Microsoft.NET.Sdk.Android.Manifest-6.0.100 30.0.100-ci.main.0+sha.d3ae4e1
```

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/17567

### CODE REVIEW

**Comment by dsplaisted** [comment]
Actually, I hit the same thing and fixed it (I think) for 5.0.300 in #17329.  So you may just want to merge the 5.0.3xx changes forward.  Also take a look at the difference between the fixes, it looks like we're handling the build number differently.

**Comment by sfoslund** [comment]
It looks like main does contain those commits but somehow the changes got lost in places (maybe a bad merge?). I'll fix the build difference but otherwise main seems to have the changes from https://github.com/dotnet/sdk/pull/17329

**Comment by dsplaisted** [comment]
I had also added test coverage which seems to have gotten lost.  Maybe you could try re-cherrypicking those commits?

**Comment by sfoslund** [comment]
> Maybe you could try re-cherrypicking those commits?

Sure, just pushed those instead of my changes

**Review by dsplaisted — APPROVED** [review]

**Comment by sfoslund** [comment]
> StdOut:
MSBuild auto-detection: using msbuild version '16.10.0.18105' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin'.
StdErr:
C:\h\w\B44909B0\t\dotnetSdkTests\iu5e2p3p.enm\ItCanBuildPro---2831E99A\ItCanBuildProjectRestoredWithNuGet5_7\ItCanBuildProjectRestoredWithNuGet5_7.csproj : warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. Missing or invalid manifest version
C:\h\w\B44909B0\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. Missing or invalid manifest version
C:\h\w\B44909B0\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): error : C:\h\w\B44909B0\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.SDK.WorkloadAutoImportPropsLocator\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
C:\h\w\B44909B0\p\d\sdk\6.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [C:\h\w\B44909B0\t\dotnetSdkTests\iu5e2p3p.enm\ItCanBuildPro---2831E99A\ItCanBuildProjectRestoredWithNuGet5_7\ItCanBuildProjectRestoredWithNuGet5_7.csproj]

@dsplaisted this is failing consistently, it looks like a workload resolver issue, do you have any ideas?

**Comment by dsplaisted** [comment]
That test calls nuget.exe to restore, which ends up using the full Framework version of MSBuild.  So it sounds like this is failing because the version of VS on the CI machine doesn't have the SDK resolver changes for the manifest version number schema change.

Probably if you change the test to set `MSBuildEnableWorkloadResolver` to false (currently it sets it to true) the test will start working.  Otherwise we can disable the test until CI machines get updated.

**Comment by lewing** [comment]
A fix here needs to make it into preview5.

**Comment by dsplaisted** [comment]
@sfoslund This needs to be retargeted to Preview 5, right?  (I disabled auto-merge because of this.)

**Comment by sfoslund** [comment]
@dsplaisted I was going to port it to preview 5 after it's in main

**Comment by sfoslund** [comment]
Preview 5 PR: https://github.com/dotnet/sdk/pull/17668

**Pull request merged**
