### PR TITLE
Allow ResolveReadyToRunCompilers to be run under FreeBSD

### PR DESCRIPTION
**Pull request by sec**
This should enable almost patchless build of runtime under FreeBSD, with R2R. @Thefrank

### CODE REVIEW

**Comment by Thefrank** [comment]
Matching runtime PR (also by @sec ) here: https://github.com/dotnet/runtime/pull/84250

**Review by josteink — APPROVED** [review]
LGTM

**Comment by sec** [comment]
Should this be changed to match it's runtime version - ex. https://github.com/dotnet/runtime/commit/1b6d95b29aeaf80598ddf3cc7e25a46740ca3759 ?

**Comment by Thefrank** [comment]
Not code owner, but the note states that it should be sync'd with runtime which I read as "match"

**Comment by sec** [comment]
Pushed changes to match with runtime code.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by sec** [comment]
Looks like ready to be merged?

**Comment by mthalman** [comment]
The SDK that contains this change fails to build the [ILCompiler project](https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj). This is a blocking issue for the RC1 release. See https://github.com/dotnet/source-build/issues/3568

**Pull request merged**
