### PR TITLE
re-enable tests and update cli

### PR DESCRIPTION
**Pull request by rohit21agrawal**
CC: @srivatsn @natidea @rrelyea  @nguerrera

### CODE REVIEW

**Comment by rohit21agrawal** [comment]
since there is not a nuget restore xplat entrypoint anymore, we need to modify build scripts so they download an older version of dotnet to restore legacy projects.

CC: @emgarten

**Comment by dsplaisted** [comment]
Alternatively, we could switch from project.json to `PackageReference` for the dependencies, as specified by #342.

**Comment by dsplaisted** [comment]
I've converted the dependencies folder to use `PackageReference` instead of project.json, and that seems to have gotten me past that issue.

Now, I'm getting errors because NuGet.CommandLine.XPlat.dll doesn't recognize the Pack command anymore.  With the current version of the CLI, is there a way to create a .nupkg from a .nuspec? @emgarten @rrelyea @rohit21agrawal @yishaigalatzer

**Comment by dsplaisted** [comment]
I've pushed my changes to use `PackageReference` to https://github.com/dsplaisted/sdk/tree/dev-ragrawal-updatecli.

It looks like support for packing a nuspec was just added in https://github.com/NuGet/NuGet.Client/pull/1100, which wouldn't have made it into the CLI we're trying to update to.  I think the path forward for now is to use the Windows NuGet.exe to create our NuGet packages, and disable package creation on other OS's for now.

**Comment by dsplaisted** [comment]
I've updated this PR with changes so that the CI builds pass:

- Switched the Dependencies projects to use `PackageReference` instead of project.json, as the .NET CLI doesn't support restoring project.json anymore
- Use NuGet.exe to build our NuGet packages, since NuGet.CommandLine.XPlat doesn't support the `pack` command anymore.  To do this, I had to disable building packages on non-Windows OS's
- Removed workaround for https://github.com/NuGet/Home/issues/3851
- Fixed an issue where MSBuild didn't like checking for the existence of files in a path with semicolons
- Disabled publish tests which were failing.  There's a null reference happening [here](https://github.com/dotnet/sdk/blob/e4eb65dee3fa7b4a5bf21a9b73f74171511b89f6/src/Tasks/Microsoft.NET.Build.Tasks/PublishAssembliesResolver.cs#L61), but when I fixed that I ran into other issues which look to be related to https://github.com/NuGet/NuGet.Client/pull/1072.  That PR adds files under project entries in the assets file with paths which include "bin/placeholder", which doesn't exist.  The publish task fails when it can't find these files.  We need to fix this but I'd suggest we do it separately so we can work on and review other fixes in parallel.

Followup items to file:

- [ ] Fix warnings about double imports in Dependencies projects
- [ ] Use NuGet pack MSBuild task to create our NuGet packages. This depends on us updating to a version of the NuGet tasks with NuGet/Nuget.Client#1100.  This will allow us to enable building packages on non-Windows OS's again
- [ ] Fix Publish task and re-enable tests

@srivatsn for approval

**Comment by dsplaisted** [comment]
I think I've fixed the publish issue, with a change I've pushed to https://github.com/dsplaisted/sdk/tree/fix-publish

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
@MattGertz for approval. This is an infrastructure-only change needed to re-enable some tests that were disabled due to a recent nuget version upgrade.

**Pull request merged**
