### PR TITLE
Clean-up Redist.csproj as ItemsToPush aren't respected from that file

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by mmitche** [comment]
I think this is right. Can you run an official build with the changes to verify?

**Comment by ViktorHofer** [comment]
Sure. Here's the build: https://dnceng.visualstudio.com/internal/_build/results?buildId=2415980&view=results

I guess I just need to compare the build manifest(s) then?

**Comment by mmitche** [comment]
yep

**Comment by ViktorHofer** [comment]
Jep diff looks good: https://www.diffchecker.com/5VZIL096/

The ItemToSign removal is probably due to postbuildsign for rolling builds vs manually queued builds.

**Review by mmitche — APPROVED** [review]

**Pull request merged**
