### PR TITLE
Put Program class in Console App template inside namespace

### LINKED ISSUE #271: C# Console App template doesn't use namespace for Program class, but adding classes will have a namespace
The .NET Core Console application template doesn't use a namespace in [Program.cs](https://github.com/dotnet/sdk/blob/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpConsoleApplication/Program.cs).  That is simpler and cleaner, but if you add a class to the project from Visual Studio, the new class will be inside the default namespace for the project.  This means you'll have to add a using statement to `Program.cs` to use any additional classes.

Possible fixes I can think of:
- Do nothing, let people rely on quick fixes to add the using statement if they need it
- Add `using $safeprojectname$;` to the `Program.cs` template
- Update the `Program.cs` template to put the `Program` class inside the default namespace for the project
- Get rid of default namespace for console apps in the SDK altogether.  This would probably mean a condition in the targets that only sets the default namespace for class libraries (or some similar criteria).  The new class template in VS (and maybe all code templates) would need to be updated so that it doesn't try to put the class in a namespace if the default namespace is empty.

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #271

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Comment by dsplaisted** [comment]
@dotnet-bot test this please

**Comment by dsplaisted** [comment]
@MattGertz for approval

#### Scenario

- Create a new .NET Core Console app
- Add a new class to the project
- Attempt to use the new class from the Program class

Currently, the new class won't be directly accessible from the Program class, as it's in a namespace, and `Program` isn't.  This change puts the `Program` class inside the default namespace for the project, which fixes the issue and aligns with the other templates.

#### Bug

#271 

#### Workarounds

Add a `using` statement to Program.cs for the default namespace, or move the `Program` class inside that namespace yourself.

#### Risk

Low

#### Performance Impact

Negligible. This adds a few more lines to a new project template.

#### Regression Analysis

Not a regression

**Comment by MattGertz** [comment]
Yes, because user would otherwise have to manually fix up their code Every. Single. Time.

**Comment by natidea** [comment]
Approved to merge via [375369](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/375369)

**Pull request merged**
