### PR TITLE
Insert TestPlatform v15.0.0-preview-20170210-02.

### PR DESCRIPTION
**Pull request by codito**
Issues fixed:
* Replace invalid characters in trx with unicode escape character (issue microsoft/vstest#320)
* Standard error messages from testhost are passed to console runner (issue microsoft/vstest#281)
* Add autogenerated header to `Program.cs` (issue microsoft/vstest#420)
* Change type name of autogenerated entrypoint (issue microsoft/vstest#430)
* Show adapter messages on runner output (issue microsoft/vstest#300)
* Use RC.3 VSSDK manifests for vsix generation
* **(Edit)** MSBuild  warning on simple xunit test project (issue microsoft/vstest#433)
ASK mode template: [Bug 383308](https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_workitems?_a=edit&id=383308&triage=true)

Required for RTW. Above bug is pending approval.

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Comment by natidea** [comment]
@srivatsn do we also need to bring this one to shiproom

**Comment by srivatsn** [comment]
We are waiting for @sbaid to bring the equivalent VS change to shiproom.

**Comment by piotrpMSFT** [comment]
@srivatsn it looks like the VS change was approved. We've already merged the CLI equivalent of this change.

**Comment by sbaid** [comment]
@Srivatsn pl go ahead with insertion of templates
@bradwilson @onovotny fyi

**Comment by srivatsn** [comment]
@MattGertz - the Testplatform bug [383308](https://devdiv.visualstudio.com/DevDiv/_workitems?id=383308&_a=edit) was approved at shiproom. Can we get approval to merge?

**Comment by bradwilson** [comment]
Is this the final changes? We're planning to ship an RTM version of xUnit.net, and we wouldn't want VS2017 RTM to reference RC2 xUnit.net.

**Comment by sbaid** [comment]
this is not final change.

**Pull request merged**
