### PR TITLE
Update NetAnalyzers version for release/7.0.2xx

### PR DESCRIPTION
**Pull request by Youssef1313**
Same as https://github.com/dotnet/sdk/pull/29463, but for 7.0.2xx

### CODE REVIEW

**Comment by Youssef1313** [comment]
Could someone take a look please?

**Review by jaredpar — APPROVED** [review]

**Comment by jaredpar** [comment]
@Youssef1313 can you fix the conflict then it should merge now.

**Comment by mavasani** [comment]
I think this needs parallel changes to Versions.Details.xml, similar to https://github.com/dotnet/sdk/pull/29975/files

**Comment by Youssef1313** [comment]
This got updated in https://github.com/dotnet/sdk/pull/29893 and I didn't notice while resolving the conflict. Closing.

**Pull request closed without merging**
