### PR TITLE
Block loading the 7.0.100 SDK in 16.11 and below VS and MSBuild versions

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]
Any reason we shouldn't bump up the [minimumMSBuildVersion](https://github.com/dotnet/sdk/blob/main/src/Layout/redist/minimumMSBuildVersion) to 17.0 instead?

**Comment by marcpopMSFT** [comment]
Fair point as the new version of the sdk should at least limit to the version of msbuild the last SDK shipped with. Should we update the min vs version in 6.0.300 as well to be 17.0? 

@baronfel any opinion on minimum msbuild versions?  We kept 6.0.100 from requiring 17.0 so that we wouldn't have issues on release day forcing customers to update their VS at the same time as their SDK.  We're now past that so there will be fewer customers impacted as those who don't want to upgrade to 17.0 can always stick with 6.0.100.

**Comment by baronfel** [comment]
I'm perfectly ok with bumping our min version on the 'next' release, so that we don't force folks to upgrade.

**Comment by marcpopMSFT** [comment]
Per offline decision, we'll update the minimum version to 17.0 in 6.0.300 and 7.0.100. I'll take care of one of those in this PR and the other separately.

**Comment by marcpopMSFT** [comment]
Waiting on this: https://github.com/dotnet/core-eng/issues/15439

**Comment by marcpopMSFT** [comment]
@dsplaisted I've updated to VS2022 helix images but there are still test failures. Most of the test failures appear to be failures to find the netfx reference packs. Is something missing from the image creation or is this a change in 2022 compared with 2019?
```
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\h\w\AECF09A2\t\dotnetSdkTests\5m1n1wv3.hgw\It_includes_n---31F8C9D8\TestApp\TestApp.csproj]
```

**Comment by dsplaisted** [comment]
@marcpopMSFT A lot of the targeting packs are no longer available with VS 2022.  Probably we should update the test assets to reference [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/).  That might be a good task for @gkulin.

**Comment by marcpopMSFT** [comment]
@dsplaisted Any ideas on how to fix WinMDInteropProjectCanBeReferenced? Looks like it can't find vcrtforwarders. If you don't have a quick fix, should we disable the test to get this in before preview 3?
```
Restoring packages for C:\h\w\A9A60968\t\dotnetSdkTests\x1ar5je2.qdi\WinMDInteropP---5FD7A248\ConsoleApp\ConsoleApp.csproj...
Restoring packages for C:\h\w\A9A60968\t\dotnetSdkTests\x1ar5je2.qdi\WinMDInteropP---5FD7A248\SimpleMathProjection\SimpleMathProjection.csproj...
GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2/microsoft.vcrtforwarders.140/index.json
```

**Comment by dsplaisted** [comment]
@marcpopMSFT The output on that failing test is truncated.  It restored fine, here's the section with the actual error:

```
    C:\git\dotnet-sdk2\artifacts\.nuget\packages\microsoft.vcrtforwarders.140\1.0.7\build\netcoreapp2.0\Microsoft.VCRTForwarders.140.targets(91,9): warning :  Because your app is being built as AnyCPU no Microsoft.VCRTForwarders.140 DLLs were copied to your ouput folder. Microsoft.VCRTForwarders.140 only supports x86, x64, or arm64 applications due to a C++ Runtime dependency. Please change your app project architecture to x86, x64, or arm64 in the Configuration Manager. [C:\git\dotnet-sdk2\artifacts\tmp\Debug\WinMDInteropP---5FD7A248\ConsoleApp\ConsoleApp.csproj]
PrepareForBuild:
  Creating directory "bin\Debug\net5.0-windows10.0.19041.0\".
  Creating directory "obj\Debug\net5.0-windows10.0.19041.0\".
  Creating directory "C:\git\dotnet-sdk2\artifacts\tmp\Debug\WinMDInteropP---5FD7A248\ConsoleApp\obj\Debug\net5.0-windows10.0.19041.0\refint\".
  Creating directory "obj\Debug\net5.0-windows10.0.19041.0\ref".
Project "C:\git\dotnet-sdk2\artifacts\tmp\Debug\WinMDInteropP---5FD7A248\ConsoleApp\ConsoleApp.csproj" (1:7) is building "C:\git\dotnet-sdk2\artifacts\tmp\Debug\WinMDInteropP---5FD7A248\SimpleMathComponent\SimpleMathComponent.vcxproj" (3:5) on node 1 (default targets).
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(823,5): error : The BaseOutputPath/OutputPath property is not set for project 'SimpleMathComponent.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\git\dotnet-sdk2\artifacts\tmp\Debug\WinMDInteropP---5FD7A248\SimpleMathComponent\SimpleMathComponent.vcxproj]
Done Building Project "C:\git\dotnet-sdk2\artifacts\tmp\Debug\WinMDInteropP---5FD7A248\SimpleMathComponent\SimpleMathComponent.vcxproj" (default targets) -- FAILED.
```

I think this is probably due to a different C++ toolset in the new VS version.  I'd suggest disabling it for now, filing a bug, and seeing if @angelazhangmsft or @j0shuams can help us update the test appropriately.

**Comment by marcpopMSFT** [comment]
Disabled and filed https://github.com/dotnet/sdk/issues/24326

**Pull request merged**
