### PR TITLE
[Experimental] support using classic projects to target .NET Core or .NET Standard

### PR DESCRIPTION
**Pull request by dsplaisted**
These changes allow you to simply change the `TargetFrameworkVersion` property of a "classic" project file to `TargetFramework` in order to target .NET Core or .NET Standard without any additional changes to your project files.

For this to work, you need the following Directory.Build.props:

```xml
<Project>
  <PropertyGroup>
    <UsingMicrosoftNETSdk>false</UsingMicrosoftNETSdk>
    <ImportCommonPropsAndTargetsFromMicrosoftNETSdk>false</ImportCommonPropsAndTargetsFromMicrosoftNETSdk>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk"/>
</Project>
```

And the following Directory.Build.targets:

```xml
<Project>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk"/>
</Project>
```

### CODE REVIEW

**Comment by davidfowl** [comment]
What's this feature? Is there a sample of using it?

**Comment by nguerrera** [comment]
It's not a feature yet ;)

We're investigating (as part of the hackathon) what it would take to support classic projects...

Microsoft.NET.Sdk today is two things:

1. All the behaviors that make new projects terse.
2. Things that are required to build for netcoreapp and netstandard.

(1) is great if you're starting fresh, but gets in the way if you would rather just retarget an existing project.

So the question is can we split these things apart, and the approach in this PR is the most expedient way to demonstrate that. 

*If* we go forward in the product with anything official, II want to formally layer the code and not just sprinkle conditions around.

**Comment by davidfowl** [comment]
> Things that are required to build for netcoreapp and netstandard.

What does that mean though? Does that basically boil down to treating the SDK like a set of props and targets?

**Comment by davidfowl** [comment]
So the goal is to take something like this:

https://github.com/zzzprojects/html-agility-pack/blob/1dfe439abf70518690106ac497455948d9c73390/src/HtmlAgilityPack/HtmlAgilityPack.fx.4.5.csproj

And change this:

https://github.com/zzzprojects/html-agility-pack/blob/1dfe439abf70518690106ac497455948d9c73390/src/HtmlAgilityPack/HtmlAgilityPack.fx.4.5.csproj#L24

To be netstandard or netcoreapp? (Or maybe reuse the same TargetFramework moniker)? The goal being that people can convert their class libraries easily? What else do they gain? Transitive P2Ps?

**Comment by nguerrera** [comment]
It's about easier conversion. If you want all the nice features you can convert all the way as before. We know folks have had a really hard time with conversion to full sdk in reasonably complex solutions. And the nature of msbuild is that automatic conversion to that is nearly impossible.

If you just want out core with your existing code, the question is can we make that easier. It's painful if you spend a bunch of time converting only to learn that you're missing a runtime feature there critical to your app. 

Once you have your apo working, you might still take an interest in doing the full blown conversion to get a bunch of nice features. But then you're doing it because that's what you want and not because it was a roadblock. 

Again, this is an investigation to see what it might look like. Nothing is committed.

**Comment by davidfowl** [comment]
> If you just want to try out core with your existing code, the question is can we make that easier. It's painful if you spend a bunch of time converting only to learn that you're missing a runtime feature that is critical to your app.

So this is about applications or libraries or both? Console applications only? (I guess WPF and Winforms in .NET Core 3.0). Web apps definitely won't work.

> Again, this is an investigation to see what it might look like. Nothing is committed.

I'm not worried about that I understand it's an experiment right now. I just want to understand it.

The reason I'm asking is also because there's no sample project in the PR 😄

**Comment by nguerrera** [comment]
Also, yes, the change to the linked line alone is the end goal of this investigation.

**Comment by nguerrera** [comment]
Winforms, WPF, console apps, and class libraries. Things that often won't require much code change at all. I think it's fine to exclude web.

**Comment by nguerrera** [comment]
> The reason I'm asking is also because there's no sample project in the PR 

It's 9 am on the first day of the hackathon. 😉

**Comment by dsplaisted** [comment]
Merging this into an experimental branch.

**Pull request merged**
