### PR TITLE
Added archival on failure, switched to public machines as the sdk is …

### PR DESCRIPTION
**Pull request by 333fred**
…a public repo.

@dotnet-bot test ci please

Tagging @nguerrera @dotnet/roslyn-infrastructure @dotnet/project-system for review.

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet-bot test ci please

**Review by basoundr — APPROVED** [review]

**Review by mavasani — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet-bot test ci please

**Comment by 333fred** [comment]
@dotnet-bot test ci please

Fixes #619.

**Comment by 333fred** [comment]
Tagging @MattGertz for merge approval, Jenkins-only change.

**Comment by TyOverby** [comment]
👍

**Pull request merged**
