### PR TITLE
Update core branding

### PR DESCRIPTION
**Pull request by sfoslund**
Removing `core` from branding/ first run experience

### CODE REVIEW

**Review by dsplaisted — COMMENTED** [review]
@KathleenDollard @richlander @terrajobst for branding updates.

@sfoslund I don't think we should be updating the .xlf files here.  I think we should let the changes flow through the localization process.

@nguerrera @wli3 thoughts?

**Comment by dsplaisted** [comment]
@sfoslund Looks like some tests are failing expecting the old strings.

**Comment by sfoslund** [comment]
@dsplaisted The .xlf files are updated automatically when building locally- should those changes not be committed?

**Comment by nguerrera** [comment]
They should be committed. As long as you didn’t edit the translation and only allowed the source text and target state to be updated, that is correct and normal.

**Review by dsplaisted — APPROVED** [review]

**Review by KathleenDollard — APPROVED** [review]

**Pull request merged**
