### PR TITLE
Pack dotnet-watch with the SDK

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/29268

### CODE REVIEW

**Comment by wli3** [comment]
There should also be a change in dotnet/installer or dotnet/installer will still override the files. And you need to make this change soon since the next insertion to dotnet/installer will fail due to missing dotnet-watch. On another thread, we need to get a good build of 5.0.2xx by Friday. You need to merge them both in a short time.

**Review by wli3 — APPROVED** [review]
Assuming you double checked the content of produced dotnet-internal nupkg

**Comment by wli3** [comment]
Also please make sure the layout is the same, there is no missing or extra layer of folders

**Comment by pranavkm** [comment]
Thanks @wli3. I confirmed that the only extra files compared to the baseline are the dotnet-watch binaries that were added.

**Pull request merged**
