### PR TITLE
Temporary fix for the cppcli tests

### PR DESCRIPTION
**Pull request by marcpopMSFT**
Updating to preview 7 is blocked by some test failures in winforms so this is an alternative option to that to unblock codeflow

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
From @dsplaisted 
I believe `_EnablePackageReferencesInVCProjects` is there because originally C++/CLI didn't support PackageReference (and NuGet restore), they only added that a few years ago.  So some of the behavior is different.  I wouldn't want to change that condition without understanding more, that would be a product change that might break something for C++/CLI.  In this case it would disable the valid TFM check for C++/CLI when using PackageReference, I don't know why that shouldn't be a valid check there.

Adding a few others to comment on why we might have had additional checks for  `_EnablePackageReferencesInVCProjects` (there are 12 total checks for that property in our various targets and I'm trying to determine if they are all necessary). In particular, the ones in targetframeworkinferences appear to check for target platform support. @olgaark @manodasanW Is my change to the targets in this PR the right change for the c++ tests that were having issues with the windows SDK target platform?

**Comment by olgaark** [comment]
_EnablePackageReferencesInVCProjects is still needed. It is set to true in cpp targets only for vc projects that have EnableManagedPackageReferenceSupport as true (false by default)

**Comment by marcpopMSFT** [comment]
> _EnablePackageReferencesInVCProjects is still needed. It is set to true in cpp targets only for vc projects that have EnableManagedPackageReferenceSupport as true (false by default)

@olgaark Thanks for the context. What I'm trying to determine here is why we have this in three places in this file `('$(Language)' != 'C++' or '$(_EnablePackageReferencesInVCProjects)`. Specifically, we're checking **or** which means that we'll skip the target for c++ but still include it if package reference is enabled for C++.

This shows up for a property group and two targets in this file. Should these three checks include the _EnablePackageReferencesInVCProjects as that means they are always triggered for c++ apps that have package ref enabled.
[propertygroup ](https://github.com/dotnet/sdk/blob/7583220d77461363bfc1787d5d1c261479baa060/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L202)
_NormalizeTargetPlatformVersion
_CheckForInvalidTargetPlatformVersion

**Comment by baronfel** [comment]
@marcpopMSFT is this still needed or did we fix it another way?

**Comment by marcpopMSFT** [comment]
@baronfel this is not strictly required to fix the prior issue as that fix was to upgrade the stage 0 SDK (done in 9, not in 8). I was hoping I'd get some feedback on whether that flag is needed in these sdk checks or not from @olgaark It sounds like it's still required for cppcli scenarios to use package ref but these sdk checks maybe don't need that additional check (and can just check for c++). IE it's possible we may still want to simplify these checks.

**Comment by marcpopMSFT** [comment]
Lucca and Olga believe that now that we've updated the stage0 version of the SDK, no changes are needed. I'm still not 100% sure that these checks are correct but it's how it was before so closing for now.

**Pull request closed without merging**
