### PR TITLE
Update dependabot to run on 4xx

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@YuliiaKovalova should we only target main for dependabot to avoid the quarterly updates needed here?

**Comment by marcpopMSFT** [comment]
ping @YuliiaKovalova

**Comment by YuliiaKovalova** [comment]
@vlada-shubina do you have any concerns with the suggestion?

**Comment by vlada-shubina** [comment]
@marcpopMSFT 

dotnet/templating has dependabot configured for all branches which are tracked for CG and we are taking those updates also for branches in servicing if needed. 

we definitely need to keep it for quarterly branch in progress, and i also recommend to keep it for branches in servicing not to miss security updates.

**Comment by marcpopMSFT** [comment]
Most of these packages are unlikely to fall afoul of CG as it only flags security issues. I want to keep them updated in main and maybe the live branch but I don't need to update every version in every branch every time there is an update (and it's clear here, that these update frequently).

So I'd prefer main, or main+7.0.4xx, but not more.

**Comment by marcpopMSFT** [comment]
Concerns with me making this main only or main + 4xx? I personally find it fairly frustrating that it creates PRs that fail the first time, require manual intervention to get the package put on our feed, and then can't be merged into servicing as the branch isn't open. At least making it so the PRs can be merged would be a step forward as right now we have a bunch into 3xx that are waiting for the branch to open.

@v-wuzhai do you think you'd be able to add dependabot PRs to your monitoring list?  When you get PRs like [this](https://github.com/dotnet/sdk/pull/32143), you have to follow [the instructions]( https://github.com/dotnet/arcade/blob/main/Documentation/MirroringPackages.md) to get the package mirrored before re-kicking the run. So far the pipeline has worked fairly well for me. Some issues I've run into with the pipeline is watch out for whitespace in the package name and you can't use "latest" if there is a newer preview version (ie latest won't just do latest/stable)

**Comment by vlada-shubina** [comment]
> Concerns with me making this main only or main + 4xx? I personally find it fairly frustrating that it creates PRs that fail the first time, require manual intervention to get the package put on our feed, and then can't be merged into servicing as the branch isn't open. At least making it so the PRs can be merged would be a step forward as right now we have a bunch into 3xx that are waiting for the branch to open.
> 
> @v-wuzhai Jason Zhai (Beyondsoft Corporation) Vendor do you think you'd be able to add dependabot PRs to your monitoring list? When you get PRs like [this](https://github.com/dotnet/sdk/pull/32143), you have to follow [the instructions](https://github.com/dotnet/arcade/blob/main/Documentation/MirroringPackages.md) to get the package mirrored before re-kicking the run. So far the pipeline has worked fairly well for me. Some issues I've run into with the pipeline is watch out for whitespace in the package name and you can't use "latest" if there is a newer preview version (ie latest won't just do latest/stable)

i don't have any objections. From templating side, we can always bump the version in servicing branches manually, in case of addressing security issues.

**Review by v-wuzhai — APPROVED** [review]

**Pull request merged**
