### PR TITLE
Update testplatform to v15.0.0-preview-20170123-02.

### PR DESCRIPTION
**Pull request by codito**
Fixes part of this release:
* Allow multiple test properties with same key [#239](https://github.com/Microsoft/vstest/issues/239), [#358](https://github.com/Microsoft/vstest/issues/358)
* Localization for testplatform vsix package [#146](https://github.com/Microsoft/vstest/issues/146)
* Working directory should be set to test source parent directory [#311](https://github.com/Microsoft/vstest/issues/311)
* Allow relative source paths to vstest.console [#331](https://github.com/Microsoft/vstest/issues/331)
* Stacktrace and error message should be in context of failed test [#285](https://github.com/Microsoft/vstest/issues/285)

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
Tagging @MattGertz for approval.

**Comment by MattGertz** [comment]
@srivatsn Template?  I'm not clear what these are.

**Comment by srivatsn** [comment]
Ah yes- @codito can you please fill out the escrow template from here - https://github.com/dotnet/roslyn-project-system/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by sbaid** [comment]
@MattGertz @srivatsn  @codito  [Bug 371113](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/371113):TestPlatform RTW fixes insertion has askmode details.

**Comment by srivatsn** [comment]
@dotnet-bot test this please.

**Comment by srivatsn** [comment]
@333fred any idea what's happening here? Is this due to https://github.com/dotnet/sdk/pull/632?

**Comment by 333fred** [comment]
Probably. I'm going to revert it.

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by 333fred** [comment]
@dotnet-bot test this please

**Comment by 333fred** [comment]
Submitted https://github.com/dotnet/sdk/pull/721 to fix the issue. The `feature/msbuild` branch was deleted from the CLI repo, and new clones are broken.

**Comment by 333fred** [comment]
@codito, can you please merge master into your branch to get the build fix I just merged?

**Pull request merged**
