### PR TITLE
Merging internal commits for release/8.0.4xx

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by Forgind — APPROVED** [review]

**Review by v-wuzhai — APPROVED** [review]

**Comment by baronfel** [comment]
@amcasey I think the changes in https://github.com/dotnet/aspnetcore/pull/57108 may have impacted the test failure we're seeing in the SDK now. We use the [dev-certs](https://github.com/dotnet/sdk/blob/00becb507df214a936675822f179b595894e1328/test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs#L56-L57) command to export the dev cert on linux and use that cert to 'secure' a Docker Container registry. We do this in part because that command seemed to generate a cert that was trusted on Linux, so we didn't have to worry about validation errors.

Did this change materially in your PR? Are there reasons why this cert wouldn't be considered valid by standard .NET HttpClient code?

**Comment by amcasey** [comment]
@baronfel Without having dug in, my knee-jerk reaction is that it's probably the change to directory permissions that's affecting you.

Having said that, I'm curious about your comment that "command seemed to generate a cert that was trusted on Linux", since that wasn't true before my change, AFAIK.

**Comment by baronfel** [comment]
Sorry, that's unclear wording on my end. What it comes down to on our end is that we would

* [configure a registry to use this cert](https://github.com/dotnet/sdk/blob/00becb507df214a936675822f179b595894e1328/test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs#L66-L67)
* [use a certificate validation callback that allows access to the localhost registry](https://github.com/dotnet/sdk/blob/a831327451798202104bc2b288220a12fa3a66c1/src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs#L81-L98)

**Comment by amcasey** [comment]
Wait, are you just hijacking validation to ignore cert errors?  If so, my changes should hopefully make that unnecessary (not for free, but better than ignoring trust).  After the change, running `dotnet dev-certs https --trust ...` on the client/receiving machine should make the cert actually trusted (at least by dotnet, openssl (with an extra step), and popular browsers).

Having said that, I would not expect my changes to have affected your ability to suppress that error.

**Comment by amcasey** [comment]
From skimming the code you linked, it appears that you're consuming/validating the cert via HttpClient (or some similar dotnet API), which should pick up trust from either the dotnet cert store or OpenSSL.  To have the dev cert added there, you can either use `dev-certs --trust` or just write it to the `X509Store` yourself.

My hypothesis is still that whatever is serving the cert is failing to access it after a directory permissions change (requested during security review) and the error is a confusing manifestation of "there is no cert".

**Comment by baronfel** [comment]
pushed a commit with the suggestion to `--trust` the dev cert. It worked for me in some local testing. If this doesn't work then we can skip the test and create an issue to re-enable it.

**Comment by amcasey** [comment]
@baronfel There's also a new requirement that the directory to which the cert is exported must already exist (again, security request).  That might be a difference between your local testing and a clean (?) lab machine.

**Comment by baronfel** [comment]
I've skipped the test so that we don't block codeflow, and logged an issue to light it up again soon.

**Comment by baronfel** [comment]
The test skip cleared that issue, now it's just the C++ issues that we've been chasing across the branches.

**Pull request merged**
