### PR TITLE
One option for fixing the locked file issue in the test

### LINKED ISSUE #33956: File used by another process
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=336802
Build error leg or test failing: Microsoft.DotNet.Cli.New.IntegrationTests.TemplateDiscoveryTests.CanRunDiscoveryTool
Pull request: https://github.com/dotnet/sdk/pull/33949

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "error : The process cannot access the file",
  "ErrorPattern": "",
  "BuildRetry": true,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=336802
**Error message validated:** `error : The process cannot access the file`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/12/2023 4:34:24 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[370415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370415)|dotnet/sdk|[Microsoft.DotNet.Cli.New.IntegrationTests.TemplateDiscoveryTests.CanRunDiscoveryTool](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370415&view=ms.vss-test-web.build-test-results-tab&runId=7860172&resultId=100044)|dotnet/sdk#34522|
|[365401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365401)|dotnet/sdk|[Microsoft.DotNet.Cli.New.IntegrationTests.DotnetNewDetailsTest.CanDisplayDetails_LocalPackage](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365401&view=ms.vss-test-web.build-test-results-tab&runId=7729826&resultId=100130)|dotnet/sdk#34476|
|[361227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361227)|dotnet/sdk|[Microsoft.DotNet.Cli.New.IntegrationTests.TemplateDiscoveryTests.CanRunDiscoveryTool](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361227&view=ms.vss-test-web.build-test-results-tab&runId=7626714&resultId=100000)|dotnet/sdk#34412|
|[344492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344492)|dotnet/sdk|[Microsoft.NET.Restore.Tests.dll.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344492&view=ms.vss-test-web.build-test-results-tab&runId=7199884&resultId=103650)|dotnet/sdk#34076|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|4|

### PR DESCRIPTION
**Pull request by marcpopMSFT**
Fixes #33956

### CODE REVIEW

**Review by MiYanni — APPROVED** [review]
Looks good! I saw the issue and suggested that updating the `BaseIntermediateOutputPath` was the best option, IMO.

**Comment by marcpopMSFT** [comment]
@MiYanni I tried that originally and while it did change the obj directory, it didn't change the bin directory. I wasn't sure if we'd end up with locking files there as that path would still overlap for each of the 8 builds of this project. Copying to a separate directory was the only way to force that.

@dsplaisted I didn't see any reusable code for copying the project around. We have CopyTestAssets in our code but that's specific to the structure of the SDK rather than arbitrary assets in other locations. Thoughts? Should we consider moving this test asset into the central SDK story and using that common CopyTestAssets instead?

**Comment by marcpopMSFT** [comment]
Chatted with Daniel offline and I'm going to try using the SDK test model of copytestassets to see if that works. Making the templating tests more like the SDK tests seems positive.

**Comment by marcpopMSFT** [comment]
Pushed an update to use CopyTestAsset like the rest of the SDK tests do. Let's see if this works for the template tests (worked locally).

**Review by MiYanni — APPROVED** [review]
:shipit:

**Pull request merged**
