### PR TITLE
Opt into IncludePackageReferencesDuringMarkupCompilation

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/15395

### CODE REVIEW

**Review by clairernovotny — APPROVED** [review]
I don't know where the right place in the SDK is for this, so I can't speak to that, but otherwise LGTM

**Review by dsplaisted — COMMENTED** [review]
Normally I would put this in a .targets file, though it would need to come before Microsoft.WinFX.targets where it's [defaulted to false](https://github.com/dotnet/wpf/blob/release/5.0/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets#L391).

Is it possible to add a test for the end-to-end scenario here, ie using source generators in a WPF project or one of the other scenarios this unblocks?

**Comment by clairernovotny** [comment]
True, a targets file would make it easier for a user to disable it in their csproj if they wanted to.

It should be possible to test for this.

**Comment by dsplaisted** [comment]
Note that testing this might require updating to a stage 0 version which has the WPF fix.

**Comment by sfoslund** [comment]
> Note that testing this might require updating to a stage 0 version which has the WPF fix.

@dsplaisted it looks like there isn't a 5.0.200 build that can be used for stage 0 that has all the changes. Specifically I'm looking at the latest 5.0.200 build locally (5.0.200-preview.21074.4) and it doesn't contain any of the changes from https://github.com/dotnet/wpf/pull/3846/files

**Comment by sfoslund** [comment]
Test should pass when we get a build to use as stage 0 from this PR: https://github.com/dotnet/sdk/pull/15492

**Comment by dsplaisted** [comment]
I was confused about stage 0, I think we don't actually need a stage 0 round-trip, we just need the WPF update merged.

**Review by dsplaisted — APPROVED** [review]

**Comment by dsplaisted** [comment]
@sfoslund LGTM

**Comment by sfoslund** [comment]
Thanks for merging @wli3!

**Comment by bording** [comment]
> Normally I would put this in a .targets file, though it would need to come before Microsoft.WinFX.targets where it's [defaulted to false](https://github.com/dotnet/wpf/blob/release/5.0/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets#L391).

Just curious, if Microsoft.WinFX.targets is defaulting it to false, why not change make the change there to default to true instead of effectively doing that with the change here?

**Comment by clairernovotny** [comment]
> > Normally I would put this in a .targets file, though it would need to come before Microsoft.WinFX.targets where it's [defaulted to false](https://github.com/dotnet/wpf/blob/release/5.0/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets#L391).
> 
> Just curious, if Microsoft.WinFX.targets is defaulting it to false, why not change make the change there to default to true instead of effectively doing that with the change here?

The reason is that WPF is part of the runtime, ships in 5.0.2/5.0.3 and they can't change the default behavior there. The SDK is expected to change features (in a compatible way) from release to release, so we can flip the default here.

**Pull request merged**
