### PR TITLE
Enhance the 'BenchViewName' for easier searching at BenchView.

### PR DESCRIPTION
**Pull request by ghost**
@DrewScoggins

### CODE REVIEW

**Comment by johnbeisner** [comment]
@dotnet-bot test ci please

**Comment by johnbeisner** [comment]
@dotnet-bot test ci please

**Comment by DrewScoggins** [comment]
LGTM

**Comment by johnbeisner** [comment]
@dotnet-bot help

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x86 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test ci please

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
