### PR TITLE
Fix over-warning bug when specifying runtime CLI option on dotnet run

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/21560

### CODE REVIEW

**Comment by sfoslund** [comment]
@marcpopMSFT We're in M2 mode starting at 4, right? When does M2 mode end?

**Review by dsplaisted — APPROVED** [review]
So the issue wasn't so much that it was warning, but that the `--self-contained` parameter wasn't supported at all by `dotnet run`?

**Comment by sfoslund** [comment]
> So the issue wasn't so much that it was warning, but that the --self-contained parameter wasn't supported at all by dotnet run?

Yep, at least not explicitly.

**Comment by marcpopMSFT** [comment]
M2 mode ends Friday at 4pm

**Review by joeloff — APPROVED** [review]

**Comment by sfoslund** [comment]
Approved by Don

**Pull request merged**
