### PR TITLE
Add a tiered compilation build variable

### PR DESCRIPTION
**Pull request by noahfalk**
All the other runtimeconfig options have a built-in property to set them in
out build targets so adding this one to follow suit.

### CODE REVIEW

**Comment by noahfalk** [comment]
@dsplaisted @livarcocc @natemcmaster - Sorry not sure what your process is for PRs so I'm spamming a bit. This was my best guess of the build side changes that would go with https://github.com/dotnet/coreclr/pull/17807

I ran build.cmd followed by test.cmd as my guess of your dev process. test.cmd had a few failures but none appeared related to the change I was making. I also manually tested copy/pasting my change into a random dotnet CLI's SDK that I already had and confirmed a project built with the new property emits the expected result into the config file (and then confirmed the config file changed the runtime behavior to ensure I didn't make a typo).

My goal is to get both of these changes reviewed against the 2.1 bar to see if they pass muster for RTM.

**Comment by noahfalk** [comment]
Also I think there will be a little ongoing discussion on the names so there may be an update to the PR coming from that angle. Hopefully it shouldn't hard to review sans knowing the final string constants.

**Comment by noahfalk** [comment]
OK I think this name is baked now.

@livarcocc - I see you added this to 2.2.1xx milestone, but just wanted to confirm you saw that we are aiming for 2.1 RTM. I've chatted with @Petermarcu, @richlander and @DamianEdwards - so far everyone seems supportive of the 2.1 plan.

**Comment by noahfalk** [comment]
My understanding was that PRs should be commited into master first and then taken to shiproom.

**Comment by livarcocc** [comment]
In the CLI, we do the opposite 😄 We merge it to the release branch (when it targets that release) and it flows automatically into master. Could you re-base?

**Comment by livarcocc** [comment]
Closing this PR. It will flow into master automatically from 3xx (if it hasn't already).

**Pull request closed without merging**
