### PR TITLE
Build installers on Windows in aspnetcore.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Contributes to https://github.com/dotnet/source-build/issues/4692

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@jkoritzinsky there are some failures in the build

**Comment by jkoritzinsky** [comment]
It looks like this whole folder is missing from the VMR. I'll check the source mapping and see if there's anything going on there.

**Comment by jkoritzinsky** [comment]
So this folder is excluded from the VMR because some of the components have a non-OSS license. See https://github.com/dotnet/source-build/issues/3537

@MichaelSimons do you have any suggestions on how we can re-enable this folder while still keeping our distro partners happy? We need it for the VMR build (it continues to not be necessary for source-build scenarios).

**Comment by wtgodbe** [comment]
> non-oss licensed content is a blocker from a source-build perspective. I don't see a description in the issue/pr trail (e.g. https://github.com/dotnet/aspnetcore/issues/49512) that describes the purpose of [license.rtf file](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf#L55) which prompted this cloaking. @wtgodbe or @jkoritzinsky can you help me understand? If truly needed, can this be brought in via some other mechanism?

I just forwarded you & Jeremy a mail thread from last year about this

**Comment by ViktorHofer** [comment]
Please forward the mail to me as well.

**Comment by MichaelSimons** [comment]
@mthalman - would it be acceptable to add [license.rtf file](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf#L55) as an excluded non-source-build installer license similar to https://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/LicenseScanTests/LicenseExclusions.txt#L141?

**Comment by mthalman** [comment]
> @mthalman - would it be acceptable to add [license.rtf file](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf#L55) as an excluded non-source-build installer license similar to https://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/LicenseScanTests/LicenseExclusions.txt#L141?

Does the license only apply to the installer?

**Comment by MichaelSimons** [comment]
> @mthalman - would it be acceptable to add [license.rtf file](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf#L55) as an excluded non-source-build installer license similar to https://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/LicenseScanTests/LicenseExclusions.txt#L141?

Additionally, would it make sense to strip these types of licenses for distro maintainers similarly to how we strip binaries?  That would help eliminate them having to "deal" with these via whatever their exclusion process is.

**Comment by mthalman** [comment]
> would it be acceptable to add [license.rtf file](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/AspNetCoreModule-Setup/license/license.rtf#L55) as an excluded non-source-build installer license similar to https://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/LicenseScanTests/LicenseExclusions.txt#L141?

Temporarily, I think it makes sense to do this.

> Additionally, would it make sense to strip these types of licenses for distro maintainers similarly to how we strip binaries? That would help eliminate them having to "deal" with these via whatever their exclusion process is.

Maybe? I'm concerned about the optics of that. Stripping binaries are fine because maintainers don't want them. Licenses have a real purpose though. I imagine there might be some suspicion of just yanking out licenses from the source. IMO, what would be better is to strip all the source associated with the license (in the same dynamic way as the stripping of binaries).

**Comment by MichaelSimons** [comment]
> IMO, what would be better is to strip all the source associated with the license (in the same dynamic way as the stripping of binaries).

I agree.

**Comment by MichaelSimons** [comment]
@jkoritzinsky - to unblock, let's remove the cloak.  You will need to add an exclusion to the license scan as I eluded to in https://github.com/dotnet/sdk/pull/44828#issuecomment-2474590242.  I will open a follow-up issue on what the appropriate was is to handle these types of situations from a source build perspective.

**Comment by jkoritzinsky** [comment]
I'll split out the source-mapping change to a separate PR. Looks like that's required.

**Comment by jkoritzinsky** [comment]
Extracted the source-mapping change to https://github.com/dotnet/sdk/pull/44857

**Comment by ViktorHofer** [comment]
Blocked on https://github.com/dotnet/dotnet/pull/110

**Comment by ViktorHofer** [comment]
```
    D:\a\_work\1\vmr\src\aspnetcore\src\Installers\Windows\TargetingPack\TargetingPack.wixproj(72,5): error MSB3932: Failed to unzip file "D:\a\_work\1\vmr\src\aspnetcore\artifacts\installers\Release\aspnetcore-targeting-pack-10.0.0-alpha.2.24563.16-win-x64.zip" because the file does not exist or is inaccessible.
    D:\a\_work\1\vmr\src\aspnetcore\src\Installers\Windows\SharedFramework\SharedFramework.wixproj(76,5): error MSB3932: Failed to unzip file "D:\a\_work\1\vmr\src\aspnetcore\artifacts\installers\Release\aspnetcore-runtime-10.0.0-alpha.2.24563.16-win-x64.zip" because the file does not exist or is inaccessible.
    D:\a\_work\1\vmr\src\aspnetcore\src\Installers\Windows\SharedFramework\SharedFramework.wixproj(78,5): error MSB3932: Failed to unzip file "D:\a\_work\1\vmr\src\aspnetcore\artifacts\installers\Release\aspnetcore-runtime-10.0.0-alpha.2.24563.16-win-x86.zip" because the file does not exist or is inaccessible.
    D:\a\_work\1\vmr\src\aspnetcore\src\Installers\Windows\AspNetCoreModule-Setup\ANCMIISExpressV2\AncmIISExpressV2.wixproj : error MSB4057: The target "Pack" does not exist in the project.
    D:\a\_work\1\vmr\src\aspnetcore\src\Installers\Windows\AspNetCoreModule-Setup\ANCMV2\ANCMV2.wixproj : error MSB4057: The target "Pack" does not exist in the project.
        0 Warning(s)
        5 Error(s)
```

The problem is that the wixprojs build too soon. They need to build after everything else is finished.

**Comment by ViktorHofer** [comment]
One step closer. New errors that I don't see offline:

```
    D:\a\_work\1\vmr\src\aspnetcore\src\Assets\Microsoft.AspNetCore.App.Internal.Assets.csproj(46,5): error : 'D:\a\_work\1\vmr\src\aspnetcore\src\Components\Web.JS\dist\Release\blazor.web.js' does not exist. Run 'npm run build' in the repo root to generate the file.
    D:\a\_work\1\vmr\src\aspnetcore\src\Components\WebView\WebView\src\Microsoft.AspNetCore.Components.WebView.csproj(68,5): error : '..\..\..\Web.JS\dist\Release\blazor.webview.js' does not exist. Falling back to checked-in copy.
    CSC : error CS1566: Error reading resource '_framework/blazor.webview.js' -- 'Could not find a part of the path 'D:\a\_work\1\vmr\src\aspnetcore\src\Components\Web.JS\dist\Release\blazor.webview.js'.' [D:\a\_work\1\vmr\src\aspnetcore\src\Components\WebView\WebView\src\Microsoft.AspNetCore.Components.WebView.csproj]
```

**Pull request merged**
