### PR TITLE
LOC CHECKIN | dotnet/sdk release/3.1.2xx | 20200204

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by tmeschter** [comment]
@nguerrera Who on the SDK side should I annoy about getting this in?

**Comment by nguerrera** [comment]
@wli3 but I think we’ll now miss p3 and take it for GA, which I assume is fine.

**Comment by wli3** [comment]
@dsplaisted you should see this and merge it as domestic cat

**Comment by wli3** [comment]
@nguerrera but I don't think there is harm merge it now. It is M2 approval time. It will be all QB start from next week to the release. I will ask for M2 approval. It may not reach preview 3 but i will be in the next insertion

**Comment by dondr** [comment]
Approved

**Pull request merged**
