### PR TITLE
Insert NuGet Build 4.7.0-preview1-4839 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-preview1-4839 into sdk master branch

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Review by livarcocc — APPROVED** [review]

**Comment by wli3** [comment]
@dotnet-bot test OSX10.12 Debug

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Releas

**Comment by wli3** [comment]
Windows_NT_FullFramework Release

**Comment by wli3** [comment]
@dotnet-bot test Windows_NT_FullFramework Release

**Comment by wli3** [comment]
Failing on Windows due to SkipNonexistentTargets, looks like Pack failed to detect full MsBuild.

D:\j\workspace\debug_windows---14cea53e\artifacts\Debug\bin\Sdks\NuGet.Build.Tasks.Pack\build\**NuGet.Build.Tasks.Pack.targets(276,7): error MSB4064: The "SkipNonexistentTargets" parameter is not supported by the "Msbuild" task. Verify the parameter exists on the task, and it is a settable public instance property. [**D:\j\workspace\debug_windows---14cea53e\artifacts\Debug\tmp\Nuget_referen---3B967D0F\D_netstandard1_0\D_netstandard1_0.csproj]
D:\j\workspace\debug_windows--

**Comment by wli3** [comment]
On core msbuild, it passes all tests but failed on pack SDK itself.

**Comment by wli3** [comment]
@rohit21agrawal could you have a look at it?

**Comment by wli3** [comment]
core msbuild hit IsPackable = false. It is a new added error. Need to dig what cause that

**Comment by rohit21agrawal** [comment]
we added a new error that is thrown when you try to pack a project which has IsPackable = false set on it.

**Comment by wli3** [comment]
@rohit21agrawal i think what we did is run /t:pack on the whole SLN. And we set all test project to be IsPackable=false to exclude. What is the recommend practice?

**Comment by wli3** [comment]
- [ ] update MSBUILD https://github.com/dotnet/sdk/pull/1873

**Comment by rohit21agrawal** [comment]
you can have a top level target like "PackProject" which is imported by all projects but only executes if IsPackabe = true. in this target you can invoke pack on the project

**Comment by wli3** [comment]
test ci please

**Comment by wli3** [comment]
@dotnet-bot test ci please

**Comment by wli3** [comment]
@dotnet-bot Test this please

**Comment by wli3** [comment]
there is another spin, but i want to keep running test on full msbuild

**Pull request closed without merging**
