### PR TITLE
Fix condition for utf7

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]

**Review by danmoseley — APPROVED** [review]
I already have a suggestion open against MSBuild to flag such typos, as they do happen from time to time.

**Comment by danmoseley** [comment]
@dotnet/domestic-cat  the below just happened. https://github.com/dotnet/core-eng/issues/14015 suggests it's due to build authoring -- two pipelines uploading the same named artifact at the same time.

```
2021-08-11T22:57:06.4524916Z Attempt '1' for uploading chunk '20' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'.
2021-08-11T22:57:06.4525531Z Generate new HttpRequest for uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip', chunk '20' of '21'.
2021-08-11T22:57:06.4526168Z Start uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip' to server, chunk '20'.
2021-08-11T22:57:06.4526978Z Finished upload chunk '20' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip', elapsed 511 (ms), response code 'Accepted'.
2021-08-11T22:57:06.4527796Z Attempt '1' for uploading chunk '21' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'.
2021-08-11T22:57:06.4528585Z Generate new HttpRequest for uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip', chunk '21' of '21'.
2021-08-11T22:57:06.4529202Z Start uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip' to server, chunk '21'.
2021-08-11T22:57:06.4532145Z Chunk '21' attempt '1' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: af03054df7faeb11b563501ac5b0ff56, Expected Offset: 0, Actual Offset: 83886080
 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: af03054df7faeb11b563501ac5b0ff56, Expected Offset: 0, Actual Offset: 83886080
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2021-08-11T22:57:06.4535515Z Backoff 6.48 seconds before attempt '2' chunk '21' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'.
2021-08-11T22:57:06.4536162Z Attempt '2' for uploading chunk '21' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'.
2021-08-11T22:57:06.4536822Z Generate new HttpRequest for uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip', chunk '21' of '21'.
2021-08-11T22:57:06.4537527Z Start uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip' to server, chunk '21'.
2021-08-11T22:57:06.4539684Z Chunk '21' attempt '2' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Bad Request
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2021-08-11T22:57:06.4542219Z Backoff 5.466 seconds before attempt '3' chunk '21' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'.
2021-08-11T22:57:06.4542842Z Attempt '3' for uploading chunk '21' of file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'.
2021-08-11T22:57:06.4543477Z Generate new HttpRequest for uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip', chunk '21' of '21'.
2021-08-11T22:57:06.4544114Z Start uploading file 'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip' to server, chunk '21'.
2021-08-11T22:57:06.4544643Z ##[section]Async Command End: Upload Artifact
```

**Comment by eerhardt** [comment]
> suggests it's due to build authoring -- two pipelines uploading the same named artifact at the same time. Is that possible here? Which pipeline owns "'BlobArtifacts/dotnet-toolset-internal-6.0.100-ci.zip'"

Same thing happened here:

https://github.com/dotnet/sdk/pull/19582#issuecomment-894677646

See also https://github.com/dotnet/core-eng/issues/14015

**Comment by danmoseley** [comment]
@dotnet/domestic-cat if this is'nt known to you I can open an issue.

**Comment by joeloff** [comment]
@danmoseley Can't say I've seen this before. I'd imagine the toolset zip is being produced by the SDK. I'll poke around a bit.

**Comment by danmoseley** [comment]
opened https://github.com/dotnet/sdk/issues/19679 for it

**Pull request merged**
