### PR TITLE
Fix exception when running "dotnet tool search"

### LINKED ISSUE #12790: dotnet tool search errors
do not provide any search term will result in bad error message.

```
PS C:\Users\kdollard\source\repos\command-line-api\command-line-api> dotnet tool search 
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.NugetSearch.NugetSearchApiParameter..ctor(AppliedOption appliedOption)
   at Microsoft.DotNet.Tools.Tool.Search.ToolSearchCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #12790

cc: @wli3

### CODE REVIEW

**Comment by Youssef1313** [comment]
An alternative fix would be to update the following line to `Accept.ExactlyOneArgument()`:

https://github.com/dotnet/sdk/blob/31aeff16973ab1cd60c9efe57567d0769ac4d7af/src/Cli/dotnet/commands/dotnet-tool/search/ToolSearchCommandParser.cs#L17

I'll wait for review.

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
@Youssef1313 I will squash merge the change. Or could you squash the commits?

**Comment by wli3** [comment]
Thanks for the contribution!

**Comment by Youssef1313** [comment]
I squashed the commits. Please note that I couldn't test the changes locally due some problems with the .NET version used in the repository.

**Comment by wli3** [comment]
@Youssef1313 run 
`build.cmd` first 
and the run `.\eng\dogfood.cmd` you can test the one you just built.

But from the test, it looks good

**Comment by Youssef1313** [comment]
@wli3 build.cmd stucks with me at:

> dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20376.1/dotnet-sdk-5.0.100-rc.1.20376.1-win-x64.zip

Probably due bad internet connection.

**Comment by wli3** [comment]
@Youssef1313 new test did not pass.
DotnetToolSearchShouldThrowWhenNoSearchTerm

Microsoft.DotNet.Cli.CommandLine.CommandParsingException : Required argument missing for command: search


Stack trace
   at Microsoft.DotNet.Cli.ParseResultExtensions.ShowHelpOrErrorIfAppropriate(ParseResult parseResult) in /_/src/Cli/dotnet/ParseResultExtensions.cs:line 21
   at Microsoft.DotNet.Cli.CommandBase.ShowHelpOrErrorIfAppropriate(ParseResult parseResult) in /_/src/Cli/dotnet/CommandBase.cs:line 21
   at Microsoft.DotNet.Cli.CommandBase..ctor(ParseResult parseResult) in /_/src/Cli/dotnet/CommandBase.cs:line 16
   at Microsoft.DotNet.Tools.Tool.Search.ToolSearchCommand..ctor(AppliedOption options, ParseResult result, INugetToolSearchApiRequest nugetToolSearchApiRequest) in /_/src/Cli/dotnet/commands/dotnet-tool/search/ToolSearchCommand.cs:line 24
   at Microsoft.DotNet.Tests.ParserTests.ToolSearchParserTests.DotnetToolSearchShouldThrowWhenNoSearchTerm() in /_/src/Tests/dotnet.Tests/ParserTests/ToolSearchParserTests.cs:line 31

**Review by wli3 — APPROVED** [review]

**Comment by Youssef1313** [comment]
@wli3, Looks like the build timed out

**Comment by marcpopMSFT** [comment]
Looks like all checks passed now.  Are we clear to merge this @wli3?

**Pull request merged**
