### PR TITLE
Re-enable scenario-tests  execution in VMR

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Review by premun — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Apparently, https://github.com/dotnet/scenario-tests/commit/5f25b3adf47d2866b5014940fa526e4cda08dc1f doesn't work.

**Comment by ViktorHofer** [comment]
Oh I know what's going on. We don't have a `dotnet` in the SDK layout anymore (omg):

image

Probably related to the join point work.

**Comment by mthalman** [comment]
> We don't have a `dotnet` in the SDK layout anymore

Seems like an important file. 😄

**Comment by ViktorHofer** [comment]
OK, I believe this has to do with SignTool dropping files when repacking the .tar.gz container: https://github.com/dotnet/arcade/issues/15232

**Pull request merged**
