### PR TITLE
Update branding to preview 6

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Review by sfoslund — APPROVED** [review]

**Comment by wli3** [comment]
@mmitche I cannot rerun the failed leg. This happened several times. Do you know who can help us on that? Looking like something wrong between github and azuredevops communication

**Comment by mmitche** [comment]
> @mmitche I cannot rerun the failed leg. This happened several times. Do you know who can help us on that? Looking like something wrong between github and azuredevops communication

@ilyas1974 @dotnet/dnceng

**Comment by MattGal** [comment]
> > @mmitche I cannot rerun the failed leg. This happened several times. Do you know who can help us on that? Looking like something wrong between github and azuredevops communication
> 
> @ilyas1974 @dotnet/dnceng

I'll poke around and get an IcM filed if it's still reproing.

**Comment by MattGal** [comment]
Doesn't seem to be happening right now (e.g. I could rerun on https://github.com/dotnet/sdk/pull/11727) but I'll still ask.

**Comment by MattGal** [comment]
I reported this specific one, but any time you see this happening while the ADO and GH status pages are green, I recommend posting a link to the relevant PR as an issue on https://developercommunity.visualstudio.com/content/problem/post.html?space=21 to get investigated.

**Comment by MattGal** [comment]
> @mmitche I cannot rerun the failed leg. This happened several times. Do you know who can help us on that? Looking like something wrong between github and azuredevops communication

For investigation purposes can you clarify which leg didn't rerun?

**Comment by wli3** [comment]
cannot find it anymore. The run history just shows everything passes https://dev.azure.com/dnceng/public/_build/results?buildId=654657&view=results

**Pull request merged**
