### PR TITLE
Update Versions.props for 7.0 branding

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
depend on https://github.com/dotnet/sdk/pull/19901

**Comment by marcpopMSFT** [comment]
retriggering the merge

**Comment by mmitche** [comment]
We probably need an update from dotnet/installer into this repo before this will pass, and dotnet/installer actually needs an update from dotnet/sdk in order to build against the 7.0 templates. I think I worked around this in installer. We'll see.

**Comment by marcpopMSFT** [comment]
Given the list of failures, we actually don't need an updated installer per se. The dotnet watch tests are fixed by the global.json update that Pranav already did.  The 3 workload failures require the fallback logic to be enabled which was turned on in rc2: https://github.com/dotnet/installer/pull/11571. So we either need to disable those, port that change and update global.json, or workaround it in the tests.  The remaining tests I've pinged Daniel on as it's searching the 6.0.100 manifests when trying to resolve packs for some reason (ie if I push the test manifest into a 6.0.100 directory, the tests pass).

**Pull request closed without merging**
