### PR TITLE
Containers: implementation of OAuth2

### LINKED ISSUE #425: Azure Container Registry auth failure when using Managed Identity
A user reported failures when attempting to use our tools when logged in to ACR via a managed identity via an Azure Devops-Managed Service Connection.  We should verify/fix that Managed Identity authentication works.

I did a bit of digging into why/how managed identities work to try and triage this. After digging into the user's report, we aren't failing _fetching_ the credentials, but we are failing during actual auth. I'm not able to get insight into the value of the token/auth that's retrieved. 

Useful links:
* the [Docker](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DockerV2/docker.ts)AzDo task
* the [common docker](https://github.com/microsoft/azure-pipelines-tasks-common-packages/tree/main/common-npm-packages/docker-common) code that the Docker task uses for handling auth - there is managed-identity-specific code here
* the [ACR-specific token code](https://github.com/microsoft/azure-pipelines-tasks-common-packages/blob/main/common-npm-packages/docker-common/registryauthenticationprovider/acrauthenticationtokenprovider.ts)

We should investigate this logic and try to set up a test suite for Managed Identity support.

### PR DESCRIPTION
**Pull request by vlada-shubina**
fixes https://github.com/dotnet/sdk-container-builds/issues/425

Implements docker auth using OAuth2: https://docs.docker.com/registry/spec/auth/oauth/

### CODE REVIEW

**Comment by baronfel** [comment]
Tests with the sdk-container-demo repo were inconclusive since I had to cherry-pick this to the SDK's release/8.0.100-preview6 branch to get a package that would work on public releases of the SDK. We can try again with this actual branch next week when preview7 releases if this hasn't been merged by then.

**Comment by baronfel** [comment]
Linked PR to sdk-container-demo showing Managed Identity pushes working: https://github.com/baronfel/sdk-container-demo/actions/runs/5858315048/job/15882011960

**Comment by baronfel** [comment]
retargeted to RC1 in hopes that we can get it merged for that release.

**Review by MichalPavlik — APPROVED** [review]

**Pull request merged**
