### PR TITLE
Insert NuGet Build 4.7.0-preview1.4982 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-preview1.4982 into sdk release/2.1.2xx branch

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by rohit21agrawal** [comment]
@livarcocc can we merge this too?

**Comment by rohit21agrawal** [comment]
fixed the merge conflict

**Comment by rohit21agrawal** [comment]
@nguerrera not sure why non-windows Pack tests are failing. are the sources different for xplat?

**Comment by rohit21agrawal** [comment]
@dsplaisted @nguerrera @livarcocc appreciate any help here to move this PR forward

**Comment by livarcocc** [comment]
This likely needs the CLI with this version of NuGet inserted here. I will update it.

**Comment by rohit21agrawal** [comment]
everything is green! happy St Patrick's day ;)

**Pull request merged**
