### PR TITLE
Don't generate deps or runtimeconfig files when build has failed but _CleanRecordFileWrites is being run

### LINKED ISSUE #1234: GenerateRuntimeConfigurationFiles fails with a crash if it doesn't find the runtimeconfig.json
1. File -> New Console App
2. Right-click project, and choose Edit ConsoleApp1.csproj
3. Change target framework to net48
4. Build:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateRuntimeConfigurationFiles" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\davkean\Source\Repos\ConsoleApp4\ConsoleApp4\bin\Debug\net48\ConsoleApp4.runtimeconfig.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(ProjectContext projectContext)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ConsoleApp4	C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	129	
```

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #1234

The `GenerateBuildRuntimeConfigurationFiles` runs before `_CheckForCompileOutputs`, so that the `FileWrites` items it adds will be picked up by `_CleanGetCurrentAndPriorFileWrites`, and incremental builds and cleans will work correctly.  (See some discussion of this on #381)

However, the `CoreBuild` target invokes the `_CleanRecordFileWrites` target [when it errors](https://github.com/Microsoft/msbuild/blob/a8a025b9751461feaedc0a78cd28c226f5872bdf/src/Tasks/Microsoft.Common.CurrentVersion.targets#L838):

```xml
  <Target
      Name="CoreBuild"
      DependsOnTargets="$(CoreBuildDependsOn)">

    <OnError ExecuteTargets="_TimeStampAfterCompile;PostBuildEvent" Condition="'$(RunPostBuildEvent)'=='Always' or '$(RunPostBuildEvent)'=='OnOutputUpdated'"/>
    <OnError ExecuteTargets="_CleanRecordFileWrites"/>

  </Target>
```

This means that even if there is a previous build error, we are trying to generate the runtime config files.  In the case of #1234, the output path where we would write them hasn't been created, so the task throws an exception.

This PR adds a condition to only run the task if the folder it's going to write to exists.  This feels like a band-aid solution though.  Is there a better way to structure this which would add the correct `FileWrites` items when needed, but not even run the target if `GetReferenceAssemblyPaths` or some other target before-hand has failed?

@rainersigwald @AndyGerlicher @nguerrera

### CODE REVIEW

**Comment by nguerrera** [comment]
Definitely a band aid. I think we should run earlier by a different mechanism. From an email thread about a related problem, beforetargets=copyfilestooutputdirectory instead of after build should do the trick.

**Review by nguerrera — CHANGES_REQUESTED** [review]
We need to find a proper fix

**Review by nguerrera — APPROVED** [review]
Looks good now. Please update the description to match the new change.

**Comment by dsplaisted** [comment]
@dotnet-bot

test Ubuntu16.04 Release
test Windows_NT Release
test Windows_NT_FullFramework Release

**Comment by dsplaisted** [comment]
@MattGertz for approval

**Customer scenario**

Build targeting a version of .NET Framework where the reference assemblies aren't installed.  This fixes an issue where an extra (and far more verbose error) would be reported, making it less obvious what the problem was.

**Bugs this fixes:** 

#1234

**Workarounds, if any**

Read the error spew carefully

**Risk**

Low

**Performance impact**

Low to none - This just changes where in the build we do some work.

**Is this a regression from a previous update?**

No

**Root cause analysis:**

Some of our targets were running even when the build failed, which caused them to fail (since the output path didn't exist).

**How was the bug found?**

Dogfooding

**Comment by dsplaisted** [comment]
@dotnet-bot test Ubuntu16.04 Release

**Comment by MattGertz** [comment]
(Just for bar context -- note that I would probably have punted on this after next week.)

**Pull request merged**
