### PR TITLE
Moving CLI/ toolset scripts to root folder

### PR DESCRIPTION
**Pull request by sfoslund**
Corrects path to stage 0 in local build scripts

### CODE REVIEW

**Review by dsplaisted — COMMENTED** [review]
How many of these scripts still work or are still necessary?  I think some of them should probably be deleted instead of being moved.

The `cli-build-env` and `cli-test-env` scripts should definitely be candidates for deletion.

**Comment by wli3** [comment]
> The cli-build-env and cli-test-env scripts should definitely be candidates for deletion.

CLI's tests can never run in test explorer without these scripts. The repo merge fixed it?

**Comment by sfoslund** [comment]
> The cli-build-env and cli-test-env scripts should definitely be candidates for deletion.

I'm not able to run a lot of the tests (not just CLI tests) locally without running `cli-build-env`, I think those ones definitely need to stay.

> How many of these scripts still work or are still necessary?

I don't have a good understanding of what the use cases are for a lot of the others, so I'm not sure which are necessary.

**Comment by dsplaisted** [comment]
> > The cli-build-env and cli-test-env scripts should definitely be candidates for deletion.
> 
> CLI's tests can never run in test explorer without these scripts. The repo merge fixed it?

There are already scripts which are more or less equivalent for the merged repo.  When you do a build it generates an `artifacts\sdk-build-env.bat` file.  And there's an `eng\dogfood.cmd` script to get to the test environment.

I'm less certain that the equivalent non-Windows scripts work, but the cli ones in the old scripts directory certainly won't work.

**Comment by wli3** [comment]
extra issue for docker files https://github.com/dotnet/sdk/issues/10945

**Comment by wli3** [comment]
I don't have an `artifacts\sdk-build-env.bat` when repo cannot build -- and I need IDE to help me resolve the build failure in cs file. 

@sfoslund you mentioned the scripts are working right? If so let's keep `cli-build-env.*` at least. And also `scripts/register-*`. At the point, I don't think we have time to shave this yak again.

dogfood.cmd and cli-test-env need to merge -- we need to use stage2 for CLI to be able to dogfood. In this case, non of them works, let's only keep one

And delete everything else.

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/issues/10946

**Comment by dsplaisted** [comment]
@wli3 `artifacts\sdk-build-env.bat` is created early on in the build process.  I think it is created in the scripts that eventually call msbuild.  So you just run `build` from the repo root to create it.

**Comment by wli3** [comment]
i see, i am using a mac, so no script is generated. So, we can also delete `sdk-build-env.bat` then. Content is the same other than dotnet_root is not set https://github.com/dotnet/sdk/issues/10949

**Comment by sfoslund** [comment]
@dsplaisted awesome, I didn't know about `sdk-build-env.*`. I'll remove `cli-build-env.*` then. 

@wli3 so to be clear, you're saying we don't need to keep any of the scripts besides `scripts/register-*`?

**Comment by wli3** [comment]
Correct. Remove everything but script/reigster*

**Comment by sfoslund** [comment]
We're getting an `Entry point was not found` error when running nuget targets for a few tests, was one of these scripts necessary for that?

**Review by wli3 — APPROVED** [review]

**Pull request merged**
