### PR TITLE
fix locale-sensitive comparison of UnmatchedArgument error strings

### PR DESCRIPTION
**Pull request by baronfel**
Forward-port of https://github.com/dotnet/sdk/pull/29559 to the 7.0.2xx release branch so that we don't miss the merge window.

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]
Looks good, same feedback as on the other version of this PR.

**Comment by baronfel** [comment]
Applied your suggested change on that other PR and cherry-picked it here as well 👍

**Comment by baronfel** [comment]
Template engine leg is failing due to the moduleinitializer issue. @dotnet/templating-engine-maintainers how should I resolve this? did the moduleinitializer fixes get into 7.0.2xx?

**Comment by JanKrivanek** [comment]
@baronfel Yes, fixed for 7.0.2xx (https://github.com/dotnet/sdk/pull/29803)

**Pull request merged**
