### PR TITLE
Update macos leg to 1015

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@TanayParikh @mkArtakMSFT There is a failure in the new AOT test leg that appears to be related to an unnecessary extra publish to azure blob: https://dev.azure.com/dnceng/public/_build/results?buildId=1503465&view=logs&j=92885c4a-db2e-5086-f9ba-51524576e2ac&t=21c5c3c8-000e-5461-4a70-e7939905edf6
Fail to upload 'D:\a\_work\1\s\artifacts\packages\Release\NonShipping\dotnet-toolset-internal-7.0.100-ci.zip' due to 'Bad Request'.
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Bad Request
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.UploadAsync(IAsyncCommandContext context, Int32 uploaderId, CancellationToken token)
Detail upload trace for file that fail to upload: BlobArtifacts/dotnet-toolset-internal-7.0.100-ci.zip

Please talk to @mmitche as I recall him fixing something like this in the future.

**Comment by mmitche** [comment]
Don't pass the publish args in that case (or really any PR case)

**Comment by TanayParikh** [comment]
> Don't pass the publish args in that case (or really any PR case)

Thanks @mmitche! I've created https://github.com/dotnet/sdk/pull/22967. There doesn't appear to be a Darwin equivalent arg we may want to remove:

https://github.com/dotnet/sdk/blob/6cdac2c22a49d7d09909dece2f6b97b81a2f77aa/eng/build.yml#L258-L266

**Comment by TanayParikh** [comment]
The un-necessary uploads should be stopped via https://github.com/dotnet/sdk/pull/22967. Thanks for calling it out!

Looks like this PR is good to merge now as well 😄 .

**Pull request merged**
