### PR TITLE
[`dotnet-new`] Add inRoot option for AddProjectsToSolutionPostAction

### PR DESCRIPTION
**Pull request by levimatheri**
For [dotnet-new issue #4178](https://github.com/dotnet/templating/issues/4178).
Adds `inRoot` argument which is passed to `dotnet sln add` as `--in-root`. 

cc @vlada-shubina

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=27986) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=27986) before we can accept your contribution.<br/><br/>:x: levimatheri [sign now](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=27986)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/sdk?pullRequest=27986) it.</sub>

**Review by vlada-shubina — CHANGES_REQUESTED** [review]
Could you please add the tests for the change:
- end-to-end tests are here: https://github.com/dotnet/sdk/blob/b573979a30d5279e14aaf52a22548b46a430f693/src/Tests/dotnet-new.Tests/PostActionTests.cs#L598-L629
- unit tests are here: https://github.com/dotnet/sdk/blob/main/src/Tests/dotnet.Tests/dotnet-new/DotnetSlnPostActionTests.cs

**Comment by vlada-shubina** [comment]
This change requires:
- documentation update:  https://github.com/dotnet/templating/wiki/Post-Action-Registry
- JSON schema update: https://github.com/dotnet/templating/blob/main/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Schemas/JSON/template.json
- port to 7.0.2xx when branch is available

**Comment by levimatheri** [comment]
@vlada-shubina I'm not sure about the unit test, I don't see one for `--solution-folder`? Sorry, a bit new to this. Do we just need to test if `DotnetSlnPostActionProcessor.TryGetProjectFilesToAdd` returns `true`?

**Comment by levimatheri** [comment]
@vlada-shubina Also, was going to add another `LocalizableString` for the `--in-root` option output. How are these translated? https://github.com/dotnet/sdk/blob/3eea35e0d77f9a1bc418a364805ff89df818e371/src/Cli/dotnet/commands/dotnet-new/LocalizableStrings.resx#L161-L166

**Comment by vlada-shubina** [comment]
> @vlada-shubina I'm not sure about the unit test, I don't see one for `--solution-folder`? Sorry, a bit new to this. Do we just need to test if `DotnetSlnPostActionProcessor.TryGetProjectFilesToAdd` returns `true` if `--in-root` is passed in?

Testing `TryGetProjectFilesToAdd` doesn't make a lot of sense.

I would do a test similar to https://github.com/dotnet/sdk/blob/39f66f56bd9d66ccfdb904482d283b5506fc5a68/src/Tests/dotnet.Tests/dotnet-new/DotnetSlnPostActionTests.cs#L197-L223 and check if `--inRoot` from args was passed properly to the mock callback.

**Comment by vlada-shubina** [comment]
> @vlada-shubina Also, was going to add another `LocalizableString` for the `--in-root` option output. How are these translated?
> 
> https://github.com/dotnet/sdk/blob/3eea35e0d77f9a1bc418a364805ff89df818e371/src/Cli/dotnet/commands/dotnet-new/LocalizableStrings.resx#L161-L166

Just change an English string in `LocalizableStrings.resx` as needed and build. The translation will come automatically after some time. If you are using placeholder or some text should not be translated, consider explaining them in `Comments` column.

**Comment by levimatheri** [comment]
@vlada-shubina PR got messed up, will submit another one.

**Pull request closed without merging**
