### PR TITLE
[LoongArch64] Add linux-loongarch64 RID for `Net90AppHostRids` and `Net90RuntimePackRids`.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
Add linux-loongarch64 RID for `Net90AppHostRids` and `Net90RuntimePackRids`.

### CODE REVIEW

**Comment by LuckyXu-HF** [comment]
Hi @shushanhf @am11 @akoeplinger  ,could you please review this PR ? Thanks.

**Comment by am11** [comment]
@LuckyXu-HF, these are already inherited from: https://github.com/dotnet/sdk/blob/570e2f951210400c8d46d758acf8916bbbd286da/src/Installer/redist-installer/targets/GenerateBundledVersions.targets#L172-L184 (6->7->8->9)

**Comment by LuckyXu-HF** [comment]
> @LuckyXu-HF, these are already inherited from:
> 
> https://github.com/dotnet/sdk/blob/570e2f951210400c8d46d758acf8916bbbd286da/src/Installer/redist-installer/targets/GenerateBundledVersions.targets#L172-L184
> 
> (6->7->8->9)

Hi @am11 , thank you very much! I will close this PR.
BTW, do you have a plan for commit the https://github.com/dotnet/runtime/pull/102628 further ? 
I believe some architectures that currently do not support NativeAOT will benefit from it. The LA64-NativeAOT feature is currently under development, and I think @shushanhf will commit it soon.

Now the build of `clr` within the main branch for LA64 will hit the relate error, it's because the NativeAot is not properly isolating well. And your PR#102628 will help to solve this issue a lot.
```shell
xuliangyu@loongson-pc:/data_loongson/xuliangyu/runtime$ ./build.sh clr -rc release  
  正在确定要还原的项目…
  工具“coverlet.console”(版本“6.0.0”)已还原。可用的命令: coverlet
  工具“dotnet-reportgenerator-globaltool”(版本“5.3.0”)已还原。可用的命令: reportgenerator
  工具“microsoft.dotnet.xharness.cli”(版本“9.0.0-prerelease.24270.4”)已还原。可用的命令: xharness
  工具“microsoft.visualstudio.slngen.tool”(版本“11.1.0”)已还原。可用的命令: slngen
  
  还原成功。
  所有项目均是最新的，无法还原。
  正在确定要还原的项目…
/data_loongson/xuliangyu/runtime/.dotnet/sdk/9.0.100-preview.3.24204.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1204: 当前平台“linux-loongarch64”不支持提前编译。 [/data_loongson/xuliangyu/runtime/Build.proj]
  无可执行操作。指定的项目均不包含可还原的包。

生成失败。

/data_loongson/xuliangyu/runtime/.dotnet/sdk/9.0.100-preview.3.24204.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1204: 当前平台“linux-loongarch64”不支持提前编译。 [/data_loongson/xuliangyu/runtime/Build.proj]
    0 个警告
    1 个错误

已用时间 00:00:14.20
Build failed with exit code 1. Check errors above.
```

**Comment by am11** [comment]
I was moving my apartment, and having some time off GitHub. 😅

**Comment by LuckyXu-HF** [comment]
> I was moving my apartment, and having some time off GitHub. 😅

Wishing you a pleasant move and have a nice day. 😅

**Pull request closed without merging**
