### PR TITLE
Add zsh compdef completion script.

### PR DESCRIPTION
**Pull request by Esgariot**
Taking another look at stuff mentioned in https://github.com/dotnet/cli/pull/13384/ 
I have no knowledge of zsh and completion scripts, just followed the suggestions from aforementioned PR.
Because of that there's few things left to do that come to mind:
- integrate this script with others so that it conforms to both [zsh sourcing/autoloading of completion files](zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files) (gets included into `fpath` somehow) and what is expected of script files here, in `scripts` folder
- add descriptions (when applicable) to `dotnet complete` output using zsh completion system's mechanisms of which I know exactly nothing.

### CODE REVIEW

**Comment by omajid** [comment]
IMO, this should replace the existing `scripts/register-completions.zsh` file (having both is redundant). I wonder if anything else in the installer needs to be updated to make sure this file is installed when appropriate?

**Comment by wli3** [comment]
@omajid we don't include this script "in the box". So far we only point user to the instruction in Github to manually add it. Btw, have you tried this script? Or could you help review this script? I don't know too much about zsh, so it takes a while for me to look into it.

**Comment by wli3** [comment]
@sfoslund how much auto completion of system commandline is "online" in SDK?

**Comment by sfoslund** [comment]
> how much auto completion of system commandline is "online" in SDK?

It should be enabled for all commands, I recently fixed a ["dotnet add package" specific issue](https://github.com/dotnet/sdk/pull/15019) but otherwise it has been supported since the original PR.

**Comment by wli3** [comment]
with some configure, the library should support `dotnet-suggest` for completion. But it is unlikely to work on SDK. Since there are so much customization in SDK

**Comment by sfoslund** [comment]
The CLI supports the `dotnet complete` command and `dotnet [suggest]` directive for getting suggestions, if that's what you're looking for.

**Comment by omajid** [comment]
> Btw, have you tried this script? Or could you help review this script?

No, sorry, I dont use zsh so I haven't reviewed or test it :(

**Comment by omajid** [comment]
> we don't include this script "in the box". So far we only point user to the instruction in Github to manually add it. 

Interesting. Is that true for bash completion too?

For the Fedora .NET Core 3.1 package, we can install/use it in from the source repo: https://src.fedoraproject.org/rpms/dotnet3.1/blob/7d66170eeba7d2f13cd15d1c05d1c259ba48c324/f/dotnet3.1.spec#_481

**Comment by wli3** [comment]
@omajid it is the same for bash. It is something to be put in user's bashrc. We need an explicit agreement from the user. We need to design a UX for that, which is not trivial

**Comment by omajid** [comment]
> @omajid it is the same for bash. It is something to be put in user's bashrc. We need an explicit agreement from the user.

If you are installing the SDK system wide, why not put the bash completion system-wide too? And if the user agrees with installing the software in the system, why wouldn't they agree with the auto-completion? If there are privacy implications, then I guess that would explain why the need for explicit agreement and UX design.

**Comment by wli3** [comment]
My understanding is bashrc belongs to the user. No program should directly editing it. Also, simply append more lines to it will not always work.

**Comment by omajid** [comment]
> My understanding is bashrc belongs to the user. No program should directly edit it. Also, simply append more lines to it will not always work.

That's right. You shouldn't edit the user's bashrc.

But you can add system-wide completion by dropping completion files into the system-wide completion directory. That's what it's meant for. That's where programs like `git` install their completion file.

```
$ pkg-config --variable=completionsdir bash-completion
/usr/share/bash-completion/completions
$ ls -l $(pkg-config --variable=completionsdir bash-completion)/git
-rw-r--r--. 1 root root 78880 Oct 29 18:11 /usr/share/bash-completion/completions/git
0  [omajid@terminus ~]$ head $(pkg-config --variable=completionsdir bash-completion)/git
# bash/zsh completion support for core Git.
#
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Conceptually based on gitcompletion (http://gitweb.hawaga.org.uk/).
# Distributed under the GNU General Public License, version 2.0.
#
# The contained completion routines provide support for completing:
#
#    *) local and remote branch names
#    *) local and remote tag names


```

**Comment by wli3** [comment]
That's a good news. Is `/usr/share/bash-completion/` available on all shells and all distros?

**Comment by omajid** [comment]
> Is /usr/share/bash-completion/ available on all shells and all distros?

Probably not. The bash completion FAQ I linked above says that `pkg-config --variable=completionsdir bash-completion` should compute the desired path.

I think this location is for bash only.

I dont know enough about zsh to figure out where that lies. Google says the environment variables `$FPATH` or `$fpath` should list all the paths where zsh looks for completion files and the system-wide location should be one of those paths.

**Comment by Esgariot** [comment]
FYI I'm still looking at this issue from time to time and I'm  __still__ a noob when it comes to zsh stuff. If there's anybody you know that's more knowledgeable in these things and would like to take a look that would be great, I don't believe it should be a big problem because package maintainers include their completions for all kinds of stuff

**Comment by Esgariot** [comment]
ultimately I think that the zsh completion scripts should land in
`$datadir/$datarootdir/zsh/site-functions/_dotnet`

https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

(thanks Megame50)

**Comment by omajid** [comment]
> I don't believe it should be a big problem because package maintainers include their completions for all kinds of stuff

I am a package maintainer in Fedora and I would love to include zsh shell completions for dotnet too! Currently we only include dotnet completions for bash.

**Comment by baronfel** [comment]
Based on some new work on System.CommandLine's completions for `dotnet suggest`, I suggest we look into a completion function similar to this:

```sh
#compdef dotnet

# debug lines, uncomment to get state variables passed to this function
# echo "\n\n\nstate:\t'$state'"
# echo "line:\t'$line'"
# echo "words:\t$words"

# Get the full line
# $words array when quoted like this gets expanded out into the full line
full_line="$words"

# Get the completion results, will be newline-delimited
completions=$(dotnet complete "$full_line")
# explode the completions by linefeed instead of by spaces into the descriptions for the
# _values helper function.
exploded=(${(f)completions})
_values 'suggestions' $exploded
```

When we add description support to `dotnet complete` the descriptions can be added using 

```sh
described=()
for i in {1..$#exploded}; do
    argument="${exploded[$i]}"
    description="hello description $i"
    entry=($argument"["$description"]")
    described+=("$entry")
done
```
and the `described` array can be used with `_values` instead of `exploded`.

**Comment by ayakael** [comment]
For what it's worth, at Alpine Linux we''ve been applying the following patch for zsh completion support:
```diff
From 4c74721e1f5da9642adab03075dda2f55719ac7b Mon Sep 17 00:00:00 2001
Patch-Source: https://github.com/dotnet/sdk/pull/14239
From: Esgariot <esgariot@icloud.com>
Date: Mon, 19 Oct 2020 23:42:37 +0200
Subject: [PATCH 1/1] Add zsh compdef completion script.

Continuing off of PR 13384 in upstream.
This commit is ready to be rebased to include appropriate co-authors
before merging PR.

---
 scripts/register-completions.zsh | 13 +++----------
 1 file changed, 3 insertions(+), 10 deletions(-)

diff --git a/src/sdk/scripts/register-completions.zsh b/src/sdk/scripts/register-completions.zsh
index 8eebe9a867..faa32fef71 100644
--- a/src/sdk/scripts/register-completions.zsh
+++ b/src/sdk/scripts/register-completions.zsh
@@ -1,10 +1,3 @@
-# zsh parameter completion for the dotnet CLI
-
-_dotnet_zsh_complete() 
-{
-  local completions=("$(dotnet complete "$words")")
-
-  reply=( "${(ps:\n:)completions}" )
-}
-
-compctl -K _dotnet_zsh_complete dotnet
+#compdef dotnet
+local completions=("$(dotnet complete "$words")")
+[[ -n "$completions" ]] && compadd -- "${(ps:\n:)completions}" 
-- 
2.34.1
```

**Comment by marcpopMSFT** [comment]
Pinging on old PRs for status. Is this PR still relevant and what would be needed to get it prepped for merge? @omajid @baronfel @Esgariot

**Comment by Esgariot** [comment]
It should be still applicable, I'll check and update the PR over the weekend

**Comment by Esgariot** [comment]
@dotnet-policy-service agree

**Comment by Esgariot** [comment]
@marcpopMSFT @wli3 Please take a look now, I've added `_files` completions to the list, because `dotnet complete` doesn't include filenames in it's output.

**Comment by Esgariot** [comment]
I've also dropped `scripts/_dotnet` and replaced the existing completion script. Looking at e.g. Arch's PKGBUILD or Homebrew Formula, I see that they just copy the completion file into `_dotnet`, in appropriate location

- https://github.com/Homebrew/homebrew-core/blob/46401325ed2c4d72adb6f1592cf6096bb844b489/Formula/dotnet.rb#LL120C6-L120C6
- https://gitlab.archlinux.org/archlinux/packaging/packages/dotnet-core/-/blob/7.0.5.sdk105-1/PKGBUILD?ref_type=tags#L151

**Comment by baronfel** [comment]
This works and works well! I tested by installing zsh in a WSL ubuntu instance and adding the `_dotnet` script to the appropriate site-functions directory, then rebuilding my zsh completions cache. Future enhancements might include filtering the `_files` to just project files, solutions, and solution filters for the common cases, but this is already a nice step up :thumbsup:

**Review by baronfel — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
Chatted with baronfel and we'll merge this and if Omajid has additional feedback we can update with a new PR. Thank you for the contribution and sorry for the delay.

**Comment by omajid** [comment]
Sorry about the lack of response. I don't use zsh, so I don't have actionable specific advice for this PR itself.

I am glad that we are finally shipping a compdef-style completion support with .NET! AFAIK compdef-style completion files are required for completion to work if maintainers want to install them system-wide.

**Pull request merged**
