### PR TITLE
Revert back to 3.1.0 runtime versions

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Comment by mmitche** [comment]
These should start passing once new cli's and toolsets built on the older runtime propagate.

**Comment by mmitche** [comment]
@wli3 These look like real errors here and need reaction.

**Comment by wli3** [comment]
@swaroop-sridhar could you look in the this test failure? I don't know the goal of the test. Seems a simple rename could resolve it

**Comment by swaroop-sridhar** [comment]
Sure @wli3, I'll fix it.

**Comment by swaroop-sridhar** [comment]
Here it is @wli3: https://github.com/dotnet/sdk/pull/4044

**Comment by wli3** [comment]
@swaroop-sridhar thanks!

**Pull request merged**
