### PR TITLE
Add support for InvariantGlobalization MSBuild property

### LINKED ISSUE #1328: Add MSBuild property for Globalization.Invariant
We added support in the runtime to turn off culture support, so you can run apps without having to install ICU on the machine.

To enable this, a flag in the runtimeconfig.json is set:

See https://github.com/dotnet/corefx/blob/master/src/System.Globalization/tests/Invariant/xunit.console.netcore.runtimeconfig.json#L4

```JSON
{
  "runtimeOptions": {
    "configProperties": {
      "System.Globalization.Invariant": true
    },
```

We should add an MSBuild property for this switch, just like we did for the GC and ThreadPool properties in https://github.com/dotnet/sdk/pull/746.

It should be as simple as adding a new line in https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L173-L193 for the property.  (And adding a test.)

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #1328

### CODE REVIEW

**Comment by dsplaisted** [comment]
@dotnet-bot test Ubuntu14.04 Debug

**Review by eerhardt — APPROVED** [review]
Looks great!

**Review by tarekgh — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by dsplaisted** [comment]
@dotnet-bot test Ubuntu14.04 Debug

**Comment by dsplaisted** [comment]
@MattGertz FYI for tell mode

**Pull request merged**
