### PR TITLE
Merge branch 'release/9.0.2xx' => 'main'

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
We already have https://github.com/dotnet/sdk/pull/45365 which contains some manual changes that are missing here (i.e. vmr-prepare.yml).

**Comment by mthalman** [comment]
@ViktorHofer - Why was this change made? https://github.com/dotnet/sdk/pull/45427/commits/cc2d8c174608956a0293a64280a654947006e34d

**Comment by ViktorHofer** [comment]
The roslyn failure here is the same one as in https://github.com/dotnet/sdk/pull/44874

**Comment by v-wuzhai** [comment]
@tmat There is a dotnet watch test failure, changes from #45055. Error message as follows: 

> Failed to find expected prefix: 'dotnet watch \ud83d\udd25 [blazorwasm (net9.0)] Hot reload succeeded.'


Could you take a look?

**Comment by v-wuzhai** [comment]
@jjonescz @marcpopMSFT Could you take a look at the failures here?

> ##[error].dotnet\sdk\10.0.100-alpha.1.24551.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: (NETCORE_ENGINEERING_TELEMETRY=Build) Found multiple publish output files with the same relative path: D:\a\_work\1\s\test\xunit.runner.json, D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.24604.4\tools\XUnit\xunit.runner.json.

**Comment by tmat** [comment]
> @tmat There is a dotnet watch test failure, changes from #45055. Error message as follows:
> 
> > Failed to find expected prefix: 'dotnet watch \ud83d\udd25 [blazorwasm (net9.0)] Hot reload succeeded.'
> 
> Could you take a look?

Please skip any failing dotnet-watch tests. They are likely failing due to net10 branding https://github.com/dotnet/sdk/issues/42920

**Review by surayya-MS — APPROVED** [review]

**Comment by v-wuzhai** [comment]
@ViktorHofer @marcpopMSFT The FullFramework leg has some test failures.  Could you please take a look?

> System.InvalidOperationException : Exception during discovery:
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.DotNet.XUnitExtensions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
File name: 'Microsoft.DotNet.XUnitExtensions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target)
at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(MethodInfo method, Type attributeType, AttributeUsageAttribute attributeUsage) in //src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs:line 101
at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in //src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs:line 88
at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in //src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 84
at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in //src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 135


> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by ViktorHofer** [comment]
> Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.

No idea honestly. @mmitche might know what's going on here.

**Comment by ViktorHofer** [comment]
> src/roslyn/src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs(217,13): error CS1503: (NETCORE_ENGINEERING_TELEMETRY=Build) Argument 4: cannot convert from 'System.Collections.Immutable.ImmutableHashSet<Microsoft.CodeAnalysis.Project>' to 'System.Collections.Generic.IReadOnlySet<Microsoft.CodeAnalysis.Project>'

@tmat can you please take a look at the dotnet watch VMR source-build failures?

**Comment by ViktorHofer** [comment]
> Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

Failing in the Ubuntu DevVersions leg. @premun any idea?

**Comment by ViktorHofer** [comment]
And last but not least:

```
No templates or subcommands found matching: 'nunit'.
    Did you mean one of the following templates?
       dotnet new nunit-test
```

@Evangelink something is wrong when using the `nunit-test` template in the VMR.

**Comment by ViktorHofer** [comment]
```
https://aka.ms/templating-exit-codes#103
< /datadisks/disk1/work/ADDA0970/p/d/dotnet new --debug:ephemeral-hive nunit --no-restore exited with 103 in 907 ms.
[xUnit.net 00:00:44.57]     EndToEnd.Tests.ProjectBuildTests.ItCanCreateAndBuildTemplatesWithDefaultFramework(templateName: "nunit", language: "") [OUTPUT] Command 'dotnet new --debug:ephemeral-hive nunit --no-restore' exited with exit code 103.
Running /datadisks/disk1/work/ADDA0970/p/d/dotnet new --debug:ephemeral-hive nunit --no-restore --language F#
> /datadisks/disk1/work/ADDA0970/p/d/dotnet new --debug:ephemeral-hive nunit --no-restore --language F#
Process ID: 72644
[xUnit.net 00:00:44.62]     EndToEnd.Tests.ProjectBuildTests.ItCanCreateAndBuildTemplatesWithDefaultFramework(templateName: "nunit", language: "") [FAIL]
[xUnit.net 00:00:44.62]       Expected command to pass but it did not.
[xUnit.net 00:00:44.62]       File Name: /datadisks/disk1/work/ADDA0970/p/d/dotnet
[xUnit.net 00:00:44.62]       Arguments: new --debug:ephemeral-hive nunit --no-restore
[xUnit.net 00:00:44.62]       Exit Code: 103
[xUnit.net 00:00:44.62]       StdOut:
[xUnit.net 00:00:44.62]       
[xUnit.net 00:00:44.62]       StdErr:
[xUnit.net 00:00:44.62]       Unable to resolve the template, the following installed templates are conflicting:
[xUnit.net 00:00:44.62]       Identity                               Template Name         Short Name  Language  Precedence  Author                                            Package
[xUnit.net 00:00:44.62]       -------------------------------------  --------------------  ----------  --------  ----------  ------------------------------------------------  -------
[xUnit.net 00:00:44.62]       NUnit3.DotNetNew.Template.CSharp.10.0  NUnit 3 Test Project  nunit       C#        11000       Aleksei Kharlov aka halex2005 (codeofclimber.ru)         
[xUnit.net 00:00:44.62]       NUnit3.DotNetNew.Template.CSharp.9.0   NUnit 3 Test Project  nunit       C#        11000       Aleksei Kharlov aka halex2005 (codeofclimber.ru)         
```

Any idea where the `NUnit3.DotNetNew.Template.CSharp.9.0` template is coming from?

**Comment by mmitche** [comment]
> @ViktorHofer @marcpopMSFT The FullFramework leg has some test failures. Could you please take a look?
> 
> > System.InvalidOperationException : Exception during discovery:
> > System.IO.FileLoadException: Could not load file or assembly 'Microsoft.DotNet.XUnitExtensions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
> > File name: 'Microsoft.DotNet.XUnitExtensions, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
> > at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
> > at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
> > at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
> > at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
> > at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
> > at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target)
> > at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(MethodInfo method, Type attributeType, AttributeUsageAttribute attributeUsage) in //src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs:line 101
> > at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in //src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs:line 88
> > at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in //src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 84
> > at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in //src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 135
> 
> > WRN: Assembly binding logging is turned OFF.
> > To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> > Note: There is some performance penalty associated with assembly bind failure logging.
> > To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

I think this error is because the binary **is** delay signed (Arcade doesn't sign, and this is the Microsoft full framework public key). The question is why XUnit cares that it's strong name signed or not.

**Comment by marcpopMSFT** [comment]
It's close, the arm64 failures look like the known timeouts so we just need the VMR legs to finish (and pass) and then can merge on red.

**Comment by v-wuzhai** [comment]
@dotnet/source-build Could you take a look at the failures here?

**Review by Evangelink — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by mthalman** [comment]
@ViktorHofer - That roslyn patch didn't work because it sets a property based on those parameters that are being passed in and the type is now incompatible.

```
/__w/1/vmr/src/roslyn/src/Features/Core/Portable/ExternalAccess/Watch/Api/WatchHotReloadService.cs(94,67): error CS0029: Cannot implicitly convert type 'System.Collections.Immutable.ImmutableHashSet<Microsoft.CodeAnalysis.Project>' to 'System.Collections.Generic.IReadOnlySet<Microsoft.CodeAnalysis.Project>' [/__w/1/vmr/src/roslyn/src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj::TargetFramework=net9.0]
```

Going back to the original issue, I don't understand why `ImmutableHashSet` isn't compatible with `IReadOnlySet` since it does implement that interface: https://github.com/dotnet/runtime/blob/d7e85d93c12aaa43937f8ef5f920c36b5afc756d/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet_1.cs#L19

**Comment by ViktorHofer** [comment]
@mthalman maybe you were looking at a previous commit? The latest patch should work.

See https://github.com/dotnet/roslyn/pull/76486 for the issue investigation.

**Comment by dsplaisted** [comment]
🎉🎉🎉

**Pull request merged**
