### PR TITLE
[WIP] adding Linux performance testing CI legs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by johnbeisner** [comment]
@dotnet-bot help

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 sdk perf tests
@dotnet-bot test Windows_NT x86 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 sdk perf tests
@dotnet-bot test Windows_NT x86 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot help

**Comment by johnbeisner** [comment]
@dotnet-bot test Linux_16.04 x64 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 sdk perf tests
@dotnet-bot test Windows_NT x86 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by livarcocc** [comment]
before merging this, please squash the commits.

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
@dotnet-bot test CI please

**Comment by johnbeisner** [comment]
Replaced by: https://github.com/dotnet/sdk/pull/2318

**Pull request closed without merging**
