### PR TITLE
[WIP] Adding Web Large performance test

### PR DESCRIPTION
**Pull request by ghost**
Most of the change is adding the WebLarge test asset; the functional change is in: 'src/Tests/Microsoft.NET.PerformanceTests/BuildPerf.cs'

The 'WebLarge' test asset is small but has a lot of files: 5 MB - 13,384 files

### CODE REVIEW

**Comment by johnbeisner** [comment]
@dotnet-bot help

**Comment by dsplaisted** [comment]
Can you separate this in to two separate commits?  One to add all the weblarge files, and one to add the test scenario?  That will make it easier to review.

Given that there are 13,000 files added here, I'm also having second thoughts about checking them in to our repo.  Maybe we should go ahead with the git checkout in the test itself.

**Comment by johnbeisner** [comment]
@dotnet-bot test Ubuntu_16.04 x64 sdk perf tests
@dotnet-bot test Windows_NT x64 sdk perf tests
@dotnet-bot test Windows_NT x86 sdk perf tests

**Review by nguerrera — CHANGES_REQUESTED** [review]
We agreed to keep the thousands of files in a separate repo so just putting a formal "request changes" on that.

Please make sure to rebase/squash out the commit that has all the files.

**Comment by johnbeisner** [comment]
@dotnet-bot test Ubuntu_16.04 x64 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test Windows_NT x64 sdk perf tests

**Comment by johnbeisner** [comment]
@dotnet-bot test Ubuntu_16.04 x64 sdk perf tests
@dotnet-bot test Windows_NT x64 sdk perf tests
@dotnet-bot test Windows_NT x86 sdk perf tests

**Comment by johnbeisner** [comment]
replaced by: https://github.com/dotnet/sdk/pull/2403

**Pull request closed without merging**
