### PR TITLE
Insert NuGet Build 5.0.0-preview3.5781 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.0-preview3.5781 into sdk release/2.2.2xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
We merged the NuGet.Packaging.Core assembly and merged it into NuGet.Packaging. 

There is a direct PackageReference to it in the build which is causing at least 1 failure.

**Comment by wli3** [comment]
I removed the reference to NuGet.Packaging.Core cc @nguerrera

**Comment by wli3** [comment]
Same there https://github.com/dotnet/sdk/pull/2832

**Comment by wli3** [comment]
I'll keep digging why that causes SDK cannot start at all

**Comment by nguerrera** [comment]
Probably needs updated stage 0 with matching nuget

**Comment by wli3** [comment]
is so we stuck. CLI cannot crossgen due to missing nuget.packaging.core.dll. What we do usually to get out of it?

**Comment by nguerrera** [comment]
In the past, we have built an sdk out of a branch with tests skipped, inserted that to cli and brought everything back to sdk. It's a mess. Binary breaking changes are a huge pain point. I think we can only get out of this by merging cli, sdk, and toolset into one repo, which is starting to look like a good enough option.

😫

**Comment by jainaashish** [comment]
For now you can ignore this PR and abandon it. But as a separate PR, remove the direct PackageReference to `NuGet.Packaging.Core` from dev16 related branches.

**Comment by nguerrera** [comment]
> as a separate PR, remove the direct PackageReference to NuGet.Packaging.Core from dev16 related branches.

We will still have to do a big song and dance to take the update. Removing the direct reference doesn't help enough without also increasing the NuGet version. Note that Microsoft.NET.Build.Tasks already has no *direct* dependency on NuGet.Packaging.Core. It has:

```
NuGet.ProjectModel
 -> NuGet.DependencyResolver.Core
   -> NuGet.Protocol
      -> NuGet.Packaging
         -> NuGet.Packaging.Core
```

And this is enough to get NuGet.Packaging.Core burned in to it:

```
.assembly extern NuGet.Packaging.Core
{
  .publickeytoken = (31 BF 38 56 AD 36 4E 35 )                         // 1.8V.6N5
  .ver 5:0:0:1
}
```

**Comment by nguerrera** [comment]
The only direct references are in tests and they are not the cause of the failure to crossgen in CLI.

**Comment by nguerrera** [comment]
There are ProjectModel API we must call like this:

```
   IL_001f:  callvirt   instance class [System.Runtime]System.Collections.Generic.IList`1<class [NuGet.Packaging.Core]NuGet.Packaging.Core.PackageDependency> [NuGet.ProjectModel]NuGet.ProjectModel.LockFileTargetLibrary::get_Dependencies()
```

We therefore cannot remove the assembly reference to Nuget.Packaging.Core unless we're using a version of NuGet that has removed it and then we still have the chicken and egg problem with the CLI.

**Comment by jainaashish** [comment]
We'll raise the new PRs with latest NuGet for dev16 preview3 which will unblock you to proceed.

**Comment by nguerrera** [comment]
If the new version of NuGet for dev16 preview3 has the same binary breaking change, I'm just pointing out that it will be just as hard to ingest. Does it still have that break? 

Just to be clear, if it does still have the break, removing the tests' direct  PackageReferences to NuGet.Packaging.Core in a separate PR before we take it won't help avoid the insertion [song and dance](https://github.com/dotnet/sdk/pull/2831#issuecomment-455223700)

**Pull request closed without merging**
