### PR TITLE
Run fewer Debug jobs

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by captainsafia** [comment]
Not sure if it is related to the changes made but AzDO/GitHub seem to reading weird states on the queued builds.

image

image


/azp run

**Comment by marcpopMSFT** [comment]
@captainsafia It could be a GH issue or could be an engineering system issue. It looks like it just doesn't updated to the yellow circle like it did before.  Might be worth reporting to the dnceng Teams channel.

**Comment by pranavkm** [comment]
I think it might have been related to the Helix outages from last night. Looks like it's fixed now.

**Comment by pranavkm** [comment]
@wli3 could you sign off when you get a chance?

**Review by wli3 — APPROVED** [review]

**Pull request merged**
