### PR TITLE
Update Microsoft.NET.HostModel version

### PR DESCRIPTION
**Pull request by elinor-fung**
This is for dotnet/core-setup#7173

It is also affecting Preview 7. This is just the change in master.

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
Can you add a DARC subscription to core-setup from this repo as well?

**Comment by elinor-fung** [comment]
Is there something I need to do other than run darc add-subscription? I ran:
`darc add-subscription --channel ".NET Core 3 Dev" --target-repo https://github.com/dotnet/sdk --source-repo https://github.com/dotnet/core-setup --target-branch master --update-frequency everyDay --ignore-checks WIP,license/cla --all-checks-passed`

(and `get-subscriptions --target-repo https://github.com/dotnet/sdk` shows it)

**Comment by livarcocc** [comment]
@elinor-fung that should do it.

**Review by jeffschwMSFT — APPROVED** [review]
lgtm

**Pull request merged**
