### PR TITLE
Merge 6.0.1xx into the 6.0.2xx branch to catch it up to current

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
azp /run

**Review by dsplaisted — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@jmarolf, @JoeRobich dotnet format had version number changes in this merge. Typically we don't see that going between branches since there is usually separate codeflow directly to 6.0.2xx for all components. a) is this expected and b) is this because of a missing codeflow from format to the 6.0.2xx branch?

**Comment by JoeRobich** [comment]
> is this because of a missing codeflow from format to the 6.0.2xx branch?

That's the problem. I will update the subscription.

**Pull request merged**
