### PR TITLE
Fix incorrect apphost being used when publishing for self-contained single-file with `NoBuild=true`

### PR DESCRIPTION
**Pull request by elinor-fung**
The `_GetAppHostCreationConfiguration` target sets the `_UseSingleFileHostForPublish` property, which determines if we (re-)create the app using `singlefilehost` on publish. When publishing with `NoBuild=true`, the target was not being run, so we bundled using `apphost`, resulting in an app that was configured to be self-contained but did not actually have the runtime as part of itself.

This change chains the target into the computation for output paths to ensure that the target runs when publishing without building, so that the correct host is used.

See https://developercommunity.visualstudio.com/t/Single-file-self-contained-failing-after/10794374

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]
Looks great, thanks a lot!

**Comment by dsplaisted** [comment]
> Is there something I'm missing here that is being flagged as failing / needing investigation?

@elinor-fung No, we have a bunch of 9.0.2xx PRs that are failing due to this issue, which we are trying to investigate and fix.  Right now I don't think 9.0.2xx changes are too urgent to merge.  If we have to, we will either start merging on red or disable the CI leg that's failing.

Thanks!

**Comment by baronfel** [comment]
Because this impacts source-build users pretty significantly I think we should request a backported servicing fix once this is merged.

**Comment by nagilson** [comment]
Rerunning to see if that timeout goes away for now.

**Comment by nagilson** [comment]
@marcpopMSFT I think this is pretty important and I would approve to merge on red if I had permission. We still have some time in Jan (like 2 weeks) so it's probably not necessary yet, but we should keep an eye out on this PR.

**Comment by marcpopMSFT** [comment]
Failures are known issues and want to prep this for customer feedback

**Pull request merged**
