### PR TITLE
Manually update NuGet to 5.6.0-preview.2.6492

### PR DESCRIPTION
**Pull request by ViktorHofer**
Manually updating the NuGet dependencies until https://github.com/NuGet/Home/issues/9279 is fixed an bits aren't flowing as usual.

cc @mmitche

### CODE REVIEW

**Comment by zivkan** [comment]
FYI, the version I tried to insert on Friday was `5.6.0-preview.2.6489` (https://github.com/NuGet/NuGet.Client/tree/5.6.0.6489)

As we didn't use our normal insertion workflow for build 6492, it has no tag in git, and it will be a newer version that VS will have.

**Comment by ViktorHofer** [comment]
> As we didn't use our normal insertion workflow for build 6492, it has no tag in git, and it will be a newer version that VS will have.

Does that mean we shouldn't merge this one?

**Comment by zivkan** [comment]
It might be better if you don't, because we need to increment our assembly version every time we insert to avoid potential issues with different binaries with the same version number (for reasons I don't understand, our build number is not used in the assembly version). The binary  you selected here already has the same assembly version that our next insertion is intended to use, although we can just bump the version now if it's difficult/slow for you to use our different package version.

**Comment by ViktorHofer** [comment]
I can wait for another official build, not a problem.

**Pull request closed without merging**
