### PR TITLE
Allow NuGetBuildTasksPackTargets to be overrideable

### LINKED ISSUE #888: Allow NuGetBuildTasksPackTargets to be overrideable
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets#L49

```NuGetBuildTasksPackTargets``` should check for whether it is already set or not before assigning a value. This allows someone to add a PackageReference to a OOB release of NuGet.Build.Tasks.Pack and set this property themselves.

### PR DESCRIPTION
**Pull request by kzu**
Fixes #888

### CODE REVIEW

**Comment by kzu** [comment]
This is blocking NuGetizer 3000 from being used in .NETStandard/.NETCore projects, since it's impossible to override the `Pack` target.

/cc @rohit21agrawal @mhutch @migueldeicaza @nguerrera @dsplaisted

**Review by rohit21agrawal — APPROVED** [review]

**Comment by natidea** [comment]
Is this PR ready to go? If so we can get it in before branch lockdown

**Comment by kzu** [comment]
It's ready!

**Review by livarcocc — APPROVED** [review]

**Comment by natidea** [comment]
This change (and subsequent ones) did not make it in before the RI. It can go into the Ask Mode branch when it opens.

**Comment by kzu** [comment]
Is this on track for 15.3 at least?

**Comment by natidea** [comment]
Yes it has been inserted into 15.3. (The RI was also for 15.3 -- it was just a question of whether it got in before or after Ask Mode started. We grandfathered this in with the first set of Ask Mode changes.)

**Pull request merged**
