### PR TITLE
[release/5.0.1xx] Remove extra version property

### PR DESCRIPTION
**Pull request by mmitche**
This was causing System.Security.Cryptography to pin at preview7

### CODE REVIEW

**Comment by mmitche** [comment]
@sfoslund I found this in master when trying to remove some feeds in https://github.com/dotnet/sdk/pull/15816. I think this may cause compile errors (it does in 6.0)

**Comment by sfoslund** [comment]
From the build errors it looks like it's still needed?

**Comment by mmitche** [comment]
@sfoslund The version that is getting used is a 5.0 preview 7 version, rather than the version that is flowing from the runtime repo.

**Review by sfoslund — APPROVED** [review]

**Comment by mmitche** [comment]
Okay, so what do we do about the missing API...i'm guessing this was a breaking change missed a while back.

@JeremyKuhne any of this look familiar from mid-.net 5 previews?

```
src\WebSdk\Publish\Tasks\Tasks\MsDeploy\GetPassword.cs(46,36): error CA1416: (NETCORE_ENGINEERING_TELEMETRY=Build) 'ProtectedData.Unprotect(byte[], byte[]?, DataProtectionScope)' is supported on 'windows'

src\WebSdk\Publish\Tasks\Tasks\MsDeploy\GetPassword.cs(46,110): error CA1416: (NETCORE_ENGINEERING_TELEMETRY=Build) 'DataProtectionScope.CurrentUser' is supported on 'windows'

```

**Comment by JeremyKuhne** [comment]
@mmitche I presume you meant to tag @bartonjs

**Comment by mmitche** [comment]
@vijayrkn Any luck with this?

**Comment by vijayrkn** [comment]
> @vijayrkn Any luck with this?

Didn't get a chance to drill into the issue yesterday. On my list. Will update as soon as I get to it.

**Comment by vijayrkn** [comment]
@mmitche - I looked at the issue and that api is only expected to work in windows. So, I should be able to suppress the warning. This shouldn't impact any functionality. Do you want me to update the PR with the suppression?

**Comment by vijayrkn** [comment]
@mmitche - I am updating this PR with the suppression. Update on the way.

**Review by vijayrkn — APPROVED** [review]

**Comment by mmitche** [comment]
Great. Good to know there isn't a potential runtime issue. What was the effect of it referencing an old p7 version rather than the latest shipped version?

**Comment by vijayrkn** [comment]
> Great. Good to know there isn't a potential runtime issue. What was the effect of it referencing an old p7 version rather than the latest shipped version?

Shouldn't have any impact. The api or the implementation hasn't changed. The only difference was the introduction of the new warning which is suppressed now.

**Pull request merged**
