### PR TITLE
format: stop checking for dotnet cli version

### PR DESCRIPTION
**Pull request by RikkiGibson**
dotnet/format#2218

@JoeRobich does this seem like a reasonable step to get more info about the issue?

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-ide for review

**Comment by RikkiGibson** [comment]
@Cosifne @dotnet/roslyn-ide for review

**Comment by Cosifne** [comment]
Might better to get a review from Joey as I am unfamiliar with the format codebase

**Comment by JoeRobich** [comment]
I am thinking that since dotnet-format is building out of the SDK repo. The dotnet CLI version and the dotnet-format version should be the "same", although it appears that the CLI's version truncates the specifics of the build number. We may just want to ditch logging the CLI version as it should be matched.

**Comment by RikkiGibson** [comment]
Per offline discussion we think we just shouldn't do this check any more because we are shipping in the sdk anyway. @JoeRobich

**Review by JoeRobich — APPROVED** [review]

**Comment by RikkiGibson** [comment]
It looks like the macOS job has failed after 3 attempts. The only [test results](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875084&view=ms.vss-test-web.build-test-results-tab) appear to be failing work items. The helix logs are very verbose and I'm having difficulty interpreting what is failing here.

@ViktorHofer @MiYanni do you have any insight into what is failing in CI here?

**Comment by RikkiGibson** [comment]
@joeloff for assistance with https://github.com/dotnet/sdk/pull/44958#issuecomment-2489994642

**Comment by joeloff** [comment]
This is just Helix timing out. We had a lot of failures on code flow PRs as well. We split some of the tests recently in main to decrease the load within a single run.

**Comment by joeloff** [comment]
I'm going to try and backport one of our changes in main to 9.0.2xx that split out the ILLink tests.

**Comment by RikkiGibson** [comment]
This PR has been stuck on CI issues for a few weeks now and I’m unsure what to do in order to move it forward.

**Pull request merged**
