### PR TITLE
Insert NuGet Build 4.8.0-preview5.5328 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.8.0-preview5.5328 into sdk release/2.1.4xx branch

### CODE REVIEW

**Comment by PatoBeltran** [comment]
@livarcocc the PR for this insertion was merged yesterday to VS.

**Comment by PatoBeltran** [comment]
@nguerrera @dsplaisted since @livarcocc is OOF

**Comment by nguerrera** [comment]
@mmitche We've somehow gotten a machine without 4.7.2 targeting pack on Jenkins

**Comment by nguerrera** [comment]
@dotnet-bot Test Windows_NT_FullFramework Debug

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
