### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Move away from blob feeds.

### CODE REVIEW

**Comment by mmitche** [comment]
I expect this won't pass until @JohnTortugo has nuget.client on the proper publishing infra.

**Comment by JohnTortugo** [comment]
@mmitche - NuGet.Client now [is using our infra](https://github.com/NuGet/NuGet.Client/blob/dev/build/publish.proj#L56) - at least partially. They persist they build to BAR and upload the artifacts to the right places. However, there is no default channel configuration for their builds, therefore no assets on feeds. For now they'll use `Darc add-build-to-channel` to do it manually.

**Comment by JohnTortugo** [comment]
But I don't think they promoted any build yet. 

@zivkan Can we promote one of the builds of NuGet.Client so that we have packages on the new feeds and then be able to merge this PR?

**Comment by mmitche** [comment]
@JohnTortugo We can wait on the latest insertion to merge this, no hurry,.

**Comment by zivkan** [comment]
@rrelyea is on NuGet hotseat this week. He's currently trying to get a build to promote/insert, but we're having CI infrastructure issues :(   installing VSIX's into VS for test automation seems flaky.

**Comment by zivkan** [comment]
We have a PR to promote a new build now: https://github.com/dotnet/sdk/pull/11078

**Comment by mmitche** [comment]
now that nuget has flowed a new build on the new infra.

**Pull request merged**
