### PR TITLE
Update the RIDs target to the latest one

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
This PR can replace #25909

**Comment by marcpopMSFT** [comment]
@v-wuzhai more merge conflicts.

**Comment by v-wuzhai** [comment]
Done

**Comment by marcpopMSFT** [comment]
I think this conflicted with another PR you made that I just merged. Please resolve. Thanks.

**Comment by v-wuzhai** [comment]
Done

**Review by marcpopMSFT — APPROVED** [review]

**Pull request merged**
