### PR TITLE
Show dogfood annotation in prompt

### PR DESCRIPTION
**Pull request by edvilme**
image
It can get confusing to users to know whether they are inside or outside dogfood. An annotation is added to the prompt in Powershell to make this clear to users.

### CODE REVIEW

**Review by baronfel — COMMENTED** [review]
related question - should we set an environment variable signifying that we are in dogfood mode? I use a custom prompt from oh-my-posh and it would be great to be able to create a prompt segment to do this instead of modifying my global prompt

**Comment by edvilme** [comment]
> related question - should we set an environment variable signifying that we are in dogfood mode? I use a custom prompt from oh-my-posh and it would be great to be able to create a prompt segment to do this instead of modifying my global prompt

I can look into respecting the current prompt, and signaling to the terminal that this is a new env. Similar to python environments maybe?

**Comment by nagilson** [comment]
It would be awesome to have this in Bash too!

**Review by nagilson — APPROVED** [review]
I really like this change, thank you 😄  It's a smart idea. I've totally forgotten which level of dogfood prompts I'm in too. So this will be rather helpful.

**Pull request merged**
