### PR TITLE
Let runtime supply the portable RID graph

### PR DESCRIPTION
**Pull request by ViktorHofer**
Contributes to dotnet/sdk#35750
Related: https://github.com/dotnet/installer/pull/17760

That deleted build task got moved into runtime: https://github.com/dotnet/runtime/blob/faf65649cc5948884e40825889016808b5e36629/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj#L52-L60

cc @tmds

### CODE REVIEW

**Comment by dsplaisted** [comment]
It looks like tests are failing because the portable RuntimeIdentifier graph can't be found.  Probably the code that creates stage 2 needs to be updated to include that file.

**Comment by ViktorHofer** [comment]
> It looks like tests are failing because the portable RuntimeIdentifier graph can't be found. Probably the code that creates stage 2 needs to be updated to include that file.

Any idea how to do that? The portable and non portable RID graphs are directly flowing from runtime -> installer and bundled into the SDK there.

**Comment by ViktorHofer** [comment]
> these two needed?

Those properties in the sdk are needed, yes.

**Review by akoeplinger — APPROVED** [review]

**Comment by xen0n** [comment]
Hi, apparently this change broke [this doc page](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#rid-graph) by accident? As the [`PortableRuntimeIdentifierGraph.json`](https://github.com/dotnet/sdk/blob/main/src/Layout/redist/PortableRuntimeIdentifierGraph.json) was removed here.

**Comment by akoeplinger** [comment]
Thanks, we need to fix the doc page.

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/docs/pull/41729

**Pull request merged**
