### PR TITLE
'dotnet configure add' command for adding new config to a solution file

### PR DESCRIPTION
**Pull request by vrushalivartak**
As reported in [here ](https://github.com/dotnet/sdk/issues/10359) support for custom configurations is missing currently in dotnet cli. 
A new dotnet configure command will enable to add, remove, rename, update the config or platform to a solution file.
This PR is for 'add' command, limited to adding config to a solution file. 
dotnet configure [<SOLUTION_FILE>] add -c|--config <name> [-cf|--copyfrom <name>] [-up|--updateproj <y/n>]

PRs for, 'add' command to add platform and 'remove', 'rename', 'update' commands, to follow after this PR is approved.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=29139) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=29139) before we can accept your contribution.<br/><br/>:x: vrushalivartak [sign now](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=29139)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/sdk?pullRequest=29139) it.</sub>

**Comment by marcpopMSFT** [comment]
Adding @baronfel as this is a new feature. This also should be "dotnet sln configuration add" rather than another root level command. This is tied to the solution file so needs to be under the sln command.

**Comment by vrushalivartak** [comment]
> Adding @baronfel as this is a new feature. This also should be "dotnet sln configuration add" rather than another root level command. This is tied to the solution file so needs to be under the sln command.

**Comment by baronfel** [comment]
I would prefer the solution-specific command for now. If we do develop longer-term plans around SDK configuration (NOTE: not MSBuild Configurations), then I would want the `config/configure` name to be available for that. If/when we need project-specific configuration support, `dotnet project configure xxx` is also viable.

**Comment by marcpopMSFT** [comment]
Following up on old PRs. Per Chet and my comment, if you want to redo this reworking the command to be part of dotnet sln, we'd consider taking a look but we're not prepared to have a top level dotnet configure at this time. Feel free to rework and open a new PR if you still want to pursue the other option.

**Pull request closed without merging**
