### PR TITLE
Updating NuGet version to 4.3.0-preview3-4123

### PR DESCRIPTION
**Pull request by jainaashish**
Updating NuGet version to 4.3.0-preview3-4123

@dsplaisted @livarcocc @srivatsn @natidea @rrelyea @emgarten

### CODE REVIEW

**Review by emgarten — APPROVED** [review]

**Comment by dsplaisted** [comment]
We need to get #1283 merged first

**Comment by jainaashish** [comment]
Why can't we directly merge this and just close #1283 ?

**Comment by dsplaisted** [comment]
@jainaashish because we usually have to do a back and forth process of updating the CLI and SDK together, due to breaking changes in NuGet.  You can try updating this PR to also update the version of the CLI as in #1283, and see whether that works.

**Comment by dsplaisted** [comment]
@dotnet-bot test this please

**Comment by nkolev92** [comment]
Closing in favor of https://github.com/dotnet/sdk/pull/1304

**Pull request closed without merging**
