### PR TITLE
Insert NuGet Build 4.7.0-rtm.5081 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-rtm.5081 into sdk release/2.1.2xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@rohit21agrawal @mishra14 this is failing due to the following:

```
error CS7036: There is no argument given that corresponds to the required formal parameter 'signedPackageVerifierSettings' of 'PackageExtractionContext.PackageExtractionContext(PackageSaveMode, XmlDocFileSaveMode, ILogger, IPackageSignatureVerifier, SignedPackageVerifierSettings)
```

Expected change in the API?

**Comment by mishra14** [comment]
Hey livar,

Yes, the API is changed. I will need to take a look at what is calling this that needs updating.

Ankit

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by livarcocc** [comment]
Another one:

```
GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs(149,25): error CS1660: Cannot convert lambda expression to type 'IPackageDownloader' because it is not a delegate type
```

I will try the build locally and fix it. This way may work faster.

**Comment by dsplaisted** [comment]
@livarcocc See this commit for what I did in a parallel PR: https://github.com/dotnet/sdk/pull/2118/commits/dcc217cab61dad2a5747b7ffdbffb8cabf19e3d7

**Comment by livarcocc** [comment]
I validated OSX locally. Merging...

**Review by livarcocc — APPROVED** [review]

**Pull request merged**
