### PR TITLE
Add RazorLangVersion 9

### PR DESCRIPTION
**Pull request by jjonescz**
(Also fixes indentation of an existing entry, so reviewing without whitespace is recommended.)

### CODE REVIEW

**Review by jaredpar — COMMENTED** [review]
Typically we don't do this until the last VS release before .NET SDK RTM. Basically start of 17.12. Why are we doing this early?

**Comment by jjonescz** [comment]
> Why are we doing this early?

I just added the new RazorLangVersion in one of my recent razor PRs where I needed to gate some functionality on it. And I thought this should be consistent.

> Typically we don't do this until the last VS release before .NET SDK RTM. Basically start of 17.12.

This makes sense, thanks. I will mark this as draft for now.

**Comment by jjonescz** [comment]
17.12 started, so I assume this is relevant again.

**Review by 333fred — APPROVED** [review]

**Comment by jjonescz** [comment]
@jaredpar can/should this be merged now?

**Comment by jaredpar** [comment]
@marcpopMSFT what .NET SDK does `main` represent right now? 

@jjonescz agree this is the right time for this work but we need to make sure this goes into the .NET 9.0.100 branch.

**Comment by marcpopMSFT** [comment]
> @marcpopMSFT what .NET SDK does `main` represent right now?
main is currently .net 9 preview 7. We haven't forked for preview 7 and we haven't created the 9.0.100 branch yet (that'll happen in August when we branch for RC1).

**Review by jaredpar — APPROVED** [review]

**Comment by jjonescz** [comment]
@marcpopMSFT @jaredpar should this be merged now?

**Review by jaredpar — APPROVED** [review]

**Pull request merged**
