### PR TITLE
Add the installer's package table to SDK docs

### PR DESCRIPTION
**Pull request by MiYanni**
## Summary

This table is used for customer's/partner's to download new SDK packages. I've moved this table into a file in the SDK repo and linked to it in our README.md. A link to this table will also be added to the dotnet/installer repo's README.md too once this is merged.

### CODE REVIEW

**Review by marcpopMSFT — COMMENTED** [review]
This is a good stopgap. Follow up questions:

1. Where should the tools that create this table live (I don't believe they were migrated over)?
2. Should we host the source build section of the installer table somewhere?
3. We're missing the list of feeds
4.  We're missing the license section
5. We're missing the link to the dotnet-install scripts
6. we're missing links to the debian packages

This is based on looking at the info here: https://github.com/dotnet/installer/blob/main/README.md

**Comment by richlander** [comment]
I'd like to chat about this. I've always found our build tables a bit awkward to use. Daily builds are not a mainline scenario, however, it would be great to make this content a bit more first class.

Definitely onboard with the questions from @marcpopMSFT. I'm offering up my services to help improve this experience and chat about what the answers.

**Comment by filipnavara** [comment]
- The old page had a whole section about NuGet feeds you need to add to actually use the daily builds. I don't see it in this PR. It's crucial to communicate that because the daily builds are unusable without it and it generates support requests.
- Will this get automatically updated as the new builds get published? If not, what is the plan to rectify that? This is quite essential when we direct customers to test a fix that was merged.

**Comment by MiYanni** [comment]
@richlander @filipnavara This PR is only intended to be a stopgap for the current dotnet/installer information. After we finish up some higher priority tasks for the repo merge, we'll revisit this and plan to do some automated generation of this information. At that time, it would be great to have a discussion around content and format of that document.

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@richlander Happy to look at improving the installer table next month. What are your thoughts on improvements to make?

Just staring at the existing table, the arm and rhel6 rows aren't needed and the version tag doesn't need to be repeated. Those are minor changes though and I imagine you had something more significant in mind.

**Comment by am11** [comment]
@MiYanni, sounds great. One question; could we keep these instructions:

````markdown
## Installers and Binaries

You can download the .NET SDK as either an installer (MSI, PKG) or a zip (zip, tar.gz). The .NET SDK contains both the .NET runtime and CLI tools.

**Note:** Be aware that the following installers are the **latest bits**. If you
want to install the latest released versions, check out the [preceding section](#looking-for-released-versions-of-the-net-core-tooling).
With development builds, internal NuGet feeds are necessary for some scenarios (for example, to acquire the runtime pack for self-contained apps). You can use the following NuGet.config to configure these feeds. See the following document [Configuring NuGet behavior](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) for more information on where to modify your NuGet.config to apply the changes.

**For .NET 9 builds**

```xml
<configuration>
  <packageSources>
    <add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**For .NET 8 builds**

```xml
<configuration>
  <packageSources>
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**For .NET 7 builds**

```xml
<configuration>
  <packageSources>
    <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Do not directly edit the table below. Use https://github.com/dotnet/installer/tree/main/tools/sdk-readme-table-generator to help you generate it. Make sure to run the table generator test and make any changes to the generator along with your changes to the table. Daily servicing builds aren't shown here because they may contain upcoming security fixes. All public servicing builds can be downloaded at http://aka.ms/dotnet-download.
````

I often find myself copying nuget.config lines from installer's readme. 😄

**Comment by MiYanni** [comment]
@am11 I've kept that section. Check this in the PR:
https://github.com/dotnet/sdk/pull/41098/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25-R44

**Comment by am11** [comment]
Thanks a lot! 👍 
(I was only reading the conversation didn't realized the section was there 🤦)

**Pull request merged**
