### PR TITLE
Tweak NETSDK1130

### PR DESCRIPTION
**Pull request by wli3**
Fix https://github.com/dotnet/sdk/issues/13233

### CODE REVIEW

**Review by dsplaisted — CHANGES_REQUESTED** [review]
I do not think we should change this to a warning.  The CSWinRT tool targets should remove the .winmd `Reference` items and replace them with the generated CSWinRT projection assembly.

The change to `ReferencePathWithRefAssemblies` is probably good.

**Comment by wli3** [comment]
@dsplaisted I updated it to only fix the ReferencePathWithRefAssemblies issue

**Review by dsplaisted — APPROVED** [review]
Do we have tests covering this?  Does this still work if you have reference assemblies disabled?

**Comment by wli3** [comment]
There is existing test. I'll check for reference assemblies being disabled

**Comment by wli3** [comment]
no longer needed

**Pull request closed without merging**
