### PR TITLE
Implicit RID support

### PR DESCRIPTION
**Pull request by WeihanLi**
#19576 

I'm sorry that I'm not sure how to implement this in the right way, and the test cases are not implemented

@agocke could you please help me on this

### CODE REVIEW

**Comment by agocke** [comment]
Happy to help with this, just finishing up a few things I have on my plate. Should be able to get to it later today or tomorrow.

**Comment by agocke** [comment]
Hmm, I wonder if this can be a change purely in `src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets`. The idea would be that we would use the SDK RID if `UseCurrentRuntimeIdentifier` is true or RuntimeIdentifer is unset and SelfContained is set to true.

**Comment by marcpopMSFT** [comment]
Isn't this just the switch `--use-current-runtime`? I don't think we'd want to make this implicit but would rather prefer customers specify the switch.

**Comment by agocke** [comment]
@marcpopMSFT I think that's a question for @richlander, as that contradicts the issue description.

**Comment by WeihanLi** [comment]
Hi @agocke, is there any more changes needed, or should wait for more feedback.
cc: @richlander @marcpopMSFT 

I could not run all the tests on my side, for some failed tests in `Microsoft.NET.Build.Tasks.UnitTests`, it would fail even I revert my changes, could you please help me with the failed test cases.

I tested the SDK with my test project,  seemed to work fine, test output as follows:

``` sh
PS C:\projects\source\dotnet\sdk> dotnet publish -c Release --self-contained
Microsoft (R) Build Engine version 17.0.0-preview-21411-06+b0bb46ab8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\projects\test\DynamicStaticFileProvider\DynamicStaticFileProvider.csproj (in 9.19 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  DynamicStaticFileProvider -> C:\projects\test\DynamicStaticFileProvider\bin\Release\net5.0\win-x64\DynamicStaticFileProvider.dll
  DynamicStaticFileProvider -> C:\projects\test\DynamicStaticFileProvider\bin\Release\net5.0\win-x64\publish\
```

**Pull request closed without merging**
