### PR TITLE
Fix case sensitivity when mapping project paths to project infos.

### PR DESCRIPTION
**Pull request by peterhuene**
When a solution contains a path to a project that differs by case for a project
reference identity, the build fails because the project info can't be found.

The fix is to make the internal map case insensitive, allowing the case
difference in a project's path in the solution file.

Fixes dotnet/cli#8048.

### CODE REVIEW

**Comment by peterhuene** [comment]
The test won't pass on case-sensitive file system as-is.  Let me rethink this approach.

**Review by nguerrera — APPROVED** [review]

**Comment by peterhuene** [comment]
@MattGertz tell mode notice

**Comment by peterhuene** [comment]
@dotnet-bot test Windows_NT Debug

**Comment by peterhuene** [comment]
@dotnet-bot test Windows_NT Release

**Pull request merged**
