### PR TITLE
Upgrade test platform and fix related code coverage tests after recent changes

### PR DESCRIPTION
**Pull request by jakubch1**

### CODE REVIEW

**Comment by jakubch1** [comment]
@sfoslund  this is tests fixes for related PR: https://github.com/dotnet/sdk/pull/17690

**Review by sfoslund — APPROVED** [review]

**Comment by v-wuzhai** [comment]
@sfoslund @jakubch1 Could we merge the PR into the main branch?

**Comment by jakubch1** [comment]
Yes, we should. But I don't have rights to do it.

**Comment by v-wuzhai** [comment]
@jakubch1 Thanks!

**Pull request merged**
