### PR TITLE
Change default version of NETStandard.Library reference to 1.6.0

### PR DESCRIPTION
**Pull request by dsplaisted**
Referencing NETStandard.Library version 1.6.1 in an app targeting .NET Core will result in updated implementations of various CoreFx libraries being published with the app.  These implementations will override the implementations that are part of the shared framework for .NET Core 1.0.  This means the app will lose some of the perf benefits (ie from ngen) and disk space benefits from using a shared framework.  As the updated implementations are from the FTS branch, this also pulls the app out of LTS.

So this PR changes the implicitly referenced version of NETStandard.Library back to 1.6.0.  This means that a .NET Core 1.0 app won't automatically fall out of LTS and lose other benefits of the shared framework simply by referencing a .NET Standard library.

@ericstj @weshaggard

### CODE REVIEW

**Comment by dsplaisted** [comment]
@MattGertz for approval

Escrow template:

#### Scenario

Reference a .NET Standard Library from an app targeting .NET Core 1.0

#### Bug

n/a

#### Workarounds

Explicitly reference NETStandard.Library 1.6.0 from the app (and ignore downgrade warnings), or modify each referenced .NET Standard library by setting the `NetStandardImplicitPackageVersion` to 1.6.0

#### Risk

Medium - This may affect some Xamarin scenarios

#### Performance Impact

Low

#### Regression Analysis

This was introduced in #582

**Comment by MattGertz** [comment]
Per agreement with various .NET Core folks and Hunter.  We need to take this.

**Comment by dsplaisted** [comment]
@onovotny As I understand it, NETStandard.Library 1.6.0 doesn't install in projects using NuGet 2.x due to https://github.com/dotnet/corefx/issues/10445.  NETStandard.Library 1.6.1 brings in a fix for this.

I tried installing NETStandard.Library 1.6.0 into various packages.config projects using VS 2017 and 2015, and I didn't hit any issues.  So I think it's not an issue if NuGet 3.x or higher is being used.  Is this still an issue for Xamarin development?  Does Xamarin Studio / Visual Studio for Mac still use NuGet 2.x?

If NETStandard.Library 1.6.0 is still a problem for Xamarin projects, I would recommend that libraries either don't include a dependency on NETStandard.Library at all in the NuGet packages they produce, or that they use dependency groups so that version 1.6.1 is only specified for Xamarin projects where it's needed.  To exclude the dependency from the package that is produced, you can do the following:

```xml
<ItemGroup>
  <PackageReference Update="NETStandard.Library" PrivateAssets="All" />
</ItemGroup>
```

For the dependencyGroup solution, it looks like this isn't yet possible without multitargeting (ie compiling twice), or without authoring the .nuspec yourself.  Here's an issue for that: https://github.com/NuGet/Home/issues/4461

**Comment by onovotny** [comment]
It's an issue with certain PCL profiles -- I.e, Profile 151 when using packages.config. The 1.6.0 packages, specifically the Impl of the RuntimeInformation one, simply forgot to include a \lib folder for it. Instead it uas a \runtimes folder, which NuGet v2 doesn't respect. So 1.6.0 packages will fail to install on Packages.config with PCL's compatible with netstandard1.1.

**Comment by onovotny** [comment]
Not including the  NETStandard.Library reference is really bad and is not the recommended behavior. Many/most libraries will include this and thus will fail to install on Packages.config profile based PCL's.

**Comment by onovotny** [comment]
I think that the only real solution here is to create a `NETStandard.Library` 1.6.2 package that includes `netcoreapp1.0` and `netcoreapp1.1` specific versions in it. You can't hold people back. You also can't say that if your library needs a newer netstandard.library package version, that it'll break someone elses LTS.

**Comment by dsplaisted** [comment]
@onovotny Our current thinking (or at least what I've chatted with @terrajobst about), is that we want to move in the direction of packages not declaring dependencies on NETStandard.Library

**Comment by onovotny** [comment]
@dsplaisted that seems like chaos. Somewhere along the line, my library has to say what it needs.

**Comment by onovotny** [comment]
By the same logic, a `netstandard.library` `2.0` package should include the single new library for the `netstandard2.0` tfm but also the existing list for the lower ones.

What's missing in `netstandard.library` is that it doesn't break out `netcoreapp1.0`/`netcoreapp1.1`/`netcoreapp2.0` to tie to the right versions for that platform -- like it does for the other platforms like UWP in some cases.

**Comment by dsplaisted** [comment]
> Somewhere along the line, my library has to say what it needs.

It says what it needs via the NuGet conventions.  Ie the DLL is in lib/netstandard2.0 or whatever.  PCLs or libraries targeting any platform before .NET Standard didn't need to have a package dependency for the "framework" they were targeting.

**Comment by onovotny** [comment]
Talking to @ericstj, the best answer for the pain might be a 1.6.0.1 targeted fix that is the implicit reference that has a backport of the runtimeinformation fix

https://github.com/dotnet/corefx/issues/15735

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
Let's change to 1.6.0 until we have a 1.6.0.1 so that folks are on LTS.

**Comment by natidea** [comment]
Approved to merge via [378773](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/378773)

**Comment by dsplaisted** [comment]
> Talking to @ericstj, the best answer for the pain might be a 1.6.0.1 targeted fix that is the implicit reference that has a backport of the runtimeinformation fix

4 components in a NuGet package version?

mind blown

**Pull request merged**
