### PR TITLE
add `dotnet new sln --format slnx`

### PR DESCRIPTION
**Pull request by kasperk81**
```sh
dotnet new sln --help
Solution File
Author: Microsoft
Description: Create an empty solution containing no projects

Usage:
  dotnet new sln [options] [template options]
  dotnet new solution [options] [template options]

Options:
  -n, --name <name>      The name for the output being created. If no name is specified, the name of the output directory is used.
  -o, --output <output>  Location to place the generated output.
  --dry-run              Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force                Forces content to be generated even if it would change existing files.
  --no-update-check      Disables checking for the template package updates when instantiating a template.
  --project <project>    The project that should be used for context evaluation.

Template options:
  -f, --format <sln|slnx>  Choose the format for the solution file: traditional (.sln) or XML-based (.slnx).
                           Type: choice
                             sln   Traditional solution file
                             slnx  XML-based solution file
                           Default: sln
```

default (without --format) is `.sln`.

Contributes to https://github.com/dotnet/sdk/issues/40913

### CODE REVIEW

**Comment by baronfel** [comment]
@kasperk81 my best guess is that resources are slammed right now preparing for .NET 9 GA? I'll kick them and see if that helps.

**Review by baronfel — APPROVED** [review]
The content here seems fine - though without `dotnet sln add` and `dotnet sln remove` users won't be able to really do anything _useful_ with the slnx yet. That's fine, I just wanted to call it out for now.

Thank you for taking an interest in this @kasperk81!

**Comment by just-ero** [comment]
Will `slnx` become the default at some point?

**Comment by baronfel** [comment]
> saw same issue in #44481. it seems to be randomly filtering out some PRs and running for others

There's an infrastructure issue in AzDo that's being worked on right now. Will bump this as I know more.

**Comment by baronfel** [comment]
This LGTM, but I'm waiting for feedback from the VS Solution team about what they would like to call the two options for sln/slnx formats.

**Comment by baronfel** [comment]
Ok I have feedback from the VS team on their desired terminology for the sln/slnx choice help text.

@kasperk81 please use the phrases "Solution file" and "XML Solution file" instead of "Traditional solution file" and "XML-based solution file".  Other than that change this is good to go!

**Comment by baronfel** [comment]
Thanks for this @kasperk81!

**Pull request merged**
