### PR TITLE
[release/8.0.1xx] Add Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100 as a dependency 

### PR DESCRIPTION
**Pull request by dkurepa**
Add Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100 as a dependency and use its version for microsoft.net.workload.emscripten.current, since it stabilizes. Fixes: https://dev.azure.com/dnceng/internal/_build/results?buildId=2268247&view=logs&j=6781b346-0bd1-5062-714a-0158c8df1d42&t=28240f7a-11a7-53df-bdd9-fb54c991f1ba&l=589

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@dkurepa you have a few PRs targeting 8.0.1xx, are you prepping them for GA?

**Review by lewing — APPROVED** [review]
this is good to go now

**Comment by lewing** [comment]
I opened https://github.com/dotnet/sdk/pull/36340 with actual values now that there is a build

**Comment by marcpopMSFT** [comment]
@lewing is this needed for GA? CC @mmitche

**Comment by mmitche** [comment]
Appears to have already been integrated. Thanks @dkurepa for putting this up.

**Pull request closed without merging**
