### PR TITLE
Allow granular opt out of assembly info generation

### LINKED ISSUE #302: AssemblyInfo Generation conflicts with User specified AssemblyInfo
In investigating this issue: https://github.com/dotnet/cli/issues/4378

I found that in project.json, existing AssemblyInfo attributes are detected prior to assembly info generation by parsing all the source files in the project. Existing assembly info attributes are excluded from the generated file.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Compiler.Common/AssemblyInfoFileGenerator.cs#L23

This explains the duplicate assembly info issues in migrated projects. 

@eerhardt @nguerrera PTAL

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #302

### CODE REVIEW

**Comment by nguerrera** [comment]
Fix #302

**Comment by nguerrera** [comment]
@eerhardt @dsplaisted @dotnet/project-system Tests added. Ready for review.

**Comment by piotrpMSFT** [comment]
@nguerrera can this be merged?

**Comment by nguerrera** [comment]
Merging to unlock CLI work. I will address any feedback with a follow up PR.

**Pull request merged**
