### PR TITLE
Allow valid property combinations during build

### PR DESCRIPTION
**Pull request by agocke**
Currently building a project marked PublishSingleFile with either UseAppHost=false or no RuntimeIdentifier
produces an error. However, this should only be an error during publish.

### CODE REVIEW

**Review by mateoatr — APPROVED** [review]
LGTM

**Review by sbomer — APPROVED** [review]
Seems reasonable to me - what's the rationale for doing the check late vs early? The `PublishSingleFileRequiresVersion30 ` checks still happen early. Should those be moved too?

**Comment by agocke** [comment]
> what's the rationale for doing the check late vs early?

It's not really late vs. early, it's moving the check to `publish` instead of `build`. With this change, if you put `PublishTrimmed` into your project file, but don't put in a runtime identifier, you get an error during build. I don't think that's relevant, there's no need to have both at the same time.

> The PublishSingleFileRequiresVersion30 checks still happen early. Should those be moved too?

I think that makes more sense to stay. Target framework can't really change between build and publish and these settings are incompatible, so I think it's reasonable to provide the error as early as possible.

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
although it is better to move the whitespace changes to a separate commit

**Pull request merged**
