### PR TITLE
Backport System.CommandLine updates to 6.0.3xx

### PR DESCRIPTION
**Pull request by baronfel**
This is a cherry-pick of the `scl-update` branch from #23085 onto the `release/6.0.2xx` branch, per @dsplaisted's [question](https://github.com/dotnet/sdk/pull/23276#issuecomment-1008363313) on the Maestro update.

@dsplaisted I've cherry picked the commits here with `git cherry-pick e4873bb1ba..scl-update` to get the commits, but for purposes of this PR should they be squashed?

### CODE REVIEW

**Review by dsplaisted — DISMISSED** [review]
Per our discussion, we are going to target this to 6.0.3xx, so marking this as request changes.

**Comment by baronfel** [comment]
updated the baseline to 6.0.3xx, will handle conflicts locally

**Comment by marcpopMSFT** [comment]
@baronfel , I think you need to revert 23380 and then merge that in with this PR, correct?

**Comment by baronfel** [comment]
Yep, working on that over the course of the day.

**Comment by baronfel** [comment]
Alright, I've reverted #23380 and then cherry-picked the commits from this branch on top of that reversion. On my local host, there were virtually no differences to the S.CL-consuming files between these changes and this PR before the changes, and the majority of the changes between my local rebased branch and this PR were as a result of other MRs to the repo during this time. This is what we'd expect to see, since the goal was to rebase the work on top of the 6.0.3xx branch + reverting the revert. All of that is to say I'm fairly confident I didn't miss anything.

**Comment by baronfel** [comment]
All green! @dsplaisted is this good to merge now? Don't want to click the button without an approval.

**Comment by dsplaisted** [comment]
Yeah, I don't want to (re)-review all these changes, but if it's green I think we can go ahead and merge it!

**Pull request merged**
