### PR TITLE
Could not copy the file deps.json because it was not found. Microsoft.Common.CurrentVersion.targets

### PR DESCRIPTION
**Pull request by komdil**
This PR fixes issue: #17645

### CODE REVIEW

**Comment by BenVillalobos** [comment]
When investigating https://developercommunity.visualstudio.com/t/Could-not-copy-the-file-SomeFiledepsj/1380752 this solution actually resolved the issue. Not sure if it's the right path or why this PR is failing, but thought it was worth mentioning.

**Comment by komdil** [comment]
@BenVillalobos  That workaround does not work on my case. In my opinion, there should be another solution because it looks like a bug. It is working when I rebuild once, when I rebuild twice it is failing. I think there should be a small change somewhere, but I don't know where. 
Can someone review that PR: #14488. That PR fixes issue related to publishing project: #1675
Maybe we should add publish conditions or add another condition there?

**Comment by komdil** [comment]
@BenVillalobos  any comments?

**Comment by BenVillalobos** [comment]
@komdil I'm not familiar with the details of applying `_UseBuildDependencyFile`, but applying `UseCommonOutputDirectory` (as suggested in the original issue) worked as well and that seemed ideal for the scenario of multiple projects pointing to the same output directory.

**Comment by komdil** [comment]
> @komdil I'm not familiar with the details of applying `_UseBuildDependencyFile`, but applying `UseCommonOutputDirectory` (as suggested in the original issue) worked as well and that seemed ideal for the scenario of multiple projects pointing to the same output directory.

Unfortunately, `UserCommandOutputDirectory` not helped. I want to know why this issue is not marked as a bug. The reason is I am available to rebuild my solution only once and getting errors on rebuilding twice.  If my project configurations are wrong, why I am not getting these errors on the first time rebuilding?

**Pull request closed without merging**
