### PR TITLE
Update onelocbuild.yml

### PR DESCRIPTION
**Pull request by wli3**
For loc process

### CODE REVIEW

**Comment by jonfortescue** [comment]
LGTM. Make sure you disable it in main as well (as having them running simultaneously causes problems).

**Review by jonfortescue — APPROVED** [review]

**Comment by wli3** [comment]
@jonfortescue how to disable main?

**Comment by jonfortescue** [comment]
@wli3 make a PR to main commenting it out will work fine.

**Comment by wli3** [comment]
Like this https://github.com/dotnet/sdk/pull/20648

**Pull request merged**
