### PR TITLE
xlf: zh-Hant: update translation

### PR DESCRIPTION
**Pull request by pan93412**
Thanks to .NET Core development & localization team!

### CODE REVIEW

**Comment by tmeschter** [comment]
@jbaltus Can the Loc team take a look at these?

**Comment by tmeschter** [comment]
@pan93412 Thank you for the contribution. Due to the way we handle localization work, we can't always take direct updates to the .xlf files--your changes might be lost in the future. I've asked our localization team to take a look at your changes.

@wli3 FYI.

**Comment by pan93412** [comment]
> @pan93412 Thank you for the contribution. Due to the way we handle localization work, we can't always take direct updates to the .xlf files--your changes might be lost in the future. I've asked our localization team to take a look at your changes.
> 
> @wli3 FYI.

Ok. :) :ok_hand:

**Comment by janbaltus** [comment]
Master branch will be localized in following week.
We currently delivered release/3.1.2xx and file list was different compared to Master

**Comment by pan93412** [comment]
> Master branch will be localized in following week.
> We currently delivered release/3.1.2xx and file list was different compared to Master

BTW could I know anyway to contribute translation to Microsoft?

**Comment by janbaltus** [comment]
PR https://github.com/dotnet/sdk/pull/10695 addressed the unlocalized stgring issue for master branch.

Regarding contribution please log an issue if you spot incorrect translation.

**Comment by nguerrera** [comment]
Closing based on above. Thank you for your effort here nonetheless, and please do feel free to log issues about translations that can be improved.

**Pull request closed without merging**
