### PR TITLE
Check if publishaot is used

### PR DESCRIPTION
**Pull request by LakshanF**
Checks to see if users set the PublishAot property to true. This will allow us to see how often `nativeAOT` form factor will be used in development.

### CODE REVIEW

**Review by AntonLapounov — APPROVED** [review]

**Comment by agocke** [comment]
FYI @KathleenDollard

**Comment by marcpopMSFT** [comment]
Ok, with this change. You'll need to fix tests though.

**Review by richlander — APPROVED** [review]

**Comment by LakshanF** [comment]
Lost track of this PR :-(, need to check the failing test to investigate the RID issue that @baronfel mentioned

**Comment by LakshanF** [comment]
> 
> Once this is merged I'll get a docs update PR for the new property on the telemetry data deckarations.

cc @baronfel, this is merged now

**Comment by baronfel** [comment]
I did this in dotnet/docs#29354 a while back, anticipating this :)

**Pull request merged**
