### PR TITLE
Adding individual test reruns

### PR DESCRIPTION
**Pull request by sfoslund**
Depends on https://github.com/dotnet/arcade/pull/6545

### CODE REVIEW

**Comment by sfoslund** [comment]
@wli3 @marcpopMSFT do you have any thoughts on how you want to keep track of tests that are rerun? Right now I'm just writing the names and failures to a file.

**Comment by marcpopMSFT** [comment]
Not sure. I don't think our existing test infrastructure or pipelines has retries built in such that it would already have results storage.  Do other teams in dotnet retry tests and what do they do with the results?

**Comment by sfoslund** [comment]
I'm not aware of any other teams that retry tests. 

@wli3 do you have any feedback about this approach?

**Comment by wli3** [comment]
Sorry for the delay. You need to try to see if it will work after the helix merge. (although the second rerun could be on the host. It might work?) Could we do something in the test runner level? So test as tool will also benefit from it.

> I'm not aware of any other teams that retry tests.

All VS tests are being retried. And they can log it in azure devops.

> I'm just writing the names and failures to a file.

I don't think that's enough. I think the hard part of the work is logging the failure. Although we might use a new Nova instance to store that. Not sure it is the right use of the infra, but it is easy to send and easy to query. And we can put a powerbi dashboard over it. Although, it is also hard to collect all the information of the test failure (stack trace, error message, output to console).

Azure devops has a build in analyses, But we need to learn how to hook into it

**Comment by sfoslund** [comment]
> Could we do something in the test runner level?

I've done some research and haven't found a way to configure that with xunit on the command line. 

> Azure devops has a build in analyses, But we need to learn how to hook into it

It would be easy to upload both the original test run and test rerun results to azure devops using [this task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?tabs=trx%2Cyaml&view=azure-devops), which hooks into their test analysis. I can look into how well they handle that in their insights once I'm able to test in azdo, which requires getting the arcade side of this change in. 

If this approach sounds good to you then I'll make the arcade PR and start looking at how azure dev ops handles multiple test runs in their insights.

**Comment by wli3** [comment]
> looking at how azure dev ops handles multiple test runs in their insights

This should be done first. And I think it is the priority. I double Azure devops can distinguish them well. However, if we cannot analyze flaky tests. This feature will do more harm than good.

I do like the idea of making rerun part of the arcade.

**Comment by sfoslund** [comment]
@wli3 @marcpopMSFT I've experimented with azdo test analytics and I'm hoping to get some feedback on the [approach I'm trying out](https://github.com/dotnet/sdk/compare/sfoslund/TestReruns?expand=1). When tests fail and we want to rerun, I publish those test results as a second .xml/.html xunit result file (separate from the one we publish normal test results to). This gets it hooked into the azdo testing analytics and, since I'm publishing the rerun results under a different name from the original results, it allows us to easily filter to get analytics on only rerun tests.

For example, here's the analytics view for my test branch:
TestRerunAnalysis
I have 3 tests enabled on this run, one that always passes (so it doesn't show up on this page because it's never rerun), one that always fails (which is rerun on the 8 legs and fails on all of them) and one that passes ~50% of the time (so it is rerun on 4/8 legs and passes on rerun once). Since this is on a testing branch it only has results for one build but with the right filtering we would be able to use this to see which tests are rerun across all legs and all CI runs.

I'm still working on adapting this for helix, since it seems like helix test runs don't publish their results as artifacts. @wli3 how does helix hook into azdo test analysis?

**Comment by wli3** [comment]
For tests running on host. It is the same, just send the build log to the artifact log folder. For helix, I don't know exactly. I use [helix SDK from arcade](https://github.com/dotnet/arcade/tree/a7e68906fa4b7abab762213441a1bfb8dd500d2a/src/Microsoft.DotNet.Helix). And it handled it for me.

**Comment by wli3** [comment]
@alexperovich do you know?

**Comment by marcpopMSFT** [comment]
Interesting idea. I like the idea of being able to use AzDO built-in analytics. So are you basically forking off the failed results into a separate run store (as if it were it's own run) and rerunning in our live pipeline such that the resulting rerun results are published there?  So you have the main run that will include passing test results and all rerun results (pass or fail) and an alternate store that includes all the initial failed results?  

Would you push the rerun to both places so the analytics would combine both the first and second pass together?

**Comment by sfoslund** [comment]
> So you have the main run that will include passing test results and all rerun results (pass or fail) and an alternate store that includes all the initial failed results?

Not quite, all test results (main runs and reruns) will go to the same place but with different naming schemes that will allow us to filter for only main runs or only reruns or just view all data as we do now.

**Comment by wli3** [comment]
@sfoslund I think for helix you do need to find out how result is reported back. However, once you have the result, the second run don't need to be run on helix again, you can just run it in the host machine.

**Comment by alexperovich** [comment]
Helix reports the test results directly from the helix machine to azure pipelines. You could turn off that functionality, but then the xmls would need to be downloaded and handled manually. We do have built-in test retry planned as part of https://github.com/dotnet/arcade/issues/5963, but we haven't started prototyping yet.

**Comment by sfoslund** [comment]
Closing this PR as individual test reruns will be a built in feature in Arcade in .NET 6 timeframe.

**Comment by marcpopMSFT** [comment]
@alexperovich good to know.  Is the automatic rerun committed as part of upcoming arcade work and do you know what timeframe we should look for it in?

**Comment by alexperovich** [comment]
We are committed to improving our system's resiliency to transient failures. Re-running test failures is one of the ways we are currently thinking, but we are still in the planning/data collection phase.

**Pull request closed without merging**
