### PR TITLE
Merge remote-tracking branch 'origin/release/2.1' 

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
Running jobs with the updated netci in Jenkins currently. Will update once passing.

**Comment by tannergooding** [comment]
Windows jobs are failing due to a max path issue. I've pinged @mmitche about updating the images to enable long path support so that ZIP extraction doesn't fail in PowerShell (and so that long path opt-in functions elsewhere as well).

**Comment by mmitche** [comment]
I've enabled this in win2016-base to see what happens.  IMO though, the the base path is already pretty short and we shouldn't be relying on a non-default feature to make the CI work.  The target path has a bunch of elements in it that could probably be shorted:

D:\j\workspace\debug_windows_nt8a96f9d2\**artifacts\.dotnet**\**2.2.0-preview1-007460**\store\x64\netcoreapp2.0\microsoft.aspnetcore.server.kestrel.transport.abstractions\2.1.0-preview1-26623\lib\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll

**Comment by tannergooding** [comment]
> The target path has a bunch of elements in it that could probably be shorted

The path I gave is just one such example. There are other files in the ZIP which are just as long (possibly longer) and it is a continued risk moving forward (as more packages are placed in the SDK store, etc). So shortening the path may not fix the issue and even then, may only fix it temporarily.

Indeed, this only became a problem in this PR because additional dependencies were put in the ZIP (in 2.2) that extended the path past the previous max.

Enabling long paths prevents the needs for CI specific hacks/workarounds (such as using the explicit long path syntax or extracting to the root drive and then moving it to the correct location with robocopy).

**Comment by mmitche** [comment]
But that also means the build process cannot work ever on Win2012, or on any developer machine that doesn't have long paths enabled.  That's why I'm skeptical.

**Comment by tannergooding** [comment]
I think that is a more general problem and one that is going to be hit more and more frequently moving forward.

There are already very few [dotnet] repos for which I can enlist, restore, build, test, and then clean today (from the default enlistment directory VS sets up -- `%UserProfile%\source\repos`, and the default nuget cache location -- `%UserProfile%\.nuget\packages`) without having something fail due to max path (generally this is the nuget cache, but occasionally it is the actual build artifacts as well).

This is consistently only an issue in Windows (as the other systems don't have such limitations) and is generally worked around by moving the enlistment directory on the box or relying on some tool having opted-into long path support.

**Comment by tannergooding** [comment]
### CI Jobs
https://ci.dot.net/job/dotnet_sdk/job/release_2.0-ci/job/debug_osx10.12/14
https://ci.dot.net/job/dotnet_sdk/job/release_2.0-ci/job/debug_ubuntu14.04/15
https://ci.dot.net/job/dotnet_sdk/job/release_2.0-ci/job/debug_ubuntu16.04/15
https://ci.dot.net/job/dotnet_sdk/job/release_2.0-ci/job/debug_windows_nt/14
https://ci.dot.net/job/dotnet_sdk/job/release_2.0-ci/job/debug_windows_nt_fullframework/14

### Signed Build
20171207.2

**Review by dsplaisted — APPROVED** [review]

**Pull request merged**
