### PR TITLE
Don't automatically set Link metadata for items coming from Shared Projects

### PR DESCRIPTION
**Pull request by dsplaisted**
**Customer scenario**

Reference a Shared Project from an Sdk-style project.

**Bugs this fixes:** 

#1415 and dotnet/cli#7092

**Workarounds, if any**

Set the `SetLinkMetadataAutomatically` property to false

**Risk**

Low.

**Performance impact**

No.

**Is this a regression from a previous update?**

Yes, referencing shared projects was regressed by #1246

**Root cause analysis:**

With #1246, we automatically set `Link` metadata for items that are outside of the project folder.  Shared project references are implemented via importing the shared project's `.projitems` file in the referencing project, so automatically setting the `Link` metadata on these items caused them to also show up in the referencing project (as well as potentially change the path under the output they were copied to).  This change avoids setting the `Link` metadata for items coming from shared projects.

**How was the bug found?**

Customer report

### CODE REVIEW

**Comment by dsplaisted** [comment]
@livarcocc @davkean @srivatsn for review

@rainersigwald @cdmihai @AndyGerlicher This uses the `DefiningProjectExtension` metadata, which appears undocumented.  Is that OK?

**Review by livarcocc — APPROVED** [review]

**Comment by davkean** [comment]
We know what the exact overhead of this condition has? Property functions are pretty damn slow.

**Review by rainersigwald — APPROVED** [review]
> @rainersigwald @cdmihai @AndyGerlicher This uses the DefiningProjectExtension metadata, which appears undocumented. Is that OK?

I didn't know it existed which isn't ideal, but yeah, this is fine. We should document it: https://github.com/Microsoft/msbuild/issues/2336

**Comment by dsplaisted** [comment]
@dotnet-bot test Windows_NT Debug

**Comment by dsplaisted** [comment]
@davkean 

> We know what the exact overhead of this condition has? Property functions are pretty damn slow.

With the fix from https://github.com/Microsoft/msbuild/pull/2326, and the following project in a folder with 11,038 items:

```xml
<Project >
  <ItemGroup>
    <None Include="**\*" />

    <!-- This is the code the SDK uses to automatically add Link metadata -->
    <None Update="@(None)">
      <LinkBase Condition="'%(LinkBase)' != ''">$([MSBuild]::EnsureTrailingSlash(%(LinkBase)))</LinkBase>
      <Link Condition="'%(Link)' == '' And '%(DefiningProjectExtension)' != '.projitems' And !$([MSBuild]::ValueOrDefault('%(FullPath)', '').StartsWith($([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))))">%(LinkBase)%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>

  </ItemGroup>

  <Target Name="Build">
    <Message Text="Item count: @(None->Count())" Importance="high" />
  </Target>

</Project>
```

I get build times of about 1.1 seconds.  Without the code to automatically set the `Link` metadata, the build time is about 0.65 seconds.

**Comment by davkean** [comment]
@dsplaisted Can you capture me a trace via PerfView (default settings are fine)? I want to see where the cost is?

**Comment by dsplaisted** [comment]
@srivatsn for approval

**Comment by srivatsn** [comment]
Just to confirm - the original change wasn't ported to 1.1 right and this regression is only if the 2.0 SDK is installed?

**Comment by dsplaisted** [comment]
@srivatsn Correct, the auto-Link feature is not in 1.1

**Comment by davkean** [comment]
The overhead for property functions and the invokes are not cheap - in that trace you sent me there's ~16% of the allocations in the MSBuild process just in overhead (all the arrays, strings, etc that get created just parsing and invoking them) and 8% of CPU time dedicated to them - the actual time spent in the actual method you call is practically nothing. We should avoid property function/method functions where possible - if we're writing a lot of these - it sounds like we're missing MSBuild language features. @AndyGerlicher

**Comment by dsplaisted** [comment]
@davkean Note that the trace I sent was from the project I pasted earlier, where it doesn't import any common targets or do anything else but assign the metadata and count them.  So it may not be a realistic look at what the perf impact would be in a more real-world project.

**Pull request merged**
