### PR TITLE
ResolveReadyToRunCompilers: map non-portable rids when targetOS is determined.

### LINKED ISSUE #28312: crossgen2 doesn't resolve compilers for non-portable rids
I'm trying to make `runtime` repo build using artifacts produced for a non-portable rid in https://github.com/dotnet/runtime/pull/75597.

The build fails while trying to resolve the R2R compiler:

```
  13:47:14.530    19>Target "ResolveReadyToRunCompilers: (TargetId:2247)" in file "/home/tmds/sdk/sdk/7.0.100-rtm.22478.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets" from project "/home/tmds/tarball41/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj" (target "_PrepareForReadyToRunCompilation" depends on it):
                     Using "ResolveReadyToRunCompilers" task from assembly "/home/tmds/sdk/sdk/7.0.100-rtm.22478.1/Sdks/Microsoft.NET.Sdk/targets/../tools/net7.0/Microsoft.NET.Build.Tasks.dll".
                     Task "ResolveReadyToRunCompilers" (TaskId:1425)
                       Task Parameter:ReadyToRunUseCrossgen2=True (TaskId:1425)
                       Task Parameter:
                           TargetingPacks=
                               Microsoft.NETCore.App
                                       NuGetPackageId=Microsoft.NETCore.App.Ref
                                       NuGetPackageVersion=7.0.0-rtm.22465.3
                                       PackageConflictPreferredPackages=Microsoft.NETCore.App.Ref;Microsoft.NETCore.App.Runtime.fedora.36-x64
                                       PackageDirectory=/home/tmds/sdk/packs/Microsoft.NETCore.App.Ref/7.0.0-rtm.22465.3
                                       Path=/home/tmds/sdk/packs/Microsoft.NETCore.App.Ref/7.0.0-rtm.22465.3
                                       RuntimeFrameworkName=Microsoft.NETCore.App
                                       RuntimePackRuntimeIdentifiers=fedora.36-x64
                                       TargetFramework=net7.0
                                       TargetingPackFormat= (TaskId:1425)
                       Task Parameter:NETCoreSdkRuntimeIdentifier=fedora.36-x64 (TaskId:1425)
                       Task Parameter:
                           Crossgen2Packs=
                               Microsoft.NETCore.App.Crossgen2.fedora.36-x64
                                       NuGetPackageId=Microsoft.NETCore.App.Crossgen2.fedora.36-x64
                                       NuGetPackageVersion=7.0.0-rtm.22465.3
                                       OriginalItemSpec=Microsoft.NETCore.App.Crossgen2.fedora.36-x64
                                       PackageDirectory=/home/tmds/tarball41/src/runtime/artifacts/source-build/self/package-cache/microsoft.netcore.app.crossgen2.fedora.36-x64/7.0.0-rtm.22465.3 (TaskId:1425)
                       Task Parameter:
                           RuntimePacks=
                               Microsoft.NETCore.App.Runtime.fedora.36-x64
                                       FrameworkName=Microsoft.NETCore.App
                                       IsTrimmable=
                                       NuGetPackageId=Microsoft.NETCore.App.Runtime.fedora.36-x64
                                       NuGetPackageVersion=7.0.0-rtm.22465.3
                                       OriginalItemSpec=Microsoft.NETCore.App.Runtime.fedora.36-x64
                                       PackageDirectory=/home/tmds/tarball41/src/runtime/artifacts/source-build/self/package-cache/microsoft.netcore.app.runtime.fedora.36-x64/7.0.0-rtm.22465.3
                                       RuntimeIdentifier=fedora.36-x64 (TaskId:1425)
                       Task Parameter:PerfmapFormatVersion=1 (TaskId:1425)
                       Task Parameter:RuntimeGraphPath=/home/tmds/tarball41/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json (TaskId:1425)
  13:47:14.535    19>/home/tmds/sdk/sdk/7.0.100-rtm.22478.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(299,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [/home/tmds/tarball41/src/runtime/artifacts/source-build/self/src/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]

```

Looking at the code in `ResolveReadyToRunCompilers.cs`, it looks like `isSupportedTarget` will be `false` because `targetOS` is will be `null` for a non-portable rid:

https://github.com/dotnet/sdk/blob/b99ebbe963623467a37c327e2544af1381b1d2c3/src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs#L144-L162

cc @ViktorHofer @hoyosjs @AntonLapounov

How can we update this code so it works for non-portable rids?

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/sdk/issues/28312.

cc @AntonLapounov @ViktorHofer ptal.

### CODE REVIEW

**Review by AntonLapounov — APPROVED** [review]
Looks reasonable. Thank you!

**Comment by tmds** [comment]
The CI failure on Windows doesn't look related to this change.

**Comment by AntonLapounov** [comment]
All CI jobs must be green to merge a PR. I have restarted the failed leg.

**Comment by tmds** [comment]
CI is all green now.

**Comment by ViktorHofer** [comment]
Thanks a lot @tmds

**Comment by tmds** [comment]
@AntonLapounov @ViktorHofer can you initiate a backport of this PR to 7.0?

**Comment by AntonLapounov** [comment]
Do we use a /backport command or do it manually in SDK?  I guess we could use the template from #28380.  I know only that this is needed for source-build.

**Comment by ViktorHofer** [comment]
There is no backport command here, you would need to do it manually. Usually in the SDK, changes are applied to the lowest applicable branch and then bots will auto-flow them into the newer branches.

**Pull request merged**
