### PR TITLE
Insert NuGet Build 5.0.0-preview1.5366 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.0-preview1.5366 into sdk release/2.1.4xx branch

### CODE REVIEW

**Comment by nguerrera** [comment]
@mishra14 This is trying to insert a 5.0 nuget into our 2.1.4xx (15.8) branch.

**Review by nguerrera — CHANGES_REQUESTED** [review]
This is the wrong branch, and I don't think we have a right branch yet.

**Comment by mishra14** [comment]
@nguerrera Thanks for pointing that out. Do you have branches for dev16/3.0 yet?

cc: @jainaashish @nkolev92

**Comment by nkolev92** [comment]
@mishra14 
That was clarified in an e-mail. 

> We currently don’t have a specific CLI/SDK branch for dev16.

**Pull request closed without merging**
