### PR TITLE
Remove Unnecessary Check In RazorSourceGenerator Targets

### PR DESCRIPTION
**Pull request by lonitra**
Related: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1803616/

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

**Comment by davidwengier** [comment]
Guessing @chsienki is the authority on this.

**Review by jaredpar — CHANGES_REQUESTED** [review]
This does not feel like the right change.

**Comment by jaredpar** [comment]
Spent a bit of time digging into this scenario today. The two properties in question here:

- `$(BuildingInsideVisualStudio)` this will be true for any build that originates from Visual Studio: design time or real builds. 
- `$(DesignTimeBuild)` this will be true for design time builds only in SDK style projects.

Given that the condition as stated appears to be redundant given that the latter implies the former. Therefore we can remove this.

**Review by jaredpar — APPROVED** [review]

**Comment by DustinCampbell** [comment]
@jaredpar, would you prefer that we close this PR and file an issue to fix the SDK more thoroughly?

**Comment by jaredpar** [comment]
I'm good with either. I took a look around to see if there were any other `and` of these two values cause it seems suspicious. Found one in android but none other here.

**Comment by tmat** [comment]
This broke dotnet-watch Hot Reload. 

`dotnet watch` sets `/p:DesignTimeBuild=true` to build the app, but it does not maintain two kinds of solutions (design-time + compile-time) like VS does. Previously, even design time build run Razor source generator in dotnet watch. Now it does not because this condition was removed.

See https://github.com/aspnet/AspNetCore-ManualTests/issues/2029

**Pull request merged**
