### PR TITLE
Merge branch 'release/7.0.2xx' => 'main'

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@vlada-shubina I tried to resolve the conflict, Could you help to review them?

**Comment by GangWang01** [comment]
PR https://github.com/dotnet/templating/pull/5223 is not ported to templating release/7.0.2xx. It causes different behaviors when dealing with disabled parameters as we recently found.

We need to change the approvals for the following tests when merging into main branch.
```
        [Theory]
        [InlineData("TestAssets.TemplateWithConditionalParameters|--paramA|valA", "A")]
        [InlineData("TestAssets.TemplateWithConditionalParameters|--paramA|valA|--paramB|valB", "AB")]
        //[InlineData("TestAssets.TemplateWithConditionalParameters|--paramA|valA|--paramB|valB|--A_enabled", "AB")]
        public Task CannotInstantiateTemplate_WithDisabledParams(string parameters, string setName)
```
Approvals:
```
// value of paramA: placeholderA
// value of paramB: placeholderB
```
@vlada-shubina do we need to port PR https://github.com/dotnet/templating/pull/5223 to templating release/7.0.2xx and adjust the test to resolve this problem, or just adjust the test for SDK main branch?

**Comment by vlada-shubina** [comment]
> PR [dotnet/templating#5223](https://github.com/dotnet/templating/pull/5223) is not ported to templating release/7.0.2xx. It causes different behaviors when dealing with disabled parameters as we recently found.
> 
> We need to change the approvals for the following tests when merging into main branch.
> 
> ```
>         [Theory]
>         [InlineData("TestAssets.TemplateWithConditionalParameters|--paramA|valA", "A")]
>         [InlineData("TestAssets.TemplateWithConditionalParameters|--paramA|valA|--paramB|valB", "AB")]
>         //[InlineData("TestAssets.TemplateWithConditionalParameters|--paramA|valA|--paramB|valB|--A_enabled", "AB")]
>         public Task CannotInstantiateTemplate_WithDisabledParams(string parameters, string setName)
> ```
> 
> Approvals:
> 
> ```
> // value of paramA: placeholderA
> // value of paramB: placeholderB
> ```
> 
> @vlada-shubina do we need to port PR [dotnet/templating#5223](https://github.com/dotnet/templating/pull/5223) to templating release/7.0.2xx and adjust the test to resolve this problem, or just adjust the test for SDK main branch?

https://github.com/dotnet/templating/pull/5223 won't be ported to release/7.0.2xx, therefore please adjust the test.

**Comment by v-wuzhai** [comment]
@marcpopMSFT @dsplaisted It seems that some of the newly enabled test runs are failed in main.

**Comment by vlada-shubina** [comment]
@v-wuzhai I merged the fix prepared by @GangWang01. There were tests failures in his PR but I don't think they are related to fix, also same failures were observed in this PR. Please let me know if you need any other assistance from templating team.

**Comment by nagilson** [comment]
No, those failures seem related to something Marc was working on.

**Comment by v-wuzhai** [comment]
##[error]Unhandled: ENOSPC: no space left on device, open 'D:\a\_temp\.taskkey'

@marcpopMSFT There seems to be no real error. Could we force to merge?

**Comment by marcpopMSFT** [comment]
I believe @joeloff already fixed this in a different PR. I'll rerun to force a remerge.

**Comment by marcpopMSFT** [comment]
Disabled the four tests that were failing in the last run. @dsplaisted it doesn't look like I can make the cppcli tests work in main because the SDK expects one set of apphost/targeting packs from it's stage 0 version but a different verison of the runtime is installed. I could try overwriting the RuntimeFrameworkVersion but that doesn't affect the targeting packs. I could maybe add in an override for the targeting packs as well but it would be more involved as we don't have a simple way of overriding that.

**Comment by dsplaisted** [comment]
@marcpopMSFT  Are the projects for those tests using NuGet PackageReference support?  I believe that in that case it shouldn't matter whether the installed versions match exactly because it should download what it needs during restore.  We've probably never validated that since PackageReference support was added though, so there might be something we need to update to make it work.

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@dsplaisted good idea. I'll have to add an extra package reference to the project as the support doesn't work without it but that appears to unblock the tests. I'll do that as a separate PR and I'll also file an issue that cppcli package reference support should enable implicit apphost download without requiring an additional reference.

**Pull request merged**
