### PR TITLE
Remove PerfTrace Support

### LINKED ISSUE #14392: Remove PerfTrace.cs and everything related
https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/Microsoft.DotNet.Cli.Utils/Tracing/PerfTrace.cs

It is an old perf measure infrastructure. We no longer use it

### PR DESCRIPTION
**Pull request by brianrob**
Fixes #14392.

This shows up in some of the CLI performance analysis that I've done.  The cost is pretty low, but we don't need it anymore either.

### CODE REVIEW

**Comment by brianrob** [comment]
cc: @marcpopMSFT

**Review by wli3 — APPROVED** [review]
Thank you for help removing this!

**Comment by brianrob** [comment]
Thanks for the review @wli3!

**Comment by stephentoub** [comment]
Contributes to https://github.com/dotnet/msbuild/issues/5876

**Pull request merged**
