### PR TITLE
Stop defaulting NeutralLanguage

### LINKED ISSUE #382: Don't add NeutralResourcesLanguageAttribute to AssemblyInfo when no embedded resources are used
Currently, the generated AssemblyInfo will always include a `NeutralResourcesLanguageAttribute` by default. This is an issue when creating a minimum dependency package without using embedded resources (e.g. just referencing `System.Runtime` for `netstandard1.0` - see attached example). The approach of building packages/libraries with minimum dependencies is still recommended for targeting `netstandard` < 2.0.

Although it is totally possible to set the `GenerateNeutralResourcesLanguageAttribute` property to false, it isn't (yet) documented very visibly and not immediately obvious.

I feel that no dependency on `System.Resources.ResourceManager` should be required by default so I propose to not emit the attribute if no `EmbeddedResource` item exists. The `project.json` tooling also did not emit the attribute.

[example.zip](https://github.com/dotnet/sdk/files/585100/example.zip)

### LINKED ISSUE #410: ResourceManager can't find parent culture resources when built using csproj/msbuild
Moving https://github.com/dotnet/cli/issues/4781 on behalf of @ryanbrandenburg

----

## Steps to reproduce
1. Clone [this](https://github.com/ryanbrandenburg/ResourceManagerMsbuild) repo
2. Run the project.

## Expected  behavior
Finds the parent culture of "en" and outputs "key1 en" (this is confirmed to work with ".NET Command Line Tools (1.0.0-preview3-003770)" which still used project.json)

## Actual behavior
Unable to find parent culture, so A MissingManifest exception is thrown.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

### PR DESCRIPTION
**Pull request by nguerrera**
This can cause MissingManifestException if project doesn't have English neutral resources in main assembly, or incorrectly displaying non-English neutral resources to English end-user.

Fix #382
Fix #410 

@srivatsn @dsplaisted @davkean

### CODE REVIEW

**Comment by dsplaisted** [comment]
I noticed the following in the assembly info targets:

```xml
<AssemblyAttribute Include="System.Resources.NeutralResourcesLanguageAttribute" Condition="'$(NeutralLanguage)' != '' and '$(GenerateNeutralResourcesLanguageAttribute)'">
```

Is there a missing ` == 'true` in the condition?  The other assembly attribute items in the file include it.

Otherwise, LGTM.

**Comment by nguerrera** [comment]
@dsplaisted Hmm, yes, though we have test coverage for this and it seems to work as is. Amended to make it consistent with nearby checks nonetheless.

**Review by dsplaisted — APPROVED** [review]

**Comment by nguerrera** [comment]
@srivatsn, just confirming that we're good to start merging RC3 changes to master without tagging Matt. If so, I'll go ahead and merge this.

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
Go ahead

**Comment by hishamco** [comment]
@nguerrera is this solve the localization issue which I addressed [here](http://hishambinateya.com/neutralresourceslanguageattribute-doesn't-respect-localization-in-asp.net-core)

**Pull request merged**
