### PR TITLE
[release/6.0.x] Build Single-File for Windows 7

### PR DESCRIPTION
**Pull request by NN---**
Backport #23177

Related to: https://github.com/dotnet/runtime/pull/63533

### CODE REVIEW

**Comment by NN---** [comment]
@VSadov

**Review by agocke — APPROVED** [review]

**Comment by NN---** [comment]
@agocke Will you merge this PR today? Thanks.

**Comment by agocke** [comment]
That's the plan, I just need to confirm the schedule

**Comment by agocke** [comment]
Servicing was approved as part of https://github.com/dotnet/runtime/pull/63533

**Pull request merged**
