### PR TITLE
add Internal args to AOT tests

### PR DESCRIPTION
**Pull request by dkurepa**
This should fix https://dev.azure.com/dnceng/internal/_build/results?buildId=2301426&view=logs&j=e0ea1dd1-b56f-550d-c202-0c362938b47b&t=f171a33f-5a94-52fc-9bfb-a5e271e27b6b

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
Shouldn't the forward port merge bot take care of this?

**Comment by dkurepa** [comment]
I never used the bot, is there some reason to use it now instead of merging this PR?

**Comment by mmitche** [comment]
The forward port bot will take care of this, but it's green so I'll merge.

**Comment by mmitche** [comment]
The bot is automatic. For this repo it merges changes from lower branches up through main.

**Pull request merged**
