### PR TITLE
Obtain internal runtime SAS tokens via federated creds

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2482329&view=results test official build

**Comment by mmitche** [comment]
The docker images that this repo uses will need attention.

**Comment by MiYanni** [comment]
@mmitche AFAIK, the docker images don't have PowerShell. So, the `Generate delegation SAS Token` will always fail. For other Arcade scripts, there is a BASH version of the same thing. Does that exist for this?

**Comment by mmitche** [comment]
> @mmitche AFAIK, the docker images don't have PowerShell. So, the `Generate delegation SAS Token` will always fail. For other Arcade scripts, there is a BASH version of the same thing. Does that exist for this?

I've been adding powershell to the images and I find ones that don't have it.

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2486928&view=results has the latest updates here.

**Comment by mmitche** [comment]
Ready to go @MiYanni

**Review by MiYanni — APPROVED** [review]

**Pull request merged**
