### PR TITLE
Don't cloak the ANCM setup folder

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This is required for #44828

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by MichaelSimons** [comment]
Failing CI legs are unrelated and failing elsewhere.  Merging.

**Comment by premun** [comment]
@mthalman uncloaking does not synchronize it there, manual PR must be opened in the VMR directly with the contents that correspond to the SHA the repository is present in the VMR in

**Comment by MichaelSimons** [comment]
> @mthalman uncloaking does not synchronize it there, manual PR must be opened in the VMR directly with the contents that correspond to the SHA the repository is present in the VMR in

Is there a tracting issue to support this scenario?

**Comment by premun** [comment]
I don't think it was ever planned to be honest - adding exclusion rules also requires removal of the content.

We can log an issue but not sure we'd fund it as the exclusions is something we won't have going forward.
Do you think it would be a frequent scenario in servicing?

**Comment by premun** [comment]
Or.. do we want to have exclusions in the full flat VMR codeflow?

**Comment by MichaelSimons** [comment]
We are still going to need/want exclusions going forward IMO.  I agree updating them is an uncommon code flow.  I guess I am looking for a better UX.  Today there is continuous uncertainty on what steps are needed as evidence here.

**Comment by premun** [comment]
I will log an issue. We will have a new person starting soon so this looks like a good candidate for an intro issue.

**Comment by mthalman** [comment]
@jkoritzinsky - You'll need to follow the [guidance above](https://github.com/dotnet/sdk/pull/44857#issuecomment-2476901822) to make this available in the VMR.

**Comment by ViktorHofer** [comment]
just FYI, @jkoritzinsky is out for a few days

**Comment by premun** [comment]
I created https://github.com/dotnet/arcade-services/issues/4152 but during writing it realized it might be quite a problematic one

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/dotnet/pull/110. PTAL

**Pull request merged**
