### PR TITLE
skip CanSortByDownloadCountAndThenByName because it's blocking

### PR DESCRIPTION
**Pull request by baronfel**
We'll want to backport this to all the other branches that are blocked once merged.

### CODE REVIEW

**Review by nagilson — APPROVED** [review]

**Comment by nagilson** [comment]
dear lord we have a lot of branches

**Comment by lewing** [comment]
Looking at the history it appears the name comparer used in the test was changed a few days ago but the name by name assertion doesn't use the same ellipsis logic to handle shortened names.

**Pull request merged**
