### PR TITLE
[24068] Remove Legacy -- behavior and use of UnparsedTokens

### PR DESCRIPTION
**Pull request by Tunduk**
@baronfel Hi! I messed up with branches a little, so here is a new PR. Sorry for this, I'll be more careful in next time. 
[Link](https://github.com/dotnet/sdk/pull/25854) for history

### CODE REVIEW

**Comment by Tunduk** [comment]
@baronfel 
Could you help me, please? On my local PC `Microsoft.DotNet.Tools.Tool.Install` is passed ok.
Am I doing something wrong?

**Comment by baronfel** [comment]
@Tunduk looks like flakiness on those tests in the CI environment. I've seen the same recently. I restarted the 2 failed runs.

**Comment by baronfel** [comment]
Alright! @marcpopMSFT this is good to merge, I've done all the local testing I was concerned about.

**Comment by marcpopMSFT** [comment]
@baronfel can you click the approve button so when I merge and everything breaks, I have a paper trail back to you? :P

**Review by baronfel — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
Thank you for your contribution!

**Comment by baronfel** [comment]
And thank you for sticking with it @Tunduk!

**Comment by baronfel** [comment]
@Tunduk it looks like this may have regressed `dotnet test` a bit (see the linked microsoft/vstest issue). I'm going to dig into it a bit today and see if I can determine the cause.

**Comment by nagilson** [comment]
This is the first time I've seen @marcpopMSFT  use `:P` and I am very intrigued. More importantly, I don't see the issue attached in reference to this:
> see the linked microsoft/vstest issue

Was it this? https://github.com/microsoft/vstest/issues/4014

**Pull request merged**
