### PR TITLE
Only show VS workload list header on windows

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Review by joeloff — APPROVED** [review]
I assume if we have data to add we'd do that conditionally as well when the header is added

**Comment by sfoslund** [comment]
> I assume if we have data to add we'd do that conditionally as well when the header is added

Yup, I believe so.

**Comment by KalleOlaviNiemitalo** [comment]
Is Visual Studio for Mac able to install .NET SDK workloads? If it is, does `dotnet workload list` display those?

**Comment by sfoslund** [comment]
> Is Visual Studio for Mac able to install .NET SDK workloads? If it is, does dotnet workload list display those?

Yes, VS for mac will also be able to install workloads but due to differences in the way those experiences are implemented, workload list can show the workloads installed via VS for mac but not VS on windows.

**Pull request merged**
