### PR TITLE
Implicitly define compilation constants for target framework

### LINKED ISSUE #195: We should inject implicit TFM DefineConstants
In project.json-based projects, we had automatic defines injected for the TFM. So if I was building for netstandard1.3, there was an implicit define #NETSTANDARD1_3 that I could automatically use in a #if.

We should add this into the dotnet/sdk as well, so developers can easily write code for specific TFMs.

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #195

The project.json based .NET CLI tooling puts underscores in place of periods in the version numbers for some framework identifiers (`NETSTANDARD1_3`), but not others (`NETCORE45`).  It also uses `NET` as an abbreviation for `.NETFRAMEWORK`.

Here I've simply defined all possibilities, so a library targeting .NET 4.6.1 will have these defines: `NET461`, `NETFRAMEWORK461`, and `NETFRAMEWORK4_6_1`.  A library targeting .NET Standard 2.0 will have `NETSTANDARD20` and `NETSTANDARD2_0` defined.

I also haven't yet figured out a good way to test this.  It gets tested incidentally as part of the preserve compilation context tests.  To directly test it I'd like to be able to build a project and get the list of compilation constants that were used.  Possible ways of doing this could be to parse the log file (ugh!) or to evaluate the project with the MSBuild APIs and get the value of the `DefineConstants` property.

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
:shipit:  After @nguerrera chimes in on the naming of the boolean to control the logic.

**Review by nguerrera — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by dsplaisted** [comment]
@dotnet-bot test this please

**Comment by dsplaisted** [comment]
@dotnet-bot test Windows_NT Debug please

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
Sheesh, was trying to close and reopen to get Jenkins going and there's no reopen button. :(

**Comment by nguerrera** [comment]
@dsplaisted I think this is because your fork hasn't been recreated after the repo went public. It didn't show when I selected "compare across forks" in an attempt to open a replacement PR on your behalf. Can you fix that up and re-submit? Sorry.

**Comment by livarcocc** [comment]
Please, re-submit.

**Pull request closed without merging**
