### PR TITLE
Add tests for disabling JsonSerializer.IsReflectionEnabledByDefault on `PublishTrimmed=true`

### LINKED ISSUE #84378: Disable JsonSerializer.IsReflectionEnabledByDefault on `PublishTrimmed=true`
>Have we decided we want this to be defaulted to `off` only when `PublishAot=true`? Or do we think we should go as far as turning it off by default when `PublishTrimmed=true`?
>
>For the ASP.NET feature switch, [we had it for both](https://github.com/dotnet/sdk/blob/e0390ce4ef21db0205cf0b16ffb93a5b659c64b4/src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L51). But I'm a little concerned about making the switch for `PublishTrimmed` at the bottom of the stack. It is a breaking change. If we do this, we will need to update Maui and Blazor WASM SDKs to turn it back `on`.
>
>We don't need to block this PR on the decision. For ASP.NET, we can just switch our SDK to change `EnsureAspNetCoreJsonTrimmability` => `JsonSerializerIsReflectionEnabledByDefault` once this is merged, and can react as changes happen.

_Originally posted by @eerhardt in https://github.com/dotnet/runtime/pull/83844#discussion_r1158727295_

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fix https://github.com/dotnet/runtime/issues/84378

cc @eerhardt @rolfbjarne @jonathanpeppers

### CODE REVIEW

**Comment by eerhardt** [comment]
The current feature switches that get set when `PublishTrimmed=true` is actually contained in dotnet/runtime:

https://github.com/dotnet/runtime/blob/d52b3038cd19aab5b95be4f1c76010b91dd07429/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets#L34-L47

Thoughts on putting this one there instead to keep them all in one place?

I think the reason they are in dotnet/runtime is because they version with the runtime version. So if you target net7.0, you get a different set than if you target net8.0.

cc @sbomer @vitek-karas

**Comment by eiriktsarpalis** [comment]
Does Microsoft.NET.ILLink.targets get included when you run build targets?

**Comment by eiriktsarpalis** [comment]
One more question -- can we set up testing in runtime or should I just make the change there and merge the sdk tests once this repo has absorbed the changes?

**Comment by eiriktsarpalis** [comment]
Given https://github.com/dotnet/runtime/pull/88480 was merged I've updated this PR to only include the tests. Will merge once an up-to-date built is absorbed and tests are passing.

**Comment by eerhardt** [comment]
Can you remove this line as part of this change?

https://github.com/dotnet/sdk/blob/9a98699c69098715dd2cb25858e53d06b936ef66/src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L49-L52

**Comment by eiriktsarpalis** [comment]
I could -- just to confirm, is it guaranteed `PublishAot == true` always implies `PublishTrimmed == true`?

**Comment by eerhardt** [comment]
> I could -- just to confirm, is it guaranteed `PublishAot == true` always implies `PublishTrimmed == true`?

Currently, yes I believe this is true. @MichalStrehovsky and @agocke can confirm. If we ever change that, we would change all the feature switches we default when PublishTrimmed=true to also check for PublishAot.

**Comment by vitek-karas** [comment]
> I could -- just to confirm, is it guaranteed PublishAot == true always implies PublishTrimmed == true

Currently it probably is... but please don't rely on it. We're discussing setting `PublishAot=true` even on mono AOTed apps, and I think mono has some cases where it can do AOT without trimming, in which case it should probably not set `PublishTrimmed=true`. Regardless, you should not make that assumption anyway. If the feature is incompatible with trimming (for example has RequiresUnreferencedCode somewhere) and independently also incompatible with AOT (for example has RequiresDynamicCode somewhere) then you should condition it on both.

**Comment by eiriktsarpalis** [comment]
@vitek-karas this suggests to me that we should update Microsoft.NET.ILLink.targets in runtime to also condition the feature switch on `PublishAot == true`. @eerhardt thoughts?

**Comment by vitek-karas** [comment]
I think the answer is "yes it should be", but the question is where. Currently the `ILLink` targets only handle trimming. We have a different set of targets for AOT. So maybe this should also be in the AOT targets as well. It would then probably also belong here: https://github.com/dotnet/runtime/blob/36481bfd079093fe7d29ef024b1fb801e6c787fe/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L36C7-L42
@MichalStrehovsky ?

**Comment by eerhardt** [comment]
I'm fine with defaulting `JsonSerializerIsReflectionEnabledByDefault` to `false` for both PublishTrimmed and PublishAot. This switch affects both trimming and AOT - it guards code that is both RequiresUnreferencedCode and RequiresDynamicCode.

**Review by eerhardt — APPROVED** [review]
LGTM

**Pull request merged**
