### PR TITLE
Move test templates to SDK repo

### LINKED ISSUE #44416: Move test templates to SDK repo
As of today, the [test-templates](https://github.com/dotnet/test-templates/tree/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0) repository is hosting test related templates.

I would like to suggest to move these templates directly to the SDK repository for the following benefits:

- these templates are only inserted into SDK
- simplify codeflow graph (reduce need for insertions and intermediate packages)
- help us moving towarded archivig this repo
- simplify handling the versions (we currently have -rtm suffix as we don't do any special final build before insertion)

I also think this is aligned with the idea of having test as core feature of the SDK.

Note that the test team is already working on SDK repo (for issues related to `dotnet test`, insertion of `test-templates` and `vstest`) so this would not complexify handling on our side.

I have already discussed offline with @marcpopMSFT about this idea.

cc @nohwnd @mariam-abdulla @pavelhorak @baronfel

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #44416

### CODE REVIEW

**Comment by Evangelink** [comment]
@marcpopMSFT I don't know if you have some acceptance tests that check the template can be created and if they automatically run all templates?

**Comment by marcpopMSFT** [comment]
@Evangelink search through this file to see if we're targeting the specific templates that were moved over: https://github.com/dotnet/sdk/blob/release/9.0.2xx/test/EndToEnd.Tests/ProjectBuildTests.cs#L342

I guess there's nothing that confirms it's using the templates you're inserting here versus some other version of the templates (say the stage 0 version). You'd have to review the binlog to confirm that I think.

**Comment by Evangelink** [comment]
@dotnet/templating-engine-maintainers This is ready for review. 

There are many basic tests, it might be worth to add more for specific feature for test projects but we didn't have them previously so I don't think it should prevent merging.

**Comment by marcpopMSFT** [comment]
Did you confirm manually that the new templates are getting picked up in the zip and other installs? Can you add an update to the codeowners file?

Not sure what else we'd be reviewing here.

**Comment by Evangelink** [comment]
Templates are correctly included:

image

image

but it made me realize that I need to update code so we stop using/packing the test template:

image

**Comment by Evangelink** [comment]
Now it should be all good @marcpopMSFT

**Comment by Evangelink** [comment]
@marcpopMSFT I'd appreciate if we could move forward this PR because it's now causing conflicts every time the current templates gets inserted.

**Comment by Evangelink** [comment]
ping @dotnet/templating-engine-maintainers

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@Evangelink sorry if I wasn't clear before. I reviewed the changes outside of the templates themselves hence my two suggestions above. I've signed off now but I didn't review anything in the templates themselves.

**Review by nohwnd — APPROVED** [review]
LGTM, I assume you copied the added files from test-templates, and the modified files look correct to me.

**Review by mariam-abdulla — APPROVED** [review]

**Pull request merged**
