### PR TITLE
Reincorporating add package suggestions

### LINKED ISSUE #15013: "dotnet add package Micr" tab completion doesn't work in .NET 6
As I'm trying to get better understanding of how tab completion is working, I noticed that in master build of sdk "dotnet add package Micr" tab completion doesn't work anymore.
Method [QueryNuGet](https://github.com/dotnet/sdk/blob/5e440989fcadb67a4f91dc4da993c85c927e4be5/src/Cli/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs#L71) is not called anymore.

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/15013

This is not a new addition, suggestions were lost when I switched to using system.command line in #14379 and I'm adding them back here. I added a test in this PR to ensure suggestions are not empty.

### CODE REVIEW

**Comment by aortiz-msft** [comment]
Could you please add a PR description including what the change is and how it was validated?

**Review by aortiz-msft — CHANGES_REQUESTED** [review]
Please add a PR description. I have added @dominoFire who owns the CLI for NuGet.

**Comment by sfoslund** [comment]
Sure, just updated the description.

**Comment by sfoslund** [comment]
Not sure why the test is failing occasionally unless we're QueryNuGet is failing. @dominoFire it looks like there aren't retries or anything, so do you think we need to have this test and if so is there a way to make it more reliable?

**Comment by dominoFire** [comment]
> Not sure why the test is failing occasionally unless we're QueryNuGet is failing. @dominoFire it looks like there aren't retries or anything, so do you think we need to have this test and if so is there a way to make it more reliable?

@sfoslund There's a good chance for flakiness in `NuGetProvidesSuggestionsForAddPackages` test, since it depends on an external service (nuget.org).

My recommendations are:

1. Disable the test and create a follow up issue to test the whole command.
2. Add a test for AddPackageParser.QueryNuGet()
3. Refactor `AddPackageParser.QueryNuGet()`  to include an injectable NuGet endpoint
4. Create a temporary mocked http server to test the functionality.

Happy to discuss.

**Comment by sfoslund** [comment]
@dominoFire thanks for taking a look, that test was added in this PR so if you think it's unnecessary I can definitely remove it. Since I didn't make any changes to QueryNuget itself I'm not sure I have a sufficient understanding to test it.

I think it's probably fine to remove this test and make this change without any test coverage, this issue only appeared because we completely switched out the parser which hopefully won't happen again for a long time :)

**Comment by dominoFire** [comment]
@sfoslund I'm OK with removing the test (`NuGetProvidesSuggestionsForAddPackages`). Don't forget to create a follow-up issue.

**Review by dominoFire — APPROVED** [review]

**Comment by sfoslund** [comment]
@aortiz-msft does anyone else need to review this PR or are we good to merge?

**Comment by dominoFire** [comment]
Tested by hand with `dotnet complete`. It works

**Comment by aortiz-msft** [comment]
> @aortiz-msft does anyone else need to review this PR or are we good to merge?

I think we are good from our side. Thanks for checking.

**Pull request merged**
