### PR TITLE
[release/7.0.2xx] Revert hot reload script injection response buffering

### PR DESCRIPTION
**Pull request by MackinnonBuck**
## Summary

Fixes a regression in memory consumption caused by large responses when debugging with hot reload enabled.

## Description

As one of the changes introduced in .NET 7 by https://github.com/dotnet/sdk/pull/27537, the hot reload script injection middleware now buffers the entire response before performing script injection. This was done to improve script injection reliability, but we recently began receiving reports from customers that were confused by the increase in server memory usage for large responses when debugging with hot reload is enabled.

This PR reverts the buffering behavior but keeps the logging improvements that help customers identify the cause of script injection failures and take steps to fix them.

For .NET 8, we will assess an alternative approach to improve script injection reliability that doesn't involve buffering each response.

## Validation

Manual validation + existing automated tests for this scenario.

## Risk

Low. This PR simply reverts the offending commit and adds back some of the improved logging behavior with no other changes to functionality.

Fixes https://github.com/dotnet/aspnetcore/issues/45037

### CODE REVIEW

**Comment by javiercn** [comment]
@MackinnonBuck sounds good.

Could you file an issue to revisit this in .NET 8.0? We should consider avoiding the script injection magic in favor of referencing the file in the document directly somehow.

**Review by javiercn — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
Are we clear to merge this?

**Comment by mkArtakMSFT** [comment]
Hi @marcpopMSFT. Can this be merged or should @MackinnonBuck wait for some green light from you?

**Comment by mkArtakMSFT** [comment]
Talked to @marcpopMSFT - the branch is open to merge.

**Pull request merged**
