### PR TITLE
Consolidate WebSDK into SDK

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
Some changes in the transition that may need tweaks:
- The license the head of websdk was apache, sdk has MIT. Fine?
- net46 targets of publish tasks were changed to net472 to match SDK. This is because the msbuild packages in SDK do not allow net46 targets. @vijayrkn indicates this is fine.

SDK layout is identical to old layout after this change.

**Comment by vijayrkn** [comment]
Thank you @mmitche for taking care of this.

**Comment by mmitche** [comment]
@vijayrkn I'm going to redo this a bit after https://github.com/dotnet/websdk/pull/1496 gets merged. I want to preserve the history in the merge and there are sopme failures that were fixed in p6 that didn't get merged into master.

**Comment by mmitche** [comment]
Closing in favor of #11914

**Pull request closed without merging**
