### PR TITLE
Insert NuGet Build 4.6.0-rtm-4862 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.6.0-rtm-4862 into sdk release/2.1.1xx branch

### CODE REVIEW

**Comment by jainaashish** [comment]
@livarcocc Can you help merge this PR?

**Comment by rohit21agrawal** [comment]
@livarcocc what's the issue here? anything we can do to help?

**Comment by livarcocc** [comment]
@rohit21agrawal this PR should have a CLI version with matching version to the SDK. So, whatever is causing the break here may very well be a legitimate break. Could you take a first pass at investigating?

**Comment by rohit21agrawal** [comment]
this is the error on Jenkins:

```
D:\j\workspace\debug_windows---c0500355\artifacts\.dotnet\2.1.100-preview-007341\sdk\2.1.100-preview-007341\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ConflictResolution.targets(58,5): error : Framework list file path 'v4.0.30319\RedistList\FrameworkList.xml' is not rooted. Only full paths are supported. [D:\j\workspace\debug_windows---c0500355\src\Tasks\Microsoft.NET.Build.Tasks\Microsoft.NET.Build.Tasks.csproj] [C:\Users\dotnet-bot\.nuget\packages\roslyntools.repotoolset\1.0.0-beta-62519-01\tools\Build.proj]
```

I don't think NuGet does anything with this file.

**Comment by livarcocc** [comment]
@dsplaisted can you take a look? Any idea how a NuGet insertion could break this?

**Comment by livarcocc** [comment]
Actually, I see this failing for the same reason here as well: https://github.com/dotnet/sdk/pull/1908.

**Comment by rohit21agrawal** [comment]
@livarcocc any update on this?

**Comment by nguerrera** [comment]
Replaced by #1947

**Pull request closed without merging**
