### PR TITLE
Workaround for VersionOption initializing to null on Mono.

### PR DESCRIPTION
**Pull request by tmds**
This is a workaround to stop the dotnet cli from throwing ArgumentNullException with Mono runtime as reported in https://github.com/dotnet/sdk/issues/41672.

If possible, we'd like this to be part of the upcoming preview6.

@lambdageek ptal

cc @Swapnali911 @uweigand @omajid

### CODE REVIEW

**Comment by tmds** [comment]
@marcpopMSFT can this be merged so it makes it into preview 6?

**Review by baronfel — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
> @marcpopMSFT can this be merged so it makes it into preview 6?

Unfortunately, we already snapped for p6 and I'm being told they do not want more changes coming in for p6 unless absolutely blocking. I'm not sure this is blocking in a common enough scenario.

**Comment by tmds** [comment]
It's not a blocker. I wasn't aware of the exact timing so I tried get it merged in case the branch was still open.

**Comment by marcpopMSFT** [comment]
> It's not a blocker. I wasn't aware of the exact timing so I tried get it merged in case the branch was still open.

I'm not sure we have the precise timing of previews documented anywhere but we've been trying to snap the branch around the third week of each month (it happened Thursday last week though had already been delayed by a day). That's when all changes are supposed to be in but there's usually a couple of days for codeflow and catching up last minute PRs. They are trying to prep an initial candidate p6 build later today for testing per my understanding. I usually disable tooling codeflow around the same time as the first candidate build and treat all PRs from then on out as approval-only.

**Comment by tmds** [comment]
Can this be merged?

**Comment by marcpopMSFT** [comment]
> Can this be merged?

Thanks for the reminder and thanks for the contribution!

**Pull request merged**
