### PR TITLE
AuthHandshakeMessageHandler: sync behavior with other clients.

### LINKED ISSUE #43319: Unable to authenticate against the OpenShift internal registry using a token.
The .NET SDK can't authenticate against the OpenShift image when the `auth.json` has an `auth` that starts with `<token>:`.

This case is treated special here:

https://github.com/dotnet/sdk/blob/3390aa48419e70e714ce0504983afc166e598644/src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs#L321-L323

The use of the `Bearer` scheme is causing the authentication to fail. When I change it to `Basic` (that is: removing the special case) then the authentication works.

With podman debug logging, there is a single GET call to the realm uri. I assume it immediately goes for the Basic auth.
```
DEBU[0000] GET https://<registry>/v2/ 
DEBU[0000] Ping https://<registry>/v2/ status 401 
DEBU[0000] GET https://<registry>/openshift/token?account=%3Ctoken%3E&scope=repository%3Atdeseyn-dev%2Fdotnet-runtime%3Apull 
DEBU[0000] Increasing token expiration to: 60 seconds   
DEBU[0000] GET https://<registry>/v2/tdeseyn-dev/dotnet-runtime/manifests/8.0 
```

@baronfel can we make the .NET 9 SDK capable of supporting this scenario by also trying basic auth for `<token>`? I can work on a PR.

For .NET 10, perhaps we can take a closer look at how `docker` and `podman` do the auth and try to mimic their behavior?

cc @omajid

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/sdk/issues/43319

- Removes the special handling of the '\<token>' username. This value is used as a sentinel from credential-helper scripts/programs. It is already handled by the docker-creds-provider .NET library.

- When there is no identity token, use the username/password with Basic auth.

### CODE REVIEW

**Comment by tmds** [comment]
@baronfel ptal. This is my understanding of the desired behavior after reading through some of the other clients code.

I am going to do some validation. I wanted to make a PR already to get early feedback.

I will include some tests when we settled on the behavior.

**Comment by tmds** [comment]
I've added a test that mocks the server behavior.

Compared to the `main` branch, there are two functional changes:

- There is no longer any special handling of the `<token>` username. What happens in https://github.com/mthalman/docker-creds-provider/blob/e4dd7658b589a4771b3ceb1c8b1b0c3de343f476/src/Valleysoft.DockerCredsProvider/NativeStore.cs#L60-L64 should be enough. `<token>` only has a special meaning when returned from a credential helper script/program.

- When we have a username/password for Bearer, previously those would be used with OAuth password_grant and then fall back to use Basic auth. This matches the behavior of regclient. I have swapped the order because I see both podman and docker do Basic auth.

**Comment by baronfel** [comment]
THANK YOU for the tests here - that's making it much easier to debug and reason about.

**Comment by tmds** [comment]
> I can't test this against baronfel/sdk-container-demo because this is targeted at main and the package produced has assembly load issues on a 9 SDK.

I can target the 9.0 branch, if that helps for verification?

**Comment by baronfel** [comment]
That would be incredibly helpful. If testing passed we were going to try to backport the fix to 9 anyway.

**Comment by tmds** [comment]
The PR is now targeting the 9.0 branch.

**Comment by baronfel** [comment]
I still couldn't get the package to work due to assembly loading problems with runtime-provided dependencies, but from local publishing I tested this with:
* ACR
* AWS ECR
* Github Packages

and all of those work well. I'm assuming you've tested with OpenShift as well @tmds?

**Comment by tmds** [comment]
Thanks for veryfing with those registries!

I verified this fixes the issue with the OpenShift registry (https://github.com/dotnet/sdk/issues/43319), and also checked docker.io and quay.io.

**Comment by tmds** [comment]
I've changed the target branch back to main.

Sorry for code view requests, it is out of my control.

**Review by baronfel — APPROVED** [review]

**Comment by baronfel** [comment]
The one test failure here is the crypto 'no more endpoints' known build error, not relevant to this PR.

**Comment by baronfel** [comment]
@tmds it looks like the full-framework test leg is consistently failing, can you take a look?

**Comment by tmds** [comment]
@baronfel I don't see anything other than the mentioned "_There are no more endpoints available from the endpoint mapper._" in the Azure CI. Do you see something different in some log/artifact?

I haven't tried to reproduce the issue by running the full-framework tests because I don't have a Windows machine.

**Comment by baronfel** [comment]
Oh, in that case that's fine. This error has been _endemic_ recently :(

**Comment by tmds** [comment]
> This error has been endemic recently :(

I skimmed through https://github.com/dotnet/dnceng/issues/3844 and it may not be fixed soon.

Does it affect many tests besides `RegistryTests.InsecureRegistry`?

If you need to continuously manually filter these out, it may be worth either skipping tests (under a limited set of conditions), or catching the exception and allowing the test to pass at that point.

**Comment by baronfel** [comment]
Just awaiting review - we can trigger the backport for sure!

**Comment by baronfel** [comment]
@dotnet/product-construction had to rerun this PR due to this leg, I was told to ping you as this happens.

**Review by MichalPavlik — APPROVED** [review]

**Pull request merged**
