### PR TITLE
Insert NuGet Build 4.9.0-preview5.5630 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.9.0-preview4.5552 into sdk release/2.1.5xx branch

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT_FullFramework Release

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX10.12 Release

**Comment by livarcocc** [comment]
Flakiness on jenkins.

@dotnet-bot Test OSX10.12 Release
@dotnet-bot Test Windows_NT_FullFramework Debug

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Debug

**Review by nguerrera — APPROVED** [review]

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX10.12 Release

**Comment by livarcocc** [comment]
@dotnet-bot Test OSX10.12 Release

**Pull request merged**
