### PR TITLE
Adding CredScanSuppressions.json under the .config directory to suppress false positives

### PR DESCRIPTION
**Pull request by vijayrkn**

### CODE REVIEW

**Comment by vijayrkn** [comment]
@dsplaisted - Do you think it is still worth adding this change to the repo to keep track of the suppressions?

**Comment by dsplaisted** [comment]
> @dsplaisted - Do you think it is still worth adding this change to the repo to keep track of the suppressions?

I don't have context on what this is for or why it would be needed.

**Comment by vijayrkn** [comment]
> I don't have context on what this is for or why it would be needed.

To avoid checkins like these - https://github.com/dotnet/sdk/commit/a8b9dbba01e64cf9036d397b3bf0adf63e9ef3e9

**Comment by dsplaisted** [comment]
I made that commit at @MattGal's request, but don't understand exactly what the problem was.

If @MattGal or someone else who has context on the issue thinks this is a good idea, then feel free to go ahead and merge.

**Comment by MattGal** [comment]
> I made that commit at @MattGal's request, but don't understand exactly what the problem was.
> 
> If @MattGal or someone else who has context on the issue thinks this is a good idea, then feel free to go ahead and merge.

I don't feel strongly, but my opinion is to not make the JSON file.  Not having it does mean if the commit history is ever lost then that will trigger Credscan again on push to relevant AzDO remote, and the JSON file does leave a place to put comments about _why_ a seemingly secret value was left in the source, but the odds of history being lost for this repo are quite low as is the cost of reviewing then suppressing it one more time.

**Comment by vijayrkn** [comment]
>I don't feel strongly, but my opinion is to not make the JSON file.

Personally I am fine either way. Since this is not a required at this point, I will abandon this PR and we can revisit this if needed in the future.

**Pull request closed without merging**
