### PR TITLE
delete nonexistent feeds

### PR DESCRIPTION
**Pull request by kasperk81**
from ci:

```

C:\h\w\B4440955\w\A54F0946\e>dotnet nuget remove source dotnet6-internal-transport --configfile C:\h\w\B4440955\t\dotnetSdkTests\udyk1dp3.krc\nuget.config 
error: Unable to find any package source(s) matching name: dotnet6-internal-transport.


Usage: dotnet nuget remove source [arguments] [options]

Arguments:
  name  Name of the source.

Options:
  --configfile  The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help     Show help information
```

### CODE REVIEW

**Comment by baronfel** [comment]
> > from ci:
> > 
> > ```
> > 
> > C:\h\w\B4440955\w\A54F0946\e>dotnet nuget remove source dotnet6-internal-transport --configfile C:\h\w\B4440955\t\dotnetSdkTests\udyk1dp3.krc\nuget.config 
> > error: Unable to find any package source(s) matching name: dotnet6-internal-transport.
> > 
> > 
> > Usage: dotnet nuget remove source [arguments] [options]
> > 
> > Arguments:
> >   name  Name of the source.
> > 
> > Options:
> >   --configfile  The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
> >   -h|--help     Show help information
> > ```
> 
> ux nit: this kind of error should not print usage. if the error relates to "unknown option" only then it makes sense to print usage (or simply `use --help to find more info`)
> 

Totally agree with this nit - unfortunately we'll need to do a little digging to see if nuget itself is printing the usage or if that's being added by the SDK CLI in our generic error handler middleware. 

Would you mind writing up an issue for this?

**Comment by marcpopMSFT** [comment]
I believe that our internal codeflow PRs automatically add these two "nonexistent" feeds. They just aren't available publicly. Not sure if there's a way for us to condition the removal to only internal builds.

CC @mmitche ?

**Comment by mmitche** [comment]
> Not sure we have the ability to read a passed in switch in these particular helix launch files. They are run on the helix machines so it would need to be an environment variable we could detect for internal versus public.

It does look like those scripts do get passed some parameter:

```
src/Tests/UnitTests.proj:      <HelixPreCommands Condition="!$(IsPosixShell)">call %HELIX_CORRELATION_PAYLOAD%\t\RunTestsOnHelix.cmd $(TestFullMSBuild);$(HelixPreCommands)</HelixPreCommands>
```

So you can probably add another based on whether to clean out feeds. Alternatively, maybe you could pipe the command output to null?

**Comment by marcpopMSFT** [comment]
@kasperk81 thoughts on the options Matt suggested since this is your PR? Those feeds do exist in our internal builds and part of the goal of removing them was to reduce friction we've seen with Azdo in the past where we query too frequently and get throttled (2k packages downloaded during our tests times 20 feeds is a lot of Azdo queries per leg).

piping the output of those lines to null would probably be the simpler change that trying to include another input argument.

**Pull request closed without merging**
