### PR TITLE
Update NuGet to 4.3.0-preview2-4082

### PR DESCRIPTION
**Pull request by natidea**
**Customer scenario**

Update SDK to the preview2 version of NuGet to unblock changes in https://github.com/dotnet/sdk/pull/1228
This change also consumes a 1.1.0 version of the CLI and makes infrastructure fixes due to breaking changes in the NuGet insertion

**Other Details**

Regular code flow

/cc @livarcocc @dsplaisted

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]
Looks good, but it looks like we need to use a different download script or pass different parameters to it to be able to successfully download this version of the CLI.

**Comment by natidea** [comment]
We built the wrong defn for the CLI. The correct one is running now, after which I will rerun all the tests

**Comment by natidea** [comment]
@dotnet-bot retest this please

**Comment by livarcocc** [comment]
@MattGertz merging since this is just flowing dependencies.

**Pull request merged**
