### PR TITLE
update nuget to 4.0.0-rtm-2323

### PR DESCRIPTION
**Pull request by rohit21agrawal**
Approved by shiproom via PR 58262

CC: @rrelyea @srivatsn

### CODE REVIEW

**Comment by srivatsn** [comment]
@rohit21agrawal master is no longer the RTM branch. We're locked down for RTM. Does this update need to happen for RTM? Resetting SDK now resets the CLI as well.

**Comment by srivatsn** [comment]
@rohit21agrawal I have retargeted the PR to dev15.0.x but you'll have to rebase your branch against dev15.0.x to avoid pulling in post RTM commits.

**Comment by rohit21agrawal** [comment]
@srivatsn done.

**Review by natidea — APPROVED** [review]

**Comment by natidea** [comment]
/cc @MattGertz for Escrow
Ask Mode Template: [387440](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/387440)

**Comment by srivatsn** [comment]
We've decided to not take this change.

**Comment by srivatsn** [comment]
Retargeted to master.

**Pull request merged**
