### PR TITLE
Update to the 8.0.7 July release

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
I think this requires the internal to public merge for 8.0.3xx to get in and then flow. CC @ericstj

**Comment by ericstj** [comment]
> I think this requires the internal to public merge for 8.0.3xx

Yeah, you need the changes that we made to SDK in 8.0.3xx, you could just cherry-pick those commits to this PR.

**Comment by ericstj** [comment]
Linking that PR - https://github.com/dotnet/sdk/pull/42075

**Review by ericstj — APPROVED** [review]
LGTM.  I audited for any other instance of pinning JSON.  I found these two:
https://github.com/dotnet/sdk/commit/d2cbbe1a2a1f4be1f103306ae1799ce86b5a782a

Those stay at 8.0.0 because they need to load whichever version VS provides.  VS will update separately.  I bet that these are going to cause some warnings (CG or NuGet) even though we don't ship the vulnerable lib.  That's unfortunate.  Would be nice to solve that with "host library targeting" story.  cc @ViktorHofer @baronfel

**Pull request merged**
