### PR TITLE
Insert NuGet Build 5.1.0-rtm.5921 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.1.0-rtm.5921 into sdk release/2.1.7xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
@nguerrera @dsplaisted 
This insertion contains the PackageDownload, FrameworkReference work.

**Comment by nguerrera** [comment]
Same here. Is this for 16.1 P1 or P2?

**Comment by nkolev92** [comment]
Yeah, all of them are P2.

**Review by nguerrera — CHANGES_REQUESTED** [review]
Waiting for branch to open for P2

**Comment by zivkan** [comment]
This PR is superseded by #3106. Please close this one.

**Pull request closed without merging**
