### PR TITLE
Remove old source-build controls

### PR DESCRIPTION
**Pull request by mmitche**
Remove parameters and environment vars passed in VMR builds that activate old arcade source build control paths.

### CODE REVIEW

**Comment by mmitche** [comment]
This will not work until various control updates have been completed.

**Review by NikolaMilosavljevic — APPROVED** [review]

**Comment by mmitche** [comment]
Needs at least the arcade update, which fixes the symbol store issues.

**Comment by mmitche** [comment]
Resolves https://github.com/dotnet/source-build/issues/3951

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
This can now be closed.

**Pull request closed without merging**
