### PR TITLE
Append hosting startup variable to existing variable if set 

### PR DESCRIPTION
**Pull request by shirhatti**
Porting https://github.com/dotnet/sdk/pull/15450 to master

### CODE REVIEW

**Comment by jkotalik** [comment]
If you get the chance, test this on both Windows an Linux (WSL is fine).

**Review by jkotalik — APPROVED** [review]

**Review by pranavkm — APPROVED** [review]

**Comment by shirhatti** [comment]
@jkotalik Will check before merging

**Comment by shirhatti** [comment]
Something in the process hierarchy is unsetting the DOTNET_STARTUP_HOOKS environment variable:

```
(1) "C:\Users\shirh\.dotnet\tools\zocket.exe"
  └── (2) "dotnet" watch run 
    └── (3) "C:\Users\shirh\source\repos\sdk\artifacts\bin\redist\Debug\dotnet\dotnet.exe" C:\Users\shirh\source\repos\sdk\artifacts\bin\redist\Debug\dotnet\sdk\6.0.100-dev\DotnetTools\dotnet-watch\6.0.100-dev\tools\net6.0\any\dotnet-watch.dll run
      └── (4) "C:\Users\shirh\source\repos\sdk\artifacts\bin\redist\Debug\dotnet\dotnet.exe" run
        └── (5)"C:\Users\shirh\source\temp\web50\bin\Debug\net5.0\web50.exe"
```

In my example, `DOTNET_STARTUP_HOOKS` is correctly set at step (2), but not at step (3)

**Comment by shirhatti** [comment]
Any ideas on what could be happening?

**Comment by jkotalik** [comment]
You using the right version of dotnet watch built here? That's the only thing I can think of.

**Comment by shirhatti** [comment]
Yeah.

This works
✔: `zocket "dotnet run C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\DotnetTools\dotnet-watch\6.0.100-dev\tools\net6.0\any\dotnet-watch.dll watch"`

This doesn't
❌: `zocket "dotnet watch"`

**Comment by shirhatti** [comment]
Ignore my previous comments. This change works fine, `zocket` was busted- https://github.com/shirhatti/zocket/blob/main/src/ReloadIntegration/ReloadHostingStartup.cs#L98-L109

**Comment by shirhatti** [comment]
While it's good to merge now, I realized that this fix isn't the most robust.

It's merging the existing environment variable with user supplied one

```csharp
var existing = Environment.GetEnvironmentVariable(envVarName);

if (!string.IsNullOrEmpty(existing))
{
    return $"{existing}{separator}{envVarValue}";
}
else
{
    return envVarValue;
}
```

However, if another `IWatchFilter` or `DotNetWatcher` itself had modified the same environment variable in `context.ProcessSpec`, it'll get clobbered. 

@pranavkm Do you want that fixed or is it good to merge as is knowing the limitation?

**Pull request merged**
