### PR TITLE
Revert #699

### LINKED ISSUE #783: Clean up from multi-targeting SDK tasks
#762 switched to multi-targeting our SDK tasks for .NET Standard and .NET Framework.  There are some cleanup items we should do that we didn't do at the time in order to reduce churn and risk:

- Remove System.Security.Claims.dll, System.Security.Principal.Windows.dll, and System.Xml.ReaderWriter.dll [from tools\net46 in the SDK layout](https://github.com/dotnet/sdk/blob/a4b62ccc2e41893ae7804b97c500dee56d5458fc/build/Nuget/Microsoft.NET.Sdk.Nuget.targets#L53-L67).  These were dependencies for the .NET Standard version of the tasks that should not be needed anymore, but were left in at the time just to be safe.
- We are excluding the Roslyn assemblies and their dependencies [from the SDK layout](https://github.com/dotnet/sdk/blob/a4b62ccc2e41893ae7804b97c500dee56d5458fc/build/Nuget/Microsoft.NET.Sdk.Nuget.targets#L118-L127).  We no longer reference Roslyn at all in our tasks, so we can delete this.
- In #699, we tried to work around assembly loading issues by avoiding running any of our tasks before NuGet restore.  Since we've addressed the underlying assembly loading issue, we can simplify our code by going back to a single target that checks for implicit package overrides

### PR DESCRIPTION
**Pull request by dsplaisted**
In #699, we tried to work around assembly loading issues by avoiding running any of our tasks before NuGet restore. Since we've addressed the underlying assembly loading issue, we can simplify our code by going back to a single target that checks for implicit package overrides

Resolves #783

### CODE REVIEW

**Comment by dsplaisted** [comment]
Since by default we implicitly run restore before build, with these changes if you have an override of an implicit package reference and do `dotnet build`, you'll get the warning message twice, once from restore and once from build:

> C:\git\dotnet-sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(198,5): warning : A PackageReference for 'Microsoft.NETCore.App' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\git\dotnet-sdk\artifacts\Debug\tmp\OverrideImplicit\OverrideImplicit.csproj]
> C:\git\dotnet-sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(198,5): warning : A PackageReference for 'Microsoft.NETCore.App' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\git\dotnet-sdk\artifacts\Debug\tmp\OverrideImplicit\OverrideImplicit.csproj]

Is it worth trying to avoid this duplicate warning? @nguerrera @livarcocc @peterhuene

**Comment by dsplaisted** [comment]
It turns out that we are now already running `CheckForImplicitPackageReferenceOverrides` before `CollectPackageReferences`, so even without this change you get the duplicate warnings.  So I think this PR doesn't affect behavior, it just deletes useless code.

**Comment by livarcocc** [comment]
Do we have an issue for the duplicate message? I think it is at least worth tracking, but I would like to have it fixed as well.

**Comment by dsplaisted** [comment]
How would we fix the duplicate warning?  The only way I can think of is to not generate the warning when running the restore operation.  That would mean you wouldn't get a warning if you just did `dotnet restore`, which is probably OK.

If that's worth doing then I think we can probably lump the change in with this PR.

Thoughts? @livarcocc @nguerrera

**Review by nguerrera — APPROVED** [review]

**Comment by dsplaisted** [comment]
Per discussion with @livarcocc, I'm just going to punt the duplicate warning issue (without filing a follow-up issue).

**Pull request merged**
