### PR TITLE
Include CodeStyle targets files even when not enforcing code style in build

### PR DESCRIPTION
**Pull request by mavasani**
Please see the PR description in https://github.com/dotnet/roslyn/pull/72238#issue-2150902975, which gives a background on this fix. This change along with that Roslyn PR is needed for fixing the regression in https://github.com/dotnet/roslyn/issues/72094

### CODE REVIEW

**Review by sharwell — APPROVED** [review]

**Review by arunchndr — APPROVED** [review]

**Comment by arkalyanms** [comment]
@marcpopMSFT this one blocks another change we might need to present to servicing - https://github.com/dotnet/roslyn/pull/72238. Could we get an approval from your side and merge?

**Comment by baronfel** [comment]
@dsplaisted / @joeloff any problems with merging this one?

**Review by joeloff — APPROVED** [review]

**Comment by joeloff** [comment]
After reading the issue/comments that were linked, this seems to be something we need. Is this only applicable to newer versions or will these need to be ported to older releases of the SDK as part of servicing?

**Comment by mavasani** [comment]
> After reading the issue/comments that were linked, this seems to be something we need. Is this only applicable to newer versions or will these need to be ported to older releases of the SDK as part of servicing?

Basically any backport of the Roslyn change will be a no-op in VS unless the underlying SDK installed has this change. So, if we are backporting the Roslyn change to VS 17.10, we want to at least backport this SDK change into whichever .NET SDK version is installed as part of  17.10

**Comment by cremor** [comment]
> So, if we are backporting the Roslyn change to VS 17.10, we want to at least backport this SDK change into whichever .NET SDK version is installed as part of 17.10

I'd have hoped that this is released as a VS 17.9.x bugfix?

**Review by MiYanni — APPROVED** [review]

**Comment by mavasani** [comment]
> > So, if we are backporting the Roslyn change to VS 17.10, we want to at least backport this SDK change into whichever .NET SDK version is installed as part of 17.10
> 
> I'd have hoped that this is released as a VS 17.9.x bugfix?

Tagging @arkalyanms. I believe this will depend on how many users are hitting this, but I am fine if we feel this should be backported to 17.9. https://github.com/dotnet/roslyn/issues/52991#issuecomment-1960692440 has suggestions on how to clean up your editorconfig to avoid hitting this case

**Comment by mavasani** [comment]
Can someone please help me with the unrelated build failure on this PR?

**Comment by baronfel** [comment]
This test has been failing consistently across a number of branches - I believe we have a team member trying to root cause it currently.

**Comment by mavasani** [comment]
> This test has been failing consistently across a number of branches - I believe we have a team member trying to root cause it currently.

@baronfel Can this PR be merged overriding the failing test leg?

**Comment by dsplaisted** [comment]
> @baronfel Can this PR be merged overriding the failing test leg?

I am investigating the failing test, but if we can consider disabling the test if we need to get this PR merged quickly.  That would be preferrable to having the test consistently failing.

**Comment by mavasani** [comment]
> > @baronfel Can this PR be merged overriding the failing test leg?
> 
> I am investigating the failing test, but if we can consider disabling the test if we need to get this PR merged quickly. That would be preferrable to having the test consistently failing.

I think that might help as we are considering backporting this fix. I'll let @arkalyanms make a call a here.

**Pull request merged**
