### PR TITLE
"Cherry pick main changes""

### PR DESCRIPTION
**Pull request by marcpopMSFT**
Reverts dotnet/sdk#19979

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
I mistakenly thought this was ready and merged it to unblock the nuget flow.  Reverted and sent this out to bring the change back.  It breaks a single test though unclear why:
d:\repos\sdk\artifacts\tmp\Debug\It_publishes_---F395A6ED\bin\Debug\net6.0-windows\win10-x64\publish>dotnet It_publishes_---F395A6ED.dll
Unhandled exception. System.Windows.Markup.XamlParseException: 'Initialization of 'It_publishes____F395A6ED.MainWindow' threw an exception.' Line number '11' and line position '7'.
 ---> System.PlatformNotSupportedException: System.Windows.Extensions types are not supported on this platform.
   at System.Xaml.Permissions.XamlAccessLevel.AssemblyAccessTo(Assembly assembly)
   at System.Windows.SystemResources.ResourceDictionaries.LoadDictionary(Assembly assembly, String assemblyName, String resourceName, Boolean isTraceEnabled, Uri& dictionarySourceUri)
   at System.Windows.SystemResources.ResourceDictionaries.LoadThemedDictionary(Boolean isTraceEnabled)

**Comment by wli3** [comment]
The merge looks alright https://github.com/dotnet/sdk/pull/19985

**Review by wli3 — DISMISSED** [review]
The CI looks good so far

**Comment by wli3** [comment]
So I think this is no longer needed?

**Comment by wli3** [comment]
Update stage 0 - see how that goes

**Comment by marcpopMSFT** [comment]
Same test failed even with the stage 0 update. One thought is that WD just flowed through as it was behind so maybe we try updating stage 0 again once we have an installer build that has the newer version of WD runtime (if we think that's the issue)

**Comment by wli3** [comment]
WPF fail caused by https://github.com/dotnet/wpf/issues/5144

**Pull request merged**
