### PR TITLE
Support automatic Link metadata for Page and Resource items

### LINKED ISSUE #2697: Automatic Link generation from LinkBase does not work for Page, Resource items
(Filing bugs from my notes after customer visit exploring porting large WPF app to .NET core 3)

This:
``` xml
<ItemGroup>
  <Page Include="..\X\**\*.xaml"  LinkBase="Y" />
</ItemGroup>
```

Does not work as it does for Compile, EmbeddedResource, AdditionalFiles, EmbeddedResource:

https://github.com/dotnet/sdk/blob/9543229b2d30f4c712846540e725014754229919/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L201-L246

This has two consequences:

1. It prevents the easy way of getting these files outside project cone to show in sln explorer
2. Xaml interpretation can actually change based on the Link so the impact of not generating a Link as expected can change the application behavior. I forget the details here, but I observed this in customer app.

I'm unsure if the WindowsDesktop SDK should be handling it or if we should add to above. We probably need to do this for Resource items as well.

cc @dsplaisted @vatsan-madhavan

### PR DESCRIPTION
**Pull request by dsplaisted**
Fix #2697

### CODE REVIEW

**Comment by dsplaisted** [comment]
@vatsan-madhavan

**Comment by vatsan-madhavan** [comment]
Does this have the potential to decouple `Foo.xaml` and `Foo.xaml.cs` in the VS UI? 

For eg, will this impact the `DependentUpon` relationship between a `Compile` item and a `.xaml` file in the UI?

**Comment by dsplaisted** [comment]
> Does this have the potential to decouple `Foo.xaml` and `Foo.xaml.cs` in the VS UI?
> 
> For eg, will this impact the `DependentUpon` relationship between a `Compile` item and a `.xaml` file in the UI?

@davkean @drewnoakes Can you comment on this?

**Comment by davkean** [comment]
This doesn't affect items in the project cone and only affects those files outside of the project that have opt'd into LinkBase. I would expect that nesting still kicks in, even in that case.

**Comment by vatsan-madhavan** [comment]
thx - lgtm!

**Pull request merged**
