### PR TITLE
Update Fedora and Ubuntu CI legs to latest

### PR DESCRIPTION
**Pull request by MichaelSimons**
Related to https://github.com/dotnet/source-build/issues/4399 and https://github.com/dotnet/source-build/issues/4301

Updated Fedora 39 to 40
Update Ubuntu 22.04 to Ubuntu 24.04

### CODE REVIEW

**Review by ellahathaway — CHANGES_REQUESTED** [review]
The build leg names [here](https://github.com/dotnet/sdk/blob/b21c4dd17b4dc32d1ac374f588996da1e939f799/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L49), [here](https://github.com/dotnet/sdk/blob/b21c4dd17b4dc32d1ac374f588996da1e939f799/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L56), and [here ](https://github.com/dotnet/sdk/blob/b21c4dd17b4dc32d1ac374f588996da1e939f799/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L63)will also need to be updated.

**Comment by MichaelSimons** [comment]
> The build leg names [here](https://github.com/dotnet/sdk/blob/b21c4dd17b4dc32d1ac374f588996da1e939f799/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L49), [here](https://github.com/dotnet/sdk/blob/b21c4dd17b4dc32d1ac374f588996da1e939f799/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L56), and [here ](https://github.com/dotnet/sdk/blob/b21c4dd17b4dc32d1ac374f588996da1e939f799/src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml#L63)will also need to be updated.

I factored out all distro versions into variables with versionless names.  Next time, we should only have to update one file.  We still have an outstanding issue regarding the artifacts rids and the prep script but I am declaring that beyond the scope of this PR (tracked with https://github.com/dotnet/source-build/issues/4301).

**Comment by MichaelSimons** [comment]
@ellahathaway - Because of the state of the SDK Diff pipeline, I was only able to validate the yml syntax was correct.  Is that sufficient or is there a simple way to run the pipeline on main?

**Comment by MichaelSimons** [comment]
Test build - https://dev.azure.com/dnceng/internal/_build/results?buildId=2453928&view=results (internal Microsoft link)

**Review by ellahathaway — APPROVED** [review]
> Because of the state of the SDK Diff pipeline, I was only able to validate the yml syntax was correct. Is that sufficient or is there a simple way to run the pipeline on main?

Unfortunately, there isn't an easy way to do this. At one point, I had an Azdo branch with changes that allowed the pipeline to run against main, but it's currently out of date. If you think it'd be useful to have, I can update it. Otherwise, the changes you've made LGTM.

**Pull request merged**
