### PR TITLE
Fix the parsing of ContainerImageTags to report invalid tags instead of silently swallowing them.

### PR DESCRIPTION
**Pull request by baronfel**
Fixes part of #37610 

## Description

Users can customize container images generated for a project in a number of ways. One of the most common is setting a custom tag, which is often a semantic label like `latest` for convenience, or a specific version number for reproducibility. It's very common for multiple tags to point to the same logical image, so the SDK tooling provides the `ContainerImageTags` MSBuild property to enable this behavior. An example of this might be

```terminal
$ dotnet publish -p:PublishProfile=DefaultContainer -p ContainerImageTags="'\"3.1.2;latest\"'"
```
However this encoding of an MSBuild semicolon-delimited property value is incorrect - MSbuild will parse it into an Item like `'\3.1.2` - no `latest` tag at all, at least on Windows with Powershell.

Each image tag is intended to be validated before the image generation process continues, but due to a bug in boolean logic the validation checks were never reported to the user, and image creation always continued regardless of success.

This PR fixes the validation checks so that they log MSBuild errors as intended, preventing user confusion around tag values.

## Customer Impact 

When users built containers with invalid tag names (either through providing bad values or incorrect MSBuild property escaping on the CLI) the containers would be built with empty tags, which for most container registries corresponds to the `latest` tag.

## Regression
**Yes,** this regressed in 7.0.300 and a user report of a related issue brought it to our attention

## Risk
Low - the fix is very obvious and we have new test coverage to prevent regressions in this area

## Testing
An automated test that validates that corrupt tag names like users sometimes pass via CLI mangling are caught and the build correctly errors.

### CODE REVIEW

**Review by MichalPavlik — APPROVED** [review]

**Comment by baronfel** [comment]
This regressed in 7.0.300 - we should consider backports.

**Comment by baronfel** [comment]
Approved by tactics over email.

**Comment by baronfel** [comment]
backports to 8.0.1xx, 7.0.4xx, and 7.0.3xx are created and will merge upon code review approval.

**Pull request merged**
