### PR TITLE
Insert NuGet Build 4.4.0-preview1-4434 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.4.0-preview1-4434 into sdk release/2.0-vs branch

### CODE REVIEW

**Comment by jainaashish** [comment]
CC @dsplaisted @nguerrera @livarcocc

**Comment by rohit21agrawal** [comment]
@dotnet-bot test Ubuntu16.04 Release please

**Comment by rohit21agrawal** [comment]
@dotnet-bot test 
Windows_NT Debug please

**Comment by wli3** [comment]
@rohit21agrawal our test are looking for nspec, and it is moved, I am fixing the test

**Comment by rohit21agrawal** [comment]
@wli3 i already fixed the tests

**Comment by wli3** [comment]
@rohit21agrawal ah, great

**Comment by wli3** [comment]
@rohit21agrawal  looks good. But due to the circular dependency we need to wait for the build of https://github.com/dotnet/cli/pull/7499 and insert it into SDK

**Comment by rohit21agrawal** [comment]
i dont think we need to update it every single time.. only when there are breaking api changes in NuGet... is that correct @nguerrera  ?

**Comment by nguerrera** [comment]
Talked offline, we're just going to do it to ensure there are no version mismatches. Sometimes they don't cause issues, but we still need the copies of nuget dlls in the SDK to match the CLI when we ship. Doing it every time makes sure we don't get it wrong. Counting the days until there's just one repo for both and this just goes away. :)

**Comment by wli3** [comment]
@nguerrera @dsplaisted @johnbeisner FYI i update DotnetCLIVersion to a version that has the new nuget but failed to upload to nuget feed

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
@MattGertz FYI this is discussed nuget version flow to SDK

**Pull request merged**
