### PR TITLE
[release/5.0.3xx] Fix WAP proj problem by removing reliance on Microsoft.NET.Sdk.targets

### LINKED ISSUE #17711: The "ProcessFrameworkReferences" task was not given a value for the required parameter "RuntimeGraphPath".
In Visual Studio 16.10 Preview 4, (with the included .NET Sdk 5.0) we are getting an error when packaging an MSIX with the Windows Application Packaging project (WAP).  

Error	MSB4044	The "ProcessFrameworkReferences" task was not given a value for the required parameter "RuntimeGraphPath".	WapProjTemplate1	C:\Program Files\dotnet\sdk\5.0.300-preview.21258.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	63	

We started seeing the failure the when I created a shim target to pull in the Microsoft.NET.Sdk.targets into the WAP build pipeline in order to properly populate the newly supported dependency tree node.

One of the targets inadvertently pulled in, Microsfot.NET.Sdk.FrameworkResolution.targets,  which calls the ProcessFrameworkReferences task, requires a RuntimeGraphPath to be passed in resulting in the error.

The error doesn't block packaging since the target isn't actually needed to build and package the WAP.

However, it is blocking CI scenarios, test scenarios, etc.

In April, I fixed the issue by importing only the targets that we needed, rather than importing all of them through the Microsoft.NET.Sdk.targets file.

This fix has made it into .NET6.0-preview5x.

We would like the dotnet team to cherry-pick this fix into .NET5.0x an insert into VS for 16.10.

PR:   https://github.com/dotnet/sdk/pull/17042
Commit hash:  151f7629b8057569168798cfda5e1e10aee5fb74

### PR DESCRIPTION
**Pull request by edwardskrod**
Fix #17711

### Description
Over the last few months, the Modern Apps team in Visual Studio worked to add a Dependencies tree into Windows Application Packaging Projects.  One of the challenges was to figure out which .Net Sdk targets were necessary to populate the tree with data.

In #15462, I created a shim in order to import the Microsoft.NET.Sdk.targets for the purpose. I chose this .target because it referenced all the other targets that were necessary to support the feature.

This introduced a bug, however.  ProcessFrameworkReferences calls the task by the same name and requires a RuntimeGraphPath property which we don’t supply.

The following error is generated:

`Error MSB4044 The "ProcessFrameworkReferences" task was not given a value for the required parameter "RuntimeGraphPath". WapProjTemplate1 C:\Program Files\dotnet\sdk\5.0.300-preview.21258.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets 63`

### Customer Impact
The error is blocking CI scenarios, test scenarios, and any scenario where a build error will block. 

The error doesn't block packaging since the target isn't actually needed to build and package the WAP.

### Regression?
 

- [x] Yes
- [ ] No

 
Regressed from 5.0.2xx.

### Risk

- [ ] High
- [x] Medium
- [ ] Low

I would argue that the risk is medium.  We are already running this change in .NET 6.0 Preview 5 with no issues.  Furthermore, it looks like there are no differences between the changes to .NET 6.0 Preview 5 and this backport.  That being said, there are always risks to a code change like this,.

### Verification

- [x] Manual (required)  (Tested against WinForms (.NETCore and .NETFramework), WPF (.NETCore and .NETFramework) in multiple configurations)
- [x] Automated

Added a Windows Application Packaging Project test.

Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

Addresses #17711
https://github.com/dotnet/sdk/issues/17711

* Pulled the needed targets from Microsoft.NET.Sdk.targets so that we don't unnecessarily reference targets, tasks and properties that WAP doesn't need.

### CODE REVIEW

**Comment by sfoslund** [comment]
@dsplaisted @edwardskrod 5.0.301 branding has been merged, is there anything else we were waiting for with this PR?

**Comment by edwardskrod** [comment]
> @dsplaisted @edwardskrod 5.0.301 branding has been merged, is there anything else we were waiting for with this PR?

Nope.  This one is ready to go.

**Comment by sfoslund** [comment]
@dsplaisted I don't see any issues with this PR but I don't know the details, can you please review? Has this change been approved by tactics?

**Comment by edwardskrod** [comment]
> @dsplaisted I don't see any issues with this PR but I don't know the details, can you please review? Has this change been approved by tactics?

I'm drafting an email to tactics now.  I'll cc you.

**Comment by dsplaisted** [comment]
Here's the PR where this was merged into 6.0: #17042

**Review by dsplaisted — APPROVED** [review]

**Pull request merged**
