### PR TITLE
Use correct column number for Razor

### LINKED ISSUE #31783: Invalid RZ Diagnostic Location
Not sure if this falls under tooling or runtime so tagged both for now.

image

The columns (ex. column 1131 for the first diagnostic) are non-existent..

Repro:
1. Build the [E2E tests](https://github.com/dotnet/aspnetcore/blob/686da2e6c5b62570a7750bc3d85179ee5e9e75fd/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj) project
2. Get RZ9991 errors with invalid `Column` numbers (note you'll have to right click on the header to see the column numbers)
3. Clicking on the diagnostic takes you to the *far* right of the page beyond any characters.

### LINKED ISSUE #32154: Incorrect Razor error `The 'functions' directive must appear at the start of the line.`
### Describe the bug
Switched from `.NET 5.0` to `.NET 6.0 preview 5` and Razor started erroring `RZ2005`

**Note:** The error probably thinks its being triggered correctly as look at the source Column it is reporting for (even though its in first column)

In VS

image

At CLI
```
...\Attributes.cshtml(205,9530): error RZ2005: The 'functions` directive must appear at the start of the line. 
...\Recipe.cshtml(274,13502): error RZ2005: The 'functions` directive must appear at the start of the line. 
...\Menu.cshtml(101,3953): error RZ2005: The 'functions` directive must appear at the start of the line. 
```

### To Reproduce

Haven't yet been able to isolate; new web project and current web project are both using `CRLF` so not that.

### Further technical details
- ASP.NET Core version: `Microsoft.AspNetCore.App 6.0.0-preview.5.21224.3`
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21225.4
 Commit:    474224c41a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21225.4\

Host (useful for support):
  Version: 6.0.0-preview.5.21224.1
  Commit:  e5dd7150e6

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21225.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21224.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21224.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21224.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- VS: Version `16.10.0 Preview 2.1`

### PR DESCRIPTION
**Pull request by benaadams**
Resolves Razor compile errors that are dependant on column position (e.g. "directive must be at start of line")

Fixes https://github.com/dotnet/aspnetcore/issues/32154
Fixes https://github.com/dotnet/aspnetcore/issues/31783

/cc @captainsafia

### CODE REVIEW

**Comment by benaadams** [comment]
Aside the source generator is so much faster at compiling than the previous method 💜

**Review by captainsafia — COMMENTED** [review]
Looks good overall.

The tests in SourceTextSourceLineCollectionTest that need to be updated.

In hindsight, that test would've served as a good indicator of this bug.

**Comment by benaadams** [comment]
Made test fix

**Review by captainsafia — APPROVED** [review]

**Comment by benaadams** [comment]
Is it too late to get this into preview4 since it causes compile errors?

**Comment by captainsafia** [comment]
Unfortunately, we missed the cutoff for preview4 with this one so it'll have to land in preview5.

**Pull request merged**
