### PR TITLE
Report corrupted global settings

### PR DESCRIPTION
**Pull request by GangWang01**
### Problem
https://github.com/dotnet/templating/issues/5972

### Solution
Report corrupted global settings before install/uninstall/update package, as well as after the operation.

### CODE REVIEW

**Comment by vlada-shubina** [comment]
@GangWang01 

the settings are only read from this code: 
https://github.com/dotnet/templating/blob/fcb35d2728f9951088cd95d2c22c0a8bf19ce8ce/src/Microsoft.TemplateEngine.Edge/BuiltInManagedProvider/GlobalSettings.cs#L82-L110

You can improve the warning by throwing typed exception at line 106 and including better message for the user, for example:

`Failed to read installed template packages list at {full file path to packages.json}. It might be due to the file is corrupted. Please review this file manually and fix the errors in JSON structure, or remove the file to clear up the list of list installed packages and reinstall them again. Details of the error: {inner exception message}`.

**Comment by GangWang01** [comment]
@vlada-shubina 
Yes, the settings are read from the code above. But throwing exception there could not stop the execution and it will report the error many times if doing so. Let me explain.

https://github.com/dotnet/templating/blob/fcb35d2728f9951088cd95d2c22c0a8bf19ce8ce/src/Microsoft.TemplateEngine.Edge/Settings/TemplatePackageManager.cs#L227-L236 loads providers and template packages got from each provider which will call the code as you mentioned. 
But getting template packages in template package manager doesn't throw the caught exception at https://github.com/dotnet/templating/blob/fcb35d2728f9951088cd95d2c22c0a8bf19ce8ce/src/Microsoft.TemplateEngine.Edge/Settings/TemplatePackageManager.cs#L109-L117. I think if throwing out the exception here it may be breaking change and have some risk.
Because it needs to get template packages prior to the operation (install/uninstall/update package) for doing some check and the operation itself needs to get template packages to combine execution result for refreshing the settings file, if reporting the error when reading the settings file the error will be reported multiple times.

I think reporting the error needs getting only providers from TemplatePackageManager, and then check the settings file with the providers at the beginning of each operation in https://github.com/dotnet/sdk/blob/main/src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs.
- EnterInstallFlowAsync
- EnterUpdateFlowAsync
- EnterUninstallFlowAsync

Considering https://github.com/dotnet/templating/issues/6128,  reporting the error might be not needed.

**Comment by vlada-shubina** [comment]
@GangWang01 The code I mentioned already throws the exception. The only change I'm suggesting is to make the error message in this exception better. It's ok if the exception is caught in some cases and is not interrupting the flow. 
This change should fix the issue.

**Comment by GangWang01** [comment]
I see. In a single flow the error/warning will appear multiple times. Let me draft a PR with tests and then to discuss if it's acceptable.

**Pull request closed without merging**
