### PR TITLE
Skip tests in official builds. We have no reason to run them again si…

### PR DESCRIPTION
**Pull request by livarcocc**
…nce they already ran on CI. This should speed up builds out of the sdk repo.

### CODE REVIEW

**Comment by nguerrera** [comment]
Does ci here refer to pr or rolling build? What coverage do we have if simultaneous prs are good on their own but fail when combined?

I've never been a fan of test one build ship another. 

Presumably progress towards exporting tests to validate final product will alleviate this concern, though.

**Review by ghost — APPROVED** [review]

**Comment by livarcocc** [comment]
I have never seen a test pass in CI and fail in the official build. This would turn it off only for official builds.

**Comment by nguerrera** [comment]
I'm not pushing back. But i have seen the exact situation of a bad combination of prs. We should have coverage for it.

**Comment by nguerrera** [comment]
Better to get test time way down and in the meantime I'm ok with the risk. But we should be testing the literal bits we ship at some point. This would be better done as a final run on the final product that is asynchronous and doesn't block flow. I think that's the direction with consolidation anyhow.

**Comment by livarcocc** [comment]
I did mean to merge this but I thought you wanted to discuss this more. If you are "ok" with this, feel free to merge for me.

**Pull request merged**
