### PR TITLE
Updating nuget version and adding it to Version.Details.xml for DARC updates.

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Review by nkolev92 — APPROVED** [review]

**Comment by nkolev92** [comment]
Is the same thing needed in the CLI repo?

**Comment by livarcocc** [comment]
> Is the same thing needed in the CLI repo?

Yes. Will do that there as well.

**Review by rainersigwald — APPROVED** [review]
Nit: when doing this kind of thing, please include the `darc` command line you ran to generate the metadata and the update in the commit message.

**Comment by livarcocc** [comment]
I generated it manually.

**Comment by dsplaisted** [comment]
@livarcocc @rrelyea  This is failing due to this bug: https://github.com/NuGet/NuGet.Client/pull/3016

> .dotnet/sdk/3.0.100-preview9-013985/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5131: References were found in the nuspec, but some reference assemblies were not found in both the nuspec and ref folder. Add the following reference assemblies:

Rob is planning to insert the fix tomorrow, though I'm not sure if we'll be able to take it all the way through.  I will add NoWarn so that we can merge this version.

**Pull request merged**
