### PR TITLE
[Blazor] Replace `webapp,razor` with `blazor` on `dotnet new`

### LINKED ISSUE #51774: [Blazor] Replace `webapp,razor` with `blazor` on `dotnet new`
We have a curated list of items that show up by default when we run `dotnet new`. We want to replace `webapp,razor` with `blazor` in that list.

It is to late for 8.0.100, but we want to do this for 8.0.101 and 8.0.200

_The 'dotnet new' command creates a .NET project based on a template._
 
```console
Common templates are:
Template Name                       Short Name    Language    Tags
----------------------------------  ------------  ----------  -------------------
ASP.NET Core Web App (Razor Pages)  webapp,razor  [C#]        Web/MVC/Razor Pages
Class Library                       classlib      [C#],F#,VB  Common/Library
Console App                         console       [C#],F#,VB  Common/Console
Windows Forms App                   winforms      [C#],VB     Common/WinForms
WPF Application                     wpf           [C#],VB     Common/WPF
```

Expected

```console
The 'dotnet new' command creates a .NET project based on a template.
 
Common templates are:
Template Name                       Short Name    Language    Tags
----------------------------------  ------------  ----------  -------------------
Blazor Web App                       blazor  [C#] Web/MVC/Razor Pages
Class Library                       classlib      [C#],F#,VB  Common/Library
Console App                         console       [C#],F#,VB  Common/Console
Windows Forms App                   winforms      [C#],VB     Common/WinForms
WPF Application                     wpf           [C#],VB     Common/WPF
```

### PR DESCRIPTION
**Pull request by surayya-MS**
Before:
old

After:

new

Fixes https://github.com/dotnet/aspnetcore/issues/51774

### CODE REVIEW

**Comment by baronfel** [comment]
@surayya-MS if you want this for 8.0.200 you'll want to `/backport` this to release/8.0.2xx once this merges.

**Comment by surayya-MS** [comment]
`CanShowBasicInfo` and `CanShowConfigWithDebugShowConfig` tests are failing. The error message is similar:
```
VerifyException : Directory: /Users/runner/work/1/s/src/Tests/dotnet-new.Tests/Approvals\nNotEqual:\n  - Received: DotnetNewDebugOptionsTests.CanShowConfigWithDebugShowConfig.OSX.received.txt\n    Verified: DotnetNewDebugOptionsTests.CanShowConfigWithDebugShowConfig.OSX.verified.txt\n\nFileContent:\n\nNotEqual:\n\nReceived: DotnetNewDebugOptionsTests.CanShowConfigWithDebugShowConfig.OSX.received.txt\nVerified: DotnetNewDebugOptionsTests.CanShowConfigWithDebugShowConfig.OSX.verified.txt\nCompare Result:\n\n\n
```
I'm not sure what that means. On my previous commits I was getting better error message and fixed those. 

@baronfel , @vlada-shubina do you know what the problem might be?

**Review by SteveSandersonMS — APPROVED** [review]
Looks great to me!

Can't say I fully understand why this exact combination of extra spaces is needed but if that's how the tests are set up and it works, all good.

Most likely you should also get approval from someone on `sdk` before merging.

**Review by MiYanni — APPROVED** [review]

**Comment by surayya-MS** [comment]
@MiYanni, @baronfel looks like I don't have permission to backport. Could you do it please?

**Pull request merged**
