### PR TITLE
Exclude Directory.Build.rsp from .gitignore template

### PR DESCRIPTION
**Pull request by MattKotsenas**
`Directory.Build.rsp` is a [documented file][1] that allows setting default arguments to command line builds. However, our .gitignore template ignores _all_ `*.rsp` files. which causes confusion:

1. Devs write an .rsp file and if they aren't being attentive forget to commit it
2. Adding it to git requires `git add --force`, which some devs mistake for a destructive or not-recommended action

Thus, explicitly allow the `Directory.Build.rsp` file.

[1]: https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2022#directorybuildrsp

### CODE REVIEW

**Review by baronfel — APPROVED** [review]

**Comment by baronfel** [comment]
We normally freeze templates by preview 6 or so, so checking with the rest of the team about applicability here. I still think we should take this, but we have some old scars from the .NET 6 release that we're working with here :)

**Comment by MattKotsenas** [comment]
Pinging here for latest status. If this is frozen until after .NET 9 that's fine, just want to make sure that:

1. We definitely don't want this for 9
2. At what point I should resume nagging 😅

**Comment by marcpopMSFT** [comment]
Triage: Ping us again in ~2 weeks after we've forked a 9.0.1xx branch for .NET9 servicing. We'll take this for 10 so as to avoid any late template changes (noting that this one is probably lower risk that source changes that have typically been the focus).

**Comment by MiYanni** [comment]
@marcpopMSFT 
> Triage: Ping us again in ~2 weeks after we've forked a 9.0.1xx branch for .NET9 servicing. We'll take this for 10 so as to avoid any late template changes (noting that this one is probably lower risk that source changes that have typically been the focus).

I think this has happened now, right? The build failure looks unrelated.

**Comment by marcpopMSFT** [comment]
@MiYanni yes, they should be free to merge this into main and the VMR failures are from the window when the ubuntu vmr leg had issues. Since there's no rush, I'd just rerun.

**Pull request merged**
