### PR TITLE
Fix handling of runtimeconfig files in incremental builds

### LINKED ISSUE #471: Incremental build deletes *.runtimeconfig.*.json if there is a runtimeconfig.template.json in the project
The issue is that the fix made for deps.json (https://github.com/dotnet/sdk/pull/424) was not made for runtimeconfig.json.

This causes every other F5 of a .NET Core App that has a runtimconfig.template.json to fail.

It turns out that the issue is less common for runtimeconfig.json because we have and Inputs=runtimeconfig.template.json which causes the task to run always if the file does not exist (and it commonly doesn't). However, if the file does exist then we get the same bad behavior for runtimeconfig.json that was seen with deps.json.

When fixing this, we should also:

* Make sure to actually skip the generation if it's up to date but there is no template file
* Audit all other uses of FileWrites for other possible latent issues here.

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #471

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Comment by MattGertz** [comment]
@nguerrera @srivatsn Can you review/validate this please?

**Comment by nguerrera** [comment]
@MattGertz Code looks good. Getting set up to test.

**Comment by nguerrera** [comment]
Let's file a separate bug for the extra things I noted in #471:

> * Make sure to actually skip the generation if it's up to date but there is no template file
> * Audit all other uses of FileWrites for other possible latent issues here.

I do think it's the right call to scope the change as you have for a servicing fix.

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
Changed the PR to target the dev15-rc2 branch.

**Comment by dsplaisted** [comment]
> Changed the PR to target the dev15-rc2 branch.

Oops.  Thanks.

**Comment by dsplaisted** [comment]
@nguerrera I've filed #496 and #497 for the follow-up issues

**Pull request merged**
