### PR TITLE
Insert NuGet Build 5.0.0-rtm.5856 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.0-rtm.5856 into sdk release/2.1.6xx branch

### CODE REVIEW

**Comment by livarcocc** [comment]
@nkolev92 is this for 16.0? Are the changes here relevant to core and the CLI? I am not sure we have time to absorve these changes and get an insertion into VS tonight.

cc @Pilchie

**Comment by nkolev92** [comment]
Yes, this is for 16.0. 
There are some CLI impacting fixes. 

See for full details https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796859

At this point there are no insertion plans beyond this one. 

As the cut off for P4 is tomorrow we are trying to get these last bits in today.

**Comment by livarcocc** [comment]
@nkolev92 my understanding is that they are spinning a build tomorrow morning, which means we would have to merge nuget on the CLI, then SDK and then back into CLI and update an insertion into VS to go in tonight to catch tomorrow morning's build. I find that risky.

**Comment by nkolev92** [comment]
I am not aware if that has changed. The schedule suggests 6pm final build.

We are running with out Visual Studio insertion with 6pm being the final build in mind. 

//cc @DoRonMotter

**Review by livarcocc — APPROVED** [review]

**Pull request merged**
