### PR TITLE
Update the VB templates to remove the globbing

### PR DESCRIPTION
**Pull request by basoundr**
@nguerrera @dsplaisted @dotnet/msbuild for review

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]
Still think this is a bad paradigm but that ship sailed a long, long time ago.

Sdk already has implicit includes for these, right?

**Comment by basoundr** [comment]
Yes, we already include them and we do that for C# too. Since we were shipping VB, this change was simply missed out

**Comment by basoundr** [comment]
@davkean @srivatsn

**Review by nguerrera — APPROVED** [review]

**Comment by basoundr** [comment]
Would the Ubuntu queue be fixed any soon? or should I go ahead and merge this PR?

**Comment by nguerrera** [comment]
@dotnet-bot Test Ubuntu16.04 Release please

**Comment by nguerrera** [comment]
> Would the Ubuntu queue be fixed any soon? or should I go ahead and merge this PR?
It passed on subsequent PRs, so trying again.

**Pull request merged**
