### PR TITLE
Add test that libraries from ASP.NET shared framework aren't included

### PR DESCRIPTION
**Pull request by dsplaisted**

### CODE REVIEW

**Review by peterhuene — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by dsplaisted** [comment]
ASP.NET has fixed this with https://github.com/aspnet/AspNetCore/pull/9180.  However, we should still add the test in this PR to our code once their change flows into this repo's stage 0.

**Comment by nguerrera** [comment]
@dsplaisted Is this still relevant?

**Comment by dsplaisted** [comment]
> Is this still relevant?

It would be good to add the test

**Comment by nguerrera** [comment]
> It would be good to add the test

@dsplaisted Can you resolve the conflict, get this to green, and merge?

**Pull request merged**
