### PR TITLE
Fix broken CoherentParentDependency and update wpf dependency

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
Noticed this trying to merge to master and needing to do update-dependencies.

Got this:
```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies to channel .NET 5 Preview 1
Microsoft.DotNet.DarcLib.DarcException: Dependency Microsoft.NET.Sdk.WindowsDesktop has non-existent parent dependency Microsoft.WindowsDesktop.App
   at Microsoft.DotNet.DarcLib.Remote.GetRequiredCoherencyUpdatesAsync(IEnumerable`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 481
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 183
```

**Comment by nguerrera** [comment]
So the wpf updates aren't flowing it seems.

**Review by dsplaisted — COMMENTED** [review]
I'll defer to @mmitche on this one, but it does seem like we should make sure that we fix anything stopping the dependencies from flowing.

**Comment by vatsan-madhavan** [comment]
This seems wrong. @rladuca  and I just realized WindowsDesktop SDK fixes aren't in the Preview 1 SDK and followed a bunch of crumbs to this PR. Looks like we may need to undo this and rebuild P1...

**Comment by nguerrera** [comment]
I don't follow

**Comment by nguerrera** [comment]
This made it go forward

**Comment by nguerrera** [comment]
This should have been the fix

**Comment by nguerrera** [comment]
Ok from offline chat, this didn't actually cause new builds to flow it just allowed the one-off update to proceed. @vatsan-madhavan is preparing a genuine fix.

**Pull request merged**
