### PR TITLE
Fix reporter encoding

### PR DESCRIPTION
**Pull request by Forgind**
Our reporter uses Console.Out and defaults it to the default code page (437). This changes it to use UTF8 encoding, which made the output look more like this:
image

instead of:
image

Fixes AB#2036256

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@baronfel should we just remove the redirect check here? https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Program.cs#L34  Do you know of a reason we shouldn't be utf8 on all platforms that support it?

**Comment by baronfel** [comment]
My inclination is that we should try to be utf8 when the platform supports it, yes. I vaguely remember that we had some discussion about this when @nagilson was working on the culture setting, but I don't remember the details. @nagilson do you remember what some of the pitfalls were, if any?

**Comment by nagilson** [comment]
Yes, for earlier builds of windows 10 utf 8 is not supported. 

https://github.com/dotnet/sdk/blob/415827f5f6417374207cd9a3b54b98054e801e0c/src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs#L109 

This file contains all of the checks necessary to see if utf8 should be used or not. Also, unless something has changed, we'd likely need to change the input encoding if you want the output encoding change to work on powershell, which is also documented in this file.

**Comment by Forgind** [comment]
This is a solution from our side, but it isn't actually a full solution, as we don't actually own all the code for dotnet --info:
https://github.com/dotnet/runtime/blob/a0beed4fa56aaf4d3cb2f02b5cdb68f8929e1a60/src/native/corehost/fxr/command_line.cpp#L305

That means the runtime part of this will still be broken even if this goes in. If we merge this, we should move the bug to their area path.

**Comment by nagilson** [comment]
Does this work in powershell command line? It would also be best if we could re use the existing is utf 8 supported check to prevent code duplication.

**Comment by Forgind** [comment]
Powershell works fine:
image

Looking into duplication now

**Comment by nagilson** [comment]
I think it has to be tested on a powershell IDE terminal, and not a regular terminal. Sorry!

**Comment by Forgind** [comment]
> ~I think it has to be tested on a powershell IDE terminal, and not a regular terminal. Sorry!~
> 
> Nvm, I guess they got rid of the blue background on the powershell terminal recently so it just looks like a regular terminal. Thank you!

Yeah; it's subtle, but they indicate that it's powershell here:
image

**Review by nagilson — APPROVED** [review]
LGTM now, thanks :)

**Pull request merged**
