### PR TITLE
Revert "[release/7.0.4xx] Update dependencies from dotnet/fsharp"

### PR DESCRIPTION
**Pull request by MiYanni**
Reverts dotnet/sdk#34087

### CODE REVIEW

**Comment by MiYanni** [comment]
Accidentally merged this into a locked down branch.

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
per offline conversation. This missed the window for August. There's not really harm in having it merged but if there is a rebuild for any reason, we'd pick up the extra change and we typically try to avoid that.

CC @KevinRansom for visibility on the fsharp changes that won't go in until September servicing.

**Comment by vzarytovskii** [comment]
The only thing which went with accidental merge is revert of one of the earlier changes (which broken one of the rare scenarios).

**Comment by MiYanni** [comment]
I've retriggered the subscription. New PR here. Will leave it be until after branch lockdown. https://github.com/dotnet/sdk/pull/34105

**Pull request merged**
