### PR TITLE
Adds fallback folder for full framework and multi-tfm projects.

### PR DESCRIPTION
**Pull request by livarcocc**
**Customer scenario**

Fallback folders were not being set for full framework projects nor multi-tfm projects. Adds fallback folder for full framework projects by removing the condition on the project being netstandard or netcore. Also, sets the properties for multi-tfm projects. We did that by evaluating all the TFMs in the project and if any of them target a 1.x project, we default to PackageSource, as we need to use the lowest common denominator here, so that the project will work independently of the TFM.

**Bugs this fixes:** 

Fixes https://github.com/dotnet/sdk/issues/1389

**Workarounds, if any**

Don't use the offline cache. Instead, we will hit the web during restore for Multi-tfm projects.

**Risk**

Low

**Performance impact**

Low. We are running another set of inner-loop evaluations.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

We were only setting the property for NuGet in the inner-loop.

**How was the bug found?**

Partner team.

@dotnet/dotnet-cli for review

@MattGertz for approval

### CODE REVIEW

**Comment by livarcocc** [comment]
@emgarten

**Review by emgarten — APPROVED** [review]
This looks good to me, Restore should read the properties after this target runs.

**Comment by livarcocc** [comment]
@emgarten does restore in va use the same target?

**Comment by emgarten** [comment]
VS restore is nominated from the project system, it wouldn't be the same. @natidea is there a target that runs before restore properties are checked? Does CollectPackageReferences run first?

**Comment by livarcocc** [comment]
We use _GenerateRestoreProjectSpec in another target, should we use the same here? We want the SDK NuGet properties to be set for both CLI and VS.

**Comment by livarcocc** [comment]
@emgarten _GenerateRestoreProjectSpec does not work, I just tried it.

**Comment by emgarten** [comment]
``_GenerateRestoreProjectSpec`` would be called later than ``_GetRestoreSettings``

**Comment by natidea** [comment]
The nomination in VS runs after the Design Time build completes and all targets have run. So yes, `CollectPackageReferences` is always run before hand, unless the DT build fails before the target has run.

**Comment by nguerrera** [comment]
@natidea Aren't all design-time builds done on the inner/configured project?

**Comment by livarcocc** [comment]
Closing this for now. Will re-activate when we have a solution that also works in VS.

**Pull request closed without merging**
