### PR TITLE
Use default arcade symbol publishing logic

### PR DESCRIPTION
**Pull request by dsplaisted**
#3584 was supposed to fix symbol publishing, but didn't work because we were copying the portable PDB files to the SymStore directory.  They need to be converted to desktop PDBs in order to be published.  The default Arcade logic handles this, so just revert to that.

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/pull/3584#discussion_r321479732 ;)

**Comment by nguerrera** [comment]
Can you put this in 3.0 so we get symbols for 3.10x servicing

**Comment by tmat** [comment]
A few more things to remove from the file:

```xml
  <Copyright>$(CopyrightNetFoundation)</Copyright>
```
This will be ignored.

```xml
 <DebugType>portable</DebugType>

 <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
   <DebugType>embedded</DebugType>
```
Arcade defaults DebugType to Embedded on CI and in local builds and to Portable in official builds.

```xml
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <ExcludeFromSourceBuild>true</ExcludeFromSourceBuild>
```

Test projects are excluded by default.

This seems to have been fixed in NuGet:
```xml
    <!-- Workaround for https://github.com/NuGet/NuGet.Client/pull/3016 -->	    <!-- Workaround for https://github.com/NuGet/NuGet.Client/pull/3016 -->
    <NoWarn>$(NoWarn);NU5131</NoWarn>
```

**Review by tmat — APPROVED** [review]

**Comment by livarcocc** [comment]
@dsplaisted can you address feedback from @tmat and be ready to merge this change when the branch opens after P3 ships?

**Comment by dsplaisted** [comment]
@livarcocc It isn't working end to end yet, ie I tried doing a build and running symchk to make sure the symbols were published correctly..  Hopefully https://github.com/dotnet/arcade/pull/4284 will fix it.

**Comment by livarcocc** [comment]
@dsplaisted what about now? We are good to merge this change for GA from the branch point of view but need confirmation from you that the change is good to go.

**Comment by dsplaisted** [comment]
We would have to take an Arcade update to get the fix for dotnet/arcade#4284.  In an email about the SDL tasks, @wtgodbe said we shouldn't update Arcade until after 3.1 GA.

We should still be able to make the changes in our branch, I don't think it will break symbol publishing any worse than it already is.

**Comment by nguerrera** [comment]
It seems GA worthy to fix symbols, have we raised with tactics?

**Comment by dsplaisted** [comment]
@nguerrera @tmat I've added a task in the YAML to upload the PDBs together with the logs.  This should enable us to manually publish the symbols without having to take the Arcade change for the 3.1.100 release.  I've also applied Tomas's feedback

**Review by nguerrera — APPROVED** [review]

**Review by tmat — COMMENTED** [review]
LGTM

**Pull request merged**
