### PR TITLE
Crossplatform ResourceUpdater

### PR DESCRIPTION
**Pull request by anatawa12**
Add e2e test for dotnet/runtime#89303.
Remove ResourceUpdater.IsSupported guard

### CODE REVIEW

**Comment by anatawa12** [comment]
CI Failure is intended for now.

**Comment by anatawa12** [comment]
@dotnet/domestic-cat ready for review

**Review by elinor-fung — APPROVED** [review]
This looks good to me from the runtime side of consuming HostWriter. @dotnet/domestic-cat could someone take a look?

**Review by MiYanni — APPROVED** [review]
Looks good! 👍

**Pull request merged**
