### PR TITLE
Add implicitly expanded design time facades to deps.json for PreserveCompilationContext

### LINKED ISSUE #480: Facades from desktop framework targeting pack are not emitted to .deps.json for PreserveCompilationContext
See: https://github.com/dotnet/sdk/issues/111#issuecomment-266103143

After some investigation, the .deps.json file does not list framework references for System.Runtime and friends that do get resolved from .NETFramework\v4.5.2\Facades during build.

This appears to be the root cause of:
* aspnet/Home#1866
* aspnet/Razor#890

@NTaylorMullen

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #480 

@srivatsn @dsplaisted @eerhardt

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Comment by MattGertz** [comment]
Approving per JoC.

**Comment by eerhardt** [comment]
Do these assemblies also get published to the "refs" folder?  If not, why do they need to be in the deps files?  Or are they retrieved a different way at runtime?

**Comment by nguerrera** [comment]
They do get published to the refs folder already but since they were missing from deps json, razor was busted.

**Comment by nguerrera** [comment]
They are framework assemblies that are referenced but they do not have IsFrameworkFile=true.

**Comment by eerhardt** [comment]
:shipit:

**Pull request merged**
