### PR TITLE
Delete "*.orig" files leftover from dependency updates

### PR DESCRIPTION
**Pull request by Nirmal4G**
These files are created by "dotnet-maestro" when there's a conflict in changes when applying dependency updates that requires user attention. As these conflicts are usually resolved before merging changes into main, the original files might remain if not properly resolved.

NOTE: These can be safely removed and doesn't need any CI/CD validation.

### CODE REVIEW

**Comment by Nirmal4G** [comment]
The files are leftovers from #17108.

**Comment by Nirmal4G** [comment]
@sfoslund 🔔

**Review by sfoslund — APPROVED** [review]
Thanks for the contribution!

**Comment by Nirmal4G** [comment]
I almost forgot. These files are also present in `main`. Do I have to create a new PR against `main` or will the changes cascade into `main`?

**Pull request merged**
