### PR TITLE
Update NetAnalyzers version for release/7.0.1xx

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6279

### CODE REVIEW

**Comment by Youssef1313** [comment]
Could someone take a look please?

**Comment by mavasani** [comment]
Needs changes to Versions.Details.xml similar to https://github.com/dotnet/sdk/pull/29975/files

**Comment by marcpopMSFT** [comment]
@Youssef1313 checking in on old PRs. Is this still needed? 1xx and 3xx both list preview versions of this package but that appears to be what we ship on nuget.org and what came in through codeflow so this almost seems expected.

**Comment by marcpopMSFT** [comment]
Got no response so closing.

**Pull request closed without merging**
