### PR TITLE
Fix issue where UseWPF / UseWindowsForms wouldn't work in Directory.Build.targets

### PR DESCRIPTION
**Pull request by dsplaisted**
#14393 broke projects that set UseWPF or UseWindowsForms in Directory.Build.targets.

This PR fixes that.

However, we probably want WPF and Windows Forms to be in their own workload eventually, at which point this would break again.  So we're not sure we want to take this PR yet.

### CODE REVIEW

**Comment by ryalanms** [comment]
@dsplaisted:  Does this also need to go into master?

**Comment by dsplaisted** [comment]
> @dsplaisted: Does this also need to go into master?

If we take this change, it will eventually go to master too.

**Comment by wli3** [comment]
@dsplaisted I don't think we get a clear decision during the meeting. Do we want to merge this? Or completely revert the change for Xamarin props import

**Comment by dsplaisted** [comment]
> @dsplaisted I don't think we get a clear decision during the meeting. Do we want to merge this? Or completely revert the change for Xamarin props import

Yes, we want to merge this.  It avoids the breaking change for now while we will continue to work on figuring out the right way to handle it.

**Review by wli3 — APPROVED** [review]

**Pull request merged**
