### PR TITLE
Honor DO_NOT_TRACK as well as DOTNET_CLI_TELEMETRY_OPTOUT

### PR DESCRIPTION
**Pull request by fowl2**
An attempt at #3917

### CODE REVIEW

**Comment by Diti** [comment]
Let that be a lesson to the open-source communities of Lobsters, Hacker News, Reddit, and StackExchange. Microsoft does not care about standardization attempts started outside of their company.

**Comment by delanym** [comment]
[Not invented here](https://en.wikipedia.org/wiki/Not_invented_here)

**Comment by Diti** [comment]
[xkcd: Standards](https://xkcd.com/927/)

**Comment by delanym** [comment]
The variable DOTNET_CLI_TELEMETRY_OPTOUT is not a standard

**Comment by kasperk81** [comment]
DO_NOT_TRACK is not the standard either

summing up https://github.com/dotnet/sdk/issues/6145 to reflect what community at large want:

1. the best thing would be if tracking is made opt-in.
2. the second best option is if user is _asked_ on the first run whether to opt-in to this data collection program.
3. the third best option is to provide a way to opt-out, for which there is existing support for DOTNET_CLI_TELEMETRY_OPTOUT flag.

DO_NOT_TRACK is just the variant of third best thing, and it is not that interesting as first two options, which will _really_ inspire confidence transparency.

**Comment by delanym** [comment]
Tracking will never be made opt-in because who in their right mind would go out of their way to turn it on? Its unrealistic.
Your second best option is not friendly for unattended installations. It also means that if I remove the application and install it again I have to answer the same question again.
I make the decision to allow telemetry on a system level, not on an application level. If I say yes to telemetry for dotnet, chances are I'm happy to do it for others and I don't want to have to answer the same dumb question over again for every machine, for every app, for every install. It also means if I change my mind, I can change it once! DO_NOT_TRACK is my system level telemetry policy and it costs nothing for dotnet to respect it - probably not even another line of code.

**Comment by khellang** [comment]
Hey @marcpopMSFT! 👋🏻 

Would it hurt anyone to honor a standard flag *in addition* to the existing flag? I'd love to hear some reasoning for this 😅

**Pull request closed without merging**
