### PR TITLE
Future should use VS 2017

### PR DESCRIPTION
**Pull request by ramarag**
@nguerrera PTAL

some more missing changes in netci.groovy

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Review by 333fred — CHANGES_REQUESTED** [review]
Remove the .netci.grooy.swp file

**Comment by 333fred** [comment]
@ramarag, this isn't going to have any effect on the Jenkins jobs. Jenkins does not pull job definitions from the future branch, only from master.

**Comment by ramarag** [comment]
removed the *.swp

**Comment by ramarag** [comment]
i don't think future branch CI jobs runs master netci.groovy for proof look at 

https://ci.dot.net/job/Private/job/dotnet_sdk/job/future/job/debug_windows_nt_prtest/34/consoleFull
THe CI is not setting SET VS150COMNTOOLS

**Review by 333fred — APPROVED** [review]
Sorry, no idea what I was thinking.

**Comment by 333fred** [comment]
@dotnet-bot test ci please

**Comment by ramarag** [comment]
The windows build failure are expected i suppose due to my previous PR with incomplete change https://github.com/dotnet/sdk/pull/808 has taken effect

**Comment by 333fred** [comment]
Immediate failure: https://ci.dot.net/job/Private/job/dotnet_sdk/job/future/job/GenPRTest/job/debug_windows_nt_prtest/1/console

**Comment by 333fred** [comment]
@dotnet-bot test ci please

**Comment by ramarag** [comment]
@dotnet-bot test ci please

**Comment by 333fred** [comment]
The updated version of `Windows_NT Debug` finished here: https://ci.dot.net/job/Private/job/dotnet_sdk/job/future/job/GenPRTest/job/debug_windows_nt_prtest/2/ successfully. The full framework test is still running https://ci.dot.net/job/Private/job/dotnet_sdk/job/future/job/GenPRTest/job/debug_windows_nt_fullframework_prtest/1/console

**Comment by 333fred** [comment]
@ramarag  https://ci.dot.net/job/Private/job/dotnet_sdk/job/future/job/GenPRTest/job/debug_windows_nt_fullframework_prtest/1/ finished successfully. You should be good to merge.

**Comment by nguerrera** [comment]
If this is the reason, maybe just let full merge through and then do a test. Seems better than a mess of history with duplicated commits

**Pull request merged**
