### PR TITLE
Update manpages for 9.0

### PR DESCRIPTION
**Pull request by am11**
With https://github.com/dotnet/docs/pull/42747 applied.

FYI @jkoritzinsky

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@am11 Any more changes coming for this or is it ready to be merged?

**Review by marcpopMSFT — APPROVED** [review]

**Comment by am11** [comment]
@marcpopMSFT, I was hoping that when https://github.com/dotnet/docs/pull/42747 is merged, I will do a clean pass with docs main branch. But it's not necessary. :)

**Comment by marcpopMSFT** [comment]
We still have time for GA. Looks like I have permissions to merge in the docs repo so I went ahead and merged the other PR if you want to do your clean pass. Let me know when you're done and I can merge it.

**Comment by am11** [comment]
@marcpopMSFT this is ready.

**Comment by marcpopMSFT** [comment]
Thanks. Looks reasonable. No point is rerunning the test legs since the manpages should not impact builds or tests.

**Comment by marcpopMSFT** [comment]
Thanks for running the tooling and updating these!

**Pull request merged**
