### PR TITLE
[gh-23135] use parent path of manifest file path as rootConfigDirectory

### PR DESCRIPTION
**Pull request by tremblaysimon**
Fix gh-23135 using parent path of manifest file. 
I didn't figure out how to do a unit test that make sense unfortunately.

### CODE REVIEW

**Comment by baronfel** [comment]
This fix looks good, can you retarget to release/7.0.2xx? I talked with the team and we're having a hard time figuring out a correct way to test this, will report back if we think of anything.

**Comment by tremblaysimon** [comment]
@baronfel I retargeted to release/7.0.2xx.

**Review by joeloff — COMMENTED** [review]
Sorry for the delay, had to catch up on all the documents, but I agree with the change.

**Review by baronfel — APPROVED** [review]

**Comment by tremblaysimon** [comment]
I was wondering if everything is ok for that PR to merged @baronfel ?

**Comment by baronfel** [comment]
Thank you for the poke @tremblaysimon - This one fell off my radar and for that I apologize profusely. I will talk with the team, but I think that we have passed our cutoff date for the 7.0.2xx release next month. One of two things will need to happen:
* we take this for the first servicing release of 7.0.2xx (and as a result we don't have to do anything to this PR except wait), or
* we retarget this to 7.0.3xx (which would mean retargeting to the release/7.0.3xx branch and me merging it there immedately)

**Comment by tremblaysimon** [comment]
@baronfel, I changed the base branch to release/7.0.3xx, I think you can merge that pull request?

**Comment by baronfel** [comment]
@tremblaysimon thanks for your patience! Merging now.

**Pull request merged**
