### PR TITLE
Disable multilevel lookup in build/test to prevent accidental machine dependencies

### PR DESCRIPTION
**Pull request by dsplaisted**
Cherry-picked multi-level lookup fix from #1519 for master

### CODE REVIEW

**Comment by dsplaisted** [comment]
@nguerrera

**Comment by nguerrera** [comment]
Why not just merge release to master?

**Review by nguerrera — APPROVED** [review]

**Comment by dsplaisted** [comment]
> Why not just merge release to master?

@nguerrera I don't think we want the version bumps in master yet

**Comment by nguerrera** [comment]
Ah, ok.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
