### PR TITLE
Updating NuGet to 4.3.0-beta1-2418

### PR DESCRIPTION
**Pull request by emgarten**
This change updates NuGet to the latest version.

My goal is to update this weekly to keep everything in sync.

### CODE REVIEW

**Comment by livarcocc** [comment]
Are you going to make a similar PR to CLI?

**Review by livarcocc — APPROVED** [review]

**Comment by emgarten** [comment]
@livarcocc I will. The current flow we are using is to update the SDK, then update the CLI with the new SDK and NuGet. Let me know if I should do this differently.

**Comment by nguerrera** [comment]
I don't know that the dependencies of the nupkg the CLI takes actually impact anything at this point, but prior updates have kept it in sync:

https://github.com/dotnet/sdk/commit/316bfc4d31f3efb0a7ce6099e3d3d4fe7f8cf457
https://github.com/dotnet/sdk/blob/master/build/Nuget/Microsoft.NET.Sdk.nuspec#L14

**Comment by nguerrera** [comment]
I think that it doesn't matter as we've already not updated it recently. This nupkg is not used other than to deliver the SDK files to the CLI. I think we should just remove the dependency. @emgarten Can you try that and include it in the CLI update?

**Pull request merged**
