### PR TITLE
Merging internal commits for release/6.0.3xx

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@rbhanda @mmitche @vseanreesermsft does msbuild need to be pushed to the public feed:
D:\a\_work\1\s\src\Tests\msbuild.Integration.Tests\msbuild.Integration.Tests.csproj : error NU1603: Microsoft.DotNet.Cli.Utils depends on Microsoft.Build (>= 17.2.2) but Microsoft.Build 17.2.2 was not found. An approximate best match of Microsoft.Build 17.3.0 was resolved. [D:\a\_work\1\s\sdk.sln]
##[error]src\Tests\msbuild.Integration.Tests\msbuild.Integration.Tests.csproj(0,0): error NU1603: (NETCORE_ENGINEERING_TELEMETRY=Restore) Microsoft.DotNet.Cli.Utils depends on Microsoft.Build (>= 17.2.2) but Microsoft.Build 17.2.2 was not found. An approximate best match of Microsoft.Build 17.3.0 was resolved.

CC @rainersigwald

**Comment by rainersigwald** [comment]
The change has private feeds for MSBuild (not sure why it has 5 of them) that I expected to work, but we should push them anyway. @Forgind can you point to the right official build?

**Comment by mmitche** [comment]
> The change has private feeds for MSBuild (not sure why it has 5 of them) that I expected to work, but we should push them anyway. @Forgind can you point to the right official build?

That's expected. It's every feed where the specific msbuild packages have appeared. They are disabled though (since they are internal). The packages should be on nuget.org, and then end up on dotnet-public.

**Comment by Forgind** [comment]
6.0.3xx corresponds to MSBuild 17.2, correct? https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=6677526&view=results is the build for 17.2.

**Review by mmitche — APPROVED** [review]

**Pull request merged**
