### PR TITLE
Switch to hosted Mac pool for CI

### PR DESCRIPTION
**Pull request by dsplaisted**
DotNetCore-Mac pool is being retired.

### CODE REVIEW

**Comment by dsplaisted** [comment]
The hosted Mac pools use OS X 10.14, which isn't supported by .NET Core 1.x.  So I retargeted some tests and disabled others.

@peterhuene there were some AppHost related changes, you might want to check to see if those are expected.

**Review by peterhuene — APPROVED** [review]

**Comment by peterhuene** [comment]
@dsplaisted which changes related to the apphost are you referring to?  I looked over the test changes and everything makes sense to me.

**Comment by dsplaisted** [comment]
@peterhuene A few of the tests now have an .exe in the output now that they target 2.1, which I wasn't sure was expected.

**Comment by nguerrera** [comment]
>  A few of the tests now have an .exe in the output now that they target 2.1,

Why is this expected exactly. I thought the exe default triggers at 3.0

**Comment by peterhuene** [comment]
It's not a default apphost, it's a RID-specific build in those tests.  The 3.0 SDK is defaulting to generating an apphost on RID-specific builds / publish for >= `netcoreapp2.1`.

**Comment by nguerrera** [comment]
Got it. :)

**Pull request merged**
