### PR TITLE
Compute SdkAnalysisLevel Property at the beginning of the SDK Targets

### PR DESCRIPTION
**Pull request by baronfel**
This is a companion PR to https://github.com/dotnet/designs/pull/308 to help bring clarity to the design doc.

It defines the SdkAnalysisLevel at the .NET Sdk.targets, basing it off of the `major.minor.featureband` of the current SDK when no user-defined value is present.

Future work should add validation of this value during the beginning of execution to prevent invalid values from permeating through the system.

### CODE REVIEW

**Comment by joeloff** [comment]
The SDK folder contains both a `.toolset` and .`version` file, in the root SDK folder and they contain the following information in case that is useful.

.toolsetversion:
```
3f5d0be2f51d49013230c45b5a9a6dad582f40f3
6.0.126-servicing.23605.37
win-x64
```

.version
```
06a93b906c5570bbbdc1a446b4a203d598202c39
6.0.126
win-x64
```

**Comment by baronfel** [comment]
Looking at the files in the 8.0.1xx SDKs I have installed, I see the following:

```
6eceda187bfd6e063bc320a37e52aad7c77c3b5b
8.0.101
win-x64
8.0.101-servicing.23580.17
```

The second line is the closest thing to what we want here, but we'd still have to do math on it in the same way this PR does to actually get the feature band for this SDK. Should we emit a file with the 'feature band' somewhere?

**Comment by joeloff** [comment]
Should we store it in the bundled versions props file maybe, precompute at build time in the installer repo instead?

**Comment by baronfel** [comment]
Closing this in favor of https://github.com/dotnet/installer/pull/18687 and a soon-to-be-opened SDK PR to read that value from the props.

**Pull request closed without merging**
