### PR TITLE
Merge master into release/2.1.3xx

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by livarcocc** [comment]
@nguerrera can you take a look at the failures here? They are about tools deps.json and the assets cache file.

**Comment by nguerrera** [comment]
It's the RAR cache writing to SDK directory like the package assets cache was. I guess Stage 0 in 2.1.3xx branch was too old to stress RAR cache. That code is hardened against I/O failure which is why the end-to-end scenario is not broken, but we will write the RAR cache to the SDK folder when we are just unzipped to user-writeable place.

**Comment by nguerrera** [comment]
Preparing fix

**Comment by nguerrera** [comment]
This is the fix:

https://github.com/dotnet/sdk/compare/merge_master_into_3xx...nguerrera:merge_master_into_3xx

Do I need to send it through ship room?

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
