### PR TITLE
Update version in global.json

### PR DESCRIPTION
**Pull request by fadimounir**
New version pulls the ILLink.Tasks and Microsoft.NET.Build.Bundle packages.

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Review by swaroop-sridhar — APPROVED** [review]

**Comment by wli3** [comment]
@dsplaisted could you take a look at why "It_discovers_assembly_parts" is failing due to update stage0?

**Comment by dsplaisted** [comment]
It looks like this was a break in the Razor SDK, which seems to have subsequently been fixed.

@fadimounir Can you try updating stage 0 to 3.0.100-preview5-011145 or later?

@rynowak FYI, it looks like the Razor SDK broke by trying to add a RelatedAssemblyAttribute to 1.x apps, where it didn't exist.  It looks like this has since been fixed though.

**Comment by fadimounir** [comment]
@dsplaisted Looks like tests are still failing even with the updated version

**Comment by dsplaisted** [comment]
@fadimounir #3107 updates stage 0 and includes a corresponding test update

**Comment by fadimounir** [comment]
Thanks!

**Pull request closed without merging**
