### PR TITLE
Add solution filter for template engine

### PR DESCRIPTION
**Pull request by GangWang01**
Add solution filter for template engine

### CODE REVIEW

**Comment by GangWang01** [comment]
@vlada-shubina @JanKrivanek please help to review.

**Review by JanKrivanek — APPROVED** [review]
Nice simplification of our work - thanks!

**Comment by vlada-shubina** [comment]
@GangWang01 please retarget to release/7.0.1xx, thank you

**Comment by GangWang01** [comment]
It's not a easy rebase. A new PR will be created instead.

**Pull request closed without merging**
