### PR TITLE
Use lowercase version of TargetFramework when constructing output path

### LINKED ISSUE #293: dotnet build3: case of -f (framework) parameter defines case, not project
## Steps to reproduce
1. `dotnet new`
2. `dotnet restore3`
3. `dotnet build3 -f NETCOREAPP1.0`
## Expected

Artifacts on disk should match TFM case in the project file.
## Actual

```
 Volume in drive C has no label.
 Volume Serial Number is 3487-F055

 Directory of C:\Users\jver\Desktop\reprocase\bin\Debug

10/17/2016  07:28 PM    <DIR>          .
10/17/2016  07:28 PM    <DIR>          ..
10/17/2016  07:28 PM    <DIR>          NETCOREAPP1.0
               0 File(s)              0 bytes
```
## Environment

`Microsoft.NET.Sdk/1.0.0-alpha-20161012-3`

`dotnet --info`

```
.NET Command Line Tools (1.0.0-preview3-003857)

Product Information:
 Version:            1.0.0-preview3-003857
 Commit SHA-1 hash:  060762090d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #293

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@MattGertz for approval.

**Comment by MattGertz** [comment]
@livarcocc Proactively approved, but don't forget the template.

**Comment by livarcocc** [comment]
@MattGertz we haven't used this template in the past for the CLI/SDK. Is this something that we should start using now?

**Comment by MattGertz** [comment]
Yes, please.  I've been letting it slide, especially since most of the approvals were simply for insertions of other tool deliverables, but for this one I'm not actually sure why the fix is required (and tomorrow the template will be mandatory anyway, as we will be in escrow).

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
