### PR TITLE
[NOMERGE] Revert "[release/9.0.1xx] Update dependencies from dotnet/runtime"

### PR DESCRIPTION
**Pull request by steveisok**
Reverts dotnet/sdk#43503

Seeing if crossgen still fails or not....

### CODE REVIEW

**Comment by ivdiazsa** [comment]
Something I'm finding very strange is that in both attempts of this CI run, the following legend is displayed at the top: `This job didn't run in this attempt. Logs shown are from a previous attempt`. Can we be sure that it's a bug in the UI and the job actually ran?

**Comment by steveisok** [comment]
> Something I'm finding very strange is that in both attempts of this CI run, the following legend is displayed at the top: `This job didn't run in this attempt. Logs shown are from a previous attempt`. Can we be sure that it's a bug in the UI and the job actually ran?

Somebody hit the retry button in azdo. There was a job unrelated that failed.

**Comment by jeffschwMSFT** [comment]
@steveisok this good to close now?

**Comment by steveisok** [comment]
> @steveisok this good to close now?

Indeed!

**Pull request closed without merging**
