### PR TITLE
Update build numbers of xunit and xunit.runner.visualstudio

### PR DESCRIPTION
**Pull request by bradwilson**

### CODE REVIEW

**Review by srivatsn — APPROVED** [review]

**Comment by srivatsn** [comment]
Tagging @MattGertz for RC3. This is an update to the xunit package version in the xunit template.

**Comment by MattGertz** [comment]
Groovy, let's take it to Shiproom.

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by natidea** [comment]
This needs to be retargeted to dev15-rc3. Approved to merge

**Pull request merged**
