### PR TITLE
Update branding for 110

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by wtgodbe** [comment]
Lots of test failures with:

> error NU5037: The package is missing the required nuspec file. Path: F:\workspace\_work\1\s\artifacts\.nuget\packages\system.linq.expressions\4.1.0

@wli3 @dsplaisted @sfoslund have you seen this before?

**Comment by dsplaisted** [comment]
This is only failing on Full framework, so it's likely an interaction with NuGet from VS.

@nkolev92 @zkat Any ideas here?

**Comment by dsplaisted** [comment]
The NU5037 failure seems to have been transient.  However, we are getting this failure on F# tests:

> FSC error FS0078: Unable to find the file 'netstandard.dll' in any of C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades C:\git\dotnet-sdk\artifacts\tmp\Debug\It_builds_a_s---7735ED47 C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp\ [C:\git\dotnet-sdk\artifacts\tmp\Debug\It_builds_a_s---7735ED47\TestApp.fsproj]

@cartermp @KevinRansom This error is happening with VS 16.8 Preview 3, though it is not happening locally for me with a later build.  Does this sound like a bug that has since been fixed?

**Comment by mmitche** [comment]
@dsplaisted Why would we use a preview VS build with the 100 band SDK?

**Comment by dsplaisted** [comment]
> @dsplaisted Why would we use a preview VS build with the 100 band SDK?

Good question.  I think it's probably because we generally use the same queues for all the different branches.

**Comment by mmitche** [comment]
> > @dsplaisted Why would we use a preview VS build with the 100 band SDK?
> 
> Good question. I think it's probably because we generally use the same queues for all the different branches.

It looks like it's using preview queues to build publicly: https://github.com/dotnet/sdk/blob/release/3.1.1xx/.vsts-ci.yml#L35
But VS2017 queue to build privately: https://github.com/dotnet/sdk/blob/release/3.1.1xx/.vsts-ci.yml#L38

I think the 1xx SDK should track 2017 in both secnearios. You wouldn't want to build the LTS with preview bits.

**Comment by cartermp** [comment]
Same F# issue as here: https://github.com/dotnet/sdk/pull/13969

**Pull request merged**
