### PR TITLE
Add internal _UseManagedNtlm feature switch

### PR DESCRIPTION
**Pull request by filipnavara**
Ref: https://github.com/dotnet/runtime/pull/90957#issuecomment-1691601831

### CODE REVIEW

**Review by sbomer — COMMENTED** [review]
Could you also add this new switch to the KitchenSink test? https://github.com/dotnet/sdk/blob/main/src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj and https://github.com/dotnet/sdk/blob/main/src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs.

**Review by sbomer — APPROVED** [review]
LGTM, thanks!

**Comment by filipnavara** [comment]
cc @wfurt ... we need this along with https://github.com/dotnet/runtime/pull/90957

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
