### PR TITLE
Update to nuget pack 4.0.0-rc2

### PR DESCRIPTION
**Pull request by rrelyea**

### CODE REVIEW

**Comment by rrelyea** [comment]
@joelverhagen @livarcocc @piotrpMSFT

**Comment by nguerrera** [comment]
@rrelyea Still blocked on not having a build of CLI with up-to-date nuget that works on Ubuntu14.04 as well as Windows (x64). @livarcocc is kicking the builds, now we wait.

**Comment by rohit21agrawal** [comment]
@dotnet-bot test this please.

**Comment by nguerrera** [comment]
Replaced by #440

**Pull request closed without merging**
