### PR TITLE
Update stage0

### PR DESCRIPTION
**Pull request by sbomer**

### CODE REVIEW

**Comment by sbomer** [comment]
@dsplaisted would you be able to look into the failures? I see two kinds:

```
It was not possible to find any compatible framework version\nThe specified framework 'Microsoft.NETCore.App', version '2.2.5' was not found.
```
due to the update in https://github.com/dotnet/core-sdk/commit/6e33b6e3de9da31f9769f31d3720706365c869d9. I'm not sure where/when 2.2.5 is supposed to be published.

The second failure is a mismatch in the expected/actual assemblies listed in the deps file, which seems like it could be related to the first failure:
```
Expected collection {\"TestApp.dll\", \"Microsoft.CSharp.dll\", \"Microsoft.VisualBasic.Core.dll\", \"Microsoft.VisualBasic.dll\", \"Microsoft.Win32.Primitives.dll\", \"mscorlib.dll\", \"netstandard.dll\", \"System.AppContext.dll\", \"System.Buffers.dll\", \"System.Collections.Concurrent.dll\", \"System.Collections.dll\", \"System.Collections.Immutable.dll\", \"System.Collections.NonGeneric.dll\", \"System.Collections.Specialized.dll\", \"System.ComponentModel.Annotations.dll\", \"System.ComponentModel.DataAnnotations.dll\", \"System.ComponentModel.dll\", \"System.ComponentModel.EventBasedAsync.dll\", \"System.ComponentModel.Primitives.dll\", \"System.ComponentModel.TypeConverter.dll\", \"System.Configuration.dll\", \"System.Console.dll\", \"System.Core.dll\", \"System.Data.Common.dll\", \"System.Data.DataSetExtensions.dll\", \"System.Data.dll\", \"System.Diagnostics.Contracts.dll\", \"System.Diagnostics.Debug.dll\", \"System.Diagnostics.DiagnosticSource.dll\", \"System.Diagnostics.FileVersionInfo.dll\", \"System.Diagnostics.Process.dll\", \"System.Diagnostics.StackTrace.dll\", ...121 more...} to be equivalent to {\"TestApp.dll\", \"Microsoft.CSharp.dll\", \"Microsoft.VisualBasic.dll\", \"Microsoft.VisualBasic.Core.dll\", \"Microsoft.Win32.Primitives.dll\", \"mscorlib.dll\", \"netstandard.dll\", \"Newtonsoft.Json.dll\", \"System.AppContext.dll\", \"System.Buffers.dll\", \"System.Collections.Concurrent.dll\", \"System.Collections.dll\", \"System.Collections.Immutable.dll\", \"System.Collections.NonGeneric.dll\", \"System.Collections.Specialized.dll\", \"System.ComponentModel.Annotations.dll\", \"System.ComponentModel.DataAnnotations.dll\", \"System.ComponentModel.dll\", \"System.ComponentModel.EventBasedAsync.dll\", \"System.ComponentModel.Primitives.dll\", \"System.ComponentModel.TypeConverter.dll\", \"System.Configuration.dll\", \"System.Console.dll\", \"System.Core.dll\", \"System.Data.Common.dll\", \"System.Data.dll\", \"System.Data.DataSetExtensions.dll\", \"System.Data.SqlClient.dll\", \"System.Diagnostics.Contracts.dll\", \"System.Diagnostics.Debug.dll\", \"System.Diagnostics.DiagnosticSource.dll\", \"System.Diagnostics.FileVersionInfo.dll\", ...120 more...}, but it contains too many items.
```

**Comment by dsplaisted** [comment]
For the first failure, 2.2.4 needs to be updated to 2.2.5 [here](https://github.com/dotnet/sdk/blob/260d55d2a1b5fe6961b1b7454d8ebf971181b177/eng/restore-toolset.ps1#L21) and the corresponding .sh file.

For the second failure, probably the Framework added some files which are now contained in the self-contained output, and the baseline for the test needs to be updated.  When this happens I debug the test and look at the variables [here](https://github.com/dotnet/sdk/blob/260d55d2a1b5fe6961b1b7454d8ebf971181b177/src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPreserveCompilationContext.cs#L129-L130) to see what was added or removed.

**Comment by sbomer** [comment]
Thank you! I'll make those updates in a bit.

**Comment by sbomer** [comment]
@dsplaisted PTAL

**Review by dsplaisted — APPROVED** [review]

**Pull request merged**
