### PR TITLE
Use Process.Kill(true) instead of KillTree

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
I'm going to yolo this for 6.0. We can see what falls out of it.

**Review by jkotalik — APPROVED** [review]
Make sure you follow up on this for the runtime folks!

Also, we want to do the same on the aspnetcore repo.

**Comment by danmoseley** [comment]
linking https://github.com/dotnet/runtime/issues/45017

**Comment by pranavkm** [comment]
@danmoseley I tried this change in the ASP.NET Core repo: https://github.com/dotnet/aspnetcore/pull/29016 but had to cancel that PR because the change caused some tests (that attempt to process-kill) to hang indefinitely. dotnet-watch has tests that verify the process it launches is killed, but none that verifies that a graph of processes is cleaned up. But preview2 is as good as any release to get customer feeedback on this.

**Pull request merged**
