### PR TITLE
Disable R2R compilations for non-exe projects

### LINKED ISSUE #3364: Block R2R compilation for library projects
Publish on library is a strange case already and trips people up a lot.

It could also be a source of problems if some lib developer publishes R2R for a certain platform/arch, and another app developer uses that lib on a different target

### PR DESCRIPTION
**Pull request by fadimounir**
Fixes #3364

### CODE REVIEW

**Comment by fadimounir** [comment]
@nguerrera PTAL.
Should this be merged to master or the release branch?

**Comment by fadimounir** [comment]
@livarcocc PTAL. If we can get this for preview 7 that would be great.

**Comment by livarcocc** [comment]
@fadimounir P7 is now in QB mdoe only changes. Do you feel like this would meet the bar or would it be ok to get this for P8?

**Comment by fadimounir** [comment]
We can git this for P8.

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
