### PR TITLE
Add Mono Stage 2 Leg to VMR SB

### LINKED ISSUE #4465: CI support for Mono stage 2 build
Consider adding a Mono build leg for the stage 2 scenario. Today we only build with Mono in stage 1. This would help to fill a gap that didn't catch https://github.com/dotnet/source-build/issues/4463.

### PR DESCRIPTION
**Pull request by ellahathaway**
Closes https://github.com/dotnet/source-build/issues/4465

This PR adds a Mono Stage 2 Leg to dotnet-source-build. [Here is an example run of the pipeline](https://dev.azure.com/dnceng/internal/_build/results?buildId=2497104&view=logs&s=9b073b6c-199e-5782-2adb-83c30ea48e21) with the proposed changes (internal Microsoft link).

### CODE REVIEW

**Comment by mthalman** [comment]
I'd like to have https://github.com/dotnet/source-build/issues/4465 triaged before merging this.

**Comment by ellahathaway** [comment]
> I'd like to have https://github.com/dotnet/source-build/issues/4465 triaged before merging this.

Makes sense. I'll convert this to a draft for now.

**Comment by MichaelSimons** [comment]
@ellahathaway - can you confirm the fsharp fix has flown into the SDK?  If not we should hold off on merging.

**Review by MichaelSimons — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Note that CI is currently on the floor. Will be fixed with https://github.com/dotnet/sdk/pull/41621

**Comment by ellahathaway** [comment]
> @ellahathaway - can you confirm the fsharp fix has flown into the SDK? If not we should hold off on merging.

Sure! Just queued https://dev.azure.com/dnceng/internal/_build/results?buildId=2478624&view=results. If it's green I'll merge.

**Comment by ellahathaway** [comment]
My test run is encountering the Stage 2 errors in https://github.com/dotnet/source-build/issues/4477 so I cannot validate if the previous fsharp error was fixed.

**Comment by ellahathaway** [comment]
> I will try to resolve them on Monday.

Thanks Viktor!

**Comment by ViktorHofer** [comment]
Note that stage2 is still broken until https://github.com/dotnet/sdk/pull/41826 is merged.

**Comment by ellahathaway** [comment]
> Note that stage2 is still broken until #41826 is merged.

Sounds good. I moved the associated issue to blocked in the meantime.

**Comment by ViktorHofer** [comment]
This is finally unblocked :)

**Comment by ellahathaway** [comment]
> This is finally unblocked :)

Wonderful! I'll queue a run of the full pipeline to check the stage 2 build.

**Comment by ellahathaway** [comment]
New pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2490555&view=results (internal Microsoft link)

**Comment by ellahathaway** [comment]
More unrelated failures: https://github.com/dotnet/source-build/issues/4494

**Comment by ellahathaway** [comment]
Testing again now that stage 2 has been fixed: https://dev.azure.com/dnceng/internal/_build/results?buildId=2497104&view=logs&s=9b073b6c-199e-5782-2adb-83c30ea48e21

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
