### PR TITLE
Re-bootstrap with Preview 6 SDK

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
I've picked up SDK and PSB Artifacts from Alpine Online MsftSdk and CentOSStream8 Online MsftSdk legs from the first VMR build that contains the fix: https://dev.azure.com/dnceng/internal/_build/results?buildId=2466165&view=results

SDK version was picked up from: https://dev.azure.com/dnceng/internal/_build/results?buildId=2466107&view=results

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Review by MichaelSimons — APPROVED** [review]

**Comment by NikolaMilosavljevic** [comment]
2 failures.

**sdk-unified-build (VMR Vertical Build Ubuntu2404_DevVersions_x64)**
```
/vmr/.dotnet/sdk/9.0.100-preview.6.24303.27/Roslyn/Microsoft.CSharp.Core.targets(85,5): error MSB6006: "csc.dll" exited with code 139. [/vmr/src/nuget-client/src/NuGet.Core/NuGet.ProjectModel/NuGet.ProjectModel.csproj]
```

**sdk-unified-build (VMR Vertical Build Windows_x64)**
```
    D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System\Drawing\ImageConverter.cs(42,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj::TargetFramework=net8.0]
    D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System\Drawing\ImageConverter.cs(42,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj::TargetFramework=net9.0]
    D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System\Drawing\Imaging\Effects\Effect.cs(11,1): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj::TargetFramework=net9.0]
```

**Comment by akoeplinger** [comment]
The first one is likely not related, `"csc.dll" exited with code 139` means the process crashed, I think I've seen that happen occasionally.

For the winforms errors we probably need to disable IDE0036 temporarily.

**Comment by NikolaMilosavljevic** [comment]
> The first one is likely not related, `"csc.dll" exited with code 139` means the process crashed, I think I've seen that happen occasionally.
> 
> For the winforms errors we probably need to disable IDE0036 temporarily.

Thanks. We'll need a patch for `winforms` - I'll update the PR.

**Review by mthalman — APPROVED** [review]

**Comment by NikolaMilosavljevic** [comment]
Two more errors in winforms:
```
2024-06-06T00:13:43.6038475Z     D:\a\_work\1\vmr\src\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.ComponentThreadContext.cs(17,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
2024-06-06T00:13:43.6039507Z     D:\a\_work\1\vmr\src\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.LightThreadContext.cs(13,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [D:\a\_work\1\vmr\src\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
```

**Pull request merged**
