### PR TITLE
Remove Jab dependency

### PR DESCRIPTION
**Pull request by eerhardt**
The DependencyInjection usage isn't necessary in ApiCompat. It can simplified to using Lazy<T> for singleton services, and just creating objects directly when necessary.

This removes the dependency on an external library, and simplifies source-build, since we no longer need to build another repo.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
As discussed offline, this makes sense and looks good! Thanks a lot

**Comment by eerhardt** [comment]
Test failures are #27767. Merging.

**Comment by joperezr** [comment]
> As discussed offline, this makes sense and looks good! 

I'd be interested in knowing the conclusions of the chat, since as you may recall I gave this feedback when the dependency was originally added.

**Review by joperezr — APPROVED** [review]
Changes look good, thanks @eerhardt!

**Comment by ViktorHofer** [comment]
> I'd be interested in knowing the conclusions of the chat, since as you may recall I gave similar feedback when the dependency was originally added.

Shared the offline Teams conversation around that with you.

**Pull request merged**
