### PR TITLE
Dev/merge internal 082420/release/5.0.1xx preview8

### PR DESCRIPTION
**Pull request by wli3**

### CODE REVIEW

**Review by sfoslund — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Comment by wli3** [comment]
packages are not in public feed yet. Will wait for tomorrow

**Comment by mmitche** [comment]
I believe we need to push the transport packages to the dotnet5 public feeds.

**Comment by mmitche** [comment]
one more attempt after pushing teh templating packages
/azp run

**Pull request merged**
