### PR TITLE
Insert NuGet Build 5.0.1-rtm.5946 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 5.0.1-rtm.5946 into sdk release/2.1.6xx branch

### CODE REVIEW

**Comment by nkolev92** [comment]
Unclear yet whether this actually needs to happen. 

Will ping again when I know more.

**Comment by nguerrera** [comment]
cc @peterhuene

**Comment by vivmishra** [comment]
Approved by 2.1.604

**Review by peterhuene — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by peterhuene** [comment]
So the stage0 build was internal and not pushed to storage.  Since we no longer trigger on this branch for CLI any more, I had to queue up manual builds.  Once that completes, I'll amend the commit to the appropriate public build.

**Comment by peterhuene** [comment]
@dotnet-bot test this please.

**Pull request merged**
