### PR TITLE
Merge release/5.0.1xx-preview1 to master

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@MSLukeWest @swaroop-sridhar The test failure looks to be a conflict between these:

* 43eb71d
* 1f2a4a1

I tried to fix the first error by absorbing a target rename in 3dac307, but that wasn't sufficient.

**Comment by swaroop-sridhar** [comment]
@nguerrera,  Given 1f2a4a1, we should undo most of the change in 43eb71d, because `ResolvedFilesToPublish` is actually consistent now in both single-file and non-single-file scenarios. In PublishSingleFile case, we only need to add the single-file bundle itself.  I'm happy to fix this.

**Comment by nguerrera** [comment]
Thanks, @swaroop-sridhar, go ahead and push to this PR branch. :)

**Comment by swaroop-sridhar** [comment]
https://github.com/nguerrera/sdk/pull/2

**Comment by swaroop-sridhar** [comment]
@nguerrera  Looks like `PublishItemsOutputGroupTests` have now passed.

**Comment by nguerrera** [comment]
Thanks I’ll move on to the remaining failures

**Comment by ViktorHofer** [comment]
@nguerrera I believe we should remove https://github.com/dotnet/sdk/pull/10732/commits/508463d28059ea9968bc1a43c46cec87390ad003 from the commits.

**Comment by nguerrera** [comment]
@ViktorHofer Good catch

**Comment by nguerrera** [comment]
I'll do a revert revert in case there is a need to do another merge from preview1.

**Review by ViktorHofer — APPROVED** [review]

**Comment by nguerrera** [comment]
@dsplaisted @wli3 This is finally green. Please review.

**Review by swaroop-sridhar — APPROVED** [review]

**Comment by ViktorHofer** [comment]
I hope this can go in now.

@jaredpar after this is merged, we got an official build and it got ingested into core-sdk which then produced an official build, we can consume a new SDK with the nuget fix 💃

**Review by wli3 — APPROVED** [review]

**Comment by mmitche** [comment]
Thanks @wli3!

**Pull request merged**
