### PR TITLE
Merge master into release/2.0.0

### PR DESCRIPTION
**Pull request by livarcocc**
@dotnet/dotnet-cli

@mattgertz merging master into release/2.0.0 so that we can move our development to this 2.0 branch.

### CODE REVIEW

**Comment by livarcocc** [comment]
test ci please

**Comment by livarcocc** [comment]
This is failing because we changed our format for our test results.

@mmitche how can I force this CI to run using the new configuration in the netci.groovy file?

**Comment by livarcocc** [comment]
@dotnet-bot test CI

**Review by nguerrera — APPROVED** [review]

**Comment by eerhardt** [comment]
> how can I force this CI to run using the new configuration in the netci.groovy file?

What we did in core-setup for a similar situation was merged in the netci.groovy changes first. Then run the CI against the PR.  Of course this breaks the branch for a while, but at least you get verification against your merge.

The other option is just merging the whole change into the branch and then running a "follow-up" PR that changes a .md file.

Either way there is a chance the branch is broken.  In the first case, it for sure is broken because the .groovy file is not sync'd with what's in the branch.  In the second case, you have a chance that the merge "just worked" and the branch isn't actually broken.

**Comment by livarcocc** [comment]
Trying @eerhardt's approach here.

**Pull request merged**
