### PR TITLE
Updated NuGet version for VS 15.3 preview3 release

### PR DESCRIPTION
**Pull request by jainaashish**
Updated NuGet version for VS 15.3 preview3 release

@rrelyea @emgarten @livarcocc @natidea @srivatsn @dsplaisted @rohit21agrawal

### CODE REVIEW

**Review by emgarten — APPROVED** [review]

**Comment by livarcocc** [comment]
@dsplaisted can you take a look? this is failing on a check that you added.

**Comment by dsplaisted** [comment]
@livarcocc at a glance, this looks like the normal issues we have when we need to update NuGet.  Our tasks depend on the NuGet APIs, and are built against the version of NuGet that's updated in this repo.  However, at runtime it loads the versions that are bundled in the CLI, causing this failure.  The task I added is now probably always the first SDK task that would be loaded that uses the NuGet APIs.

We need to do the dance where we create a build of the SDK from a separate branch with tests disabled, insert that into the CLI (while simultaneously updating the CLI's version of NuGet), and then insert the updated CLI back into the SDK together with the NuGet version update.

**Comment by jainaashish** [comment]
@dsplaisted so can you please take care of this?

**Comment by livarcocc** [comment]
@jainaashish where are the equivalent PRs to the dotnet/cli repo?

**Comment by jainaashish** [comment]
@dsplaisted I haven't created those yet since I was waiting for this to be completed. But let me create those as well.

**Comment by livarcocc** [comment]
those need to happen first actually.

**Comment by jainaashish** [comment]
here you go - https://github.com/dotnet/cli/pull/6744 https://github.com/dotnet/cli/pull/6745

**Comment by dsplaisted** [comment]
The remaining failure looks like #1289, which should be fixed by #1290

**Comment by dsplaisted** [comment]
@dotnet-bot test this

**Comment by dsplaisted** [comment]
@dotnet-bot test this please

**Comment by dsplaisted** [comment]
@MattGertz FYI for NuGet insertion

**Pull request merged**
