### PR TITLE
Set the EnableDynamicLoading property before importing Microsoft.PackageDependencyResolution.targets

### PR DESCRIPTION
**Pull request by jkoritzinsky**
The condition for `CopyLocalLockFileAssemblies` in Microsoft.Package.DependencyResolution.targets depends on the `EnableDynamicLoading` property and should be true in the `EnableComHosting` case.

This issue was discovered when working on https://github.com/dotnet/winforms/pull/4685

cc: @ericstj @RussKie

### CODE REVIEW

**Review by dsplaisted — APPROVED** [review]
Could we have a test for this?  It could go next to `GivenThatWeWantToBuildALibrary.It_can_build_with_dynamic_loading_enabled`

**Comment by dsplaisted** [comment]
FYI @elinor-fung @jkoritzinsky, looks like this has been broken since before #3305

**Review by RussKie — APPROVED** [review]
👍 

Tested in https://github.com/dotnet/winforms/pull/4685#issuecomment-899882567

**Comment by ericstj** [comment]
So @russkie mentioned this regressed in preview7 https://github.com/dotnet/winforms/pull/4685#issuecomment-899204843

Do we understand why it regressed to make sure there aren't any other properties regressed?

**Comment by dsplaisted** [comment]
No, I don't know why this would have regressed in Preview 7.  I looked at the diff between Preview 5 and Preview 7 for Microsoft.NET.Sdk.targets and Microsoft.PackageDependencyResolution.targets, and it doesn't look like anything changed that would have affected this.

I don't know exactly what regressed or how, but it seems like it may not have been related to the issue being fixed in this PR.

**Comment by jkoritzinsky** [comment]
Based on https://github.com/dotnet/samples/pull/4773, I believe this regressed due to the `.runtimeconfig.dev.json` not being produced by default any more.

**Pull request merged**
