### PR TITLE
Allow dotnet host path to be overridden via DOTNET_INSTALL_DIR environment variable

### LINKED ISSUE #2098: Do not assume specific location of dotnet CLI
The tests currently assume dotnet CLI is installed in `$(RepoRoot)/.dotnet`:

https://github.com/dotnet/sdk/blob/master/src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs#L119

Instead the tests should use `DOTNET_INSTALL_DIR` environment variable to locate dotnet CLI.

In future we might want to change this to `DOTNET_ROOT`, once it's implemented.

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes #2098

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows_NT Release

**Comment by livarcocc** [comment]
Build timeout, likely machine problem.

@dotnet-bot Test OSX10.12 Debug

**Comment by dsplaisted** [comment]
@dotnet-bot Test OSX10.12 Debug

**Comment by dsplaisted** [comment]
@MattGertz FYI, this is a test-only change

**Pull request merged**
