### PR TITLE
Fix the cppcli tests by upgrading to preview 7 in stage 0

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@jjonescz @jared to fix a windows sdk issue that was failing the cppcli tests, I upgraded to preview 7. This caused a bunch of failures as it triggered the torn toolset package to be downloaded for our tests (but it expected the -ci version of the package). I disabled using the torn toolset in our helix tests by changing the .cmd file to set the build with framework to false. However, that broke one of the tests we had for that.

I tried fixing it and failed so I went ahead and disabled so we could get unblocked but we'll want to figure out how to fix it later:
It_downloads_Microsoft_Net_Compilers_Toolset_Framework_when_MSBuild_is_torn

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
approving preemptively if this goes green this is an infrastructure change that broken things

**Comment by marcpopMSFT** [comment]
Following up on this @jjonescz @dsplaisted an alternative to disabling the roslyn package in our tests is to copy it to our nuget cache so the tests can find it. That would fully test this package more. It's probably worth filing an issue to do that instead.

**Pull request merged**
