### PR TITLE
Delete src/SourceBuild/patches/roslyn/0001-ambiguous-call-site.patch

### PR DESCRIPTION
**Pull request by ViktorHofer**
Testing

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@Jozkee can you please help with the failure in the sdk-source-build leg? Is the ambiguous call breaking change intentional?

`/vmr/src/roslyn/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CodeGenerationHelpers.cs(74,27): error CS0121: The call is ambiguous between the following methods or properties: 'string.Join(string?, ReadOnlySpan<object?>)' and 'string.Join(string?, ReadOnlySpan<string?>)' [/vmr/src/roslyn/src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj::TargetFramework=net9.0]`

cc @jeffhandley

**Comment by Jozkee** [comment]
You can fix it by changing the [src](https://github.com/dotnet/roslyn/blob/35e4223e35fc8f924d6f9e1b0728916f5bcb4433/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeGeneration/CodeGenerationHelpers.cs#L74) to `string.Join(".", (ReadOnlySpan<string?>)[.. names])` that seems like the best target between `ReadOnlySpan<string?>` and `ReadOnlySpan<object?>`.

It is not clear to me why the collection expression `[.. names]` gets ambiguous here cc @dotnet/roslyn.

**Comment by Jozkee** [comment]
Seems like you still need to keep the patch because roslyn hasn't bumped their [dotnet version](https://github.com/dotnet/roslyn/blob/35e4223e35fc8f924d6f9e1b0728916f5bcb4433/global.json#L3) and haven't stepped into this error.

**Comment by ViktorHofer** [comment]
Just realized that this only affects source-build because in that build configuration, the library in question targets `net9.0` while the msft build targets `net8.0`. That TFM difference is intentional.

**Comment by 333fred** [comment]
> I'm more concerned about a potential breaking change for our customers that we don't know about yet. 

This will be solved by first-class spans. @jjonescz, another test case for the matrix.

**Comment by 333fred** [comment]
I expect it will work like arrays do in this scenario, because ROS<string> is a more specific type than ROS<object>. If that isn't the case, that's concerning, because the point of first-class spans _is_ to solve cases like this where spans behave differently than arrays. https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRj1UwAJUCAWAbj2IIE4AKAIkB4NwEH2WBKW3AGQCWAZ2AAeCpgB8pKAEMAtgFNhpALyylAdya88AYQB0AKQD2gqKxYxSAbUOH5y4QF09uYulL7SAb3oAbOQAzOQEZGYWTJKkwkoADnJgcsCmYDaSti6kAG5yADYQStzqMiySLHwUQaihMZGWMXGJyanppKYARgBWSgDGwFm5BUUlamVdvQOVeAC+pEA==

**Comment by cston** [comment]
> I expect it will work like arrays do in this scenario, because `ROS<string>` is a more specific type than `ROS<object>`.

The better conversion rules for collection expression conversions do not include a variance rule for `ReadOnlySpan<T>` (that was probably an oversight), and the rules do not fall back to implicit conversion when the two types are span types, so this case will not be handled by the implicit conversions for *first-class spans*.

The fix may be to add a rule to [better conversion](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#overload-resolution) for collection expressions for `ReadOnlySpan<T>` variance, or perhaps remove the collection expression specific rules entirely and rely on *first-class spans* when compiling with `-langversion:13` or higher.

**Comment by cston** [comment]
> The fix may be to add a rule to [better conversion](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#overload-resolution) for collection expressions for `ReadOnlySpan<T>` variance, or perhaps remove the collection expression specific rules entirely and rely on _first-class spans_ when compiling with `-langversion:13` or higher.

Actually, removing the collection expression rules (and relying on *first-class spans*) would be a breaking change since we currently prefer `ReadOnlySpan<T>` over `Span<T>` for collection expressions while *first-class spans* prefers `Span<T>`.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/roslyn/pull/73656 now hits the failure as well and I expect the roslyn team to fix / work around this directly in the roslyn code base to unblock the Arcade dependency flow. Therefore closing this PR.

**Pull request closed without merging**
