### PR TITLE
Revert workaround for runtimeconfig generation issue

### PR DESCRIPTION
**Pull request by dsplaisted**
Original commit: 150c6fa0aae7347be7e3a452492faad5ddb34f7e.

PR with discussion of issue and workaround: #17948

Workaround is no longer needed with #17982

The workaround seems to negatively affect the local dev experience for this repo, as you often run into locked task files when trying to build.

### CODE REVIEW

**Comment by dsplaisted** [comment]
@dotnet/msbuild @rainersigwald When I update stage 0, this is now failing with:

> C:\git\dotnet-sdk\sdk.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.

This is when Arcade is using the MSBuild task to build the solution file.  The solution file hasn't changed, and works with `dotnet build` and Visual Studio.  Has something changed that could impact how the MSBuild task works with solution files?

**Comment by rainersigwald** [comment]
> > C:\git\dotnet-sdk\sdk.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.
> 
> This is when Arcade is using the MSBuild task to build the solution file. The solution file hasn't changed, and works with `dotnet build` and Visual Studio. Has something changed that could impact how the MSBuild task works with solution files?

This sounds like the "can't build solution out-of-proc" issue that @rokonec was working on. It's likely related to the NOINPROCNODE change.

**Comment by marcpopMSFT** [comment]
@dsplaisted can this be closed since preview 6 is done?  Does it need to be in main?

**Comment by dsplaisted** [comment]
We should eventually try to get it into main.

**Review by sfoslund — APPROVED** [review]

**Pull request merged**
