### PR TITLE
Include version in deps.json

### LINKED ISSUE #12301: GenerateDepsFile doesn't include file or assembly version for Project references
Create an app with a reference to another project.  Build.  Examine deps file.

Expect: file of referenced project includes file and assembly version.
Actual: versions are missing.

Compare to.  Raw file reference to output TargetPath of the project.  This will include the file and assembly versions.

This hinders a fix for https://github.com/dotnet/runtime/issues/698

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #12301

Assembly version is easy. File version is best effort, since I didn't see a better way to find the 'real' path to the output assembly than using the paths passed in when calling the task. I don't know if that's guaranteed to be complete, but it at least had what I needed in the simple case I was testing, and if it's missing, it should just not include it rather than failing.

Before:
image

After:
image

The app (12301.csproj in this case) has a ProjectReference to library. This adds the assembly version and file version to that reference in the deps.json.

### CODE REVIEW

**Review by dsplaisted — COMMENTED** [review]
I would prefer to see a test for this.  It would help make it clearer what the change does and make it easier to review.

**Comment by Forgind** [comment]
This isn't worth a test. I added two screenshots instead.

**Review by nagilson — APPROVED** [review]
Thank you for this change, it looks good to me! The screenshot was helpful. I would retarget this to 8.0.400 or main before merging, though.

**Comment by Forgind** [comment]
> Thank you for this change, it looks good to me! The screenshot was helpful. I would retarget this to 8.0.400 or main before merging, though.

Good point. I can retarget to 8.0.4xx.

**Pull request merged**
