### PR TITLE
Generate Content for a Test at Run-time -- release/3.1.2xx

### PR DESCRIPTION
**Pull request by wli3**
With this change, a part of the content for the test-asset HellowWorldWithSubDirs
is not checked in, but generated during test execution in order to circumvent certain issues like:
* Git Clone: Cannot clone files with long names on Windows if long file name support is not enabled
* Nuget Pack: By default ignores files starting with "."

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
Hmm, @msftbot didn't comment on auto merge tag, are we missing something on this repo to use it?

**Comment by wli3** [comment]
@nguerrera  i haven't dig into it, but SDK repo works while on CLI the bot comments but it does not actually merge

**Comment by nguerrera** [comment]
@wli3 On core-sdk it merged: https://github.com/dotnet/core-sdk/pull/5812

**Comment by nguerrera** [comment]
I asked on Teams about how to onboard it correctly.

**Pull request merged**
