### PR TITLE
[release/7.0.1xx] Update man pages post 7.0 GA

### PR DESCRIPTION
**Pull request by omajid**
There are no manual changes in this commit. Everything was done by `sdk/documentation/manpages/tool/run_docker.sh`.

### CODE REVIEW

**Comment by omajid** [comment]
cc @baronfel @dsplaisted @tdykstra

**Comment by omajid** [comment]
Anyone know if we can somehow hook up running `sdk/documentation/manpages/tool/run_docker.sh` to some sort of automation that runs it once every few months or so?

**Comment by baronfel** [comment]
@omajid checkout the `schedule` trigger for GitHub actions. You could create a scheduled action that worked on the main and release branches to do this.

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
let's wait to merge until 7.0.102 is open for changes.

**Pull request merged**
