### PR TITLE
[VMR] Enable building Mono Cross AOT verticals

### LINKED ISSUE #3845: Implement Vertical Build for Linux Alpine arm64 CrossAOT
This issue covers productization of the following vertical: **Linux Alpine arm64 CrossAOT**
- **Build OS**: Mariner
- **Target OS**: Linux Alpine
- **Build OS Arch**: x64
- **Target Arch**: arm64
- **Stack Type**: Short
- **Key Artifacts**: Linux Alpine arm64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3847: Implement Vertical Build for Linux Alpine x64 CrossAOT
This issue covers productization of the following vertical: **Linux Alpine x64 CrossAOT**
- **Build OS**: Mariner
- **Target OS**: Linux Alpine
- **Build OS Arch**: x64
- **Target Arch**: x64
- **Stack Type**: Short
- **Key Artifacts**: Linux Alpine x64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3852: Implement Vertical Build for Linux arm64 CrossAOT
This issue covers productization of the following vertical: **Linux arm64 CrossAOT**
- **Build OS**: Mariner
- **Target OS**: Linux GLIBC
- **Build OS Arch**: x64
- **Target Arch**: arm64
- **Stack Type**: Short
- **Key Artifacts**: Linux arm64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3862: Implement Vertical Build for Linux x64 CrossAOT
This issue covers productization of the following vertical: **Linux x64 CrossAOT**
- **Build OS**: Mariner
- **Target OS**: Linux GLIBC
- **Build OS Arch**: x64
- **Target Arch**: x64
- **Stack Type**: Short
- **Key Artifacts**: Linux x64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3872: Implement Vertical Build for MacOS arm64 CrossAOT
This issue covers productization of the following vertical: **MacOS arm64 CrossAOT**
- **Build OS**: MacOS
- **Target OS**: MacOS
- **Build OS Arch**: x64
- **Target Arch**: arm64
- **Stack Type**: Short
- **Key Artifacts**: MacOS arm64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3876: Implement Vertical Build for MacOS x64 CrossAOT
This issue covers productization of the following vertical: **MacOS x64 CrossAOT**
- **Build OS**: MacOS
- **Target OS**: MacOS
- **Build OS Arch**: x64
- **Target Arch**: x64
- **Stack Type**: Short
- **Key Artifacts**: MacOS x64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3888: Implement Vertical Build for Windows arm64 CrossAOT
This issue covers productization of the following vertical: **Windows arm64 CrossAOT**
- **Build OS**: Windows
- **Target OS**: Windows
- **Build OS Arch**: x64
- **Target Arch**: arm64
- **Stack Type**: Short
- **Key Artifacts**: Windows arm64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### LINKED ISSUE #3891: Implement Vertical Build for Windows x64 CrossAOT
This issue covers productization of the following vertical: **Windows x64 CrossAOT**
- **Build OS**: Windows
- **Target OS**: Windows
- **Build OS Arch**: x64
- **Target Arch**: x64
- **Stack Type**: Short
- **Key Artifacts**: Windows x64 CrossAOT Runtime Packs for Android and Wasm

Implementation of this vertical may depend on completion of other items within the Unified Build Space:
- [ ] *Link issues as necessary*

When complete, the following will be true:
- [ ] The vertical builds successfully and required changes are backported to individual repos.
- [ ] The vertical's outputs are verified as being complete and correct as compared to the current .NET official build.
- [ ] The vertical is enabled in VMR rolling CI and PR (if applicable).

**T-Shirt Size: Small (default, update as necessary)**

### PR DESCRIPTION
**Pull request by akoeplinger**
Contributes to https://github.com/dotnet/source-build/issues/3902

Closes https://github.com/dotnet/source-build/issues/3845
Closes https://github.com/dotnet/source-build/issues/3847
Closes https://github.com/dotnet/source-build/issues/3852
Closes https://github.com/dotnet/source-build/issues/3862
Closes https://github.com/dotnet/source-build/issues/3876
Closes https://github.com/dotnet/source-build/issues/3872
Closes https://github.com/dotnet/source-build/issues/3888
Closes https://github.com/dotnet/source-build/issues/3891

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
LGTM if it works

**Review by mmitche — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
