### PR TITLE
Insert NuGet Build 4.7.0-preview1-4927 into sdk

### PR DESCRIPTION
**Pull request by nugetlurker**
Insert NuGet Build 4.7.0-preview1-4927 into sdk release/2.1.2xx branch

### CODE REVIEW

**Comment by nguerrera** [comment]
This will fail until #1972 is merged up to the release/2.1.2xx branch.

**Comment by mishra14** [comment]
@dotnet-bot Test Windows_NT_FullFramework Debug
@dotnet-bot Test Windows_NT_FullFramework Release

**Comment by mishra14** [comment]
@nguerrera can we get this in now? https://github.com/dotnet/sdk/pull/1972 seems to be merged.

**Comment by nguerrera** [comment]
We needed #1974 too.

**Comment by nguerrera** [comment]
Should pass now

**Comment by mishra14** [comment]
@nguerrera tests are green now. Thanks! 

Just a followup, this PR is targeting 15.7 in VS world. I am not sure what 2.1.2xx corresponds to?

**Comment by nguerrera** [comment]
2.1.2xx correlates to 15.7 in VS. :)

**Review by nguerrera — APPROVED** [review]

**Pull request merged**
