### PR TITLE
dotnet tool install skip unlisted version

### LINKED ISSUE #24037: Unlisted packages are still installed via `dotnet tool install` without `--version` despite correctly not showing up in `dotnet tool search`
### Describe the bug
A tool that was incorrectly versioned was pushed to NuGet.org and had to be unlisted. 
The version is correctly hidden from searches both via nuget.org and via `dotnet tool search` but `dotnet tool install` seems to ignore this and just locate the version via the provided [v3-flatcontainer list](https://api.nuget.org/v3-flatcontainer/octopus.dotnet.cli/index.json) 
image

I can vaguely get on board with argument that if there are dependencies on that version then it shouldn't break them by being completely inacessable, but shouldn't that really only apply in that case if that specific version is requested via `--version` rather than by default?
What's the point of hiding it in the search if its still the one that is installed by default, that feels a little unexpected for the end user and potentially less safe.

It's worth noting this also [existed and since been fixed](https://github.com/NuGet/Home/issues/7466) in `NuGet.exe`

### To Reproduce
1. Publish two versions of a tool to nuget.org
2. [Unlist](https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages#unlisting-a-package) the latest version
3. Run `dotnet tool search <TOOLNAME>` and validate that the unlisted version does not show up
3. run `dotnet tool install --global <TOOLNAME>`
**Result**
The later but, _unlisted_ version is installed
**Expected**
The latest _listed_ result is installed

### Further technical details
This can be reproduced through the dotnet sdk container
```
> run --rm -it mcr.microsoft.com/dotnet/sdk:6.0 bash
> dotnet tool install --global Octopus.DotNet.Cli
```
using dotnet version `6.0.200`

**Update: 25 Feb** I have since had to contact the NuGet team directly to get the package properly "deleted" so the specific package in this example is no longer a problem but the fundamental issue still remains.

### PR DESCRIPTION
**Pull request by JiaqiWang18**
Fixes #24037 
Use the `NugetToolSearchApiRequest` to get the latest listed package version in `dotnet tool install <PACKAGE_ID>` when `--version` is not supplied.

### Manual Testing
Created a test tool `jackywang118.botsay` with two versions where the most recent version `2.0.0` is unlisted. 
Run `dotnet tool install jackywang118.botsay`, version `1.0.0` should be installed
A request to [https://azuresearch-usnc.nuget.org/query?q=jackywang118.botsay&packageType=dotnettool&semVerLevel=2.0.0](https://azuresearch-usnc.nuget.org/query?q=jackywang118.botsay&packageType=dotnettool&semVerLevel=2.0.0) is made to get the most recent listed package version

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
@baronfel

**Comment by baronfel** [comment]
This is great! I'd love to see a test validating the behavior though - I think that would require getting known packages with the expected unlisted/listed statuses added to the internal feeds.  

Scheduling-wise, @marcpopMSFT this rides the line between a fix and an feature - I think it's what users expect out of NuGet so I'd be happy to see this in 7.0.2xx rather than waiting for 8.0.1xx (which is what main is targeted for).

**Comment by JiaqiWang18** [comment]
> This is great! I'd love to see a test validating the behavior though - I think that would require getting known packages with the expected unlisted/listed statuses added to the internal feeds.
> 
> Scheduling-wise, @marcpopMSFT this rides the line between a fix and an feature - I think it's what users expect out of NuGet so I'd be happy to see this in 7.0.2xx rather than waiting for 8.0.1xx (which is what main is targeted for).

Thanks for the feedback! Could you point me to where these internal feeds are located? Is there an example test that is using this internal feed you are talking about?

**Comment by baronfel** [comment]
The feeds I mention are defined in the [nuget.config](https://github.com/dotnet/sdk/blob/0778d8b9b378acdbda21d3ff97917f2f35417dbf/NuGet.config#L15) in the root of the repo, so if you had sample packages that you wanted to use for a test, we could coordinate to get those versions downloaded to an appropriate feed (we have to communicate with an internal team for this), and then your test would be good to go.  @dotnet/domestic-cat is this an acceptable plan?

**Comment by JiaqiWang18** [comment]
> The feeds I mention are defined in the [nuget.config](https://github.com/dotnet/sdk/blob/0778d8b9b378acdbda21d3ff97917f2f35417dbf/NuGet.config#L15) in the root of the repo, so if you had sample packages that you wanted to use for a test, we could coordinate to get those versions downloaded to an appropriate feed (we have to communicate with an internal team for this), and then your test would be good to go. @dotnet/domestic-cat is this an acceptable plan?

I did create this package [`jackywang118.botsay`]( https://www.nuget.org/packages/jackywang118.botsay/) to test.
It has two versions where `2.0.0` is unlisted and `1.0.0` is not. Maybe this package could be added so that it can be used in test cases under `ToolInstallLocalCommandTests` and `ToolInstallGlobalOrToolPathCommandTests` to verify that only `1.0.0` will be installed if running `dotnet tool install jackywang118.botsay`

**Comment by JiaqiWang18** [comment]
@baronfel sounds like I can't test it by myself. Would it be reasonable to get this PR in and file another issue for the testing part?

**Comment by knocte** [comment]
ping? I'm affected by issue #24037 and would prefer this reviewed/merged instead of having to write a workaround.
Thanks!

**Comment by baronfel** [comment]
Thanks for the ping, @knocte - I dropped the ball on this one. Need to get a listed and unlisted package to test with into MS internal feeds, but we can't just take random packages. I'll pick this up again and work with the internal team to get tool packages created and pushed.

**Comment by baronfel** [comment]
@JiaqiWang18 is there source for `jackywant118.botsay` available?

**Comment by knocte** [comment]
@JiaqiWang18 ping?

**Comment by JiaqiWang18** [comment]
> @JiaqiWang18 is there source for `jackywant118.botsay` available?

@baronfel Yes, I do have the source code.

**Comment by knocte** [comment]
ping? :)

**Comment by JL03-Yue** [comment]
Investigating

**Review by JL03-Yue — APPROVED** [review]

**Comment by knocte** [comment]
Why was author information not preserved?

**Comment by marcpopMSFT** [comment]
> Why was author information not preserved?

Not sure what you mean. GH still considers jiaqiwang18 the [author ](https://github.com/dotnet/sdk/pulls?q=is%3Apr+author%3AJiaqiWang18+is%3Aclosed) of this PR. It lists Annie as the merger as someone from the team has to merge.

BTW, we chatted offline and investigated ways to test this using our internal AzDO feeds but were not able to do so and decided it wasn't worth investigating further for a regression test.

**Comment by knocte** [comment]
> GH still considers jiaqiwang18 the [author ](https://github.com/dotnet/sdk/pulls?q=is%3Apr+author%3AJiaqiWang18+is%3Aclosed)of this PR.

Right, but that's just GH, I'm referring to git.

> It lists Annie as the merger as someone from the team has to merge.

Normally when a PR is merged, there are 2 commits: the one from the merger and the real commit of the PR. In this case it has been squashed to one, but when you select this option in GH, it normally preserves author information (the one you extract with git tools, such as git log), why didn't it preserve it this way? I guess you used another tool to merge. I don't think this is an acceptable policy.

**Comment by marcpopMSFT** [comment]
Interesting. That seems like a bug in GH or maybe just unintended behavior of which option @JL03-Yue chose in the dropdown menu (GH includes three options when merging).

**Comment by elinor-fung** [comment]
I expect this was merged with 'Create a merge commit'. All the original commits - with correct author information - are there in the actual history:
https://github.com/dotnet/sdk/commits/main/src/Cli/dotnet/commands/dotnet-tool/install/ParseResultExtension.cs

As an aside - does the sdk repo have a general policy on which option to use? In runtime, we actually only allow squash and merge as we find that makes for simpler / easier to understand history.

**Comment by marcpopMSFT** [comment]
SDK has to use the merge commit option for the inter-branch codeflow as otherwise it gets confused about commits that were modified/reverted so I've left the default as that.  You're right though that squash and merge is better for history most of the time.

**Comment by pokdeep** [comment]
I think this change caused an issue I saw whilst building net8 rc1 base images in my companies build infrastructure. 
We use private nuget feeds and all traffic to nuget.org is blocked, our base images tries to install the latest version of certain dotnet tools e.g. coverlet.console, so we don't specify as version, but with this change it tries to connect to nuget.org to get latest versions causing the build to fail.

A workaround is to specify the version flag, e.g. `dotnet tool install coverlet.console --version 6.0.0` or `dotnet tool install coverlet.console --version 6` as a partial pin
[stacktrace.txt](https://github.com/dotnet/sdk/files/12648866/stacktrace.txt)

**Comment by marcpopMSFT** [comment]
@pokdeep please file a separate issue with the details and we'll take a look.

**Pull request merged**
