### PR TITLE
userlocal detection: also force last digits to zero for non-preview versions.

### PR DESCRIPTION
**Pull request by tmds**
@dsplaisted ptal.

cc @omajid

### CODE REVIEW

**Comment by omajid** [comment]
Without this fix, `dotnet workload install` fails when run as non-root on 6.0.101.

**Review by dsplaisted — APPROVED** [review]
Would it be possible to add some test coverage for this?

We're working on treating [different preview versions as different workload bands](https://github.com/dotnet/sdk/pull/22446).  I don't know if you want to do that here.  If so, we'd need to change the logic that drops the userlocal marker file to put it in a preview-specific directory as appropriate, and the logic here would change to use the `SdkFeatureBand` class to convert from the SDK version to the feature band version.

**Comment by marcpopMSFT** [comment]
@tmds @omajid Per Daniel's message about, would you be able to create a test for this and update the description with our tactics template (see any issues labeled servicing-approved)?  I wouldn't block on getting a test given the short timeframe for getting this in (Feb releases are code complete next week)

**Comment by tmds** [comment]
I'll look into this on Monday.

**Comment by omajid** [comment]
For what it's worth, we (Red Hat) included this fix as a local patch for our 6.0.101 builds. We can continue carrying that local fix for future releases (6.0.102?). We aren't blocked on the fix being merged here, though it would obviously be very nice to have and would benefit other users of source-build too.

**Comment by marcpopMSFT** [comment]
@leecow let's discuss in tactics tomorrow. RH has a workaround for this as they put the fix in their patch but others could be affected. We should decide where the fix should go.

**Pull request merged**
