### PR TITLE
Mark Razor source generator files as generated

### PR DESCRIPTION
**Pull request by martincostello**
Give the output files from the Razor Source Generator a `.g.cs` suffix so that they are treated as a generated file to prevent it being flagged by source analyzers for violations the application developer cannot fix themselves and so that tools such as coverlet ignore them.

I _think_ this is part of the fix (and is the same as #16777 which seems to have gone as part of somet refactoring), but I couldn't get the tests to debug through the source generator in Visual Studio 2022 preview 2, so I wasn't able to actually inspect my changes and check they were actually being applied.

I think there's _also_ an issue with coverlet, as if I try and exclude the RSG-generated files from coverage anyway using a filter of `[*]AspNetCoreGeneratedDocument*`, it still refuses to cover any of the code due to it being unable to find the files from the source-generator on disk.

I haven't gotten as far as trying to debug coverlet yet, but I noticed from structured logging that the source files from the RSG didn't have the `.g.cs` suffix:

```
[coverlet] Unable to instrument module: C:\Coding\martincostello\api\tests\API.Tests\bin\debug\net6.0\API.dll, pdb without local source files, [C:\Coding\martincostello\api\src\API\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Views_Docs_Index_cshtml.cs]
```

Relates to dotnet/aspnetcore#31719.

/cc @captainsafia

### CODE REVIEW

**Review by captainsafia — COMMENTED** [review]
Looks good!

There are some tests that need to be updated. They look for a particular file path. Doing a search of "Razor.SourceGenerator" should find the test cases that need to be updated to look for files with the `.g.cs` extension.

**Comment by martincostello** [comment]
Great, thanks. I'll get those updated 👍

**Comment by martincostello** [comment]
Passing now - I'm not sure what the dev workflow should be for these, but I couldn't seem to get the tests locally to consume the changes I was actually making, so I had to guess at whether it would fix and let AzDo run them for me to get the feedback.

**Comment by captainsafia** [comment]
@martincostello I typically use the instructions here for running tests from the command line: https://github.com/dotnet/sdk/blob/main/documentation/project-docs/developer-guide.md#using-the-built-dotnet

**Comment by martincostello** [comment]
@captainsafia Ah, I didn't find that, thanks 🤦 - I made the assumption it was like the aspnetcore repo, and used the restore, build and test `.cmd` files to do it. I'll know for the future now 😄

**Pull request merged**
