### PR TITLE
Fix available typo and XML typo

### PR DESCRIPTION
**Pull request by nagilson**
Fix for #18903 https://github.com/dotnet/sdk/issues/26021 
Also noticed there are 2 typos in all of the Resx file comments! (Not super important) @marcpopMSFT do you have any contacts on that team?

### CODE REVIEW

**Comment by danmoseley** [comment]
Yes it's probably not worth fighting the resx comment. Ideally the template wouldn't have these comments at all. Last time I asked about that, some time ago, they pointed out it would have to be done in such a way that it wasn't removed from existing files.

**Comment by marcpopMSFT** [comment]
@nagilson for translation/resource questions, reach out to @cristianosuzuki77

**Comment by danmoseley** [comment]
@nagilson I think removing the resx comment by default would require something like

1. find all the .NET SDK/VS code that edits resx files and ensure that it doesn't add the resx comment back if it is not already present.
2. remove the comment from some or all of the resx files included in project templates (these are in https://github.com/dotnet/templating and some other repos) plus the individual template for "add new resx file" (not sure where this is located, it's likely in VS sources)

for 1, ResxResourceWriter was already fixed in .NET Core it seems -- https://github.com/dotnet/winforms/pull/452. But if I make a new Winforms project, targeting .NET 7, remove the comment, and then edit the resources through the graphical designer, it puts it back. So a change would be needed in that designer -- I assume it is effectively part of the Winforms designer. Perhaps @DustinCampbell knows.

for 2, this can only be done for templates that will only be manipulated by tooling that has already been adjusted to be tolerant. Eg., we could remove the comment from templates for .NET 8, once the lowest version of Visual Studio supporting those templates had been changed. We would certainly not want to ship templates that VS or some other tool immediately dirties.

It would be nice to remove the schema at the same time - ResxResourceWriter still writes that. 

Having said all this, although I've long wished this be cleaned up, I can't claim it's any kind of priority.

**Comment by nagilson** [comment]
Thank you for the thorough explanation, there are more working parts to it than I thought. I see why it hasn't been done now. May discuss this with Rainer, though I don't think it will be on our priority list anytime soon. Perhaps if some free time emerges in some future sprint, I will take a look at it.

**Pull request merged**
