### PR TITLE
Mess around with the retry logic to help pinpoint the templating time…

### PR DESCRIPTION
**Pull request by marcpopMSFT**
…outs

### CODE REVIEW

**Review by joeloff — APPROVED** [review]
Looks like the PR passed the tests now in 27 minutes instead of timing out after 3 hours.

**Comment by marcpopMSFT** [comment]
A different test timed out instead on a different leg. I can't tell if it's related or not. Let's rerun everything to get more data.

**Comment by marcpopMSFT** [comment]
template engine failed in this run so this didn't help.

**Pull request closed without merging**
