### PR TITLE
Enable `dotnet run` to work on non-Windows environments

### PR DESCRIPTION
**Pull request by bradwilson**
Fix for #11787

### CODE REVIEW

**Review by marcpopMSFT — APPROVED** [review]
Did you test this locally? I don't think we have automated tests in the mono area.

**Comment by bradwilson** [comment]
On macOS 10.15.5:

image

**Comment by bradwilson** [comment]
I cannot test on Ubuntu 18.04:

image

Missing zlib isn't the problem:

image

Also, if you're wondering what those 12 changed files are, you have several `.sh` files that are missing execute bits:

image

I didn't make that change in this PR, but I can if you'd like.

**Comment by bradwilson** [comment]
You cannot test on Ubuntu 18.04 by default:

image

I was able to comment out the lines to install 1.0.5 and 1.1.2, and then able to verify that it works:

image

Also, if you're wondering what those 12 changed files are, you have several `.sh` files that are missing execute bits:

image

I didn't make that change in this PR, but I can if you'd like.

**Comment by bradwilson** [comment]
@marcpopMSFT You need anything else from me?

**Comment by marcpopMSFT** [comment]
@bradwilson Nope, looks good.  We just missed it in our PR review meeting last week.  Mind filing an issue for those .sh files as that makes sense as a separate PR to me?

**Pull request merged**
