### PR TITLE
Update DotNetBuild.props

### PR DESCRIPTION
**Pull request by ViktorHofer**
With the repo merge this isn't required anymore.

### CODE REVIEW

**Comment by mmitche** [comment]
@ViktorHofer Did the internal zips get removed?

**Comment by ViktorHofer** [comment]
Not yet, no. But it isn't used anymore in the sdk build afaik.

**Comment by mmitche** [comment]
> Not yet, no. But it isn't used anymore in the sdk build afaik.

They need to get removed before this gets merged, otherwise the source build nupkg will fail to push to the AzDO feed. I think it will go over 500MB

**Comment by ViktorHofer** [comment]
Ah right, makes sense.

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@ViktorHofer I approved not realizing it was set to automerge. Does some other work need to happen asap now?

**Pull request merged**
