### PR TITLE
Update RepoToolset to 1.0.0-beta-62412-04

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Review by tannergooding — CHANGES_REQUESTED** [review]
I need to merge this into `release/2.0.0` along with the SNK fixes.

**Comment by tmat** [comment]
OK. I made some changes around dependency uptake - the toolset now completely handles ```DotNetPackageVersionPropsPath``` and ```PB_PackageVersionPropsUrl``` without the repo doing anything. 
For now it translates ```-PackageVersion```s to ```-Version```s in the downloaded props file.

**Comment by tmat** [comment]
test this please

**Review by tannergooding — APPROVED** [review]
Turns out, sdk is the one repo that was already using the MicrosoftShared key.

**Pull request merged**
