### PR TITLE
Move to automated loc infrastructure

### PR DESCRIPTION
**Pull request by nguerrera**
Adopting the new loc infrastructure from https://github.com/dotnet/xliff-tasks

- .xlf files now keep themselves in sync:
  - Builds from within VS will just update them automatically 
  - Builds from command-line/jenkins/microbuild will fail if .xlf is out-of-date
  - msbuild /t:UpdateXlf (or msbuild /p:UpdateXlfOnBuild=true) will do the manual .xlf update on the command line
- The translated .resx files are now generated during the build
  - There is therefore no manual step needed upon loc handback. Just merge loc team PR and the translations will be in the product

### CODE REVIEW

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
I would suggest putting a [DO NOT MERGE] at the title of the PR, it is much easier to see.

**Comment by nguerrera** [comment]
OK. I've done some extra verification that strings are being picked up correctly and live from the xlf:

1. Edit Strings.fr.xlf to add `Allo!!!'` to front of French message for "unable to infer targetframeworkidentifier"
2. Build
3. Use built sdk on French machine

Result:
```
c:\src\sdk\bin\Debug\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(84,5):
error : Allo!! Impossible de déduire TargetFrameworkIdentifier et/ou TargetFrameworkVersion à partir de TargetFramework='foo'. Ils doivent être spécifiés explicitement. [C:\temp\qqq\qqq.csproj]
```

**Comment by nguerrera** [comment]
Putting back [DO NOT MERGE]. Fixing an issue where we're stripping the BOM on document edit.

**Comment by nguerrera** [comment]
BOM issue is fixed. This is ready.

**Comment by nguerrera** [comment]
@MattGertz FYI. Infrastructure-only change.

**Review by livarcocc — APPROVED** [review]

**Comment by livarcocc** [comment]
@nguerrera this is great. Let's merge this. I will leave you the honor for this one.

**Pull request merged**
