### PR TITLE
Upgrade rather than install, in case .NET is on container/machine alr…

### PR DESCRIPTION
**Pull request by mmitche**
…eady

### CODE REVIEW

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2484657&view=results

**Review by NikolaMilosavljevic — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
Duh, this change is in the installer code. Ported over to the 4xx branch of installer manually in the above PR.

**Pull request merged**
