### PR TITLE
Merge 1xx to 200

### PR DESCRIPTION
**Pull request by rainersigwald**
This should unblock the MSBuild update in 5.1.2xx #14582.

### CODE REVIEW

**Comment by rainersigwald** [comment]
Helps to choose the right base branch 🤦🏻‍♂️

**Comment by marcpopMSFT** [comment]
@rainersigwald, we were planning on shipping 5.0.2xx-preview 3 with 5.0.1 as 5.0.2 is still in flight (we've disabled dependency flow from runtime repos).  So I think you need to ensure no 5.0.2 updates to the version file.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/pull/14913 was the manual update to 5.0.1.

**Comment by rainersigwald** [comment]
@marcpopMSFT ok, pushed with that merge resolution.

**Comment by marcpopMSFT** [comment]
@wli3 The pipeline for Darwin Debug has been stuck on the running tests in helix for 2 hours when the release version took 15 minutes.  Is helix stuck perhaps?

**Comment by marcpopMSFT** [comment]
Finally failed, rerunning

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@rainersigwald merged it before anyone else causes a conflict.  I'll retrigger the 5.0.2xx msbuild merge PR tests

**Pull request merged**
