### PR TITLE
[master] Attempt to remove some feeds

### PR DESCRIPTION
**Pull request by mmitche**
To see what happens

### CODE REVIEW

**Comment by dsplaisted** [comment]
Assuming this was just for testing and not needed anymore.  Feel free to reopen as appropriate.

**Comment by mmitche** [comment]
I was mainly trying to see whether this was possible to reduce some nuget service load in the tests.

**Comment by mmitche** [comment]
This is dependent on https://github.com/dotnet/sdk/pull/15833

**Pull request merged**
