### PR TITLE
Fix `dotnet list package` when current directory contains a `#` character in Unix systems

### LINKED ISSUE #19654: `dotnet list package` fails when current directory path contains `#` character
When running `dotnet list package` while in the directory of a project with a `#` character in its path, I get the following error:
```
% pwd
/Users/allan/C#
% dotnet list package
Could not find file or directory '/Users/allan/C'.
...
```

This works fine when the path doesn't contain a `#` character, or if I specify the project name in the command:
```
% dotnet list Test.csproj package
Project 'Test' has the following package references
   [net5.0]: No packages were found for this framework.
```

### Steps to reproduce

1. Create a folder called `C#` and `cd` into it.
2. Create a new project (e.g. `dotnet new console -n Test -o .`)
3. Run `dotnet list package` and observe the issue described above.

### Other observations

- `dotnet list reference` doesn't seem to have this issue.
- Paths with other special characters may also be affected.

### Environment
```
% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.403 [/usr/local/share/dotnet/sdk]
  3.1.404 [/usr/local/share/dotnet/sdk]
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  3.1.408 [/usr/local/share/dotnet/sdk]
  3.1.409 [/usr/local/share/dotnet/sdk]
  3.1.410 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]
  5.0.203 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### PR DESCRIPTION
**Pull request by allanrodriguez**
Fixes #19654.

Updated `ListPackageReferencesCommand` to get the solution or project file/directory the same way as `ListProjectToProjectReferencesCommand` instead of using `PathUtility.GetAbsolutePath`, which cuts the path off at the `#` symbol when a Unix-style base path matches the relative path.

I looked into fixing `GetAbsolutePath` by replacing the existing `Uri` implementation with `Path.GetFullPath(string path, string basePath)`, but didn't get very far since this override was recently added in .NET Standard 2.1 (`Microsoft.DotNet.Cli.Utils` currently targets 1.5).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=20449) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=20449) before we can accept your contribution.<br/><br/>:x: allanrodriguez [sign now](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=20449)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/sdk?pullRequest=20449) it.</sub>

**Comment by KalleOlaviNiemitalo** [comment]
Wouldn't `Path.GetFullPath(string path)` work here? I think it would be even better than `Path.GetFullPath(string path, string basePath)` with the current directory as `basePath`.

```
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. All rights reserved.                                                                                             
C:\>CD C:\Windows

C:\Windows>CD D:\usr

C:\Windows>pwsh
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Windows> [System.IO.Directory]::GetCurrentDirectory()
C:\Windows
PS C:\Windows> [System.IO.Path]::GetFullPath("System32")
C:\Windows\System32
PS C:\Windows> [System.IO.Path]::GetFullPath("D:games")
D:\usr\games
PS C:\Windows> [System.IO.Path]::GetFullPath("System32", [System.IO.Directory]::GetCurrentDirectory())
C:\Windows\System32
PS C:\Windows> [System.IO.Path]::GetFullPath("D:games", [System.IO.Directory]::GetCurrentDirectory())
D:\games
```

**Comment by KalleOlaviNiemitalo** [comment]
If PathUtility.GetAbsolutePath is no longer used and won't be fixed, can it be marked obsolete?

**Comment by allanrodriguez** [comment]
`Path.GetFullPath(string path)` would work fine for the `ListPackageReferencesCommand` use case, but it would break `PathUtility.GetAbsolutePath` because the caller expects to be able to pass in a base path other than the current working directory (assuming that `GetAbsolutePath` has callers outside this repo).

**Review by nkolev92 — APPROVED** [review]

**Comment by allanrodriguez** [comment]
I realized that it's probably on me to merge this in 😅 If that's the case, I don't have write access to this repo. Could someone help me merge this?

**Comment by marcpopMSFT** [comment]
We don't have a good process for following up on reviewed PRs to get them merged if they are old (we look for approved, green PRs on the front page of PRs). This got missed and then fell off the front page. Change looks reasonable to me, has approval, and was merged fairly recently with main so merging.  In the future, feel free to ping dotnet/domestic-cat to get merge help as that's our build rotation. Sorry for the slow reply.

**Pull request merged**
