### PR TITLE
Removed install scripts and tests, added readme

### LINKED ISSUE #12992: Remove dotnet-install.ps1 scripts from this repo
The dotnet-install scripts have been moved to the https://github.com/dotnet/install-scripts repo.

They should be deleted in this repo.

### PR DESCRIPTION
**Pull request by bekir-ozturk**
Delivers https://github.com/dotnet/sdk/issues/12992.

Removed the tests as well, after moving them to install scripts repo in https://github.com/dotnet/install-scripts/pull/75.

### CODE REVIEW

**Comment by bozturkMSFT** [comment]
@wli3 @mmitche  What are the chances that we are breaking someones build pipeline with this change? Do we know anyone that is relying on scripts being in this repo?

**Comment by mmitche** [comment]
> @wli3 @mmitche What are the chances that we are breaking someones build pipeline with this change? Do we know anyone that is relying on scripts being in this repo?

I think it's low. While we don't have a way of finding out for sure, I haven't ever heard of anyone using the scripts in the repo directly.

**Review by mmitche — APPROVED** [review]

**Comment by wli3** [comment]
@bozturkMSFT  you need to remove InstallationScript.Tests/InstallationScript.Tests.csproj from the sln file. Open the sln file with VS and remove the csproj from solution explorer and save it.

**Comment by bozturkMSFT** [comment]
@wli3

**Review by wli3 — APPROVED** [review]

**Comment by sebastienros** [comment]
>  I haven't ever heard of anyone using the scripts in the repo directly.

Guess what ;)

**Comment by bozturkMSFT** [comment]
Hi @sebastienros,
 Can you give a bit info about why you are using the version here and not the one in https://dotnet.microsoft.com/download/dotnet-core/scripts?

**Comment by sebastienros** [comment]
I changed my links to use the alias now. Thanks. I don't remember the reason why I was not using these earlier, but I knew about it, so there was a reason. Maybe they were not pointing to the most recent version and I needed a fix ...

Don't worry it's all solved. And in case you look for someone for depends on it, remember I do!

**Pull request merged**
