### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by dsplaisted**

### CODE REVIEW

**Comment by eerhardt** [comment]
Looks like the new test I added is failing. I can fix it up in the morning. 

The "future" branch added a new property to the runtimeconfig.json file, and I added a baseline test in "master".

**Comment by eerhardt** [comment]
Well the tests now pass, but it looks like the template solution is broken on Windows builds:

```
D:\j\workspace\debug_windows---ec7a1ce0\sdk-templates.sln.metaproj : error MSB4057: The target "restore" does not exist in the project. [D:\j\workspace\debug_windows---ec7a1ce0\sdk-templates.sln]
```

One thing to note:  We do have an older/private NuGet version in the future branch.  This was needed in order to get the `netcoreapp2.0` => `netstandard2.0` TFM mapping in NuGet.  Was there a change to how nuget restore works against .sln files?

**Comment by rainersigwald** [comment]
Solution-level restore should be handled by targets dropped into a subfolder of MSBuild. But it may have been working by using the newish pass-unknown-solution-target-to-each-individual-project-in-the-solution behavior. I'd check the layout of the MSBuild directory and the version of the MSBuild that's being used.

**Comment by nguerrera** [comment]
> D:\j\workspace\debug_windows---ec7a1ce0\sdk-templates.sln.metaproj : error MSB4057: The target "restore" does not exist in the project. [D:\j\workspace\debug_windows---ec7a1ce0\sdk-templates.sln]

This would be due to building with VS 2015 instead of 2017

**Comment by nguerrera** [comment]
Spoke too soon. This is happening in Jenkins. I'll take a look.

**Comment by ramarag** [comment]
i think this failure is due to jenkins no running the job in VS2017, as it sets VS150COMNTOOLS in https://github.com/dotnet/sdk/blob/e5bcce98b216aeaed9a901a90647f0a06c306d35/netci.groovy#L47

As the netci.groovy in this PR is not used to trigger the PR, the jenkins never sets the VS150COMNTOOLS.

Do we merge https://github.com/dotnet/sdk/commit/d3ba728fd111ad32c21819bb129284d19ad9ad5b seperately and re run this job ?

**Comment by nguerrera** [comment]
> Do we merge d3ba728 seperately and re run this job ?

OK.

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT Debug please

**Comment by ramarag** [comment]
i belive i missed a few commits. trying another PR https://github.com/dotnet/sdk/pull/812

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT Debug please

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT Debug please

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT Release please

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT Debug please

**Pull request merged**
