### PR TITLE
Update .editorconfig template with new defaults

### PR DESCRIPTION
**Pull request by JoeRobich**
Adds defaults for new code style options.

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
Talked to tactics and we don't need approval from there specifically but they want to ensure there are extra eyes on this since it's late in the release cycle for 9.

@JoeRobich which stakeholders should review this? Can you take a look at fixing the templating tests.

Also, we want to ensure this is in for preview 7 so get it in in the next week.

**Comment by JoeRobich** [comment]
> @JoeRobich which stakeholders should review this?

That is a good question. This is my first time updating the template in the SDK. Maybe @mikadumont or @arkalyanms know who could help review.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by sharwell** [comment]
Definitely need to remove the `end_of_line` setting; that was a bug prior to this change.

**Comment by JoeRobich** [comment]
> Definitely need to remove the `end_of_line` setting; that was a bug prior to this change.

Thanks @sharwell! I didn't look closely at the configuration that was already present. With eol removed do you feel good about these updates?

**Pull request merged**
