### PR TITLE
Update branding to 2.1.4xx

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by livarcocc** [comment]
@mmitche Any idea why CI is not getting kicked off here? Did I miss something when I updated dotnet-ci? The same is happening here as well https://github.com/dotnet/cli/pull/9088

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by johnbeisner** [comment]
@dotnet-bot test this please

**Comment by johnbeisner** [comment]
@livarcocc 
"Any idea why CI is not getting kicked off here" - run the Jenkins generator job manually:
https://ci.dot.net/job/dotnet_cli/job/release_2.1.4xx/job/generator/
and then ask "test this please"

**Pull request merged**
