### PR TITLE
Update branding for 3.1.4xx 3.1.4xx

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@zivkan this is failing with 

> error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.ProjectModel, Version=5.7.1.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Is there something in dotnet-tools-internal that should now be public?

**Comment by zivkan** [comment]
The package was pushed to public `dotnet-tools` feed this morning: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools%40Local&package=NuGet.ProjectModel&protocolType=NuGet&version=5.7.1-rtm.4&view=overview

Although I'm confused why it's looking for assembly version 5.7.1.7. I'd expect the package to contain 5.7.1.4 given the pacakge version.

I'll continue to look further.

**Comment by wtgodbe** [comment]
It's possible that this PR was put up just before the package got made public

**Comment by zivkan** [comment]
I don't understand why, but assembly version 5.7.1.7 does appear to be in package version 5.7.1-rtm.4. So, I hope it was just a timing issue, although I'm surprised there wasn't an error when restoring packages, rather than this runtime error. I admit I don't understand the details of assembly loading, but I thought that .NET Core removed strong name verifications.

**Comment by wtgodbe** [comment]
Looks like it wasn't a timing issue, the failure is still happening

**Comment by zivkan** [comment]
Are we able to download the binaries it was testing, to check what assembly version NuGet.*.dll has?  I don't see in the build log where it restored NuGet's packages, so I can't figure out what version of NuGet it's actually using.

**Pull request merged**
