### PR TITLE
Files not ending in css are probably not css files

### PR DESCRIPTION
**Pull request by Bouke**
The log message incorrectly labels these files "css" files, but actual "css" files are handled in the other branch.

### CODE REVIEW

**Comment by baronfel** [comment]
This looks sane to me, but I'd like @pranavkm's eyes on it real quick in case something else is happening here that I'm just not seeing.

**Review by pranavkm — APPROVED** [review]
Thanks!

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @Bouke. Sorry for taking so long to get this merged.

**Pull request merged**
