### PR TITLE
Delete unnecessary test project files

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@dsplaisted The error of this PR is the same as that of [PR(#21539),](https://github.com/dotnet/sdk/pull/21539) so I will merge this PR into [PR(#21539),](https://github.com/dotnet/sdk/pull/21539) does it make sense for you?

**Comment by v-wuzhai** [comment]
The restored changes are made in #25479

**Comment by marcpopMSFT** [comment]
@v-wuzhai is this change meant to be all deletes? I retargeted to 4xx and github is only showing deletes in this PR.

**Comment by v-wuzhai** [comment]
I just deleted the src/Assets/TestProjects/RazorSimplePages folder in this PR

**Comment by marcpopMSFT** [comment]
Ok, seems reasonable to me to clean up extra test projects. Adding some that may want to briefly review.

**Review by marcpopMSFT — APPROVED** [review]

**Pull request merged**
