### PR TITLE
Merge 6.0.1xx-rc2 to 6.0.1xx

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Review by dsplaisted — COMMENTED** [review]
When we merge branches, we usually don't want to include any changes to the versions files or anything in the `eng/common` folder.  Those are handled by Maestro dependency flow.

**Comment by sfoslund** [comment]
@dsplaisted fixed the version update issues, mind re-reviewing? (also https://github.com/dotnet/sdk/pull/21662)

**Comment by dsplaisted** [comment]
@sfoslund There are still changes under `eng/common`, in `global.json`, and for the version of `dotnet-format` in `Versions.props` and `Version.Detail.xml`.  Are those intentional?  Normally I think none of those should be updated.

**Comment by sfoslund** [comment]
@dsplaisted just fixed those, thanks for pointing them out

**Review by dsplaisted — APPROVED** [review]

**Pull request merged**
