### PR TITLE
Alpha Branding

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by marcpopMSFT** [comment]
@baronfel There is a container endtoend test failing
/datadisks/disk1/work/957B07E0/p/d/sdk/10.0.100-ci/Containers/build/Microsoft.NET.Build.Containers.targets(241,5): error CONTAINER1015: Unable to access the repository 'dotnet/runtime' at tag '9.0' in the registry 'mcr.microsoft.com'. Please confirm that this name and tag are present in the registry.

**Comment by baronfel** [comment]
I'd disable it for now - we are at a chicken and egg moment. The docker team won't have 9.0 images available until RC1 actually releases, at which point we can reenable the test

**Comment by marcpopMSFT** [comment]
@tmat @mkArtakMSFT @dotnet/roslyn-ide there are a few watch test failures. Note that this is the initial net10.0 branding so some tests may be particularly sensitive to that.

Assert.StartsWith() Failure: String start does not match
String:         null
Expected start: "Changed!"

Assert.StartsWith() Failure: String start does not match
String:         null
Expected start: "Updated types: Printer"

Microsoft.CodeAnalysis.MSBuild.RemoteInvocationException : An exception of type System.InvalidOperationException was thrown: We don't have an MSBuild to use; HasUsableMSBuild should have been called first to check. - file BuildHost.cs line 133

**Comment by marcpopMSFT** [comment]
@v-wuzhai would you be able to disable all of the failing tests in this PR and create an issue to track reenabling them? Since this is the start of the net10 work, I think it's ok to disable things temporarily to get unblocked.

**Comment by marcpopMSFT** [comment]
@dotnet/product-construction this is trying to update branding for sdk to 10 and is the first step among many we'll have to do before main is ready for net10:
https://github.com/dotnet/sdk/blob/main/documentation/general/UpdateToNewTargetFramework.md

Can we disable unified build in main for now as the failures look like it wasn't there to be a net10 build? What should the process for this be?

**Comment by marcpopMSFT** [comment]
@dotnet/source-build-internal looks like the source build leg is now failing. Any ideas? This is the first step to enabling net10 support (which is really just having a 10 branding version of the SDK).
```
System.InvalidOperationException : Failed to execute /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet format /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/projects-202408220754550270/FormatProject/FormatProject.csproj
Exit code: 3
Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.
```

**Comment by ellahathaway** [comment]
> @dotnet/source-build-internal looks like the source build leg is now failing. Any ideas? This is the first step to enabling net10 support (which is really just having a 10 branding version of the SDK).
> 
> ```
> System.InvalidOperationException : Failed to execute /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet format /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/projects-202408220754550270/FormatProject/FormatProject.csproj
> Exit code: 3
> Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.
> ```

Looking - seems like the same issues as https://github.com/dotnet/source-build/issues/3004

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
