### PR TITLE
revert part of #29916

### PR DESCRIPTION
**Pull request by kasperk81**
to unblock linux-musl test in installer https://github.com/dotnet/installer/pull/15228#issuecomment-1384737277

### CODE REVIEW

**Comment by kasperk81** [comment]
@marcpopMSFT

**Comment by ViktorHofer** [comment]
@kasperk81 the .NET Framework leg is failing.

**Comment by kasperk81** [comment]
> crossgen2.exe" exited with code -1073741819.

don't think this change can cause crossgen2 crash like that. anyways, sync'd main to rerun ci.

**Comment by kasperk81** [comment]
full framework leg passed.
> An update for template package 'Microsoft.TemplateEngine.Samples::8.0.100-alpha.1.23066.9' is available.

in template leg isn't related (it will be fixed once https://github.com/dotnet/sdk/pull/29967 is merged)

**Comment by ViktorHofer** [comment]
> in template leg isn't related (it will be fixed once https://github.com/dotnet/sdk/pull/29967 is merged)

Any idea why this is happening in main?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Ah, we should probably add the ` --no-update-check        Disables checking for the template package updates when instantiating a template.` flag to the test invocations. Will do that in a separate PR.

**Comment by ViktorHofer** [comment]
@dotnet/templating-engine-maintainers https://github.com/dotnet/templating/blob/3b7bc2c69f41dd5205b850632b0f76c457254010/tools/Microsoft.TemplateEngine.Authoring.TemplateVerifier/VerificationEngine.cs#L340-L344 should probably pass the `--no-update-check` to the `dotnet new <template-name>` command.

A test failed here in this PR because the template samples package was installed but then later when instantiating the templates, the update checks detected a newer package being available in the feeds:

```
1 The template "Contoso Sample 06" was created successfully.
      + 
      + An update for template package 'Microsoft.TemplateEngine.Samples::8.0.100-alpha.1.23066.9' is available.
      + To update the package use:
      +    dotnet new install Microsoft.TemplateEngine.Samples::8.0.100-alpha.1.23067.1
```

**Comment by kasperk81** [comment]
@ViktorHofer now there is a new pr https://github.com/dotnet/sdk/pull/29969 so it is complaining about the next version

**Comment by YuliiaKovalova** [comment]
I am taking a look.

**Pull request merged**
