### PR TITLE
remove installer from version file

### PR DESCRIPTION
**Pull request by kasperk81**
installer and sdk have same values in main

https://aka.ms/dotnet/9.0.1xx/daily/productCommit-win-x64.json
https://aka.ms/dotnet/9.0.1xx/daily/productCommit-win-x64.txt

### CODE REVIEW

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
Triage: we decided it was better to break in previews and we can revert if we get complaints. CC @mmitche who often knows places stuff like this is used.

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
The linked crank code is what I would mainly worry about. I think this is the right change. It means that clients who look for the metadata could check if installer exists. If it does, use it (downlevel versions). Otherwise use sdk.

**Comment by sebastienros** [comment]
> it should have been "sdk" from the get-go

From what I recall the values in installer and sdk were not the same and we always took the one from installer to work with dotnet-install. We were doing the same thing in the aspnetcore repos to update the sdk version, and I even documented it to prevent any confusions. So I assume "sdk" and "installer" being the same value is not very old.

**Comment by martincostello** [comment]
> From what I recall the values in installer and sdk were not the same

My experience was the same, which is why I've also had to update my GitHub Action to prepare for this change.

**Comment by baronfel** [comment]
@martincostello for my info could you link to your action? Always curious to see how and where folks use the various metadata we support to varying degrees.

**Comment by martincostello** [comment]
Sure - the action is here: [martincostello/update-dotnet-sdk](https://github.com/martincostello/update-dotnet-sdk)

The PR I mentioned was this one: https://github.com/martincostello/update-dotnet-sdk/pull/906

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
