### PR TITLE
Fix SDK version parsing from global.json in install script on macOS

### PR DESCRIPTION
**Pull request by kondratyev-nv**
Running install script `scripts/obtain/dotnet-install.sh` with `jsonfile` argument works on macOS only when `sdk` section has a single property `version`. When `sdk` section has multiple properties, for example,
```json
"sdk": {
    "version":  "5.0.100-preview.6.20310.4",
    "allowPrerelease": true,
    "rollForward": "major"
  }
```
a version is detected as `5.0.100-preview.6.20310.4allowPrerelease:truerollForward:major`.
Also, in a case when `version` is not the first property in `sdk` a version can not be detected returning an error ``dotnet_install: Error: Unable to find the SDK:version node in `global.json` ``.

The problem seems to be in line:
```
sdk_list="$(echo -e "${sdk_list}" | tr -d '[[:space:]]')"
```
On macOS, echo does not have a `-e` argument, and all lines of key-value pairs in `sdk_list` are merged into a single line. So, removing it seems to fix it. I don't have a Linux to test the changes, but I hope CI will catch any issues on Linux.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=12339) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=12339) before we can accept your contribution.<br/><br/>:x: kondratyev-nv [sign now](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=12339)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/sdk?pullRequest=12339) it.</sub>

**Comment by marcpopMSFT** [comment]
@donJoseLuis does the install script change needed in the install-scripts repo and should we remove the copy from this repo to reduce confusion?

**Comment by marcpopMSFT** [comment]
Ping @donJoseLuis

**Comment by kondratyev-nv** [comment]
@marcpopMSFT Thanks for the help! I've created an issue in install-scripts repo https://github.com/dotnet/install-scripts/issues/61 concerning that problem. Unfortunately, I wan not able to create a similar PR in install-scripts repo, so I'll wait for a response to the issue.

**Comment by marcpopMSFT** [comment]
@bozturkMSFT Should he close this and do all of the work in the install-scripts repo?

**Pull request closed without merging**
