### PR TITLE
Add sudo home override

### LINKED ISSUE #19523: /Users/USERNAME/.dotnet/sdk-advertising-temp/ cannot be accessed
I get this when I run `dotnet workload list --machine-readable` after installing with sudo.

I think it is due to this temp directory was created under sudo, so when run without sudo it cannot be accessed. We might want to separate folder for different elevation or set explicit permission for this folder. Note, on different Linux, $HOME under sudo could be the current user or the root depends on how sudo the application is configed.

### LINKED ISSUE #19823: dotnet workload install creates dir with root permissions
Steps to reproduce:
Clean env
 Install https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.7-macos-x64-installer
Execute sudo `dotnet workload install maui ` or `dotnet workload install wasm-tools`  or any of the .NET 6 workloads  from command line.
Check 'dotnet new mvc --auth Individual -o mvcind` after maui install.

Expected Behaviour:
mvc project gets creates and restores successfully

Actual Behaviour:
mvc project gets created but fails to restore 
Cause: `dotnet workload install`  creates ~/.nuget with  root permissions and when `dotnet new `runs for an individual auth,  permission is denied.

### PR DESCRIPTION
**Pull request by wli3**
https://github.com/dotnet/sdk/issues/20195

Fix #19823
Fix #19523

### CODE REVIEW

**Review by sfoslund — APPROVED** [review]

**Comment by GouriKumari** [comment]
@wli3  : After installing rc1 in a clean machine, dotnet workload list --machone-readable needs to be executed with elevated privileges. Is that expected?

**Comment by sfoslund** [comment]
@GouriKumari I fixed this issue a few weeks ago, but I believe it missed rc1. You shouldn't see the problem in rc2: https://github.com/dotnet/sdk/pull/20067

**Comment by GouriKumari** [comment]
@sfoslund : Is there time to include it in rc1?  #20196 Is fix from this PR also missed rc1?

**Comment by sfoslund** [comment]
I don't think so, it looks like we already have a candidate build.

**Pull request merged**
