### PR TITLE
Bundle NuGet.Build.Tasks.Console in redist

### LINKED ISSUE #9267: Ensure Static Graph restore is available in dotnet.exe
This basically means ingesting https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj into the SDK. 

We should discuss with the .NET Core team what branches they want the changes in. 

fyi @jeffkl

### PR DESCRIPTION
**Pull request by ViktorHofer**
Add the NuGet.Build.Tasks.Console package for the pack bundle.
Fixes https://github.com/NuGet/Home/issues/9267

### CODE REVIEW

**Comment by nkolev92** [comment]
Does this automatically lay out the things the way it's supposed to? 
Can you point to the code where that's happening?

**Comment by jeffkl** [comment]
I think so, when building this project, you just get a bunch of stuff in the output directory because of the various PackageReference items.  And then this target lays things out:

https://github.com/dotnet/toolset/blob/8a99876e947686898a5208e26cac316dfeff449a/src/redist/targets/GenerateLayout.targets#L139

**Comment by ViktorHofer** [comment]
This is the default behavior becuase [CopyLocalLockFileAssemblies](https://github.com/dotnet/sdk/pull/10794/files#diff-49a48b4ddecfa5954174d2a69d8de0a1R7) is being set.

**Review by nkolev92 — APPROVED** [review]

**Comment by nkolev92** [comment]
I assume this will be blocked on https://github.com/NuGet/NuGet.Client/pull/3285 making it's way into the SDK?

**Comment by ViktorHofer** [comment]
Right

**Comment by ViktorHofer** [comment]
https://github.com/NuGet/NuGet.Client/pull/3285 still needs to be approved by someone from the team :)

**Comment by nkolev92** [comment]
Yep, getting to it haha :D

**Review by dsplaisted — COMMENTED** [review]
Together with this could we add a basic test that exercises the functionality added with this package?  That way we would at least have a sanity check that the files are going in the right place and working.

**Review by wli3 — DISMISSED** [review]
Need test

**Comment by ViktorHofer** [comment]
@jeffkl this is now building successfully. Do you have time to add a test?

**Comment by jeffkl** [comment]
Sigh the package is still wrong.
image
Nothiing copes the `runtimeconfig.json` since assemblies in `lib` are only treated as reference assemblies not runable apps.

We'll need to either fix the package and have the `runtimeconfig.json` under `runtimes\any\native` or do something custom in this repo.

**Comment by ViktorHofer** [comment]
Jeff it seems you were right about contentfiles. That's how VSTest does it:

image

**Comment by ViktorHofer** [comment]
Manually requeued the build because of the AzDO outage: https://dnceng.visualstudio.com/public/_build/results?buildId=560056&view=logs

**Comment by ViktorHofer** [comment]
Tests are added and the build is green: https://dnceng.visualstudio.com/public/_build/results?buildId=560056&view=logs

**Pull request merged**
