### PR TITLE
Updating the MSBuild Task DLLs to be versioned with every build.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/sdk/issues/2161

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @davkean, @livarcocc, @nguerrera

**Review by nguerrera — APPROVED** [review]

**Comment by livarcocc** [comment]
I would imagine we would want this fixed for 2.1.3xx, in which case, we need to target that branch, fill out the ask mode template and tag matt for m2 approval. After that, we will take it to shiproom.

**Comment by nguerrera** [comment]
In v1 escrow, we got this approved as infrastructure only. Not sure if the same shiproom exemption applies now ;). See #815

**Comment by livarcocc** [comment]
re-target to release/2.1.3xx, we will merge it as a infra-structure change then. No neet for approval.

**Comment by nguerrera** [comment]
We should apply this fix to all active servicing branches too.

**Comment by livarcocc** [comment]
Then 2.1.1xx is the best branch for it, as it will flow everywhere else from there.

**Comment by tannergooding** [comment]
Retargeted to release/2.1.3xx

**Comment by livarcocc** [comment]
Can you actually re-target to 2.1.1xx?

**Comment by tannergooding** [comment]
Retargeted to release/2.1.1xx

**Comment by livarcocc** [comment]
@tannergooding can you fast track the merges so this reaches release/2.1.3xx?

**Pull request merged**
