### PR TITLE
Skip a templating test when run internally

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by joeloff — APPROVED** [review]
hacky, but okay :)

**Comment by marcpopMSFT** [comment]
> hacky, but okay :)

Know of a better way to do this? It was failing internal codeflow with a 404 error about the feed. Not sure of a better way to detect an internal build and not sure of another way of fixing the test.

**Comment by joeloff** [comment]
> > hacky, but okay :)
> 
> Know of a better way to do this? It was failing internal codeflow with a 404 error about the feed. Not sure of a better way to detect an internal build and not sure of another way of fixing the test.

Possibly pass a preprocessor definition from the YAML in the pipeline, then wrap the test inside a `#ifdef`

**Comment by joeloff** [comment]
> > > hacky, but okay :)
> > 
> > 
> > Know of a better way to do this? It was failing internal codeflow with a 404 error about the feed. Not sure of a better way to detect an internal build and not sure of another way of fixing the test.
> 
> Possibly pass a preprocessor definition from the YAML in the pipeline, then wrap the test inside a `#ifdef` and set some default for when running from the commandline or IDE

**Pull request merged**
