### PR TITLE
Fix dogfood in build.sh

### PR DESCRIPTION
**Pull request by sbomer**
Looks like it was broken by https://github.com/dotnet/sdk/pull/2178

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
This looks good to me.

cc @livarcocc, @dotnet/dotnet-cli to look as well:
  * Should we put this in an earlier branch than master. It appears it was broken in 2.1.3xx branch
  * Will this interfere with the arcade change?

**Comment by livarcocc** [comment]
@nguerrera We should push this to earlier branches, I would say release/2.1.4xx. Also, yes, there will be a conflict with the arcade work. I will make sure to merge that.

**Comment by nguerrera** [comment]
I'll cherry-pick this and fix it up along with some other needed fixes to dogfood. My care factor for fixing in downlevel branches is gone since the infrastructure is too divergent. Most dev activity is master/3.0+ now anyway.

**Comment by nguerrera** [comment]
This is now in PR at #2801

**Pull request closed without merging**
