### PR TITLE
Use csc task instead of Roslyn API

### LINKED ISSUE #692: Signing satellite assemblies fails when using full key
Delay sign or full sign a project with satellite resources with a snk file that has public and private key:

```
C:\Program Files\dotnet\sdk\1.0.0-rc3-004512\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(213,5): error : Errors occured when emitting satellite assembly 'D:\Src\repros\SatelliteAssemblyHostIssue\obj\Debug\netcoreapp2.0\fr\SatelliteRepro.resources.dll'. [D:\Src\repros\SatelliteAssemblyHostIssue\SatelliteRepro.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc3-004512\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(213,5): error : error CS7027: Error signing output with public key from file 'D:\Src\repros\SatelliteAssemblyHostIssue\test.snk' -- Assembly signing not supported. [D:\Src\repros\SatelliteAssemblyHostIssue\SatelliteRepro.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc3-004512\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(213,5): error : warning CS7033: Delay signing was specified and requires a public key, but no public key was specified [D:\Src\repros\SatelliteAssemblyHostIssue\SatelliteRepro.csproj]
```

Note: Public signing (in all cases) or delay signing when snk file has only public key work correctly.

I think we should fix this by invoking csc and removing our dependency on Roslyn as an API.

### PR DESCRIPTION
**Pull request by nguerrera**
**Customer scenario**
It is not possible to fully sign satellite assemblies built by the SDK when using core msbuild via dotnet CLI instead of desktop msbuild

**Bugs this fixes:**
#692 

**Workarounds, if any**
None.

**Risk**
Low. This removes some code that did the satellite generation via Roslyn API and replaces it with a simple call to the compiler via the Csc task

Removing the unnecessary direct SDK -> Roslyn dependency also reduces risk of assembly conflict issues that keep cropping up elsewhere.

**Performance impact**
Zero to VS. 

Minimal to CLI. 

There might be some overhead to using Csc vs. the API, but it only applies to projects that build satellites and furthermore only when building via the CLI. VS will continue to use the same AL.exe process that has been used for years via desktop msbuild.

**Is this a regression from a previous update?**
No. This has never worked.

**Root cause analysis:**
Missing test coverage (added with PR) for intersection of satellite assembly usage with full signing.

**How was the bug found?**
Reported by ASP.NET team and identified as blocking.

@srivatsn @dsplaisted @dotnet/project-system

### CODE REVIEW

**Comment by natidea** [comment]
Please also do a signed build to validate these changes

**Review by srivatsn — APPROVED** [review]

**Comment by nguerrera** [comment]
@MattGertz for approval to take to ship room for RTW

**Comment by MattGertz** [comment]
(Sorry for the label confusion -- I set it, then had second thoughts, turned it off, realized my second thoughts were bogus, and then added the wrong label...)

**Comment by natidea** [comment]
Approved to merge via [371309](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/371309)

**Pull request merged**
