### PR TITLE
Use ComHost generation code from HostModel.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Now that the ComHost generation code exists in `Microsoft.NET.HostModel`, change the sdk to use that implementation instead of the one in the SDK itself.

cc: @nguerrera

### CODE REVIEW

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
The reason why I didn't want to take this in a fast approaching release in a nuthsell:

```
   F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018: File name: 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options) [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options) [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at Microsoft.NET.HostModel.ComHost.ClsidMap.Create(MetadataReader metadataReader, String clsidMapPath) [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateClsidMap.ExecuteCore() [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
      F:\workspace\_work\1\s\artifacts\bin\Release\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(448,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [F:\workspace\_work\1\s\artifacts\tmp\Release\It_copies_the---095E2160\ComServer.csproj]
```

**Comment by nguerrera** [comment]
This is going to come down to the age old issue of binding redirects being needed on framework vs. msbuild tasks which can't provide them, I think. There's a ref to version 4.0.1.0 but I think we have 4.0.1.1.

MSBuild itself actually depends on this, but does not have a binding redirect for it.

cc @rainersigwald @ericstj

**Comment by nguerrera** [comment]
@ericstj I don't suppose we can ask for System.Text.Json out of master to have a ref graph with at most one version per assembly, like we managed to arrange for MetadataLoadContext. I think at this point, with this targeting 5.0 I'd prefer to look for a more sustainable solution.

**Comment by jkoritzinsky** [comment]
@ericstj any chance you can help out with Nick's question?

**Comment by ericstj** [comment]
Sorry I missed this.  Could be possible, depends on what we need to target.  I'll file an issue.

**Comment by ericstj** [comment]
Actually, If I install the latest System.Text.Json it references System.Memory 4.0.1.1 so we may have already fixed this.  Can you double check @nguerrera?

**Comment by jkoritzinsky** [comment]
It looks like Microsoft.NET.HostModel is still compiling against an older System.Text.Json. The subscriptions in dotnet/runtime haven't been updated, and as a result the reference is out of date. I'll open an issue on dotnet/runtime about it.

**Comment by jkoritzinsky** [comment]
@ericstj I just built System.Text.Json locally and I don't see it referencing System.Memory 4.0.1.1, I only see it referencing 4.0.1.0. Where are you seeing the updated version reference?

**Comment by ericstj** [comment]
I looked at the last shipping package.
```
// C:\Users\ericstj\.nuget\packages\system.text.json\4.7.0\lib\netstandard2.0\System.Text.Json.dll
// System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
```
Indeed if I look at the state of dotnet/runtime I confirm what you're seeing.  Something regressed this post 3.x.  I'll see what's going on.

**Comment by jkoritzinsky** [comment]
I just tested this PR with a HostModel built against System.Text.Json 4.7.0 and it worked, so I'm going to go with that for now while we try to figure out what regressed post 3.x.

**Comment by ericstj** [comment]
I found the regression and put up a PR to fix it.

**Comment by dsplaisted** [comment]
@jkoritzinsky @ericstj What's the status of this?

**Comment by jkoritzinsky** [comment]
It’s blocked on dotnet/runtime#2115 which is blocked on dotnet/runtime#1918

**Comment by nguerrera** [comment]
Yay!

**Pull request merged**
