### PR TITLE
Update sdk

### PR DESCRIPTION
**Pull request by sbomer**

### CODE REVIEW

**Comment by nguerrera** [comment]
@dsplaisted @wli3 CI failure looks like the same thing with the apphost and tool restore you were telling me about. Can you help @sbomer ? This update is needed to unblock the linker.

**Comment by wli3** [comment]
This is the issue. We would need to wait for the fix the checkin and get a new SDK stage 0

**Comment by dsplaisted** [comment]
Yes, global tools are currently broken, but should be fixed when this PR flows into core-sdk: https://github.com/dotnet/cli/pull/11166

**Comment by nguerrera** [comment]
Is that flowing every build? If not can you kick darc

**Comment by dsplaisted** [comment]
@nguerrera  Will is flowing the changes through darc

**Comment by dsplaisted** [comment]
I think this will be fixed in build 3.0.100-preview5-011375 or higher

**Comment by sbomer** [comment]
Trying with 011367 which looks like it has the above change: https://dnceng.visualstudio.com/internal/_build/results?buildId=160933. I'll continue attempting the update as we get new builds. Thanks @dsplaisted!

**Comment by sbomer** [comment]
Still fails with 3.0.100-preview5-011377. Trying 01138 now.

**Comment by sbomer** [comment]
@dsplaisted the update doesn't appear to have fixed it. Could you please take a look?

**Comment by wli3** [comment]
That bug is solved by 3.0.100-preview5-011462 however, another bugs shows up in https://github.com/dotnet/sdk/pull/3147

Due to s.t.json API breaking change. core-sdk and CLI's version mismatch. I need to get https://github.com/dotnet/cli/pull/11193 in get it flow to core-sdk

**Comment by wli3** [comment]
finally done here https://github.com/dotnet/sdk/pull/3153

**Pull request closed without merging**
